dotnet/arcade-services

- src/Maestro/Maestro.Contracts/CoherencyErrorDetails.cs
- src/Maestro/Maestro.MergePolicies/ValidateCoherencyMergePolicy.cs
This is due to https://github.com/dotnet/arcade-services/pull/1945
https://github.com/dotnet/arcade-services/issues/2678
> Fix file headers that now become errors

- Directory.Packages.props
- src/Maestro/Maestro.Web/Maestro.Web.csproj
https://github.com/dotnet/arcade-services/issues/2648
> Pin `NuGet.Protocol` to `6.6.1`

- azure-pipelines.yml
- eng/templates/stages/secret-validation.yml
One more speed improvement around the secret validation stage
https://github.com/dotnet/arcade-services/issues/2698
> Make the Secret Validation stage not depend on anything

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs
Some improvements I collected while investigating the git patch size limit problem
No release notes
> Add better logging for initialization errors

- azure-pipelines.yml
- eng/templates/stages/deploy.yaml
Fix for https://dev.azure.com/dnceng/internal/_build/results?buildId=2210924&view=results
> [HOTFIX] Publish build to BAR in production

- .config/dotnet-tools.json
- Directory.Packages.props
- azure-pipeline-weekly.yml
- azure-pipelines.yml
- eng/Version.Details.xml
- eng/Versions.props
- eng/enforce-issue.ps1
- src/Maestro/Maestro.DataProviders/SharedKustoQueries.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/GetAssetOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/GetAssetCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs
https://dev.azure.com/dnceng/internal/_workitems/edit/5210
> [Rollout] Production rollout, 2023-07-12

- .github/ISSUE_TEMPLATE/rollout-issue.md
Resolves https://github.com/dotnet/arcade-services/issues/2743
Minor improvement to GitHub rollout issue template
> add minor improvements to rollout issue template

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
https://github.com/dotnet/arcade-services/issues/2768
Fixed restoration of VMR-patched submodule files during VMR sync
> Fix restoration of VMR-patched submodule files

- .config/dotnet-tools.json
- eng/Version.Details.xml
- eng/Versions.props
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/FileSystem.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/IFileSystem.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
https://dev.azure.com/dnceng/internal/_workitems/edit/5229
> [Rollout] Production rollout 2023-07-26

- eng/Version.Details.xml
- eng/Versions.props
- eng/common/retain-build.ps1
- eng/common/templates/steps/retain-build.yml
- global.json
- src/Maestro/Maestro.Web/Pages/Index.cshtml
- src/Maestro/Maestro.Web/Pages/Index.cshtml.cs
- src/Maestro/maestro-angular/src/app/services/application-insights.service.ts
- src/Maestro/maestro-angular/src/index.html
- src/Microsoft.DotNet.Darc/Darc/Program.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2240668&view=results
Rollout issue: https://github.com/dotnet/dnceng/issues/552
> [Rollout] Production rollout, 2023-08-16

- .github/ISSUE_TEMPLATE/issue-with-release-notes.md
- .github/pull_request_template.md
https://github.com/dotnet/arcade-services/issues/2830
Added a template for issues containing release notes
> Create template for issues with release notes

- azure-pipeline-codeql.yml
https://github.com/dotnet/arcade-services/issues/2839
Removes the auto injected CG in arcade-services-codeql
> Remove autoinjected CG from codeql

- src/Microsoft.DotNet.Darc/DarcLib/RemoteRepoBase.cs
This was introduced in https://github.com/dotnet/arcade-services/issues/2823
Fix `git checkout` argument bug
> Fix `git checkout` argument bug

- azure-pipelines.yml
Rollout issue: https://github.com/dotnet/arcade-services/issues/2850
Pipeline break: https://dev.azure.com/dnceng/internal/_build/results?buildId=2249696&view=results
> [hotfix]Fix yaml template

- src/Microsoft.DotNet.Darc/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/DarcLib/GitNativeRepoCloner.cs
- src/Microsoft.DotNet.Darc/DarcLib/GitRepoCloner.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/ProcessManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/IGitRepoCloner.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
https://github.com/dotnet/arcade-services/issues/2862
Use env variables to pass in tokens to `git`
> Use env variables to pass in tokens to `git`

- Directory.Packages.props
https://github.com/dotnet/arcade-services/issues/2855
https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade-services/alert/8132149?typeId=6567134
Updated `Microsoft.Azure.Services.AppAuthentication` to `1.6.2`
> Bump `Microsoft.Azure.Services.AppAuthentication`

- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/InitializeOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrSyncCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrInitializer.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrUpdater.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
https://github.com/dotnet/arcade-services/issues/2876
> Allow to discard generated patches during VMR sync

- .config/dotnet-tools.json
- eng/Version.Details.xml
- eng/Versions.props
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2260976&view=results
Rollout issue: https://github.com/dotnet/dnceng/issues/794
> [Rollout] Production rollout, 2023-09-13

- src/Microsoft.DotNet.Darc/DarcLib.AzDev/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/AzureDevOps/AzureDevOpsPipelineResourceParameter.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/AzureDevOps/AzureDevOpsRunResourcesParameters.cs
https://github.com/dotnet/arcade-services/issues/2925
Add pipeline resource parameters to StartNewBuildAsync method
> Start a new pipeline build with resource parameters

- .github/ISSUE_TEMPLATE/rollout-issue.md
https://github.com/dotnet/arcade-services/issues/2928
SKIP IN RELEASE NOTES
> Improve rollout instructions

- .config/dotnet-tools.json
- .github/ISSUE_TEMPLATE/rollout-issue.md
- Directory.Packages.props
- eng/Version.Details.xml
- eng/Versions.props
- src/Microsoft.DotNet.Darc/DarcLib.AzDev/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/AzureDevOps/AzureDevOpsPipelineResourceParameter.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/AzureDevOps/AzureDevOpsRunResourcesParameters.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2281754&view=results
Rollout issue: https://github.com/dotnet/dnceng/issues/934
> [Rollout] Production rollout, 2023-10-04

- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/MaestroApplication/ApplicationPackageRoot/ApplicationManifest.xml
> Listen to HTTP on 8088

- src/Maestro/Maestro.Web/PackageRoot/ServiceManifest.xml
> Fix the http endpoint name

- src/Maestro/MaestroApplication/ApplicationPackageRoot/ApplicationManifest.xml
- src/Maestro/MaestroApplication/ApplicationParameters/Int.xml
- src/Maestro/MaestroApplication/ApplicationParameters/Prod.xml
> Implement the new HTTP endpoint like the original one

- src/Maestro/Maestro.Web/MaestroDelegatedStatelessWebService.cs
- src/Maestro/Maestro.Web/MaestroServiceHost.cs
- src/Maestro/Maestro.Web/MaestroServiceHostWebSite.cs
- src/Maestro/Maestro.Web/Program.cs
Adds a new ServiceInstanceListener for the new HTTP port
Add http listener
> Add Listener on the http endpoint

- .config/dotnet-tools.json
- Directory.Packages.props
- eng/Version.Details.xml
- eng/Versions.props
Resolves https://github.com/dotnet/arcade-services/issues/2991
bump `Azure.Identity` to 1.10.3
> bump Azure.Identity to 1.10.3

- src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrSyncCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
Fixes https://github.com/dotnet/arcade-services/issues/3024
Fixed determining of staged files in a local git repo
> Fix determining of staged files in a local git repo

- src/Maestro/Maestro.Web/Startup.cs
https://github.com/dotnet/arcade-services/issues/3004
The changes we did in https://github.com/dotnet/arcade-services/pull/3034 were not enough. They worked for the Authentication screen, but not for the actual login.
This change will make it so every.
According to [the official documentation](https://learn.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-7.0#forward-the-scheme-for-linux-and-non-iis-reverse-proxies:~:text=When%20it%20isn%27t%20possible%20to%20add%20forwarded%20headers%20and%20all%20requests%20are%20secure), this change is what we need
Change the request schema on every call to HTTPS
> Change the request schema on every call to HTTPS

- eng/templates/stages/deploy.yaml
https://github.com/dotnet/arcade-services/issues/3042
> Increase deployment and decrease E2E test stage timeouts

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
https://github.com/dotnet/arcade-services/issues/3059
> Fix the VMR commit change log

- global.json
Follow up after https://github.com/dotnet/arcade-services/issues/3053
Updated .NET to `8.0.100`
> Update SDK to `8.0.100`

- azure-pipelines.yml
A problem after downgrading the tests
https://github.com/dotnet/arcade-services/issues/3068
> Publish `net6.0` artifacts of `ScenarioTests`

- azure-pipelines.yml
Test pipeline: https://dev.azure.com/dnceng/internal/_build/results?buildId=2317181&view=results
https://github.com/dotnet/arcade-services/issues/3070
> Allow staging deployments from a dev branch

- azure-pipelines.yml
https://github.com/dotnet/arcade-services/issues/3076
Remove references to out-of-date variable groups and clean up YAML
> Remove references to out-of-date variable groups and clean up YAML

- src/Microsoft.DotNet.Darc/DarcLib/Helpers/GitRepoUrlParser.cs
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs
- test/Microsoft.DotNet.DarcLib.Tests/Helpers/GitRepoUrlParserTest.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
Adds missing tests and fixes some edge cases missed in https://github.com/dotnet/arcade-services/issues/3080
> Add unit tests for gradual fetching during VMR sync

- .vault-config/vmr-synchronization.1.yaml
- .vault-config/vmr-synchronization.2.yaml
https://github.com/dotnet/arcade-services/issues/3075
> Register VMR-sync-required secrets into the secret manifest

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
https://github.com/dotnet/arcade-services/issues/3075
> Log name of the patch that fail to apply

- .config/dotnet-tools.json
- azure-pipelines.yml
- eng/Version.Details.xml
- eng/Versions.props
- eng/templates/steps/test.yml
- src/Maestro/Maestro.DataProviders/DarcRemoteFactory.cs
- src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs
- src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/FileSystem.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/GitRepoType.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/GitRepoUrlParser.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/IFileSystem.cs
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalLibGit2Client.cs
- src/Microsoft.DotNet.Darc/DarcLib/RemoteConfiguration.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrGitClientFactory.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncRepoChangesTest.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- test/Microsoft.DotNet.DarcLib.Tests/Helpers/GitRepoUrlParserTest.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2321467&view=results
Rollout issue: https://github.com/dotnet/dnceng/issues/1475
> [Rollout] Production rollout, 2023-11-29

- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- test/Maestro.ScenarioTests/TestParameters.cs
Contributes to https://github.com/dotnet/arcade-services/issues/3031
Fix incorrect git args order for auth header
> fixup auth header git args

- .vault-config/maestrolocal.yaml
- .vault-config/shared/maestro-secrets.yaml
- azure-pipelines.yml
- docs/scenarios.md
- src/Maestro/Client/src/Generated/MaestroApi.cs
- src/Maestro/Client/src/Microsoft.DotNet.Maestro.Client.csproj
- src/Maestro/Maestro.Web/.config/settings.json
- src/Maestro/Maestro.Web/Properties/launchSettings.json
- src/Maestro/maestro-angular/src/maestro-client/generate-client.cmd
- src/Maestro/maestro-angular/src/maestro-client/maestro.ts
- src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs
- src/Microsoft.DotNet.Darc/Darc/Models/PopUps/AuthenticateEditorPopUp.cs
https://github.com/dotnet/arcade-services/issues/3094
Use the new maestro urls in Darc and BarViz
> Replace old Maestro url with the new one

- Directory.Packages.props
- src/Maestro/Maestro.Data/Maestro.Data.csproj
- src/Maestro/Maestro.Data/Models/MergePolicyDefinition.cs
- src/Maestro/Maestro.Data/SqlServerDbContextOptionsExtensions.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/Asset.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/AssetLocation.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/Build.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/Channel.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/DefaultChannel.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/MergePolicy.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/Subscription.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/SubscriptionPolicy.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Models/Build.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Models/Goal.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Models/Subscription.cs
- src/Maestro/Maestro.Web/Api/v2020_02_20/Models/Build.cs
- src/Maestro/Maestro.Web/Api/v2020_02_20/Models/Channel.cs
- src/Maestro/Maestro.Web/Api/v2020_02_20/Models/DefaultChannel.cs
- src/Maestro/Maestro.Web/Api/v2020_02_20/Models/Goal.cs
- src/Maestro/Maestro.Web/Api/v2020_02_20/Models/Subscription.cs
- src/Maestro/Maestro.Web/Maestro.Web.csproj
Things of a past that can be expressed via nullable references
https://github.com/dotnet/arcade-services/issues/3140
Removed `JetBrains.Annotations`
> Remove `JetBrains.Annotations`

- test/Maestro.ScenarioTests/EndToEndFlowLogic.cs
- test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
https://github.com/dotnet/arcade-services/issues/3031
Fixed a flaky PR title validation in E2E tests
> Fix PR title validation in E2E tests

- src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/ManifestRecord.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/ComponentListGenerator.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrRegistrations.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- test/Microsoft.DotNet.DarcLib.Tests/Models/VirtualMonoRepo/ManifestRecordTests.cs
Also adds a support for AzDO links
https://github.com/dotnet/arcade-services/issues/2917
Generates VMR component list in a separate file
> Move VMR component list out of main README

- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- test/Maestro.ScenarioTests/EndToEndFlowLogic.cs
- test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
https://github.com/dotnet/arcade-services/issues/3031
Fixed a flaky PR title validation in E2E tests
> Sort repo names in PR titles alphabetically

- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrRegistrations.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/WorkBranch.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/WorkBranchFactory.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
It is better to pass around a strong-typed class representing a repository rather than a path to a local dir.
https://github.com/dotnet/arcade-services/issues/3155
> Create a class representing a local git repository

- src/Microsoft.DotNet.Darc/Darc/Operations/GetAssetOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/GetAssetCommandLineOptions.cs
https://github.com/dotnet/arcade-services/issues/2600
Allow getting all assets belonging to a build via `darc get-asset`
> Allow getting assets by BAR build ID via `darc get-asset`

- azure-pipelines-product-construction-service.yml
- eng/templates/stages/deploy.yaml
My most [recent PR](https://github.com/dotnet/arcade-services/issues/3158) has some small issues that this one fixes.
Small fixes
> Fix docker image naming, e2e tests

- Directory.Build.props
- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
https://github.com/dotnet/arcade-services/issues/3165
Improve 403 (forbidden) result code handling for darc. accompany with guidance.
> darc gives SSO guidance when 403s happen

- Directory.Packages.props
https://github.com/dotnet/dnceng/issues/1782
Bump Asp and EF packages
> Bump Asp and EF packages

- Directory.Packages.props
- src/Maestro/Maestro.Data/Maestro.Data.csproj
- src/Microsoft.DotNet.Darc/DarcLib/Microsoft.DotNet.DarcLib.csproj
https://github.com/dotnet/dnceng/issues/1836
https://github.com/dotnet/dnceng/issues/1835
Bump more packages
> Bump more packages

- .vault-config/vmr-synchronization.1.yaml
https://github.com/dotnet/arcade-services/issues/3218
> Track a new VMR sync secret

- .vault-config/vmr-synchronization.1.yaml
Wrong scope set in https://github.com/dotnet/arcade-services/issues/3222
> Fix scope of a code read PAT

- azure-pipeline-codeql.yml
https://github.com/dotnet/arcade-services/issues/3234
> Fix the CodeQL pipeline

- docs/DevGuide.md
https://github.com/dotnet/arcade-services/issues/3254
> Add dev guide for SQL model changes

- docs/DevGuide.md
https://github.com/dotnet/arcade-services/issues/3254
> Add Maestro API Client dev guide instructions

- src/Microsoft.DotNet.Darc/DarcLib/Actions/Remote.cs
Introduced in https://github.com/dotnet/arcade-services/commit/40ea8783ac779ea6ee1772c92b52976ec9c88863#diff-b04b87ab9300230d2e6857992c070be5244011b05be3c1393ed57582f6c619cf
https://github.com/dotnet/arcade-services/issues/3264
> Fix an NRE when updating `eng/common` files

- src/Microsoft.DotNet.Darc/DarcLib/Actions/Remote.cs
Introduced in https://github.com/dotnet/arcade-services/commit/40ea8783ac779ea6ee1772c92b52976ec9c88863#diff-b04b87ab9300230d2e6857992c070be5244011b05be3c1393ed57582f6c619cf
https://github.com/dotnet/arcade-services/issues/3264
> Fix an NRE when updating `eng/common` files, part 2

- src/Microsoft.DotNet.Darc/Darc/Operations/AddSubscriptionOperation.cs
Fixes an NRE introduced in https://github.com/dotnet/arcade-services/issues/3281
> Fix NRE in `darc add subscription`

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
This PR doesn't solve https://github.com/dotnet/arcade-services/issues/3277 entirely but unblocks the synchronization with a (possibly unsafe) operation so that installer PR unified build legs get working again.
Fixes a problem with EOLs during VMR synchronization on Windows
> Work around problems with EOLs during Windows VMR syncs

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
This PR fixes a code path for recursive synchronization too which #3287 missed.
This PR doesn't solve https://github.com/dotnet/arcade-services/issues/3277 entirely but unblocks the synchronization with a (possibly unsafe) operation so that installer PR unified build legs get working again.
Fixes a problem with EOLs during VMR synchronization on Windows
> Work around problems with EOLs during Windows VMR syncs part 2

- eng/templates/steps/build.yml
- src/ProductConstructionService/ProductConstructionService.AppHost/Program.cs
Always use the latest released aspire version
> Always used the latest release aspire version

- azure-pipelines-product-construction-service.yml
https://github.com/dotnet/arcade-services/issues/3269
Don't include in release notes
> Fix displayName indentation

- eng/templates/steps/build.yml
- src/ProductConstructionService/ProductConstructionService.AppHost/Program.cs
> Do not force `dotnet-public` on Aspire installation

- Directory.Packages.props
https://github.com/dotnet/arcade-services/issues/3301
> Update NuGet.Packaging to resolve CG alert

- src/Maestro/Client/src/Build.cs
- src/Microsoft.DotNet.Darc/Darc/Helpers/UxHelpers.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/DeleteBuildFromChannelOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/UpdateDependenciesOperation.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrCodeflowTest.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
https://github.com/dotnet/arcade-services/issues/3253
Added support for forward-flowing BAR builds to the VMR
> Implement forward flow of builds

- Directory.Packages.props
- eng/templates/steps/build.yml
- global.json
- src/ProductConstructionService/ProductConstructionService.AppHost/Program.cs
- src/ProductConstructionService/Readme.md
> Bump aspire to preview3

- src/Maestro/README.md
I tried to document the flow that is mostly in https://github.com/dotnet/arcade-services/blob/main/src/Maestro/SubscriptionActorService/PullRequestActor.cs
https://github.com/dotnet/arcade-services/issues/3320
> Document dependency update flow

- src/Maestro/SubscriptionActorService/PullRequestActor.cs
> Add more logging to PR actor

- Directory.Packages.props
- eng/Version.Details.xml
- eng/Versions.props
- src/Maestro/Maestro.Web/Controllers/WebHooksController.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/Microsoft.DotNet.Maestro.Tasks.csproj
This is a special rollout to address https://github.com/dotnet/dnceng/issues/2065
> [HOTIX] Rollout 2024-02-27

- src/Maestro/Maestro.DataProviders/SqlBarClient.cs
- src/Microsoft.DotNet.Darc/Darc/Helpers/UxHelpers.cs
- test/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_sorted_text.verified.txt
- test/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_text.verified.txt
- test/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.cs
https://github.com/dotnet/arcade-services/issues/3255
Start displaying `SourceDirectory` property in subscription list
> Display `SourceDirectory` property in subscription list

- src/Microsoft.DotNet.Darc/DarcLib/TelemetryRecorder.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/ProductConstructionService/ProductConstructionService.Api/Controllers/CodeFlowController.cs
- src/ProductConstructionService/ProductConstructionService.Api/Controllers/Models/CreateBranchRequest.cs
- src/ProductConstructionService/ProductConstructionService.Api/InitializationBackgroundService.cs
- src/ProductConstructionService/ProductConstructionService.Api/Queue/JobProcessors/CodeFlowJobProcessor.cs
- src/ProductConstructionService/ProductConstructionService.Api/Queue/JobScope.cs
- src/ProductConstructionService/ProductConstructionService.Api/Queue/Jobs/CodeFlowJob.cs
- src/ProductConstructionService/ProductConstructionService.Api/Telemetry/TelemetryRecorder.cs
- test/ProductConstructionService.Api.Tests/JobScopeTests.cs
https://github.com/dotnet/arcade-services/issues/3316
> Enable pushing of code flow branches

- src/Microsoft.DotNet.Darc/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemoteGitRepo.cs
Functionality will be needed for https://github.com/dotnet/arcade-services/issues/3317 and https://github.com/dotnet/arcade-services/issues/3352
Added functionality to tell if a remote git branch exists
> Add "does branch exist" operation to git remotes

- eng/service-templates/ProductConstructionService/provision.bicep
https://github.com/dotnet/arcade-services/issues/3373
Update Container Registry bicep to use the premium SKU and add a retention policy
> Update Container Registry bicep

- src/Maestro/Maestro.Contracts/ISubscriptionActor.cs
- src/Maestro/SubscriptionActorService/ActionRunner/ActionResult.cs
- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- src/Maestro/SubscriptionActorService/PullRequestDescriptionBuilder.cs
- test/SubscriptionActorService.Tests/ActorTests.cs
- test/SubscriptionActorService.Tests/MockReminderManager.cs
- test/SubscriptionActorService.Tests/PullRequestActorTests.cs
- test/SubscriptionActorService.Tests/PullRequestDescriptionBuilderTests.cs
- test/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs
- test/SubscriptionActorService.Tests/SubscriptionActorService.Tests.csproj
- test/SubscriptionActorService.Tests/SubscriptionActorTests.cs
- test/SubscriptionActorService.Tests/SubscriptionOrPullRequestActorTests.cs
- test/SubscriptionActorService.Tests/TestsWithMocks.cs
This is a preparation for https://github.com/dotnet/arcade-services/issues/3317.
Hopefully no functional changes here, just enabling nullability which uncovered some interesting code paths that could be split.
> Enable nullability for Maestro actors

- src/Maestro/Maestro.DataProviders/SqlBarClient.cs
Resolves: https://github.com/dotnet/arcade-services/issues/3383
Fixed a problem with loading dependency graphs in BarViz
> Fix an NRE in BarViz

- src/Maestro/SubscriptionActorService/PullRequestActor.cs
Fixing a bug introduced in https://github.com/dotnet/arcade-services/issues/3381
Fixed a problem where PRs older than March 13th were not able to update anymore
> Forget the PR state when deserialization fails

- .config/dotnet-tools.json
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/SetupNugetSources.ps1
- eng/common/templates-official/job/job.yml
- eng/common/templates/job/job.yml
- global.json
- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- test/SubscriptionActorService.Tests/PendingUpdatesTests.cs
- test/SubscriptionActorService.Tests/PullRequestActorTests.cs
- test/SubscriptionActorService.Tests/UpdateAssetsTests.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2406092&view=results
> [Rollout] Production rollout, 2024-03-18

- eng/templates/stages/deploy.yaml
https://github.com/dotnet/arcade-services/issues/3396
> Fix approval stage after 1ES migration

- azure-pipelines.yml
> [HOTFIX] Use 1es-windows-2019

- eng/firewall.ps1
https://github.com/dotnet/arcade-services/issues/3419
Fixes the failing firewall.ps1 script and replaces `powershell` with `azure cli`. 
Use `azure cli` in `firewall.ps1`
> [HOTFIX] Rewrite firewall.ps1 using az cli instead of powershell modules

- eng/templates/stages/deploy.yaml
https://github.com/dotnet/arcade-services/issues/3408
We need to rollout Maestro ASAP. We're commenting out the part of the code that's causing the rollout to fail. There are no changes to bar models, so a migration is not needed. We'll revert this
Do not include in release notes
> [HOTFIX] comment out bar migration job

- src/Maestro/bootstrap.ps1
https://github.com/dotnet/arcade-services/issues/3434
> Make the bootstrap script not throw errors

- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- src/Maestro/SubscriptionActorService/PullRequestBuilder.cs
- test/SubscriptionActorService.Tests/PullRequestBuilderTests.cs
Chunking a future larger PR into smaller pieces
> Add generation of code flow PR titles and descriptions

- eng/templates/stages/secret-validation.yml
https://github.com/dotnet/arcade-services/issues/3396
> Fix the weekly pipeline after 1ES migration

- src/Maestro/Maestro.DataProviders/SqlBarClient.cs
Fixes https://github.com/dotnet/arcade-services/issues/3437
Fixes missing build number in Maestro PRs
> Copy all build fields

- .config/dotnet-tools.json
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/templates-official/job/job.yml
- eng/templates/stages/secret-validation.yml
- global.json
- src/Maestro/Maestro.DataProviders/DarcRemoteFactory.cs
- src/Maestro/Maestro.DataProviders/SqlBarClient.cs
- src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs
- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- src/Maestro/SubscriptionActorService/PullRequestBuilder.cs
- src/Maestro/bootstrap.ps1
- src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs
- src/Microsoft.DotNet.Darc/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemoteFactory.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/PcsConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/Program.cs
- test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
- test/SubscriptionActorService.Tests/PullRequestBuilderTests.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2414250&view=results
Rollout issue: https://github.com/dotnet/dnceng/issues/2351
> [Rollout] Production rollout, 2024-03-27

- src/Microsoft.DotNet.Darc/Darc/Operations/UpdateDependenciesOperation.cs
Fixes https://github.com/dotnet/arcade-services/issues/3447
Before, coherency was only updated along two paths in update-dependencies, and the set of dependencies fed to the coherency check was not the full set of repo dependencies. This meant that in some invocations, dependencies would be updated without corresponding coherency updates. Instead, always update coherency, and always pass the full set of dependencies to the coherency calc.
https://github.com/dotnet/arcade-services/issues/3447
> Always update coherency with update-dependencies

- eng/Version.Details.xml
- eng/Versions.props
- src/Microsoft.DotNet.Darc/Darc/Operations/UpdateDependenciesOperation.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2419537&view=results
Rollout issue: https://github.com/dotnet/dnceng/issues/2407
> [Rollout] Production rollout, 2024-04-03

- src/Maestro/maestro-angular/package-lock.json
This is connected to a package removal that happened here: https://github.com/dotnet/arcade-services/issues/3458
> Regenerate `package-lock.json`

- src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs
Fixes https://github.com/dotnet/arcade-services/issues/3479
Fixed calling `darc` commands with no authentication
> Fix calling `darc` without authentication

- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Found the problem here https://github.com/dotnet/installer/issues/19307
Clean ignored files properly during VMR syncs
> Clean also ignored files during VMR syncs

- docs/DevGuide.md
https://github.com/dotnet/arcade-services/issues/2995
> Update DevGuide with PCS<->Maestro debugging steps

- Directory.Packages.props
- docs/DevGuide.md
- global.json
- src/ProductConstructionService/ProductConstructionService.Api/Queue/QueueConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.AppHost/ProductConstructionService.AppHost.csproj
- src/ProductConstructionService/ProductConstructionService.AppHost/appsettings.Development.json
- src/ProductConstructionService/ProductConstructionService.ServiceDefaults/Extensions.cs
- src/ProductConstructionService/Readme.md
- test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
Updated PCS to use .NET Aspire preview 5
> Updated PCS to use .NET Aspire preview 5

- src/Microsoft.DotNet.Darc/Darc/Operations/Operation.cs
https://github.com/dotnet/arcade-services/issues/3507
Fixed `darc` telemetry initialization
> Fix telemetry initialization in `darc`

- azure-pipelines.yml
These were removed as all images now support PT
Resolves https://github.com/dotnet/arcade-services/issues/3482
> Stop using `-pt` images

- Directory.Packages.props
> Update NuGet packages to resolve CG warnings

- src/ProductConstructionService/Readme.md
https://github.com/dotnet/arcade-services/issues/3516
skip in release notes
> Update PCS MI docs

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Introduced in https://github.com/dotnet/arcade-services/pull/3411
Resolves https://github.com/dotnet/arcade-services/issues/3522
> Do not restore patches that will be added

- azure-pipelines.yml
- eng/templates/stages/deploy.yaml
https://github.com/dotnet/arcade-services/issues/3516
https://dev.azure.com/dnceng/internal/_workitems/edit/6146
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2444251&view=results
Authenticate Bar migrations using Managed Identity
> Authenticate Bar migrations using Managed Identity

- azure-pipelines.yml
- src/Maestro/DependencyUpdater/.config/settings.Production.json
- src/Maestro/FeedCleanerService/.config/settings.Production.json
- src/Maestro/Maestro.Web/.config/settings.Production.json
- src/Maestro/SubscriptionActorService/.config/settings.Production.json
https://github.com/dotnet/arcade-services/issues/3516
don't include
> [HOTFIX] Fix bar url

- eng/Version.Details.xml
- eng/Versions.props
- src/Maestro/DependencyUpdater/.config/settings.Development.json
- src/Maestro/DependencyUpdater/.config/settings.Production.json
- src/Maestro/DependencyUpdater/.config/settings.Staging.json
- src/Maestro/DependencyUpdater/.config/settings.json
- src/Maestro/FeedCleanerService/.config/settings.Development.json
- src/Maestro/FeedCleanerService/.config/settings.Production.json
- src/Maestro/FeedCleanerService/.config/settings.Staging.json
- src/Maestro/FeedCleanerService/.config/settings.json
- src/Maestro/Maestro.Web/.config/settings.Development.json
- src/Maestro/Maestro.Web/.config/settings.Production.json
- src/Maestro/Maestro.Web/.config/settings.Staging.json
- src/Maestro/Maestro.Web/.config/settings.json
- src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/SubscriptionsController.cs
- src/Maestro/MaestroCoreHealthMonitor/.config/settings.Development.json
- src/Maestro/MaestroCoreHealthMonitor/.config/settings.Production.json
- src/Maestro/MaestroCoreHealthMonitor/.config/settings.Staging.json
- src/Maestro/MaestroCoreHealthMonitor/.config/settings.json
- src/Maestro/SubscriptionActorService/.config/settings.Development.json
- src/Maestro/SubscriptionActorService/.config/settings.Production.json
- src/Maestro/SubscriptionActorService/.config/settings.Staging.json
- src/Maestro/SubscriptionActorService/.config/settings.json
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2453838&view=results
Rollout issue: https://github.com/dotnet/dnceng/issues/2898
> [Rollout] Production rollout, 2024-05-22

- src/Maestro/bootstrap.ps1
> Use local .NET when bootstrapping configuration

- .config/dotnet-tools.json
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/templates-official/job/source-index-stage1.yml
- eng/common/templates/job/source-index-stage1.yml
- global.json
- src/Maestro/DependencyUpdater/.config/settings.Development.json
- src/Maestro/DependencyUpdater/.config/settings.Production.json
- src/Maestro/DependencyUpdater/.config/settings.Staging.json
- src/Maestro/DependencyUpdater/.config/settings.json
- src/Maestro/Maestro.Web/.config/settings.Development.json
- src/Maestro/Maestro.Web/.config/settings.Production.json
- src/Maestro/Maestro.Web/.config/settings.Staging.json
- src/Maestro/Maestro.Web/.config/settings.json
- src/Maestro/SubscriptionActorService/.config/settings.Development.json
- src/Maestro/SubscriptionActorService/.config/settings.Production.json
- src/Maestro/SubscriptionActorService/.config/settings.Staging.json
- src/Maestro/bootstrap.ps1
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/DatabaseConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/PcsConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.json
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2461150&view=results
Rollout issue: https://github.com/dotnet/dnceng/issues/2950
> [Rollout] Production rollout, 2024-05-29

- Directory.Packages.props
- src/Maestro/Maestro.Authentication/AuthenticationConfiguration.cs
- src/Maestro/Maestro.Authentication/Maestro.Authentication.csproj
- src/Maestro/Maestro.Web/.config/settings.Production.json
- src/Maestro/Maestro.Web/.config/settings.Staging.json
- src/Maestro/Maestro.Web/Maestro.Web.csproj
- src/Maestro/Maestro.Web/Startup.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/AuthenticationConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/SwaggerConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/ProductConstructionService.Api.csproj
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json
- test/Maestro.Web.Tests/Maestro.Web.Tests.csproj
- test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
Supports both the current way (custom Maestro tokens) as well as tokens issued against the **Maestro (staging)** entra application
https://github.com/dotnet/dnceng/issues/2695
Maestro/PCS now support Entra-based auth
> Add Entra-based auth to Maestro and PCS

- src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs
Introduced in https://github.com/dotnet/arcade-services/issues/3561
> Fix an NRE in LocalSettings

- src/Maestro/Maestro.Authentication/AuthenticationConfiguration.cs
Bug introduced in https://github.com/dotnet/arcade-services/issues/3560
> Fix auth scheme selection

- azure-pipeline-weekly.yml
https://github.com/dotnet/dnceng/issues/2963
skip in release notes
> Synchronize secrets on Monday and Thursday

- src/Maestro/Maestro.Web/.config/settings.Production.json
https://github.com/dotnet/dnceng/issues/2695
Added support for Entra-based auth to Maestro
> Enable Entra auth in prod Maestro

- .vault-config/helixkv.yaml
- .vault-config/maestroint.yaml
- .vault-config/maestrolocal.yaml
- .vault-config/maestroprod.yaml
- .vault-config/product-construction-dev.yaml
- .vault-config/product-construction-int.yaml
- .vault-config/shared/maestro-secrets.yaml
- eng/templates/stages/deploy.yaml
- src/Maestro/Maestro.Web/.config/settings.json
- src/Maestro/MaestroCoreHealthMonitor/.config/settings.Development.json
- src/Maestro/MaestroCoreHealthMonitor/.config/settings.json
https://github.com/dotnet/arcade-services/issues/3566
Cleanup secrets that are no longer needed after migration to Managed Identities
> Cleanup secrets

- .vault-config/helixkv.yaml
- .vault-config/maestroint.yaml
- .vault-config/maestrolocal.yaml
- .vault-config/maestroprod.yaml
- .vault-config/product-construction-dev.yaml
- .vault-config/product-construction-int.yaml
- .vault-config/shared/maestro-secrets.yaml
- eng/templates/stages/deploy.yaml
- src/Maestro/Maestro.Web/.config/settings.json
- src/Maestro/MaestroCoreHealthMonitor/.config/settings.Development.json
- src/Maestro/MaestroCoreHealthMonitor/.config/settings.json
Reverts dotnet/arcade-services#3581
> Revert "Cleanup secrets"

- src/Maestro/Client/src/MaestroApi.cs
- src/Maestro/Client/src/MaestroApiCredential.cs
- src/Maestro/Client/src/MaestroApiFactory.cs
- src/Maestro/Client/src/MaestroApiOptions.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
- src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs
- src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs
- src/Microsoft.DotNet.Darc/Darc/Options/ICommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/BarApiClient.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/PcsConfiguration.cs
- test/Maestro.ScenarioTests/TestParameters.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
Adds federated credential authentication flow for Darc usage scenarios in AzDO pipelines - https://github.com/dotnet/dnceng/issues/2694
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2466299&view=logs&j=5d8dc80d-c400-5444-7559-06a7a0cb1d99&t=e8feac86-8f0f-5fe1-b2ef-d08c0cee394d
> Add federated creds auth flow

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
> Allow interactive login on Maestro task

- src/Maestro/Client/src/MaestroApi.cs
- src/Maestro/Client/src/MaestroApiCredential.cs
Fixes https://github.com/dotnet/dnceng/issues/3013
Fixed using darc with old Maestro URIs
> Make new darc auth work with old URIs

- .vault-config/product-construction-dev.yaml
- .vault-config/product-construction-int.yaml
https://github.com/dotnet/arcade-services/issues/3593
Don't include in release notes
> Put new subscritpion for PCS kvs

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
> Fix Maestro task interactive auth

- src/Microsoft.DotNet.Darc/Darc/Models/PopUps/AuthenticateEditorPopUp.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/AuthenticateOperation.cs
https://dev.azure.com/dnceng/internal/_workitems/edit/6441
> Update `darc authenticate` instructions

- src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs
> Improve the help string for the `IsCi` flag

- src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs
Do not warn about local settings when outputting JSON
> Do not warn about local settings when outputting JSON

- Directory.Packages.props
- src/Maestro/SubscriptionActorService/Program.cs
- src/Maestro/SubscriptionActorService/PullRequestPolicyFailureNotifier.cs
- src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs
- src/Microsoft.DotNet.Darc/Darc/Models/PopUps/AuthenticateEditorPopUp.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/AuthenticateOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs
- src/ProductConstructionService/ProductConstructionService.Client/PcsApiCredential.cs
- src/ProductConstructionService/ProductConstructionService.Client/PcsApiFactory.cs
- src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionService.Client.csproj
- src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionServiceApi.cs
- src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionServiceApiOptions.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2470752&view=results
Rollout issue: https://github.com/dotnet/dnceng/issues/3045
> [Rollout] Production rollout, 2024-06-11

- src/Maestro/Client/src/MaestroApi.cs
- src/Maestro/Client/src/MaestroApiCredential.cs
- src/Maestro/Client/src/MaestroApiFactory.cs
- src/Maestro/Client/src/MaestroApiOptions.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
- src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs
- src/Microsoft.DotNet.Darc/DarcLib/BarApiClient.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/PcsConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json
- src/ProductConstructionService/ProductConstructionService.Client/Generated/ProductConstructionServiceApi.cs
- src/ProductConstructionService/Readme.md
- test/Maestro.ScenarioTests/TestParameters.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
https://dev.azure.com/dnceng/internal/_workitems/edit/6451
Enable managed identity based auth for PCS->Maestro calls
> Use MI to call Maestro from PCS

- src/Microsoft.DotNet.Darc/Darc/Operations/UpdateDependenciesOperation.cs
- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
Related to a Teams thread where people reported some confusion about the error handling.
Improved error reporting in `darc update-dependencies`
> Improve logging for `darc update-dependencies`

- eng/enforce-issue.ps1
Test: https://dev.azure.com/dnceng/internal/_workitems/edit/6451
> Allow linking AzDO issues in PR descriptions

- src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs
> [Hotfix] Fix an NRE in darc

- azure-pipelines.yml
- eng/templates/stages/deploy.yaml
- test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
- test/Maestro.ScenarioTests/ScenarioTests_Channels.cs
- test/Maestro.ScenarioTests/TestParameters.cs
Resolves https://github.com/dotnet/arcade-services/issues/3629
Internal test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2473004&view=results
> Switch auth for scenario tests

- src/Maestro/Client/src/MaestroApiCredential.cs
Added support for system assigned managed identities in Maestro credential
> Support system assigned managed identities in Maestro credential

- src/Microsoft.DotNet.Darc/Darc/Operations/SetRepositoryMergePoliciesOperation.cs
> Improve error message when setting repository policies

- Directory.Packages.props
Fixes: https://github.com/dotnet/arcade-services/issues/3652
> Bump the Azure.Identity package version

- src/Microsoft.DotNet.Darc/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/GatherDropCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/HttpRequestManager.cs
Add support to use managed identity for gather drop operation instead of SAS tokens
https://dev.azure.com/dnceng/internal/_workitems/edit/6488
> Gather drop blob downloads without SAS tokens using Entra identity

- src/Maestro/Maestro.Common/Maestro.Common.csproj
Latest refactor of libraries ended up like this: https://github.com/dotnet/arcade/issues/14864
> Make `Maestro.Common` packable

- src/Maestro/DependencyUpdater/.config/settings.Production.json
- src/Maestro/DependencyUpdater/.config/settings.Staging.json
- src/Maestro/DependencyUpdater/.config/settings.json
- src/Maestro/FeedCleanerService/.config/settings.Production.json
- src/Maestro/FeedCleanerService/.config/settings.Staging.json
- src/Maestro/FeedCleanerService/.config/settings.json
- src/Maestro/Maestro.Web/.config/settings.Production.json
- src/Maestro/Maestro.Web/.config/settings.Staging.json
- src/Maestro/Maestro.Web/.config/settings.json
- src/Maestro/SubscriptionActorService/.config/settings.Production.json
- src/Maestro/SubscriptionActorService/.config/settings.Staging.json
- src/Maestro/SubscriptionActorService/.config/settings.json
- src/ProductConstructionService/Readme.md
This turns on features added in https://github.com/dotnet/arcade-services/issues/3662 for production environment
https://dev.azure.com/dnceng/internal/_workitems/edit/6419
> Use MIs in prod Maestro instead of AzDO tokens

- src/Maestro/maestro-angular/src/themes/_base.scss
Changes colours a bit to satisfy the low contrast on channel button hover
https://dev.azure.com/dnceng/internal/_workitems/edit/6102
> Fix contrast of channel buttons

- src/Maestro/Maestro.Web/Pages/_Layout.cshtml
Fixes https://dev.azure.com/dnceng/internal/_workitems/edit/6103
Fixes https://dev.azure.com/dnceng/internal/_workitems/edit/6101
Tracked by https://github.com/dotnet/arcade-services/issues/3589
> Fix a11y of main menu navigation

- src/Maestro/maestro-angular/src/app/app.component.html
- src/Maestro/maestro-angular/src/themes/_base.scss
- src/Maestro/maestro-angular/src/themes/dark/styles.scss
- src/Maestro/maestro-angular/src/themes/light/styles.scss
Fixes https://dev.azure.com/dnceng/internal/_workitems/edit/6103
Fixes https://dev.azure.com/dnceng/internal/_workitems/edit/6101
Tracked by https://github.com/dotnet/arcade-services/issues/3589
> Fix a11y of main menu navigation, part 2

- .github/ISSUE_TEMPLATE/rollout-issue.md
Minor improvement to rollout checklist discovered during https://github.com/dotnet/arcade-services/issues/3674
> Update instructions for rolled out issues

- .github/ISSUE_TEMPLATE/rollout-issue.md
- src/Maestro/maestro-angular/src/app/app.component.html
- src/Maestro/maestro-angular/src/themes/_base.scss
- src/Maestro/maestro-angular/src/themes/dark/styles.scss
- src/Maestro/maestro-angular/src/themes/light/styles.scss
https://github.com/dotnet/arcade-services/issues/3686
> [Rollout] Production rollout 2024-06-27

- eng/templates/stages/deploy.yaml
https://github.com/dotnet/arcade-services/issues/3694
There is something wrong with `az login`, we're doing this to unblock scenario tests while we investigate
issue https://github.com/dotnet/arcade-services/issues/3700
> Continue azure cli test on error

- Directory.Packages.props
Version update based on Component Governance vulnerability scan
https://github.com/dotnet/arcade-services/issues/3707
> Azure.Extensions.AspNetCore.DataProtection.Keys version update

- eng/service-templates/ProductConstructionService/provision.bicep
We were asked to add this tag to our VNet
https://github.com/dotnet/arcade-services/issues/3711
> Add required tag to PCS Vnet bicep

- Directory.Packages.props
Update version of Azure.Security.KeyVault.Keys nuget package
https://github.com/dotnet/arcade-services/issues/3708
> Version update for Azure.Security.KeyVault.Keys

- .config/dotnet-tools.json
- Directory.Packages.props
- eng/Version.Details.xml
- eng/Versions.props
- global.json
- src/Microsoft.DotNet.Darc/Darc/Operations/Operation.cs
https://github.com/dotnet/arcade-services/issues/3720
> Rollout hotfix to unbreak all publishing

- eng/common/post-build/publish-using-darc.ps1
> Temporarily hardcode darc version to unblock rollout

- eng/common/post-build/publish-using-darc.ps1
Reverts change made to unblock https://github.com/dotnet/arcade-services/issues/3724
> Revert hardcoded darc

- eng/templates/stages/deploy.yaml
Fixes indentation https://github.com/dotnet/arcade-services/issues/3694#issuecomment-2230845831
> Fix pipeline indentation

- src/Microsoft.DotNet.Darc/Darc/Operations/Operation.cs
resolves errors seen in https://github.com/dotnet/dnceng/issues/3464
> Register IRemoteTokenProvider

- Directory.Packages.props
- global.json
> Bump Aspire and .NET SDK

- src/Maestro/FeedCleanerService/Program.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/Operation.cs
- src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json
https://dev.azure.com/dnceng/internal/_workitems/edit/6699
> Fix AzDO client in local PCS runs

- src/Maestro/maestro-angular/src/app/app.component.html
- src/Maestro/maestro-angular/src/app/widget/side-bar/side-bar.component.html
Fixes https://dev.azure.com/dnceng/internal/_workitems/edit/6103
> Add aria labels to page navigations

- eng/templates/stages/deploy.yaml
- src/Maestro/Maestro.Authentication/AuthenticationConfiguration.cs
- src/Maestro/Maestro.Authentication/BarTokenAuthenticationHandler.cs
- src/Maestro/Maestro.Web/.config/settings.Development.json
- src/Maestro/Maestro.Web/.config/settings.Staging.json
- src/Maestro/Maestro.Web/.config/settings.json
- Fixes old BAR token validation
- Simplifies auth schemes by running all of them side-by-side (so that later we can add another Entra app easily)
https://dev.azure.com/dnceng/internal/_workitems/edit/6711
> Fix BAR token validation

- .vault-config/helixkv.yaml
- .vault-config/maestrolocal.yaml
- .vault-config/shared/maestro-secrets.yaml
https://dev.azure.com/dnceng/internal/_workitems/edit/6594
> Remove no longer needed secrets

- src/Maestro/Maestro.Authentication/AuthenticationConfiguration.cs
https://dev.azure.com/dnceng/internal/_workitems/edit/6711
> Fix role validation for BAR tokens

- .vault-config/product-construction-dev.yaml
- .vault-config/product-construction-int.yaml
- Directory.Packages.props
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/PcsConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/VirtualMonoRepo/VmrConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json
https://dev.azure.com/dnceng/internal/_workitems/edit/6420
> Stop using AzDO token in PCS, update Aspire to 8.1

- azure-pipelines.yml
Changes order of stages in YAML from this
to this
> Improve how the main pipeline is displayed in the UI

- src/Maestro/Maestro.Web/.config/settings.Staging.json
- src/Maestro/Maestro.Web/Startup.cs
https://dev.azure.com/dnceng/internal/_workitems/edit/6740
Allows to select better the MI we use for ApiRedirection
> Use system MI for Staging->Prod API redirection

- src/Microsoft.DotNet.Darc/Darc/Options/GetChannelCommandLineOptions.cs
https://github.com/dotnet/arcade-services/issues/3745
> Fix get channel output format

- Directory.Packages.props
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2005079/?view=edit
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2005078/?view=edit
> Bump Swagger/Swashbuckle

- src/Maestro/Maestro.Web/Pages/Account/AccountController.cs
- src/Maestro/Maestro.Web/Pages/_Layout.cshtml
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/2110747
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1866761
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1866760
> Fix un-escaped redirect paths

- src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs
- test/Maestro.Web.Tests/TestDatabase.cs
https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/1641611/
> Fix connection string CodeQL violations

- test/Microsoft.DotNet.Darc.Tests/DependencyRegistrationTests.cs
https://github.com/dotnet/arcade-services/issues/3785
> Fix Darc DI registration test and enable it

- test/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs
Tied to a fix of the test in https://github.com/dotnet/arcade-services/issues/3796
> Fix asset validation in E2E tests

- test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
https://github.com/dotnet/arcade-services/issues/3812
> Fix Darc GitHubFlow_NonBatched test

- src/Maestro/Client/src/MaestroApiFactory.cs
- src/Maestro/Client/src/MaestroApiOptions.cs
- src/Maestro/Maestro.Common/AppCredentials/AppCredential.cs
- src/Maestro/Maestro.Common/AppCredentials/AppCredentialResolver.cs
- src/Maestro/Maestro.Common/AppCredentials/CredentialResolverOptions.cs
- src/Maestro/Maestro.Common/AzureDevOpsTokens/AzureDevOpsTokenProvider.cs
- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
- src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs
- src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs
- src/Microsoft.DotNet.Darc/Darc/Options/ICommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/BarApiClient.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/PcsConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionServiceApiOptions.cs
- test/Maestro.ScenarioTests/TestParameters.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
Contributes to https://dev.azure.com/dnceng/internal/_workitems/edit/6604/
Follow-up to https://github.com/dotnet/arcade-services/pull/3817
Remove support for federated token authentication
> Remove federated token auth

- Directory.Packages.props
- azure-pipelines.yml
- eng/templates/stages/deploy.yaml
- src/Maestro/Client/src/MaestroApiFactory.cs
- src/Maestro/Client/src/MaestroApiOptions.cs
- src/Maestro/Maestro.Common/AppCredentials/AppCredential.cs
- src/Maestro/Maestro.Common/AppCredentials/AppCredentialResolver.cs
- src/Maestro/Maestro.Common/AppCredentials/CredentialResolverOptions.cs
- src/Maestro/Maestro.Common/AzureDevOpsTokens/AzureDevOpsTokenProvider.cs
- src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs
- src/Maestro/Maestro.Web/Pages/Account/AccountController.cs
- src/Maestro/Maestro.Web/Pages/_Layout.cshtml
- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
- src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs
- src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs
- src/Microsoft.DotNet.Darc/Darc/Options/ICommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/BarApiClient.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/PcsConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionServiceApiOptions.cs
- test/Maestro.ScenarioTests/EndToEndFlowLogic.cs
- test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
- test/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs
- test/Maestro.ScenarioTests/TestParameters.cs
- test/Maestro.Web.Tests/TestDatabase.cs
- test/Microsoft.DotNet.Darc.Tests/DependencyRegistrationTests.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
Rollout issue: https://github.com/dotnet/arcade-services/issues/3820
> Rollout 2024-08-13

- eng/service-templates/ProductConstructionService/provision.bicep
- eng/service-templates/ProductConstructionService/scheduledContainerJob.bicep
- src/ProductConstructionService/ProductConstructionService.Api/Dockerfile
- src/ProductConstructionService/Readme.md
https://github.com/dotnet/arcade-services/issues/3801
> Fix CWD when running container apps

- src/Maestro/maestro-angular/src/app/services/build-status.service.ts
- src/Maestro/maestro-angular/src/environments/environment.prod.ts
- src/Maestro/maestro-angular/src/environments/environment.ts
- src/ProductConstructionService/ProductConstructionService.Api/Dockerfile
- src/ProductConstructionService/ProductConstructionService.Api/Pages/Index.cshtml.cs
- src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
- src/ProductConstructionService/ProductConstructionService.Api/ProductConstructionService.Api.csproj
- src/ProductConstructionService/ProductConstructionService.Api/Program.cs
- src/ProductConstructionService/ProductConstructionService.Api/Queue/QueueConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/VirtualMonoRepo/VmrConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.json
- test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
https://github.com/dotnet/arcade-services/issues/3810
- Fixes globalization/culture problems - installs ICU + sets invariant globalization
- Stops Angular prefixing API paths with `_/` - no longer needed because we don't need to distinguish this case due to auth differences
- Turns on API redirection
> Fix remaining 500s on PCS BarViz

- src/Maestro/Client/src/Generated/Models/SubscriptionPolicy.cs
- test/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_json.verified.txt
> Output update frequency as string in json formatted output

- src/Maestro/Maestro.Web/Controllers/AzDevController.cs
- src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/IAzureDevOpsClient.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/ApiRedirection.cs
- src/ProductConstructionService/ProductConstructionService.Api/Controllers/AzDevController.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.json
https://github.com/dotnet/arcade-services/issues/3810
The controller was relaying all headers which were getting in conflict with the Entra auth on AzDO's side so we were getting 401s.
> Fix the AzDev controller

- azure-pipelines-product-construction-service.yml
- eng/deployment/product-construction-service-deploy.ps1
- eng/templates/stages/deploy.yaml
> Supply the right PCS token when starting the service

- azure-pipelines-product-construction-service.yml
Forgotten variables from https://github.com/dotnet/arcade-services/issues/3834
> Fix Maestro app ID variables

- src/Microsoft.DotNet.Darc/Darc/Operations/GetDefaultChannelsOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/GetDefaultChannelsCommandLineOptions.cs
> Support json format output and id query for get-default-channels

- src/ProductConstructionService/ProductConstructionService.Api/Dockerfile
Broken by https://github.com/dotnet/arcade-services/issues/3845
> Include the WorkItems project in Docker

- test/ProductConstructionService.Api.Tests/ApiTestConfiguration.cs
- test/ProductConstructionService.Api.Tests/BuildController20190116Tests.cs
- test/ProductConstructionService.Api.Tests/BuildController20200914Tests.cs
- test/ProductConstructionService.Api.Tests/ChannelsController20180716Tests.cs
- test/ProductConstructionService.Api.Tests/ChannelsController20200220Tests.cs
- test/ProductConstructionService.Api.Tests/DefaultChannelsController20200220Tests.cs
- test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
- test/ProductConstructionService.Api.Tests/LoggingConfigurationTests.cs
- test/ProductConstructionService.Api.Tests/ProductConstructionService.Api.Tests.csproj
- test/ProductConstructionService.Api.Tests/RepositoryUrlAttributeTests.cs
- test/ProductConstructionService.Api.Tests/SubscriptionsController20200220Tests.cs
- test/ProductConstructionService.Api.Tests/TestDatabase.cs
Resolves https://github.com/dotnet/arcade-services/issues/3848
> Migrate `Maestro.Web.Tests` to `PCS.Api.Tests`

- eng/service-templates/ProductConstructionService/provision.bicep
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/DataProtection.cs
- src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json
Resolves https://github.com/dotnet/arcade-services/issues/3815
> Enable data protection

- src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
- src/ProductConstructionService/ProductConstructionService.Api/Program.cs
- src/ProductConstructionService/ProductConstructionService.Common/ProductConstructionServiceExtension.cs
- src/ProductConstructionService/ProductConstructionService.Common/StateManager.cs
- src/ProductConstructionService/ProductConstructionService.Common/StateManagerFactory.cs
- test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
- test/ProductConstructionService.Api.Tests/LoggingConfigurationTests.cs
Resolves https://github.com/dotnet/arcade-services/issues/3805
Adds a State Manager and its factory for managing Redis connection
> Add state manager

- src/ProductConstructionService/ProductConstructionService.Api/Pages/DependencyFlow/Incoming.cshtml.cs
Porting https://github.com/dotnet/arcade-services/issues/3869
> Port changes of Maestro's Incoming page to PCS

- azure-pipelines-pr.yml
- azure-pipelines-product-construction-service.yml
- eng/templates/steps/docker-build.yml
- eng/templates/steps/test.yml
- src/ProductConstructionService/ProductConstructionService.Api/Dockerfile
https://github.com/dotnet/arcade-services/issues/3852
> Build docker during pr

- azure-pipelines-product-construction-service.yml
- eng/service-templates/ProductConstructionService/provision.bicep
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/DataProtection.cs
- src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemConfiguration.cs
https://github.com/dotnet/arcade-services/issues/3815
> Fix data protection related deployment errors

- src/ProductConstructionService/ProductConstructionService.DependencyFlow/Properties/AssemblyInfo.cs
- test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
https://github.com/dotnet/arcade-services/issues/3807
> Cover PR actors with DI tests

- test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
- test/Maestro.ScenarioTests/ScenarioTests_AzDoFlow.cs
- test/Maestro.ScenarioTests/ScenarioTests_Channels.cs
- test/Maestro.ScenarioTests/ScenarioTests_DefaultChannels.cs
- test/Maestro.ScenarioTests/ScenarioTests_Dependencies.cs
- test/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs
- test/Maestro.ScenarioTests/ScenarioTests_RepoPolicies.cs
- test/Maestro.ScenarioTests/ScenarioTests_Subscriptions.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests_AzDoFlow.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests_Channels.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests_DefaultChannels.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests_Dependencies.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests_GitHubFlow.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests_RepoPolicies.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests_Subscriptions.cs
https://github.com/dotnet/arcade-services/issues/3837
> Use unique branch/channel names per each test

- src/ProductConstructionService/ProductConstructionService.AppHost/Program.cs
> Hardcode Redis port in local devenv

- azure-pipelines-product-construction-service.yml
> Batch PCS pipeline runs

- eng/service-templates/ProductConstructionService/provision.bicep
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json
- src/ProductConstructionService/ProductConstructionService.SubscriptionTriggerer/SubscriptionTriggerer.cs
- test/ProductConstructionService.Api.Tests/ApiTestConfiguration.cs
> Fix DLL path in container jobs

- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemoteGitRepo.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.json
- test/Microsoft.DotNet.DarcLib.Tests/GitHubClientTests.cs
Got broken in https://github.com/dotnet/arcade-services/commit/f3171a145ce3bdf15ca303a095e24141e7bcab67
Resolves https://github.com/dotnet/arcade-services/issues/3906
> Fix PCS->GitHub app based auth

- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json
https://github.com/dotnet/arcade-services/issues/3901
> Stop redirecting PCS INT to PROD

- src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionServiceApiOptions.cs
https://github.com/dotnet/arcade-services/issues/3901
> Fix PCS client not sending the authorization header

- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json
https://github.com/dotnet/arcade-services/issues/3805
> Fix redis connection by turning on SSL

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCloneManager.cs
- src/ProductConstructionService/ProductConstructionService.Api/InitializationBackgroundService.cs
> Fix VMR initialization and clone the URI from configuration

- src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.json
> Silence noisy SQL logging in INT

- .vault-config/product-construction-dev.yaml
- azure-pipelines-product-construction-service.yml
- eng/templates/jobs/e2e-pcs-tests.yml
- eng/templates/steps/docker-build.yml
https://github.com/dotnet/arcade-services/issues/3901
> Run scenario tests in PCS pipeline

- .github/ISSUE_TEMPLATE/rollout-issue.md
We recently updated the Scenario Test stage name, but didn't update the kusto query. This PR fixes it
https://github.com/dotnet/arcade-services/issues/3923
> Update Kusto query in rollout issue

- azure-pipelines-product-construction-service.yml
- eng/templates/jobs/e2e-pcs-tests.yml
- test/ProductConstructionService.ScenarioTests/TestParameters.cs
> Fix building repo in PCS pipeline & fix PCS token in E2E tests

- eng/service-templates/ProductConstructionService/container-app.bicep
- eng/service-templates/ProductConstructionService/container-environment.bicep
- eng/service-templates/ProductConstructionService/container-registry.bicep
- eng/service-templates/ProductConstructionService/key-vaults.bicep
- eng/service-templates/ProductConstructionService/managed-identities.bicep
- eng/service-templates/ProductConstructionService/nsg.bicep
- eng/service-templates/ProductConstructionService/provision.bicep
- eng/service-templates/ProductConstructionService/redis.bicep
- eng/service-templates/ProductConstructionService/scheduledContainerJob.bicep
- eng/service-templates/ProductConstructionService/storage-account.bicep
- eng/service-templates/ProductConstructionService/virtual-network.bicep
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json
https://github.com/dotnet/arcade-services/issues/3913
https://github.com/dotnet/arcade-services/issues/3899
> Refactor bicep, change redis name

- src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
- src/ProductConstructionService/ProductConstructionService.Api/Program.cs
- src/ProductConstructionService/ProductConstructionService.Common/MetricRecorder.cs
- src/ProductConstructionService/ProductConstructionService.Common/ProductConstructionServiceExtension.cs
- src/ProductConstructionService/ProductConstructionService.ServiceDefaults/Extensions.cs
- src/ProductConstructionService/ProductConstructionService.ServiceDefaults/ProductConstructionService.ServiceDefaults.csproj
- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItem.cs
- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemConsumer.cs
- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemProducer.cs
- test/ProductConstructionService.DependencyFlow.Tests/UpdaterTests.cs
https://github.com/dotnet/arcade-services/issues/3933
> Measure time messages wait in the work item queue

- src/ProductConstructionService/ProductConstructionService.Common/RedisCache.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
> Increase wait time in PCS E2E tests

- src/ProductConstructionService/ProductConstructionService.BarViz/Layout/NavMenu.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Build.razor
just adds an empty build page where we'll add other components.
It's set to a static page right now, we'll add the attributes and routing later
> Add build page

- src/ProductConstructionService/ProductConstructionService.BarViz/Components/Subscriptions.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Build.razor
> Add subscriptions component

- src/ProductConstructionService/ProductConstructionService.BarViz/Components/Assets.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Build.razor
> add assets component

- src/ProductConstructionService/ProductConstructionService.BarViz/Layout/NavMenu.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Properties/launchSettings.json
> Add channel filter

- src/ProductConstructionService/ProductConstructionService.BarViz/Layout/NavMenu.razor
> Add query params for channel filtering

- src/ProductConstructionService/ProductConstructionService.BarViz/Components/ChannelNavMenuItem.razor
> Show message when a channel has no repos

- src/ProductConstructionService/ProductConstructionService.BarViz/App.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/SiteSettingsPanel.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Layout/MainLayout.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/wwwroot/css/app.css
> Add theme selection

- src/ProductConstructionService/ProductConstructionService.BarViz/Components/Assets.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/Subscriptions.razor
> Stretch and style the assets/subscriptions

- src/ProductConstructionService/ProductConstructionService.BarViz/Components/ChannelNavMenuItem.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/FocusedChannelsSection.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Layout/NavMenu.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/ProductConstructionService.BarViz.csproj
- src/ProductConstructionService/ProductConstructionService.BarViz/wwwroot/css/app.css
- src/ProductConstructionService/ProductConstructionService.BarViz/wwwroot/index.html
> Add focused channels section

- src/ProductConstructionService/ProductConstructionService.Api/Controllers/AzDoController.cs
- src/ProductConstructionService/ProductConstructionService.Api/Controllers/Models/AzDoBuild.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Code/Helpers/DateFormatter.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/BuildInfo.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Build.razor
- src/ProductConstructionService/ProductConstructionService.Client/Generated/AzDo.cs
- src/ProductConstructionService/ProductConstructionService.Client/Generated/Models/AzDoBuild.cs
- src/ProductConstructionService/ProductConstructionService.Client/Generated/ProductConstructionServiceApi.cs
> Add ongoing and latest failed builds to BuildInfo

- src/ProductConstructionService/ProductConstructionService.BarViz/Code/Helpers/BuildGraphData.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Code/Helpers/BuildHelper.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Code/Helpers/BuildTreeViewItem.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/BuildInfo.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/Dependencies.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/Dependencies.razor.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/DependencyGrid.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/DependencyGrid.razor.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/DependencyTree.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Build.razor
> Add DependencyTree tab

- Directory.Packages.props
- src/ProductConstructionService/ProductConstructionService.BarViz/Components/FocusedChannelsSection.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Layout/NavMenu.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/ProductConstructionService.BarViz.csproj
- src/ProductConstructionService/ProductConstructionService.BarViz/Program.cs
> Add storage for focused channels

- src/ProductConstructionService/ProductConstructionService.BarViz/Layout/NavMenu.razor
> Remove empty categories

- test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
- test/Maestro.ScenarioTests/TestParameters.cs
Resolves: https://github.com/dotnet/arcade-services/issues/4012
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2550068&view=results
> Make azdo token optional for local scenario test run

- .config/dotnet-tools.json
- eng/Version.Details.xml
- eng/Versions.props
- global.json
- test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
- test/Maestro.ScenarioTests/TestParameters.cs
https://github.com/dotnet/arcade-services/issues/4015
> Rollout 2024-10-02

- src/ProductConstructionService/ProductConstructionService.Deployment/Deployer.cs
Fixes minor issue with using Azure CLI in Deployer service introduced by https://github.com/dotnet/arcade-services/issues/3937
Successful build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2555373&view=results
> Fixup deployer invoking azure cli

- src/ProductConstructionService/ProductConstructionService.BarViz/Layout/NavMenu.razor
> Fix an NRE in front-end with INT/local data

- azure-pipeline-weekly.yml
> Fix the weekly pipeline (move to windows 2022)

- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/ProductConstructionService.DependencyFlow.Tests/PendingCodeFlowUpdatesTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/PendingUpdatePullRequestUpdaterTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/UpdateAssetsForCodeFlowTests.cs
Resolves https://github.com/dotnet/arcade-services/issues/4038
> Update codeflow PR title/descriptions with every update

- .vault-config/product-construction-prod.yaml
- azure-pipelines-product-construction-service.yml
- eng/service-templates/ProductConstructionService/container-environment.bicep
- eng/service-templates/ProductConstructionService/managed-identities.bicep
- eng/service-templates/ProductConstructionService/production.bicepparam
- eng/service-templates/ProductConstructionService/provision.bicep
- eng/service-templates/ProductConstructionService/provision.ps1
- eng/service-templates/ProductConstructionService/redis.bicep
- eng/service-templates/ProductConstructionService/staging.bicepparam
- eng/templates/jobs/e2e-pcs-tests.yml
- eng/templates/steps/docker-build.yml
- src/Maestro/Client/src/MaestroApiOptions.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Production.json
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json
- src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionServiceApiOptions.cs
- src/ProductConstructionService/ProductConstructionService.Deployment/Deployer.cs
- src/ProductConstructionService/ProductConstructionService.FeedCleaner/appsettings.Production.json
- src/ProductConstructionService/ProductConstructionService.LongestBuildPathUpdater/appsettings.Production.json
- src/ProductConstructionService/ProductConstructionService.SubscriptionTriggerer/appsettings.Production.json
- src/ProductConstructionService/Readme.md
https://github.com/dotnet/arcade-services/issues/3799
> Add PCS prod environment

- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.json
- src/ProductConstructionService/ProductConstructionService.Common/MetricRecorder.cs
- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemConsumer.cs
- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemProcessorState.cs
- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemScopeManager.cs
- test/ProductConstructionService.WorkItem.Tests/WorkItemsProcessorScopeManagerTests.cs
Resolves https://github.com/dotnet/arcade-services/issues/4022
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2560100&view=results
> Add multiple work item consumers

- arcade-services.sln
Probably something from the past - references to files that do not exist in the repo
> Remove non-existing files from main solution

- src/ProductConstructionService/ProductConstructionService.Api/Controllers/StatusController.cs
- src/ProductConstructionService/ProductConstructionService.WorkItems/ReplicaWorkItemProcessorStateCache.cs
https://github.com/dotnet/arcade-services/issues/4086
> Fix the new deployment

- src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleaner.cs
https://github.com/dotnet/core-eng/issues/9366
> Do not delete feeds in feed cleaner

- src/Maestro/FeedCleanerService/.config/settings.Production.json
https://github.com/dotnet/arcade-services/issues/4073
> Disable Maestro's feed cleaner in PROD

- src/ProductConstructionService/ProductConstructionService.BarViz/Components/DependencyGrid.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Layout/MainLayout.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Build.razor
- src/ProductConstructionService/Readme.md
https://github.com/dotnet/arcade-services/issues/4044
https://github.com/dotnet/arcade-services/issues/4047
> Add channel to page title and fix staleness

- src/ProductConstructionService/ProductConstructionService.Cli/Operations/DeploymentOperation.cs
https://github.com/dotnet/arcade-services/issues/4103
> Deactivate previous revision after a succesfull deployment

- eng/templates/stages/deploy.yaml
Contributes to https://github.com/dotnet/arcade-services/issues/4081
Fixes a small mistake in GitHub token name made in https://github.com/dotnet/arcade-services/pull/4106
> Fixup GitHub token name

- eng/templates/jobs/e2e-pcs-tests.yml
Contributes to https://github.com/dotnet/arcade-services/issues/4081
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2571742&view=results
> Remove obsolete var group

- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/MsBuildPropsFile.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrCodeflowTest.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
https://github.com/dotnet/arcade-services/issues/4029
> Add support for forward flowing dependency updates

- src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/SourceMapping.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/SourceMappingFile.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/SourceMappingParser.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/Constants.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrRecursiveSyncTests.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsOneTimeSetUp.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
https://github.com/dotnet/arcade-services/issues/4158
> Add `disableSynchronization` option to vmr source mappings

- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/BackflowOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/ForwardFlowOperation.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrBackFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrBackflowTest.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
Resolves https://github.com/dotnet/arcade-services/issues/3354
> Ignore excluded assets in codeflow updates

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Follow-up for https://github.com/dotnet/arcade-services/issues/4164
> Log when we skip disabled VMR mappings

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Resolves https://github.com/dotnet/arcade-services/issues/4187
> Order VMR patches before stripping/restoration

- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrUpdater.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrBackflowTest.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- Generate component list & third party notices
- Reapply VMR patches correctly
> Configure forward flow correctly

- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTwoWayCodeflowTest.cs
This adds a test that detects conflicts in version files (other files are not in conflict).
I believe we will want to eventually try to resolve these because we might be hitting this exact conflict in our day-to-day flows.
Once we resolve this, this test should start failing because the conflict goes away.
https://github.com/dotnet/arcade-services/issues/3318
> Add a test for out-of-order merging without conflicts

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCloneManager.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
https://github.com/dotnet/arcade-services/issues/3318
> Create and assign issues to TODOs

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CloneManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCloneManager.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
https://github.com/dotnet/arcade-services/issues/4197
> Clean up clones before usage

- src/Microsoft.DotNet.Darc/DarcLib/Models/Darc/DependencyGraph.cs
Fixes https://github.com/dotnet/arcade-services/issues/4213
> Fix asset comparison during graph building

- azure-pipelines-product-construction-service.yml
https://github.com/dotnet/arcade-services/issues/3455
> Add an approval stage to the PCS pipeline

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/WorkBranch.cs
https://github.com/dotnet/arcade-services/issues/4109
> Squash merge commits in VMR sync

- azure-pipelines-product-construction-service.yml
- eng/templates/stages/deploy.yaml
Broke in https://github.com/dotnet/arcade-services/issues/4230
> Fix approval stages

- test/ProductConstructionService.ScenarioTests/CodeFlowScenarioTestBase.cs
- test/ProductConstructionService.ScenarioTests/EndToEndFlowLogic.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_AzDoFlow.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_Builds.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_GitHubFlow.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_MergePolicies.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_SdkUpdate.cs
https://github.com/dotnet/arcade-services/issues/4172
https://github.com/dotnet/arcade-services/issues/4210
> Delete PR branches after scenario tests

- src/ProductConstructionService/ProductConstructionService.AppHost/Program.cs
https://github.com/dotnet/aspire/issues/5078
> Remove Aspire workaround for local Redis

- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrBackflowTest.cs
https://github.com/dotnet/arcade-services/issues/4196
> Add a test around version files of follow-up backflow updates

- src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/PullRequestController.cs
Failed to parse repositories that do not conform to our naming
> Fix an exception in the PR controller

- azure-pipelines.yml
https://github.com/dotnet/arcade-services/issues/3455
> Remove job dependency in BAR publishing

- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/PullRequests.razor
https://github.com/dotnet/arcade-services/issues/4268
> Fix sorting on the tracked pull requests page

- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
https://github.com/dotnet/arcade-services/issues/4280
> Add exception logging to GetPullRequestStatus

- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
https://github.com/dotnet/arcade-services/issues/4282
> Rollout 2024-12-30

- .github/ISSUE_TEMPLATE/rollout-issue.md
https://github.com/dotnet/arcade-services/issues/4241
> Update rollout instructions

- src/ProductConstructionService/ProductConstructionService.WorkItems/ReminderManager.cs
https://github.com/dotnet/arcade-services/issues/4277
> Check if a reminder already exists when trying to set one

- src/ProductConstructionService/ProductConstructionService.Api/Pages/Error.cshtml
- src/ProductConstructionService/ProductConstructionService.Api/Pages/Error.cshtml.cs
- src/ProductConstructionService/ProductConstructionService.Api/Program.cs
Reverts dotnet/arcade-services#4287
> Revert "Remove unused error page, fix OPTIONS requests"

- src/ProductConstructionService/ProductConstructionService.Api/Pages/Error.cshtml
- src/ProductConstructionService/ProductConstructionService.Api/Pages/Error.cshtml.cs
- src/ProductConstructionService/ProductConstructionService.Api/Program.cs
Rolling out a revert of the OPTIONS fix
https://github.com/dotnet/arcade-services/issues/4288
> [Rollout] Production rollout 2025-01-02 part 2

- .github/ISSUE_TEMPLATE/rollout-issue.md
> Make the rollout process more lightweight

- eng/service-templates/ProductConstructionService/FullCreate/staging.bicepparam
https://github.com/dotnet/arcade-services/issues/4309
> Fix bicep resource names

- .github/ISSUE_TEMPLATE/rollout-issue.md
> Remove rollout instructions around the rollout column

- .config/dotnet-tools.json
- .github/ISSUE_TEMPLATE/rollout-issue.md
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/templates/job/job.yml
- global.json
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/RemoteRepoBase.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrUpdater.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/ProductConstructionServiceApiOptions.cs
- src/ProductConstructionService/ProductConstructionService.ReproTool/ReproTool.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/GitOperationsHelper.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrBackflowTest.cs
Rollout issue: https://github.com/dotnet/arcade-services/issues/4326
> [Rollout] Production rollout 2025-01-15

- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemScope.cs
Resolves https://github.com/dotnet/arcade-services/issues/4329
> Fixup missing operation id for work item scope

- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemScope.cs
Fix for https://github.com/dotnet/arcade-services/issues/4330
> Log work item result within operation's logging scope

- src/Microsoft.DotNet.Darc/DarcLib/Remote.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInfo.cs
Path was not properly cleaned, so the eng/common/file.txt wasn't appearing in the target repo
https://github.com/dotnet/arcade-services/issues/4253
> Fix Vmr Arcade Sdk Update Scenario test

- src/Microsoft.DotNet.Darc/DarcLib/LocalLibGit2Client.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/SourceManifest.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrRegistrations.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrRepoDeletionTest.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncRepoChangesTest.cs
- test/ProductConstructionService.ScenarioTests/CodeFlowScenarioTestBase.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlow.cs
https://github.com/dotnet/arcade-services/issues/3378
> Add support for batchable forward flow subscriptions

- README.md
- src/ProductConstructionService/DependencyFlowProcess.md
We lot this document during https://github.com/dotnet/arcade-services/issues/4293
> Revive the dependency flow diagram

- eng/new-issue.ps1
https://github.com/dotnet/arcade-services/issues/4371
> Add a script for creating new issues quickly

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Fixes https://github.com/dotnet/arcade-services/issues/4377
> Fix VMR patch restoration

- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/ForwardFlowOperation.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
Broken by https://github.com/dotnet/arcade-services/issues/4376
> Fix VMR cloning in PCS

- src/Maestro/Maestro.Common/AppCredentials/CredentialResolverOptions.cs
- src/Maestro/Maestro.Common/AzureDevOpsTokens/AzureDevOpsTokenProvider.cs
- test/ProductConstructionService.ScenarioTests/TestParameters.cs
https://github.com/dotnet/arcade-services/issues/4393
> Remove use of local credentials

- eng/Version.Details.xml
- eng/Versions.props
- src/Maestro/Maestro.Common/AppCredentials/CredentialResolverOptions.cs
- src/Maestro/Maestro.Common/AzureDevOpsTokens/AzureDevOpsTokenProvider.cs
- src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemoteGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/Remote.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/Exceptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/SubscriptionsController.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Subscriptions.razor
- src/ProductConstructionService/ProductConstructionService.Common/RedisCache.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/InProgressPullRequest.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/WorkItems/SubscriptionUpdateWorkItem.cs
- test/ProductConstructionService.DependencyFlow.Tests/MockRedisCache.cs
- test/ProductConstructionService.DependencyFlow.Tests/PendingCodeFlowUpdatesTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/UpdateAssetsForCodeFlowTests.cs
- test/ProductConstructionService.ScenarioTests/CodeFlowScenarioTestBase.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlow.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlowConflicts.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_SdkUpdate.cs
- test/ProductConstructionService.ScenarioTests/TestParameters.cs
- test/ProductConstructionService.WorkItem.Tests/FakeRedisCache.cs
Rollout issue: https://github.com/dotnet/arcade-services/issues/4399
> [Rollout] Production rollout 2025-01-31

- src/ProductConstructionService/ProductConstructionService.Api/Program.cs
https://github.com/dotnet/arcade-services/issues/4410
> Enable Http Logging in PCS

- src/ProductConstructionService/ProductConstructionService.Api/Api/GitHubInstallationIdResolver.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2018_07_16/Controllers/SubscriptionsController.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2019_01_16/Controllers/SubscriptionsController.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/SubscriptionsController.cs
- src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
- test/ProductConstructionService.Api.Tests/SubscriptionsController20200220Tests.cs
https://github.com/dotnet/arcade-services/issues/4426
> Resolve installation ID when missing

- src/Microsoft.DotNet.Darc/DarcLib/Helpers/HttpRequestManager.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/GitHubInstallationIdResolver.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2018_07_16/Controllers/SubscriptionsController.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2019_01_16/Controllers/SubscriptionsController.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/SubscriptionsController.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/SubscriptionTriggerConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
- test/ProductConstructionService.Api.Tests/SubscriptionsController20200220Tests.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_Dependencies.cs
https://github.com/dotnet/arcade-services/issues/4434
> [Rollout] Production rollout 2025.02.10

- src/Microsoft.DotNet.Darc/Darc/Operations/GetAssetOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/GetAssetCommandLineOptions.cs
> Add latest option to get-asset operation

- eng/templates/jobs/darc-and-api-tests.yml
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
https://github.com/dotnet/arcade-services/issues/4425
> Fix AzDo tests broken in #4440

- src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/ProductConstructionServiceApi.cs
https://teams.microsoft.com/l/message/19:afba3d1545dd45d7b79f34c1821f6055@thread.skype/1739370352933?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&parentMessageId=1739370352933&teamName=.NET%20Core%20Eng%20Services%20Partners&channelName=First%20Responders&createdTime=1739370352933
> Add a link to `Darc.md` during auth issues in darc

- src/ProductConstructionService/ProductConstructionService.Api/Api/v2018_07_16/Controllers/SubscriptionsController.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/SubscriptionTriggerConfiguration.cs
https://github.com/dotnet/arcade-services/issues/4454
> Improve logging when triggering subscriptions

- Directory.Packages.props
- src/ProductConstructionService/ProductConstructionService.BarViz/_Imports.razor
Resolves https://github.com/dotnet/arcade-services/issues/4456
> Bump FluentUi to 4.11.4

- src/Microsoft.DotNet.Darc/Darc/Helpers/UxHelpers.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/ForwardFlowOperation.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/CodeFlowResult.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrBackFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/Build.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/IPullRequestUpdater.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/PendingCodeFlowUpdatesTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestBuilderTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/SubscriptionUpdaterTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/UpdateAssetsForCodeFlowTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/UpdaterTests.cs
- test/ProductConstructionService.SubscriptionTriggerer.Tests/SubscriptionTriggererTests.cs
https://github.com/dotnet/arcade-services/issues/3364
> Finalize codeflow pr description

- src/Microsoft.DotNet.Darc/DarcLib/LocalLibGit2Client.cs
https://github.com/dotnet/arcade-services/issues/4199
> Add a basic retry around git push

- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Subscriptions.razor
Resolves https://github.com/dotnet/arcade-services/issues/4455
> Add sub filter to address query

- src/ProductConstructionService/ProductConstructionService.Cli/Operations/DeploymentOperation.cs
- src/ProductConstructionService/ProductConstructionService.WorkItems/LocalReplicaWorkItemProcessorStateCacheFactory.cs
- src/ProductConstructionService/ProductConstructionService.WorkItems/ReplicaWorkItemProcessorStateCache.cs
Resolves https://github.com/dotnet/arcade-services/issues/4350
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2650120&view=results
> Activate new revision before stopping the current one

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CodeFlowVmrUpdater.cs
https://github.com/dotnet/arcade-services/issues/4485#issue-2875299411
> Don't generate codeowners during PCS flows

- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
https://github.com/dotnet/arcade-services/issues/4351
Making the VmrCodeflower more slim with stuff that does not belong there
> Pull git operations from `VmrCodeflower` to git clients

- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/SubscriptionPullRequestUpdate.cs
- test/ProductConstructionService.DependencyFlow.Tests/PendingCodeFlowUpdatesTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestBuilderTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestPolicyFailureNotifierTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/UpdateAssetsForCodeFlowTests.cs
https://github.com/dotnet/arcade-services/issues/4406#issue-2823535440
> Implement batched codeflow PR description & title

- src/ProductConstructionService/ProductConstructionService.Api/Api/v2018_07_16/Models/AssetData.cs
Rollout Issue:
https://github.com/dotnet/arcade-services/issues/4517
> Asset name length updated according to database field (#4516)

- src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/FeedConstants.cs
- src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerJob.cs
https://github.com/dotnet/arcade-services/issues/4467
> Precompile regexes used in `FeedCleaner`

- src/Microsoft.DotNet.Darc/DarcLib/Helpers/FeedConstants.cs
- src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerJob.cs
https://github.com/dotnet/arcade-services/issues/4467
> Stop cleaning symbol feeds

- src/ProductConstructionService/ProductConstructionService.Api/Configuration/SpaApplicationBuilderExtensions.cs
- src/ProductConstructionService/ProductConstructionService.Api/ProductConstructionService.Api.csproj
- src/ProductConstructionService/ProductConstructionService.Api/Program.cs
Resolves https://github.com/dotnet/arcade-services/issues/4339
> Use a custom Spa middleware to avoid 500s from OPTIONS requests

- src/ProductConstructionService/ProductConstructionService.Api/Configuration/AuthenticationConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/Program.cs
- src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json
https://github.com/dotnet/arcade-services/issues/4318
> Redirect to the original URI after a sign-in

- src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleaner.cs
- src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerJob.cs
- src/ProductConstructionService/ProductConstructionService.FeedCleaner/appsettings.Development.json
- test/ProductConstructionService.FeedCleaner.Tests/FeedCleanerTests.cs
https://github.com/dotnet/arcade-services/issues/2533
https://github.com/dotnet/arcade-services/issues/4467
> Clean symbol feeds with no matching packages

- src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/InProgressPullRequest.cs
- test/Microsoft.DotNet.DarcLib.Tests/Helpers/VersionDetailsParserTests.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
Introduced in https://github.com/dotnet/arcade-services/issues/4570
> Fix failing backflow scenario tests

- src/ProductConstructionService/ProductConstructionService.Common/AddJobLoggingExtension.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerJob.cs
- test/ProductConstructionService.FeedCleaner.Tests/FeedCleanerTests.cs
https://github.com/dotnet/arcade-services/issues/4578
> Log operation id in feed cleaner

- src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs
- src/ProductConstructionService/ProductConstructionService.Common/AddJobLoggingExtension.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/InProgressPullRequest.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerJob.cs
- test/Microsoft.DotNet.DarcLib.Tests/Helpers/VersionDetailsParserTests.cs
- test/ProductConstructionService.FeedCleaner.Tests/FeedCleanerTests.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
https://github.com/dotnet/arcade-services/issues/4581
Will wait for https://dev.azure.com/dnceng/internal/_build/results?buildId=2666314&view=results to finish to see if the tests are fixed before merging
> [Rollout] Production rollout 2025-03-19

- src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
Will be needed https://github.com/dotnet/arcade-services/issues/4571 as well as https://github.com/dotnet/arcade-services/issues/4515 so creating a PR for it now
> Add support for branch deletion and stage change detection

- .config/dotnet-tools.json
- eng/Version.Details.xml
- eng/Versions.props
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/ILocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/LocalGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrRegistrations.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/DependencyFlowConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PcsVmrBackFlower.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PcsVmrForwardFlower.cs
- test/ProductConstructionService.ScenarioTests/CodeFlowScenarioTestBase.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
Rollout issue: https://github.com/dotnet/arcade-services/issues/4592?reload=1
> [Rollout] Production rollout 2025-03-25

- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestBuilderTests.cs
Document was renamed in https://github.com/dotnet/arcade/issues/15653
> Fix links to code flow documentation, add links to subscription IDs

- src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/CodeFlowResult.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
Resolves https://github.com/dotnet/arcade-services/issues/4476
> Use `Codeflow` object when returning from `VmrCodeflow`

- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
Improve / fixup scenario tests wait failure message by adding minutes awaited to the message
> Improve scenario tests wait failure message

- src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/ForwardFlowCommandLineOptions.cs
- tools/FlatFlowMigrationCli/MigrationLogger.cs
- tools/FlatFlowMigrationCli/Operations/MigrateOperation.cs
- tools/FlatFlowMigrationCli/Options/MigrateOptions.cs
https://github.com/dotnet/arcade-services/issues/4601
> Allow to migrate only specific repos

- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Codeflows.razor
Resolves https://github.com/dotnet/arcade-services/issues/4636
> Fix an NRE on the codeflows page

- tools/FlatFlowMigrationCli/ISubscriptionMigrator.cs
- tools/FlatFlowMigrationCli/MigrationLogger.cs
- tools/FlatFlowMigrationCli/Operations/IOperation.cs
- tools/FlatFlowMigrationCli/Operations/MigrateOperation.cs
- tools/FlatFlowMigrationCli/Operations/Operation.cs
- tools/FlatFlowMigrationCli/Operations/RollbackOperation.cs
- tools/FlatFlowMigrationCli/Options/MigrateOptions.cs
- tools/FlatFlowMigrationCli/Options/Options.cs
- tools/FlatFlowMigrationCli/Options/RollbackOptions.cs
- tools/FlatFlowMigrationCli/Program.cs
- tools/FlatFlowMigrationCli/SubscriptionMigrator.cs
https://github.com/dotnet/arcade-services/issues/3169
> Add the migration rollback command

- docs/Darc.md
- src/Microsoft.DotNet.Darc/Darc/Options/AddSubscriptionCommandLineOptions.cs
https://github.com/dotnet/arcade-services/issues/3467
> Move Darc docs to arcade-services

- tools/FlatFlowMigrationCli/Operations/MigrateOperation.cs
https://github.com/dotnet/arcade-services/issues/3170
> Finalize the list of special repos during migration

- Directory.Packages.props
- NuGet.config
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/SwaggerConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
- src/ProductConstructionService/ProductConstructionService.Api/ProductConstructionService.Api.csproj
Resolves https://github.com/dotnet/arcade-services/issues/4681
Swagger UI was not working since we deployed the new front end anyway
> Stop using SwaggerUI

- src/Microsoft.DotNet.Darc/DarcLib/Microsoft.DotNet.DarcLib.csproj
> Remove unnecessary `DarcLib` dependencies

- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
Scenario tests have been a bit flaky since https://github.com/dotnet/arcade-services/issues/4620
> Increase wait time in scenario tests

- src/Microsoft.DotNet.Darc/Darc/Operations/UpdateSubscriptionOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/SubscriptionsCommandLineOptions.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/SubscriptionsController.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Codeflows.razor
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
https://github.com/dotnet/arcade-services/issues/4644
> Handle empty strings in subscription source/target directory

- Directory.Packages.props
- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/sdl/packages.config
- eng/templates/stages/deploy.yaml
- global.json
- src/Microsoft.DotNet.Darc/Darc/Operations/UpdateSubscriptionOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/SubscriptionsCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/GitHubTokenProvider.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/HttpRequestManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/Microsoft.DotNet.DarcLib.csproj
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/SubscriptionsController.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/SwaggerConfiguration.cs
- src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
- src/ProductConstructionService/ProductConstructionService.Api/ProductConstructionService.Api.csproj
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Codeflows.razor
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
- tools/FlatFlowMigrationCli/Operations/MigrateOperation.cs
- tools/ProductConstructionService.Cli/Operations/DeploymentOperation.cs
- tools/ProductConstructionService.Cli/Options/DeploymentOptions.cs
https://github.com/dotnet/arcade-services/issues/4711
> [Rollout] Production rollout 2025-04-23

- Directory.Build.props
- Directory.Packages.props
- NuGet.config
Resolves https://github.com/dotnet/arcade-services/issues/4695
> Switch from `FluentAssertions` to `AwesomeAssertions`

- tools/FlatFlowMigrationCli/Operations/MigrateOperation.cs
https://github.com/dotnet/arcade-services/issues/3170
> Fix VSTest URI in the flat flow migration CLI

- Directory.Build.props
- Directory.Packages.props
- NuGet.config
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionFileCodeFlowUpdater.cs
- test/Microsoft.DotNet.DarcLib.Tests/Helpers/DependencyFileManagerTests.cs
- tools/FlatFlowMigrationCli/Operations/MigrateOperation.cs
https://github.com/dotnet/arcade-services/issues/4730
> [Rollout] Production rollout 2025-04-24

- Directory.Packages.props
- src/Microsoft.DotNet.Darc/DarcLib/Microsoft.DotNet.DarcLib.csproj
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionFileCodeFlowUpdater.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VersionFileCodeFlowUpdaterTests.cs
https://github.com/dotnet/arcade-services/issues/4718
In addition, add tests for asset exclusion.
> Allow for asset exclusion by globbing

- Directory.Packages.props
- src/Microsoft.DotNet.Darc/DarcLib/Microsoft.DotNet.DarcLib.csproj
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionFileCodeFlowUpdater.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VersionFileCodeFlowUpdaterTests.cs
https://github.com/dotnet/arcade-services/issues/4741
> [Rollout] Production rollout 2025-04-25

- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestBuilderTests.cs
Resolves https://github.com/dotnet/arcade-services/issues/4708
> Use `...` for commit diffs

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionFileCodeFlowUpdater.cs
Part of https://github.com/dotnet/arcade-services/issues/4697
> Add build ID to code flow dependency update commit message

- src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
Fix for https://github.com/dotnet/arcade-services/issues/4717
> Fix transient success failures

- tools/ProductConstructionService.Cli/Operations/DeploymentOperation.cs
https://github.com/dotnet/arcade-services/issues/4768
> Use AzCli to deploy containerapp

- eng/service-templates/ProductConstructionService/RecreateEnvOnly/recreate.bicep
We made these edits in Azure already so now just setting the bicep straight.
> Update cron schedule of ACA jobs

- eng/service-templates/ProductConstructionService/RecreateEnvOnly/recreate.bicep
- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/CodeFlowOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/CodeFlowResult.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PcsVmrBackFlower.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
- tools/ProductConstructionService.Cli/Operations/DeploymentOperation.cs
https://github.com/dotnet/arcade-services/issues/4774
> [Rollout] Production rollout 2025-04-30-II

- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
Fix for https://github.com/dotnet/arcade-services/issues/4717
> fix transient success p2

- src/Maestro/Maestro.MergePolicies/AllChecksSuccessfulMergePolicy.cs
- src/Maestro/Maestro.MergePolicies/CodeFlowMergePolicy.cs
- src/Maestro/Maestro.MergePolicies/DontAutomergeDowngradesMergePolicy.cs
- src/Maestro/Maestro.MergePolicies/MergePolicy.cs
- src/Maestro/Maestro.MergePolicies/NoRequestedChangesMergePolicy.cs
- src/Maestro/Maestro.MergePolicies/ValidateCoherencyMergePolicy.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/MergePolicyEvaluator.cs
- test/ProductConstructionService.ScenarioTests/CodeFlowScenarioTestBase.cs
https://github.com/dotnet/arcade-services/issues/4612 
Fixes a bug introduced in the issue above
> Give each MergePolicy an explicit name

- azure-pipelines.yml
It's already run as part of 1ESPT
> Do not run CG explicitly

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_SdkUpdate.cs
- test/ProductConstructionService.ScenarioTests/TestRepository.cs
https://github.com/dotnet/arcade-services/issues/4823
> [Rollout] Production Rollout 2025 05 09

- .gitignore
- eng/service-templates/ProductConstructionService/FullCreate/production.bicepparam
- eng/service-templates/ProductConstructionService/FullCreate/provision.bicep
- eng/service-templates/ProductConstructionService/FullCreate/staging.bicepparam
- eng/service-templates/ProductConstructionService/RecreateEnvOnly/production.bicepparam
- eng/service-templates/ProductConstructionService/RecreateEnvOnly/recreate.bicep
- eng/service-templates/ProductConstructionService/RecreateEnvOnly/staging.bicepparam
- eng/templates/stages/deploy.yaml
- src/Maestro/Maestro.Data/Models/UpdateFrequency.cs
- src/Maestro/Maestro.DataProviders/SqlBarClient.cs
- src/Microsoft.DotNet.Darc/Darc/Constants.cs
- src/Microsoft.DotNet.Darc/Darc/Options/GetDependencyFlowGraphCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/Darc/Options/SubscriptionCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/Darc/Options/SubscriptionsCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/BarApiClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/IBarApiClient.cs
- src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/Generated/Models/UpdateFrequency.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2018_07_16/Models/UpdateFrequency.cs
- src/ProductConstructionService/ProductConstructionService.LongestBuildPathUpdater/LongestBuildPathUpdater.cs
- src/ProductConstructionService/ProductConstructionService.SubscriptionTriggerer/Program.cs
- test/Microsoft.DotNet.Darc.Tests/DependencyFlowGraphTests.cs
> Add everyTwoWeeks and everyMonth update frequencies to Maestro

- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
- test/Microsoft.DotNet.DarcLib.Tests/GitHubClientTests.cs
> Rollout 2025-05-14 pt2

- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Codeflows.razor
https://github.com/dotnet/arcade-services/issues/4732
> Add hover to the codeflows page

- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Codeflows.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Subscriptions.razor
- Wrong forward flow subscriptions where looked up
- Resolves https://github.com/dotnet/arcade-services/issues/4747
https://github.com/dotnet/arcade-services/issues/4732
> Fix which codeflow subscriptions are shown in BarViz

- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/Local.cs
Resolves https://github.com/dotnet/arcade-services/issues/4849
> Fix fetching `eng/common` files from the VMR

- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/GitRepoUrlUtils.cs
- src/Microsoft.DotNet.Darc/DarcLib/Local.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Codeflows.razor
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Subscriptions.razor
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestConflictNotifier.cs
- src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleaner.cs
- src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerJob.cs
- test/ProductConstructionService.FeedCleaner.Tests/FeedCleanerTests.cs
https://github.com/dotnet/arcade-services/issues/4856
> [Rollout] Production rollout 2025-05-21

- src/Maestro/Maestro.MergePolicies/DependencyUpdateSummary.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionFileCodeFlowUpdater.cs
https://github.com/dotnet/arcade-services/issues/4862
> Update version files even with conflicts upon opening a PR

- src/Maestro/Maestro.MergePolicies/DependencyUpdateSummary.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/UpdateChannelOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/UpdateChannelCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/Darc/Program.cs
- src/Microsoft.DotNet.Darc/DarcLib/BarApiClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/IBarApiClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionFileCodeFlowUpdater.cs
- src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/Generated/Channels.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2018_07_16/Controllers/ChannelsController.cs
- src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/ChannelsController.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- tools/ProductConstructionService.ReproTool/Operations/Operation.cs
https://github.com/dotnet/arcade-services/issues/4873
> [Rollout] Production rollout 2025-05-22

- .github/copilot-instructions.md
- .github/copilot-setup-steps.yml
Taken from https://github.com/dotnet/arcade-services/issues/4866
> Add instructions and env setup for Copilot

- Directory.Packages.props
> Bump .NET Aspire to 9.3.0

- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/VmrDiffOperation.cs
Resolves https://github.com/dotnet/arcade-services/issues/4860
> Fix `darc vmr diff` not accounting for checked-in but ignored files

- .github/ISSUE_TEMPLATE/codeflow-issue.yml
- .github/copilot-instructions.md
- .github/copilot-setup-steps.yml
- Directory.Packages.props
- README.md
- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/VmrDiffOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrDiffOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/SourceMappingParser.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/Subscription.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Home.razor
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestConflictNotifier.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/Microsoft.DotNet.Darc.Tests/inputs/source-mappings.json
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncAdditionalMappingsTest.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsOneTimeSetUp.cs
https://github.com/dotnet/arcade-services/issues/4885
> [Rollout] Production rollout 2025-05-28

- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestConflictNotifier.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlowConflicts.cs
https://github.com/dotnet/arcade-services/issues/4841
> Fix `View in..` links and scenario tests

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
Resolves https://github.com/dotnet/arcade-services/issues/4887
> Ignore backflows from different branches

- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Subscriptions.razor
Similar change to https://github.com/dotnet/arcade-services/issues/4850
> Fix the width of the last column in the Subscriptions page

- src/Microsoft.DotNet.Darc/DarcLib/Helpers/ProcessExecutionResult.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/CodeFlowResult.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/Exceptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Subscriptions.razor
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PcsVmrBackFlower.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestConflictNotifier.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/ProductConstructionService.DependencyFlow.Tests/PendingCodeFlowUpdatesTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
- test/ProductConstructionService.DependencyFlow.Tests/UpdateAssetsForCodeFlowTests.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlowConflicts.cs
https://github.com/dotnet/arcade-services/issues/4896
> [Rollout] Production rollout 2025-05-29

- tools/ProductConstructionService.ReproTool/Operations/Operation.cs
https://github.com/dotnet/arcade-services/issues/4881
> Handle case where target branch doesn't exist in fork in repro tool

- docs/DevGuide.md
https://github.com/dotnet/arcade-services/issues/4933
> Add DevGuide instructions for redis connections

- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/VmrDiffOperation.cs
https://github.com/dotnet/arcade-services/issues/4924
> Correctly apply exclusion filters, include submodules in them

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CodeFlowVmrUpdater.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
https://github.com/dotnet/arcade-services/issues/4707
> Fix commit messages during forward flow `OppositeDirectionFlow` codepath

- eng/service-templates/ProductConstructionService/FullCreate/container-app.bicep
- src/Maestro/Maestro.Common/AzureDevOpsTokens/AzureDevOpsTokenProvider.cs
https://github.com/dotnet/arcade-services/issues/4996
> Resolve CodeQL alert around `DefaultAzureCredential`

- src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/Constants.cs
- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemoteGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/Remote.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/Exceptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlow.cs
https://github.com/dotnet/arcade-services/issues/5030
> Stop ForwardFlow updates if they'd overwrite manual PR changes

- src/Maestro/Maestro.MergePolicies/AllChecksSuccessfulMergePolicy.cs
- test/ProductConstructionService.ScenarioTests/ProductConstructionService.ScenarioTests.csproj
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
https://github.com/dotnet/arcade-services/issues/5028
> Retry Maestro Merge Policy fetch in tests

- .config/dotnet-tools.json
- azure-pipelines.yml
- eng/Version.Details.xml
- eng/Versions.props
- eng/templates/jobs/darc-and-api-tests.yml
- eng/templates/jobs/e2e-pcs-tests.yml
- src/Maestro/Maestro.MergePolicies/AllChecksSuccessfulMergePolicy.cs
- src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/Constants.cs
- src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemoteGitRepo.cs
- src/Microsoft.DotNet.Darc/DarcLib/Remote.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/Exceptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
- test/ProductConstructionService.ScenarioTests/ProductConstructionService.ScenarioTests.csproj
- test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlow.cs
https://github.com/dotnet/arcade-services/issues/5053
> [Production rollout] Rollout 2025 07 16

- src/Microsoft.DotNet.Darc/Darc/Models/PopUps/AuthenticateEditorPopUp.cs
Fixes https://github.com/dotnet/arcade-services/issues/5056
> Update darc github PAT link to fine-grained token and update text

- src/Maestro/Maestro.MergePolicies/StandardMergePolicy.cs
- src/Maestro/Maestro.MergePolicies/VersionDetailsPropsMergePolicy.cs
https://github.com/dotnet/arcade-services/issues/5092
> Run VersionDetailsProps check on dependency flow PRs too

- src/Microsoft.DotNet.Darc/Darc/Operations/UpdateSubscriptionOperation.cs
https://github.com/dotnet/arcade-services/issues/4612
> Properly update subscription with standard auto merge policy

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/BackflowConflictResolver.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CloneManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrVersionFileMerger.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrVersionFileMergerTests.cs
- tools/ProductConstructionService.ReproTool/Operations/FlowCommitOperation.cs
https://github.com/dotnet/arcade-services/issues/5109
> Properly handle dotnet-tools.json deletion

- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/BackflowConflictResolverTests.cs
https://github.com/dotnet/arcade-services/issues/5123
> Add a test for case insensitive dependencies

- src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/Helpers/IDependencyFileManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/BackflowConflictResolver.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/ForwardFlowConflictResolver.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- test/Microsoft.DotNet.DarcLib.Codeflow.Tests/ForwardFlowTests.cs
- test/Microsoft.DotNet.DarcLib.Codeflow.Tests/TwoWayCodeflowTests.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/ForwardFlowConflictResolverTests.cs
- test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlowConflicts.cs
https://github.com/dotnet/arcade-services/issues/4792
> Exclude version files in all places during FF

- Directory.Packages.props
- NuGet.config
- global.json
- src/ProductConstructionService/ProductConstructionService.Api/Dockerfile
- src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemConfiguration.cs
> Update Aspire and .NET SDK

- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/CodeFlowOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/GenerateTpnOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/GetRepoVersionOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/ResetOperation.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CodeFlowVmrUpdater.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CodeflowChangeAnalyzer.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCloneManager.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrScanner.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
> Refresh VMR metadata after checkouts

- .github/ISSUE_TEMPLATE/rollout-issue.md
- src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/VmrDiffOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrDiffOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/Exceptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
- test/Microsoft.DotNet.DarcLib.Codeflow.Tests/BackflowTests.cs
- test/Microsoft.DotNet.DarcLib.Codeflow.Tests/ForwardFlowTests.cs
- test/Microsoft.DotNet.DarcLib.Codeflow.Tests/Helpers/GitOperationsHelper.cs
https://github.com/dotnet/arcade-services/issues/5199
> [Rollout] Production rollout 2025-08-26

- src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs
Reduce wait interval from 60 seconds to 30 seconds.
> Decrease wait interval for build promotion

- src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/JsonVersionProperty.cs
https://github.com/dotnet/arcade-services/issues/5248
> Improve logging when JSON merging fails

- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/FlatJson.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/JsonFileMerger.cs
- src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionDetailsFileMerger.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/JsonFileMergerTests.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/SimpleConfigJsonTests.cs
- test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VersionDetailsFileMergerTests.cs
> Always merge JSON/V.D.xml gracefully and post conflict comments

- src/Microsoft.DotNet.Darc/Darc/Models/PopUps/AddSubscriptionPopUp.cs
- src/Microsoft.DotNet.Darc/Darc/Models/PopUps/MergePoliciesPopUpHelpers.cs
- src/Microsoft.DotNet.Darc/Darc/Models/PopUps/SetRepositoryMergePoliciesPopUp.cs
- src/Microsoft.DotNet.Darc/Darc/Models/PopUps/SubscriptionPopUp.cs
- src/Microsoft.DotNet.Darc/Darc/Models/PopUps/UpdateSubscriptionPopUp.cs
- src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/DarcLib/Microsoft.DotNet.DarcLib.csproj
- src/Microsoft.DotNet.Darc/DarcLib/Models/Darc/Yaml/InputSubscriptionYamlData.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/Darc/Yaml/MergePolicyYamlData.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/Darc/Yaml/SubscriptionUpdateYamlData.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/Darc/Yaml/SubscriptionYamlData.cs
- src/Microsoft.DotNet.Darc/DarcLib/Remote.cs
- src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/Generated/Configuration.cs
- src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/Generated/ProductConstructionServiceApi.cs
- src/ProductConstructionService/ProductConstructionService.Api/Configuration/ApiRedirection.cs
- src/ProductConstructionService/ProductConstructionService.Api/Controllers/ConfigurationController.cs
- tools/ProductConstructionService.Cli/Operations/RefreshConfigurationOperation.cs
- tools/ProductConstructionService.Cli/Options/RefreshConfigurationOptions.cs
- tools/ProductConstructionService.Cli/Program.cs
> Config controller layout

- src/Microsoft.DotNet.Darc/Darc/Operations/AddSubscriptionOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Operations/SubscriptionOperationBase.cs
- src/Microsoft.DotNet.Darc/Darc/Options/AddSubscriptionCommandLineOptions.cs
> Add id as a parameter to add subs, sort them by channel name

- tools/ProductConstructionService.ReproTool/Operations/ReproOperation.cs
> Initialize `darc` correctly in the repro tool

- src/Microsoft.DotNet.Darc/Darc/Operations/UpdateDependenciesOperation.cs
- src/Microsoft.DotNet.Darc/Darc/Options/UpdateDependenciesCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/DarcLib/Local.cs
- src/Microsoft.DotNet.Darc/DarcLib/Models/Darc/AssetMatcher.cs
https://github.com/dotnet/arcade-services/issues/5221
> Allow `darc update-dependencies` to update specific VMR folders with `target-directory`
