dotnet/arcade-services

src/Maestro/SubscriptionActorService/PullRequestActor.cs
PRs created with Maestro currently have "Update dependency files" which isn't all that useful for anyone.  This extends the title with the repos that are involved, up to a max of 80 characters, at which point it simply lists the number of input subscriptions that are involved. This also fixes an issue where the listed input builds in the PR description were listed by build asset registry database ID, rather than the build number.
=> Create more descriptive PR names

src/Microsoft.DotNet.Darc/src/DarcLib/Microsoft.DotNet.DarcLib.csproj
This is so the prod build (which builds stable packages) won't fail nuget package.  There are no stable 16.* versions
=> Downgrade client to stable version

src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs, src/Maestro/Maestro.Data/Migrations/20190111011037_onDeleteRestrict.Designer.cs, src/Maestro/Maestro.Data/Migrations/20190111011037_onDeleteRestrict.cs
@JohnTortugo when you responded to @ChadNedzlek's feedback you updated just the data context model snapshot which didn't actually do anything. This change updates the DbContext to specify Restrict for those foreign keys.
=> Fix OnDelete.Restrict

azure-pipelines.yml
Microsoft.DotNet.Maestro.Tasks comes from this repo now, so it needs to be restorable using typical feeds unless we update everywhere arcade is used.
Up the timeout to avoid lock contention failures
=> Switch back to dotnet-core feed

src/Maestro/SubscriptionActorService/.config/settings.Production.json, src/Maestro/SubscriptionActorService/.config/settings.Staging.json, src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/DarcSettings.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs
The normal temp path for service fabric applications tends to be too long to clone some repositories like aspnet/AspNetCore
=> Specify a temporary path to clone repositories

src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/UpdateDependenciesCommandLineOptions.cs
Until we have the diamond dependency issue figured out, this will help ASPNet do manual updates
=> Allow filtering of source repo in update-dependencies

src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/TriggerSubscriptionsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GetSubscriptionsCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/SubscriptionsCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/TriggerSubscriptionsCommandLineOptions.cs
Nate pointed out that there was no way to trigger just AspNetCore subscriptions because AspNetCore-Tooling is a subscription.  This adds regex and exact options and refactors them into a common class
=> Add --exact and --regex options to subscription operations

src/Microsoft.DotNet.Darc/src/Darc/Microsoft.DotNet.Darc.csproj, src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/AddSubscriptionPopUp.cs, src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/SubscriptionPopUp.cs, src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/UpdateSubscriptionPopUp.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/UpdateSubscriptionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Program.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
Work for https://github.com/dotnet/arcade/issues/1935
Editing subscriptions only supports non-quiet mode (pop up) given the amount of permutations possible. With the pop up the user defines explicitly the changes which we will take wholesale validating that the data is valid.
=> Update subscriptions work

src/Maestro/SubscriptionActorService/PullRequestActor.cs
As we add release branches PRs will become a little more confusing without this.
=> Include the target branch in the PR title

src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyGraphOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GetDependencyGraphCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs
If a valid sha/repo combo is present, but the eng/Version.Details.xml file is not found,
this is probably because the mentioned sha is not onboarded onto dependency flow.  This is fine
in isolated cases.  Log as warning and then continue.
=> Do not fail if dependency graph walk yields a valid node with no eng/Versions.Details.xml

src/Microsoft.DotNet.Darc/src/DarcLib/AzureDevOpsClient.cs
This fixes this error when we are fetching files from AzDo and a request is ok to fail, like when trying the different versionTypes when trying to fetch a file:
`The request message was already sent. Cannot send the same request message multiple times.`
=> Create a new HTTP request each time we retry an Azure DevOps operation.

src/Microsoft.DotNet.Darc/src/DarcLib/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/AzureDevOpsClientTests.cs
This one fixes a scenario in particular when in a graph there are AzDo dependencies which have a repo URL that includes the user.
This doesn't fixes https://github.com/dotnet/arcade/issues/2121 completely since I'm not touching the API but fixes a fraction of it
=> Handle AzDO URLs with users in them

azure-pipelines.yml, src/Maestro/DependencyUpdater/DependencyUpdater.cs, src/Maestro/Maestro.Contracts/IDependencyUpdater.cs, src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/SubscriptionsController.cs
Part workaround (add temporary REST api to trigger daily update)
Part catch on failure to update so a single failure during daily updates doesn't take down the others.
Also need to add more applicaiton logging because appinsights is dropping events.
=> Catch failures during updates

src/Maestro/SubscriptionActorService/PullRequestActor.cs
Failing to do so may lead to a case where we update the latest build id with the wrong data.
I'm not positive that this is the issue with the latest build id, but it is a potential source of issues
=> Remove old updates when updating an existing PR with a build

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs, src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxManager.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddDependencyOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependenciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyGraphOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/VerifyOperation.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LocalHelpers.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyTestDriver.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/TestHelpers.cs
Submodules generally have their .git directory in the parent repo's .git directory, so this assumption breaks for them.
Fixes #184.
=> Use show-toplevel to get root of Git repo instead of parent of .git folder.

src/Maestro/DependencyUpdater/DependencyUpdater.cs, src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/DelegatedStatefulService.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/IServiceImplementation.cs
The way BARContext is inserted into DependencyUpdater and ReleasePipelineRunner today is through IoC to [the class constructor](https://github.com/dotnet/arcade-services/blob/1454160d212e1ccb2e00cb2911a1315e6b893938/src/Maestro/DependencyUpdater/DependencyUpdater.cs#L46). The problem here is that the RunAsync methods of these services never return and therefore the BARContext object is never reloaded with external changes, which result in wrong behavior in some cases.
As per talk with @alexperovich the fix for now will be to make the RunAsync methods of these services to return the amount of time the caller should wait before calling RunAsync again. Therefore the method won't execute in an infinite loop anymore and the object it's contained will be recreated 'frequently'.
=> Reorganizing the way we invoke RunAsync

src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs, src/Maestro/Maestro.Web/Pages/Index.cshtml, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts, src/Maestro/maestro-angular/src/app/page/build/build.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.ts, src/Maestro/maestro-angular/src/app/util/names.ts, src/Maestro/maestro-angular/src/app/widget/side-bar/side-bar.component.html, src/Maestro/maestro-angular/src/styles.scss
- Make Build Graph api always return the root build
- Make user name display properly for people with non-ascii characters in their names
- Include bootstrap transition styles for collapse elements
- Add error display for failures to load build info from AzDev
- Display AzDev repo uri in build dependency table if there is no github uri
- Properly determine "coherent" bit for builds that have a build number that isn't a parsable number
- Display only the last path segment of AzDev repo uris in the sidebar
- Allow the sidebar to scroll
=> Fix several problems with BAR visualization

src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts, src/Maestro/maestro-angular/src/app/page/build/build.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.ts
- Handle "includeToolsets" in the table component rather than in the observable
- Calculate coherency relative to all builds, and just product builds. Use proper coherency info based on "includeToolsets"
- Animate addition and removal of table elements when "includeToolsets" is toggled
- Add title attributes to icons to help screen readers and add tooltips
=> Fix build graph table

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Make `LookupForMatchingGitHubRepository` accept GitHub URLs as input.
Tests were like this:
- Input was https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-arcade
Output Repository: https://github.com/dotnet/arcade
- Input was https://github.com/dotnet/arcade
Output Repository: https://github.com/dotnet/arcade
- Input was https://dnceng@dev.azure.com/dnceng/internal/_git/dotnet-arcade-services
Output Repository: https://github.com/dotnet/arcade-services
- Input was https://github.com/jcagme/arcade-services
Output Repository: https://github.com/jcagme/arcade-services
=> Fix LookupForMatchingGitHubRepository to accept github URLs as input.

LICENSE.TXT
Maestro PR's are failing due to mismatch between Arcade-services LICENSE.TXT and Arcade SDK MIT License. I assume we want to follow Arcade license?
Failing maestro build: https://dev.azure.com/dnceng/9ee6d478-d288-47f7-aacc-f6e6d082ae6d/_build/results?buildId=130304
=> Update LICENSE.TXT to match Arcade.SDK MIT License

src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyGraphOperation.cs
Currently we fail to produce the graph image if there are repo names which include a '.' in the name sucha as "nuget.client".
=> Handle repos with a '.' in the name

src/Maestro/Maestro.Web/Pages/Index.cshtml.cs, src/Maestro/maestro-angular/angular.json, src/Maestro/maestro-angular/maestro-angular.proj, src/Maestro/maestro-angular/package-lock.json, src/Maestro/maestro-angular/package.json, src/Maestro/maestro-angular/post-build.js, src/Maestro/maestro-angular/src/app/app.module.ts, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.ts, src/Maestro/maestro-angular/src/app/page/recent-build/recent-build.component.ts, src/Maestro/maestro-angular/src/app/pipes/relative-date.pipe.spec.ts, src/Maestro/maestro-angular/src/app/pipes/relative-date.pipe.ts, src/Maestro/maestro-angular/src/app/pipes/time-ago.pipe.spec.ts, src/Maestro/maestro-angular/src/app/pipes/time-ago.pipe.ts, src/Maestro/maestro-angular/src/app/services/channel.service.ts, src/Maestro/maestro-angular/src/maestro-client/maestro.ts, src/Maestro/maestro-angular/src/maestro-client/models.ts
- Add node postbuild steps to produce stats and a bundle report file
- Publish the bundle-report file as a build artifact
- Remove moment and replace it with date-fns reducing the vendor bundle size by ~30%, taking gzipped size from 219 KB to 146KB
- Adjust angular generated code to produce parameter objects for methods, rather than multiple parameters.
=> Improve the BAR visualization build and bundle size

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
When publishing to BAR and the dependency is not found in the DB Log.Message instead of a warning so builds don't fail given than most do log warnings as errors.
Sample failed build: https://dev.azure.com/dnceng/internal/_build/results?buildId=133451
=> Log message when a dependency is not found in BAR

src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.scss, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts, src/Maestro/maestro-angular/src/app/page/build/build.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.ts, src/Maestro/maestro-angular/src/helpers.ts
- topologicalSort now orders nodes by node keys where possible while still maintaining the topological ordering
- Repository url on top of the build page now shows the azDev repo url if there isn't a github one
- Prevent recalculation of layout when hovering rows in the dependency graph table by changing visibility of the icons, rather than using ngIf to show the correct icon
=> Fix more bugs in BAR Visualization

src/Maestro/SubscriptionActorService/ActionRunner/ActionRunner.cs
While there are plenty of non-fatal (and expected) errors in the failed actions, I'd like to have a single place to look for them while we push for a more stable Maestro.
=> Track failed actions in appinsights

src/Maestro/Maestro.GitHub/GitHubTokenProvider.cs, src/Maestro/Maestro.GitHub/Maestro.GitHub.csproj, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/ExponentialRetry.cs
Adds a general purpose retry method (same as one from Helix API).
Use this in a couple cases to test it out and see whether the pattern works. We have seen quite a few 500 errors coming from github, and this should help. If it works I'll widen the usage out to the other Octokit calls
=> Add general purpose retry and retry for a couple cases

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
This change adds a cache containing all assets for found builds to avoid hitting the api a lot.
=> Cache assets for already found builds

src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/CloneCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Program.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs
This adds a new darc verb, `clone`, that will either clone a specified remote repo and all repos in its dependency graph, or look at a local Version.Details.xml and clone all repos in it and all repos in their dependency graph.  It will put all the repos in the same directory with the format `{name}.{sha}`.
=> Implement repo uberclone.

src/Maestro/Maestro.Web/Startup.Api.cs, src/Maestro/Maestro.Web/Startup.cs
- Also use references for enum definitions to preserve the enum names defined in the code.
=> Add x-ms-paginated to swagger doc

src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyDetailComparer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/DependencyGraph/input/core-sdk/c57bde45936fc120c0124bf964f570c45bfd8f8b/graph-with-toolset.xml
We don't need to build the full graph during coherency updates each time.  Most of the time the nodes we are looking for are close to the root node of the graph.  Add the ability to break the graph build when a specified set of dependencies or assets are seen (dependency break is for common child coherency). Overall this drastically improves performance, maybe by an order of magnitude in local scenarios
=> Shortcut dependency graph build during coherency updates

src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
Arcade dependency update PR will now attempt to update the tools.dotnet and sdk.version sections of global.json if they are older than what arcade uses.
Validated by triggering a test subscription that opened this PR: https://github.com/dotnet/arcade-validation/pull/243
=> Flow dotnet version to global.json as part of arcade dependency updates

src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs
Should be case insensitive.  Fix the tests so that they will catch this.
=> Fix dependency name comparison

src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
Looks like if an environment failed, stopping the execution of the release pipeline, the environments which did not run will have a "notstarted" and that won't change. We need to check if environments contain one of the "stop" statuses and if they do consider the whole release as completed.
=> Fix issue contents and in progress definition

src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
We are seeing APIExceptions with a "Server Error" message during this operation. Expanding to grabbing anything higher to 500 in case what they are actually sending over is one of the other flavors of 5XX
=> Retry on anything higher than 500

src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
Disable this for now as the last committer might not have anything to do with the reason the pipeline failed or cannot fix the issue. This mechanism will be improved in the future.
=> Disable tagging commit author when release pipeline fail

src/Maestro/maestro-angular/src/app/app.module.ts, src/Maestro/maestro-angular/src/app/page/build-graph-tree/build-graph-tree.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-tree/build-graph-tree.component.spec.ts, src/Maestro/maestro-angular/src/app/page/build-graph-tree/build-graph-tree.component.ts, src/Maestro/maestro-angular/src/app/page/build/build.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.ts, src/Maestro/maestro-angular/src/app/pipes/get-repository-name.pipe.spec.ts, src/Maestro/maestro-angular/src/app/pipes/get-repository-name.pipe.ts, src/Maestro/maestro-angular/src/app/pipes/repo-name.pipe.spec.ts, src/Maestro/maestro-angular/src/app/pipes/repo-name.pipe.ts, src/Maestro/maestro-angular/src/app/util/names.ts, src/Maestro/maestro-angular/src/app/widget/side-bar-channel/side-bar-channel.component.html, src/Maestro/maestro-angular/src/app/widget/side-bar-channel/side-bar-channel.component.ts, src/Maestro/maestro-angular/src/tree-view/definitions.ts, src/Maestro/maestro-angular/src/tree-view/index.ts, src/Maestro/maestro-angular/src/tree-view/tree-node-list/tree-node-list.component.html, src/Maestro/maestro-angular/src/tree-view/tree-node-list/tree-node-list.component.scss, src/Maestro/maestro-angular/src/tree-view/tree-node-list/tree-node-list.component.spec.ts, src/Maestro/maestro-angular/src/tree-view/tree-node-list/tree-node-list.component.ts, src/Maestro/maestro-angular/src/tree-view/tree-node/tree-node.component.html, src/Maestro/maestro-angular/src/tree-view/tree-node/tree-node.component.scss, src/Maestro/maestro-angular/src/tree-view/tree-node/tree-node.component.spec.ts, src/Maestro/maestro-angular/src/tree-view/tree-node/tree-node.component.ts, src/Maestro/maestro-angular/src/tree-view/tree-view.module.ts, src/Maestro/maestro-angular/src/tree-view/tree-view/tree-view.component.html, src/Maestro/maestro-angular/src/tree-view/tree-view/tree-view.component.spec.ts, src/Maestro/maestro-angular/src/tree-view/tree-view/tree-view.component.ts
This change adds a tree view as an option for the build dependency view.
=> Add prototype tree view for builds

src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/AzureDevOps/AzureDevOpsCheckState.cs
fixes https://github.com/dotnet/arcade/issues/1715
Validated this with these Test prs:
* https://dev.azure.com/dnceng/internal/_git/maestro-test2/pullrequest/983?_a=overview (policy bypassed because "Not all comments resolved" policy was set to be ignored by the subscription)
* https://dev.azure.com/dnceng/internal/_git/maestro-test2/pullrequest/984?_a=overview (policy not bypassed, all required policies were successful)
* https://dev.azure.com/dnceng/internal/_git/maestro-test2/pullrequest/968?_a=overview (Policy not bypassed, the work items linked policy was ignored, and is not required)
* https://dev.azure.com/dnceng/internal/_git/maestro-test2/pullrequest/960?_a=overview (PR was not auto merged due to no checks)
* https://dev.azure.com/dnceng/internal/_git/maestro-test2/pullrequest/986 …
=> Use evaluations API for Azure DevOps auto merge

src/Maestro/tests/Scenarios/azdoflow-nonbatched.ps1, src/Maestro/tests/Scenarios/channels.ps1, src/Maestro/tests/Scenarios/common.ps1, src/Maestro/tests/Scenarios/default-channels.ps1, src/Maestro/tests/Scenarios/githubflow-nonbatched-with-coherency.ps1, src/Maestro/tests/Scenarios/githubflow-nonbatched.ps1, src/Maestro/tests/Scenarios/githubflow-release-pipeline-nonbatched.ps1
First stab at https://github.com/dotnet/arcade/issues/2484
* Test scripts now mostly don't have to worry about managing which resources to delete.
* Fix azure devops api version
* Move PR checks for AzDO and Github to their own functions, so future test scripts can just call that instead of duplicating the code.
=> Some scenario test script refactoring

src/Maestro/maestro-angular/src/app/app-routing.module.ts, src/Maestro/maestro-angular/src/app/app.module.ts, src/Maestro/maestro-angular/src/app/resolvers/build-resolver.service.spec.ts, src/Maestro/maestro-angular/src/app/resolvers/build-resolver.service.ts, src/Maestro/maestro-angular/src/app/resolvers/channel-resolver.service.spec.ts, src/Maestro/maestro-angular/src/app/resolvers/channel-resolver.service.ts, src/Maestro/maestro-angular/src/app/services/application-insights.service.ts, src/Maestro/maestro-angular/src/app/services/router-event-handler.service.spec.ts, src/Maestro/maestro-angular/src/app/services/router-event-handler.service.ts, src/Maestro/maestro-angular/src/helpers.ts
This change adds support for updating the page title and the name reported to application insights for every route navigation.
=> Change the page title and name based on route navigation

src/Maestro/tests/Scenarios/azdoflow-nonbatched.ps1, src/Maestro/tests/Scenarios/common.ps1, src/Maestro/tests/Scenarios/githubflow-nonbatched-with-coherency.ps1, src/Maestro/tests/Scenarios/githubflow-nonbatched.ps1, src/Maestro/tests/Scenarios/githubflow-release-pipeline-nonbatched.ps1
Botched refactoring was causing tests to fail with incorrect PR names being checked.
=> add sourceRepoName parameter to Check-PR functions

src/Maestro/SubscriptionActorService/MaestroBarClient.cs, src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/AddSubscriptionPopUp.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddSubscriptionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
- Add a way to batch subscriptions in add-subscription.
- Fix a few bugs related to dumping of subscriptions info (null ref when merge policies were not present on batchable subscriptions)
=> Enable batchable subscriptions in add-subscription

src/Maestro/tests/Scenarios/all.ps1, src/Maestro/tests/Scenarios/azdoflow-nonbatched.ps1, src/Maestro/tests/Scenarios/common.ps1, src/Maestro/tests/Scenarios/githubflow-nonbatched-with-coherency.ps1, src/Maestro/tests/Scenarios/githubflow-nonbatched.ps1, src/Maestro/tests/Scenarios/githubflow-release-pipeline-nonbatched.ps1
As of https://github.com/dotnet/arcade-services/pull/374 the format returned by `darc get-dependencies` changed, and that broke the assertions in the scenario tests.
Also adding an optional parameter that will be passed during deployments to add a local source for Darc installation so that we can install the correct Darc version without having to wait for it to be published in the feeds.
=> Fix scenario tests break and add darcPackageSource parameter

src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts
Since we were trying to find incoherencies based on AzDO version numbers, we were running into issues when the values would be compared numerically. For example: 
20190422.23 version number IS larger than 20190422.5, but not when compared numerically (nearly a quarter is smaller than a half). So, we need to compare the values on build ID, which is inserted into the database in order, so we should not run into issues there.
=> Finding incoherencies based on build ID rather than build number

src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
Closes: https://github.com/dotnet/arcade/issues/2334
Instead of removing the artifact everytime, let's just patch the existing one in case one exist or otherwise add one if no one exist.
=> Fix release pipeline runner artifact source manipulation

src/Microsoft.DotNet.Darc/src/Darc/Microsoft.DotNet.Darc.csproj, src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
When --release is passed (formerly --separated), generate a per-repo layout and a release.json file describing the output layout.
Fix a couple other minor issues (e.g. manifest.txt was preferencing AzDO URLs)
=> Generate release json file automatically and change some switches around

src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts
A few changes here: 
* Incoherent dependencies are now highlighted in table-danger
* Parent nodes with incoherent dependencies are highlighted in table-warning
* Added to Help tooltip regarding the key to these highlights
=> Highlighting parent nodes with incoherent dependencies

src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts, src/Maestro/maestro-angular/src/app/page/build/build.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.ts
Changes: 
* Added toggle to build page to show all dependencies. Default is set to off. 
* Shows or hides non-immediate dependencies depending on the toggle. 
Minor fix: 
* Moved exclamation icon outside of SHA link.
=> Functionality to show only root and immediate dependency builds by default, and toggle to show all dependencies

src/Maestro/MaestroApplication/MaestroApplication.sfproj, src/Maestro/MaestroApplication/packages.config
This version of the Service Fabric package should contain a fix for the MSBuild race conditions it caused on (transitive) ProjectReferences of the `.sfproj`, for example https://github.com/dotnet/core-eng/issues/6183.
Note: I haven't built/tested this.
=> Service Fabric SDK 1.6.8

src/Maestro/tests/Scenarios/all.ps1, src/Maestro/tests/Scenarios/clone.ps1, src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/CloneCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/ILocal.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs
- Fix clone operation to work without a real PAT.
- Instead of hitting the GitHub API to get the dependency graph, clone the repo then get the dependencies locally.
- Remove unneeded BAR dependency.
- Add two options for limiting the uberclone: depth limit and ignored repos.
- Add one option for relocating `.git` directories (to simulate the way submodules work in regular git).
=> Some fixes for anonymous uberclone and additional options.

src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/AssetsController.cs
Looks into the assembly informational version for DarcLib to get the package version of Darc.
This specific API allows for anonymous access.
With this, we can change darc-init.ps1/sh to make this quick call to the prod deployment, rather than having to update the version number manually in those files
=> Add anonymous to get the Darc version matching the Maestro++ version

src/Maestro/tests/Scenarios/common.ps1
One of the tests is failing due to max path issues because the temp path in the machine is too long. Use the agent workfolder as the test root to see if that's enough to get the test working
=> Use agent workFolder if running under vsts

src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
Fixes: https://github.com/dotnet/arcade/issues/2737
Basically do not move a build to a channel if there were environments in the release that failed
=> Don't move a build if the release failed

src/Maestro/tests/Scenarios/azdoflow-batched.ps1, src/Maestro/tests/Scenarios/githubflow-batched.ps1
The new warning when adding a batched subscription w/o merge policy is messing with the way we check if a subscription was created in the tests.
=> Add merge policy to batched subscription tests

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs
A few repos have extremely long file names for testing (AspNetCore, core-setup, and F#).  Unlike the Git command line, LibGit2Sharp does not attempt to mitigate MAX_PATH issues when checking out entire commits.  This change makes it so that if checking out the whole commit fails, we will instead check out individual files and just skip the ones that have paths that are too long.
There is some slight risk in that we will no longer catch if an actual source file cannot be checked out due to MAX_PATH.  We will emit a warning and the build will likely fail in that case.
=> Workaround for MAX_PATH issues on Windows

src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
Closes: https://github.com/dotnet/arcade/issues/2841
- Patch artifact source when its configuration doesn't match what we expect. 
- Add more logging.
=> Patch artifact source when its configuration doesn't match what we expect

src/Maestro/tests/Scenarios/azdoflow-batched.ps1, src/Maestro/tests/Scenarios/githubflow-batched.ps1
* The github-batched tests were leaving github branches behind due to a typo.
* Some logging fixes during the tests.
=> Stop leaking github branches during scenario tests

src/Microsoft.DotNet.ServiceFabric.ServiceHost/FixedApplicationInsigthtsLoggerProvider/FixedApplicationInsightsLoggerFactoryExtensions.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/FixedApplicationInsigthtsLoggerProvider/FixedApplicationInsightsLoggerProvider.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/Microsoft.DotNet.ServiceFabric.ServiceHost.csproj
I believe this fixes the current deployment failure.
The type for the ApplicationInsightsLoggerOptions changed in the internal API we are using.
@alexperovich Could you link to the issue where we're going to change the way we set up App Insights for the service so we can clean this up?
As a heads up, this type is marked as obsolete, but I don't believe it's worth spending more time debugging this failure if this change unblocks the service deployment.
=> Use the new right type for ApplicationInsightsLoggerOptions

src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Maestro/tests/Scenarios/common.ps1
Fixes an extra space before the first repo name introduced in #445
=> Remove extra space in PR title now that we insert a space before every Repo name

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
Closes: https://github.com/dotnet/arcade/issues/3015
Add a `-latest` option to darc gather-drop. The goal with this is to be able to run a gather-drop to test the latest added asset location to an asset.
=> Add `-latest` option to gather-drop

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Relates to: https://github.com/dotnet/arcade/issues/1789
Output two new variables: IsStableBuild and IsInternalBuild. These variables will later be used by the publishing pipeline to decide which kind of feed should be created.
Tested this locally with a mock xunit setup.
=> Add AzDo IsStableBuild and IsInternalBuild variables

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
As it turns out if we add this attribute (isOutput) to the command it makes the variable visible to other **jobs** but the variable isn't accessible to other **steps** in the same job that created the variable...
=> Fix Publish to BAR ##VSO output syntax

src/Maestro/Maestro.Contracts/Asset.cs, src/Maestro/SubscriptionActorService/MaestroBarClient.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileContentContainer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/VersionFiles.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyDetail.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Microsoft.DotNet.Darc.Tests.csproj, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/EmptyVersions1/input/NuGet.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/EmptyVersions2/input/NuGet.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/SupportAlternateVersionPropertyFormats1/input/NuGet.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/SupportAlternateVersionPropertyFormats2/input/NuGet.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateArcadeDependency1/input/NuGet.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateArcadeDependency2/input/NuGet.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateDependencies1/input/NuGet.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateDependencies3/input/NuGet.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateDependencies4/input/NuGet.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateDependencies5/input/NuGet.config
dotnet/arcade#2174
Flow feeds into NuGet.config when we find an asset that is located in one of the package feeds that are automatically created by the publishing process.
Validation:
https://github.com/maestro-auth-test/maestro-test2/pull/618/files added feed https://dnceng.pkgs.visualstudio.com/public/_packaging/darc-pub-arcade-fd8184c3fcde81eb27ca4c061c6e171f418d753f for dependencies foo and bar.
https://github.com/maestro-auth-test/maestro-test2/pull/619 removed the feed from the first PR, and added two additional ones for the new package locations for the newer versions of foo and bar.
https://github.com/maestro-auth-test/maestro-test2/pull/620 the new build only produced packages foo and baz (new) the PR adds the feeds for the new assets, and leaves the feed for the existing bar …
=> Include darc managed feeds as part of dependency update PRs

src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
dotnet/arcade#3136
Azure DevOps returns a different status for partially successful builds. Add this new status to the ones that trigger a release pipeline.
=> Trigger release on Partially successful builds

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
We changed our approach to this to instead check if the branch name contains the "internal" word. Therefore we can do that comparison using AzDO predefined variables.
=> Remove creation of IsInternalBuild azdo variable

eng/Versions.props, src/Maestro/Maestro.MergePolicies/Maestro.MergePolicies.csproj, src/Maestro/SubscriptionActorService/SubscriptionActorService.csproj, src/Microsoft.DotNet.Darc/src/Darc/Microsoft.DotNet.Darc.csproj, src/Microsoft.DotNet.Darc/src/DarcLib/Microsoft.DotNet.DarcLib.csproj, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Microsoft.DotNet.Darc.Tests.csproj
This version includes a fix for Ubuntu 18.04 not having libcurl3.
=> Update LibGit2Sharp to 0.26.0.

src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs
When I added the safe checkout for long files names, I introduced a bug where we treat all failures as long file name failures and so we never fetch to see if a commit is available in the source repository.  This change makes it so we fetch and attempt a commit checkout again before attempting a file-by-file checkout.
Recommend appending `?w=1` to the diff for review.
Fixes #440.
=> Add fetch when safe checkout fails.

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs
Another change for https://github.com/dotnet/arcade/issues/3220
The blob feeds look slightly different, and don't include the `nuget/v<version>` portion.
Validated that with this change the blob feeds actually flow to NuGet.config, as seen here: https://dnceng.visualstudio.com/internal/_git/dotnet-arcade-validation/pullrequest/2035?_a=files&path=%2FNuGet.config
=> Fix blob feed regex

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs
Final part of https://github.com/dotnet/arcade/issues/2862
We now stage the files that we update during `update-dependencies`, and we respect the file mode of the file from the original repo:
Validated:
Before:
After running `darc update-dependencies --channel ".Net tools - latest"`
(100755) is the executable-file mode.
=> Respect file mode during darc update-dependencies

azure-pipelines.yml
Disabling until https://github.com/dotnet/arcade/issues/3294 since it's causing failures in official builds.
=> disable failing SDL job

src/Maestro/tests/Scenarios/all.ps1, src/Maestro/tests/Scenarios/azdoflow-feedflow.ps1, src/Maestro/tests/Scenarios/common.ps1
https://github.com/dotnet/arcade/issues/3106
Adds a test that adds assets with feeds that follow the patterns for feeds we manage through Dependency flow, and checks that those feeds are included in the NuGet.config for the pr branch.
=> Add test to check feeds flow through Maestro PRs when they should

src/Maestro/DependencyUpdater/DependencyUpdater.cs, src/Maestro/Maestro.AzureDevOps/AzureDevOpsTokenProvider.cs, src/Maestro/Maestro.GitHub/GitHubTokenProvider.cs, src/Maestro/SubscriptionActorService/PackageRoot/Config/Settings.xml
To solve https://github.com/dotnet/core-eng/issues/6946 we analyzed using a CancellationToken that we would cancel once we hit a timeout but after looking at all places we'd need to change we decided to just up the `OperationTimeout` so mono operations are able to complete.
This also includes caching of the GH access token which helps alleviate the "Bad Credentials" error we are seeing since we'll use tokens that we're created some time before not just immediately before (in most cases)
=> Up timeout and add token caching

src/Maestro/SubscriptionActorService/MergePolicyCheckResult.cs, src/Maestro/SubscriptionActorService/PackageRoot/Config/Settings.xml, src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Maestro/SubscriptionActorService/SynchronizePullRequestResult.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs
We used nullable booleans as tri-state enums in certain cases when synchronizing pull requests. The meanings of the true, false, and null states varied, but generally did not follow a pattern of "yes", "no" and "I don't know". Unfortunately, there was also a 4th state. If SynchronizePullRequestAsync threw, we would return null (default value for nullable bool) out of ActionRunner, causing us to lose track of the PR. Exceptions are relatively rare, but the dominant exception (Octokit credentials exception) is transient and we would end up tracking the PR properly upon retry 5 minutes later.
Fix this by changing the results of SynchronizePullRequestAsync and CheckMergePolicyAsync over to enums. The default value of the enum (Invalid) will now avoid unregistering the reminder.
=> Replace nullable boolean logic with enums

src/Maestro/Maestro.GitHub/GitHubTokenProvider.cs, src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs
Need a little clearer marker as to when we are getting/refreshing the remote to diagnose the Octokit exceptions.
=> Add logging when getting a remote

src/Microsoft.DotNet.Darc/src/Darc/Microsoft.DotNet.Darc.csproj, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs
When coherency updates form chains, where there is more than one leaf, at least 3 elements in the chains, and common elements in the chains, we would end up running the coherency update for the middle elements of the chain more than once. This was not necessary, and ended up listing those elements more than once.
Fix this by breaking the chain building process if we have already updated an element in the chain.
=> Fix duplicate listed entries from coherency updates

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Relates to https://github.com/dotnet/arcade/issues/3188
This is one of two PRs that I'll create to change the way stages are activated in the YAML publishing pipeline. 
With the current format and [the way we activate channel stages](https://github.com/dotnet/arcade/blob/master/eng/common/templates/post-build/channels/public-dev-release.yml#L16) substring matches will activate a channel. For instance, if the list of default channels is "131,141" and a channel has ID 3 or 4, the condition will be true and incorrectly activate the channel. 
Since AzDO doesn't have a good handling of these variables as array of strings/ints I resorted to adding a delimiter between each channel and then later I'll change the condition to include the delimiter. After this PR the example above would then become …
=> Change default channel list variable format

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs
Found this exception triggering quite a bit today. Ended up finding the culprit because the repo's version.Details.xml was small, but this should help with investigations in the future.
=> Log the duped asset name

src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
https://github.com/dotnet/arcade/issues/3501
30 minutes is a lot of time, it gaves the users the impression that some failure happened.
=> Reduce time between build status checks

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/Models/Manifest.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Relates to: https://github.com/dotnet/arcade/issues/3476
Recover the `IsStable` property from the build manifest and expose it as an ADO variable.
Tested the modified version of Maestro.Tasks (Note the information recorded in ReleaseConfigs.txt):
- Here for a non-stable build: https://dnceng.visualstudio.com/internal/_build/results?buildId=291482&view=results
- Here for a stable build: https://dnceng.visualstudio.com/internal/_build/results?buildId=291483&view=results
=> Recover IsStableBuild from Manifest

src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/GitHubClientTests.cs
The cache entries must have their size set with SetSize or the size is lost (maybe not set at all?) and the system will throw InvalidOperationException at runtime.
=> Fix cache entry size setup

src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs, src/Maestro/SubscriptionActorService/DarcRemoteMemoryCache.cs, src/Maestro/SubscriptionActorService/Program.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/GitHubClientTests.cs
When setting up the memory cache with AddMemoryCache(), the memory cache ends up shared between components. As it turns out, EF does not implement their use of the cache as a Size based cache. Thus, the service will fail in unexpected ways when performing DB queries. Instead, a custom memory cache singleton should be created so that the cache is not shared.
=> Fix memory caching (again)

src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs, src/Maestro/SubscriptionActorService/.config/settings.json, src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs, src/Maestro/maestro-angular/package-lock.json, src/Microsoft.DotNet.Darc/src/Darc/Helpers/RemoteFactory.cs, src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxManager.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AuthenticateOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyGraphOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/SetRepositoryMergePoliciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/CommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LocalHelpers.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs, src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyTestDriver.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/GitHubClientTests.cs
Feed the location of the git executable into DarcLib and various classes. The Service Fabric clusters don't have it installed and on the path, so we need to download it when we want to use it.
=> Download git to a temporary location in service fabric

src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxManager.cs
The UxManager looks up the root dir, which is not necessary.  This causes the subscription tests to fail in rollout because they use the UxManager (read from stdin)
=> Fix UxManager root git dir lookup

src/Maestro/Maestro.Web/Api/v2018_07_16/Models/RepositoryBranch.cs, src/Maestro/Maestro.Web/Api/v2018_07_16/Models/SubscriptionPolicy.cs, src/Maestro/tests/Scenarios/common.ps1, src/Maestro/tests/Scenarios/subscriptions.ps1
Disallow creation of merge policies that have more than one merge policy with the same name. I don't know of any cases where this has actually happened, but it could create confusion, like if you created two AllChecksSuccessful policies with different ignored checks. In addition, having this invariant makes some of the forthcoming update subscription code simpler.
=> Disallow duplicate merge policies

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Formerly, this would have thrown ArgumentOutOfRangeException, which is non-ideal. It doesn't really tell the user anything. A regression was introduced when .xml started being required for the manifests. This is reasonable, but coreclr was publishing the manifest files without .xml
=> Better error message if no manifests were found

src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
Up to this point, we've not had a repo that had "PublishUsingPipelines" set to true and was in the DevDiv account. This doesn't work, since the release pipeline is in dnceng. This is a corner case that is not interesting because stages release handles this case already.  Skip releases if they are in a different org/project.
=> [production] Skip releasing if build is in different org/project

src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/SubscriptionsController.cs, src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/SubscriptionsController.cs
Ensure that the duplicate subscription handling works for update by ensuring the duplicate lookup doesn't find the subscription you're trying to update.
=> Ensure duplicate subscription handling works for update-subscriptions

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Tested by doing a Gather-drop of a core-setup build that published blobs to azdo feeds
=> let gather-drop hack its way around downloading blobs from azdo

src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyFlowGraphOperation.cs
The dependency graph adds an automated node from arcade master to .NET Tools - Latest today because the master branch only goes to validation, but implicitly this always flows to .NET Tools - Latest. Add the same for .NET 3 Tools
=> Add an automated node to the dependency graph for .NET 3 Tools

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
The build lookup during publish must verify that the commit matches the commit of each dependency. Otherwise, we will always record the latest version of each dependency that has the same version, even if it was not actually referenced in the repository.
=> Fix build lookup

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/AssetDataComparer.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Remove duplicated assets when merging multiple build manifests.
=> Remove duplicated assets

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/GitFileManagerTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Microsoft.DotNet.Darc.Tests.csproj, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/RemoveAllManagedFeeds/NuGet.output.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/WhiteSpaceCorrectlyFormatted/NuGet.input.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/WhiteSpaceCorrectlyFormatted/NuGet.output.config
The location of the clear element was being moved to after the maestro managed feeds. The tests passed as expected. It turns out that the xml documents are read with "preserve whitespace" on inside Maestro, but the tests did not read them as such. This triggered a bug in the feed update code, it incorrectly assumed the first element after the package sources node would be the clear element, while it was actually a whitespace node.
Fix is twofold:
- Run the tests by reading the xml documents the same way that Maestro does (use GitFileManager)
- Always remove the clear node and add it directly after the package sources node.
=> Fix location of <clear /> element

src/Microsoft.DotNet.Darc/src/DarcLib/DependencyOperations.cs
Update the mapping of known SDK packages to include potential names of future SDKs. For https://github.com/dotnet/arcade/issues/4015.
Adding some preemptively to avoid potentially rollout lag in the future. If any aren't used when the actual names of these SDKs is finalized, they can be cleaned up. Alternatively, the hard-coded list could be replaced by a system that recognizes the SDK packages to avoid updates like this.
=> Add names of potential future SDK package IDs

src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimeline.cs
We need sourcebranch for timelinebuilds to know what channel a build is *intending* to publish to (for determining channel reliability).
I need to add the column to Kusto before merging this PR.
FYI @mmitche @epananth
=> Add sourcebranch to Timeline tables

src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs
If two channels have a commmon substring, commands using this helper can't specify a channel because multiple channels will always match. Instead, return a single channel when there is an exact match.
=> Allow resolve single channel to resolve exact matches

src/Maestro/tests/Scenarios/common.ps1, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepoExtension.cs
Add a 90 second wait while all the dependency update PRs are processed and the PR title gets updated.
should help with dotnet/arcade#3988
The INT logs are also filled with:
```
An exception occurred in the database while iterating the results of a query for context type 'Maestro.Data.BuildAssetRegistryContext'.
System.NullReferenceException: Object reference not set to an instance of an object.
at Microsoft.DotNet.DarcLib.IGitRepoExtension.NormalizeBranchName(String branch) in /_/src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepoExtension.cs:line 45
at lambda_method(Closure , MaterializationContext )
at Microsoft.EntityFrameworkCore.Query.EntityLoadInfo.Materialize()
at Microsoft.EntityFrameworkCore.Query.Internal.QueryBuffer.GetEntity(IKey key, EntityLoadInfo entityLoadInfo, Boolean …
```
=> Add retries when checking the PR title during tests

src/Maestro/Client/src/Generated/Builds.cs, src/Maestro/Client/src/Generated/DefaultChannels.cs, src/Maestro/Client/src/Generated/Models/BuildGraph.cs, src/Maestro/Client/src/Generated/Models/SubscriptionData.cs, src/Maestro/Client/src/Generated/Repository.cs, src/Maestro/Client/src/Generated/Subscriptions.cs, src/Maestro/Maestro.Data/Models/Build.cs, src/Maestro/Maestro.Data/Models/DefaultChannel.cs, src/Maestro/Maestro.Data/Models/Repository.cs, src/Maestro/Maestro.Data/Models/Subscription.cs, src/Maestro/tests/Scenarios/common.ps1, src/Maestro/tests/Scenarios/default-channels.ps1, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyFlowGraphOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetHealthOperation.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepoExtension.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyFlowGraph.cs
This reverts commit 8d5521fc34ee78c009e74658d61fbdf1206c2822.
This change is messing up default channel assignment during the publishing process. Causing silent publishing failures.
=> [HOTFIX] Revert "Normalize branch names by removing refs/heads (#648)"

src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs, src/Maestro/Maestro.Data/Models/Build.cs, src/Maestro/Maestro.Web/Api/v2019_01_16/Models/Build.cs, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/maestro-client/models.ts
Fixes https://github.com/dotnet/arcade/issues/2782, https://github.com/dotnet/arcade/issues/2784
Adds a "Staleness" column which is a "reasonably" accurate reflection of how many more recent version of a dependency are available.  "Reasonable" meaning, it tries to figure out which channels may have relevant dependencies and how many of those are newer.  It's possible that subscriptions have changed or some other abnormal behavior which means the estimate is no longer valid.
FYI @adiaaida @meganaquinn @epananth
=> Add staleness metric to barviz

src/Maestro/maestro-angular/src/app/app.module.ts, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts
This change adds functionality to barviz to check the dependency graph
for dependency cycles. For each node, we walk through the dependency
tree for that node and check to see if any of its product subdependencies
share the same repository url as the node's repository url, indicating a
cycle. We record that there is a cycle and the cycle path in the
BuildData.
In the UI, we display a redo symbol to indicate that there is a cycle at
a particular node, and the hover text includes the cycle path.
Note: The example includes toolsets since we do not currently have any product dependency cycles, and I wanted to test that it was working properly.
=> Add dependency cycle check to barviz

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
The amount of concurrency we were allowing when downloading builds was a little aggressive. It was regularly causing the downloads to hang (presumably thread pool starvation). Introduce a semaphore to limit concurrenycy a specific number of parallel downloads. The default is 4.
=> Limit download concurrency

src/Microsoft.DotNet.Darc/src/Darc/Options/AddDependencyCommandLineOptions.cs
A common method for adding a new dependency involves using add-dependency, the calling update-dependencies to get the right version number and commit. update-dependencies uses the repo uri as a shorthand to look up what builds should be applied to the local branch, so not including the repo uri makes that flow impossible. You could push the branch, and allow Maestro to eventually update the dependencies, but most likely if you don't have the right version, you couldn't check in the new dependency anyway.
It's probably best to just require the repo uri initially.
=> Require repo for add-dependency

eng/Versions.props
LibGit2Sharp 0.27.0-preview-0020 improves support for a number of architectures and linux distributions: https://github.com/libgit2/libgit2sharp/pull/1714
This makes it possible to use arcade (via source-build) on RHEL on arm64.
As an example, I need it for this PR: https://github.com/dotnet/source-build/pull/1300
=> Bump LibGit2Sharp version

src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyTestDriver.cs
Asset locations were not being loaded for dependencies when doing local update-dependencies. This causes the updater to remove all maestro managed feeds in the nuget.config file.
=> Fix update-dependencies to honor nuget.config

src/Maestro/tests/Scenarios/common.ps1
Add another one minute of wait time as the tests are still somewhat flaky. It'll be worth investigating more in depth if this isn't enough to stabilize the tests.
=> Increase retries during pull request title check during batched tests

NuGet.config
Add the dotnet-tools feed to fix Arcade restores.
Remove the dotnet-core feed as it doesn't look like we need anything from it given this test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=395610&view=results
=> Add dotnet-tools feed

src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs
Do not stage files, except for adds (where the file mode may be interesting) when doing update dependencies locally.
Additionally, remove a filter preventing the deletion of files when operating locally.
=> Do not stage files in local git client

src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddDefaultChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/SetRepositoryMergePoliciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/TriggerSubscriptionsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddDefaultChannelCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs
One complaint from some users is that it's easy to mess up default channels, subscriptions, etc. with typos. You can easily type a wrong repo name or branch name and then be confused as to why things are not updating automatically.
To mitigate this, I've introduced checks on operations that deal with branches and repositories. These checks will make sure that branches and repositories exist, and if they do not, they will prompt the user to continue or abort.
This commit also fixes a case where AzDO will return bad request instead of 404 when checking for a branch that doesn't exist.
=> Prompt the user when branches or repos do not exist

src/Maestro/Client/src/Generated/Models/BuildRef.cs, src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs, src/Maestro/Maestro.Data/Migrations/20191018204719_AddTimeToInclusionInMinutes.Designer.cs, src/Maestro/Maestro.Data/Migrations/20191018204719_AddTimeToInclusionInMinutes.cs, src/Maestro/Maestro.Data/Models/Build.cs, src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/BuildsController.cs, src/Maestro/Maestro.Web/Api/v2019_01_16/Models/Build.cs, src/Maestro/Maestro.Web/Api/v2019_01_16/Models/BuildData.cs, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts, src/Maestro/maestro-angular/src/maestro-client/models.ts, src/Maestro/tests/Scenarios/all.ps1, src/Maestro/tests/Scenarios/common.ps1, src/Maestro/tests/Scenarios/dependencies.ps1
We want to know, at each level of the dependency graph, how long it took
for a dependency to get to core-sdk. So, when a change is checked into
coreclr, how long does it take to get from coreclr, through the longest
path in the dependency graph, to core-sdk. This work adds
TimeToInclusion to the BuildDependencies table. TimeToInclusion measures
how long it took from when a build was added to the Build table until
the first build that depended on it was added to the BuildDependencies
table. We then can use the TimeToInclusion in BarViz to calculate how
long it took for that dependency to appear in the dependency graph of
each repo that has it in its dependency graph. This is most important at
the core-sdk level, where we can then discover how long it takes for a
runtime change to flow all …
=> Add TimeToInclusion to BAR and BarViz

src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/ChannelsController.cs, src/Maestro/maestro-angular/src/app/services/channel.service.ts, src/Maestro/maestro-angular/src/maestro-client/maestro.ts
BarViz wasn't showing all repositories in a channel because it was using a paged API to determine the repositories which are contributing to a channel.  Only the first page was returned and so, if a repository hadn't published recently, then it wouldn't show up in the repo list.  This change adds a new API which does the repo list query so that we get a more consistent result set.
=> Missing repositories in BarViz channel list

src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxManager.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Helpers/UxManagerHelpers.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Microsoft.DotNet.Darc.Tests.csproj
Darc takes its editor config from git. When it fails because the git config is not correct (for example, in a case of bad escaping of paths with spaces), it errors out with a very generic error message.
The fix is to provide a more descriptive message.
I wrote few unit tests during research of the issue, so I'm adding them too even though they do not replicate any fixed problem with the codebase. They just demonstrate the current code handles the git config well as long as it's properly escaped.
=> Editor path error handling

src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxManager.cs
Sorry, https://github.com/dotnet/arcade-services/pull/734 isn't complete. The happy path is alright, but the fix does not work as Process.Start() won't trigger `FileNotFoundException` -- it's `Win32Exception` in the case we are interested in. The `FileNotFoundException` is an artifact of my previous testing.
`Win32Exception` seems generic, but the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.process.start?redirectedfrom=MSDN&view=netframework-4.8#System_Diagnostics_Process_Start) states it happens when "There was an error in opening the associated file."
=> Editor path error handling, 2

src/Maestro/Client/src/Generated/Builds.cs, src/Maestro/Client/src/Generated/Channels.cs, src/Maestro/Client/src/Generated/Models/Build.cs, src/Maestro/Client/src/Generated/Models/BuildData.cs, src/Maestro/Client/src/Generated/Models/BuildRef.cs, src/Maestro/Client/src/Generated/Models/BuildUpdate.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs, src/Maestro/SubscriptionActorService/MaestroBarClient.cs, src/Maestro/tests/Scenarios/builds.ps1, src/Maestro/tests/Scenarios/common.ps1, src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateBuildOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/UpdateBuildCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Program.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs
This adds support for marking builds as released or non-released and optionally skipping downloads of released builds. This is so the coherency QB can more easily trim out previously released builds that show up in the graph.
Includes:
- Tests
- Darc command to set a build as released (`update-build`)
- get-build print out
Also regenerates the client
=> Darc support for release/non-released builds

src/Maestro/MaestroApplication/ApplicationPackageRoot/ApplicationManifest.xml, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/UpdateDependenciesCommandLineOptions.cs
For remote coherency scenarios (not specific version update or update from a directory), include an option that will only bring dependencies into correct coherency state. This allows users to adjust a dependency manually and then ask the tool to bring everything else into line.
=> Add a coherency only option to update-dependencies

src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html
The visualization is confusing for BarViz users, so remove the column until we have something that is easier to explain.
=> Remove time to inclusion visualization

src/Microsoft.DotNet.Darc/src/Darc/Operations/GetChannelsOperation.cs
IDs are needed in some cases (e.g. channel publishing) and looking up using the swagger api is clunky.
=> Order channels by name and print their IDs

src/Microsoft.DotNet.Darc/src/Darc/Microsoft.DotNet.Darc.csproj, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/Microsoft.DotNet.DarcLib.AzDev.csproj, src/Microsoft.DotNet.Darc/src/DarcLib/Microsoft.DotNet.DarcLib.csproj
The change to upgrade LibGit2Sharp and enable Darc on arm64 (https://github.com/dotnet/arcade-services/pull/694) does not actually work without also using netcoreapp3.0.
=> Update Darc to netcoreapp3.0.

src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/ChannelsController.cs, src/Maestro/maestro-angular/package-lock.json, src/Maestro/tests/Scenarios/azdoflow-feedflow.ps1, src/Maestro/tests/Scenarios/azdoflow-nonbatched.ps1, src/Maestro/tests/Scenarios/channels.ps1, src/Maestro/tests/Scenarios/common.ps1, src/Maestro/tests/Scenarios/githubflow-nonbatched.ps1
Adds the ability to remove builds from channels. There are times when builds get accidentally added to a channel. In these cases, we'd like to NOT do another build, and simply roll back. This is fairly straightforward. The build+channel combo is removed from the BuildChannels channels table, and if it happened to be that the build was the last applied build, then re-triggering the subscription will roll back to previous build.
Added scenario tests that check for this behavior.
=> Build channel removal

src/Maestro/tests/Scenarios/common.ps1
In some tests, we need to check multiple times to determine whether a PR has been updated. By default azdo seems to be running the script with ErrorAction = stop. Since the caller of Compare-Array-Output always throws if the return value is unexpected, change it to use Write-Host
=> Compare-Array-Output should use Write-Host

src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFile.cs
This should make sure that https://github.com/dotnet/arcade/issues/4193 stops happening.
Presumably, if we get a cache hit for the file, it means it was found in the repo we are checking it for, so we should always default to adding the file.
=> Always return cached arcade items with an add operation

src/Maestro/maestro-angular/package-lock.json, src/Maestro/tests/Scenarios/common.ps1, src/Maestro/tests/Scenarios/subscriptions.ps1, src/Microsoft.DotNet.Darc/src/Darc/Operations/DeleteSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/DeleteSubscriptionsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/DeleteSubscriptionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/DeleteSubscriptionsCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Program.cs
Deprecate delete-subscription and replace with delete-subscriptions (same parameter set supported, plus all the filters of get-subscriptions and trigger subscriptions). This will allow easier cleanup of large numbers of subscriptions.
=> Allow deletion of subscriptions based on filters.

src/Maestro/tests/Scenarios/common.ps1
Actually get the PR information every time we check for the title.
fix for https://github.com/dotnet/arcade/issues/3988 which were not flaky, just broken because of this and only passed by sheer luck.
=> Get the pull request information when waiting for the title to match during scenario tests.

src/Maestro/SubscriptionActorService/MaestroBarClient.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyFlowGraphOperation.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
When the channel names were changed for .NET Tools, get-flow-graph broke because it hard coded the channel names. Fix these up and change over to using an ID instead, which is stable.
=> Fix channel info in get-flow-graph

src/Dotnet.Status.Web/Startup.cs
So that we can manage permissions and tokens without having specific people on the hook
=> Allow bots-high to get access site too

eng/common/templates/steps/publish-logs.yml
File was deleted during  https://github.com/dotnet/arcade-services/pull/816 due to https://github.com/dotnet/arcade/issues/4193
I'll disable the daily arcade subscription for arcade-services until we roll out next week (which includes the fix for #4193) as I want us to make sure everything is stable, and there's a likelyhood that tomorrow's update will delete the file again.
=> Bring back deleted eng/common file

src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/HealthMetrics/ProductDependencyCyclesHealthMetric.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs
The API was previously throwing an http exception when this happened, leading health checks to fail.
=> Return null from GetLastCommitShaAsync if there are no commits

src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs, src/Maestro/SubscriptionActorService/Program.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/PackagesHelper.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/Actors/DelegatedActor.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/DelegatedStatefulService.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/DelegatedStatelessService.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/TemporaryFiles.cs
In particular, the "git-portable" downloads were filling the harddrive.
Try and manage the temporary files a little better... each instance of each service gets
it's own directory, and we'll clean them at startup and shutdown.
Fixes dotnet/core-eng#8483
Fixes dotnet/core-eng#8482
=> Cleanup temporary files

CodeCoverage.runsettings, arcade-services.sln, azure-pipelines.yml, eng/Versions.props, eng/convert-codecoveragetoxml.ps1, eng/test.yaml, src/Maestro/DependencyUpdater/DependencyUpdater.csproj, src/Maestro/SubscriptionActorService/SubscriptionActorService.csproj, src/Maestro/tests/DependencyUpdater.Tests/CheckSubscriptionsAsyncTests.cs, src/Maestro/tests/DependencyUpdater.Tests/UpdateDependenciesAsyncTests.cs, src/Microsoft.DotNet.Darc/src/Darc/Microsoft.DotNet.Darc.csproj
Code coverage was added: https://dnceng.visualstudio.com/internal/_build/results?buildId=454615&view=codecoverage-tab 
Notes: 
- Excluded the Microsoft.DotNet.Darc.Tests project since it was throwing OutOfMemory eceptions. Will write an issue for those to be investigated. 
- Increased the MSBuild and Microsoft.NET.Test.Sdk versions in order to support code coverage from dotnet test. 
- DebugType = Full is required for code coverage, too.
=> Add Code Coverage and run unit tests for Arcade Services during PR

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
Add support for downloading from authenticated locations.  These come in two forms:
- Azure DevOps feeds. This was half-supported before, but the default headers were set on the client, rather than a header per-request. This was both not thread safe as well as incorrect if there was any mix of auth and non-auth.
- Blob storage accounts or other general URIs. In this case, I added a parameter to the gather drop operation which accepts a list of sas suffixes. If an anonymous request fails, the sas uris will be appended one by one and the downloads will retry. While a bit 'brute force', this approach has better ux than others, like providing specific key/value pairs for specific blob url prefixes, etc.
=> Download from authenticated locations

src/Maestro/maestro-angular/src/app/page/build/build.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.ts, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/HealthMetrics/SubscriptionHealthMetric.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
- Fix Subscription table width
- Fix incorrect comments (subscriptions have source channels, not target channels)
- Remove channel filter from Subscription table data (filter should not be applied because the display page is the target channel and subscriptions have source channels, so filtering on the display page's channel is incorrect)
=> Subscription Table Bug Fixes

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
When blobs are published to package feeds, they still have the full path of the asset (not just the package name) in the BAR DB. Strip off the other path elements.
Also add an asset filter parameter to allow for better debugging.
=> Fix download of blobs from package feeds

src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/BuildTimeController.cs
I'm not sure how I missed this, but in all of the edits, I somehow missed projecting the TargetBranch channel in the public kusto query.
=> Project TargetBranch for public kusto query for buildtimes api

src/DotNet.Status.Web/GitHubUserTokenHandler.cs, src/DotNet.Status.Web/Startup.cs
Too many web hook style programs use basic auth for their
mechanism. Let's to what Azure DevOps does and treat
the password as the token and ignore the username
Also fix bouncing from the the status and error pages
=> Allow basic auth with token

src/Maestro/tests/Scenarios/azdoflow-feedflow.ps1, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs
* Only flow feeds for an asset if it's only avaiable in maestro managed feeds
* Only populate nugetFeed locations during dependency updates. The container feed type is unrestorable
* Explicitly check that the build container is not in the flowed feeds in the scenario tests
=> [Rollout] Only flow feeds for an asset if it's only avaiable in maestro managed feeds

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/HealthMetrics/ProductDependencyCyclesHealthMetric.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraphNode.cs
Up to this point, CPD has some odd quirks. It chooses the dependency that it wants to update to based how shallow the asset it finds it in the graph (lowest wins). But it does so using incomplete information in some cases. In order to improve the overall performance of CPD, most of which is graph build time, the graph build was aborted when a specific set of assets was found. This might lead to some odd choices. For instance, if a repo depends on two input dependencies from repo A, one pinned and one not pinned, then a CPD that is reachable from those two dependencies will could potentially choose to update based on the pinned input.
These choices are not wrong, but they aren't usually what the user wants. The user often just wants the path to the newest potential dependency. Doing this …
=> Fix CPD unusual choice issue

src/Shared/Microsoft.DotNet.Kusto/Microsoft.DotNet.Kusto.csproj
I need the Microsoft.DotNet.Kusto package in a project in dotnet-helix-machine so I need it to be published as a package as some other projects in this solution.
=> Make Microsoft.DotNet.Kusto packable

eng/deploy.yaml
I believe this is the fix for https://github.com/dotnet/core-eng/issues/8638
=> Use the endpoint parameter during Notify deployment end job

src/DotNet.Status.Web/Controllers/AlertHookController.cs
We weren't adding this label, which is the label we attempt to use to find a live issue to mark it as "inactive"
=> Add missing alert label required for finding open issue

src/Monitoring/Sdk/GrafanaClient.cs
The most recent deployment changed the uid to a string (as it should, it should be "statusHook"), but that breaks the <int> cast we had when trying to update it.
=> uid is, of course, a string now

eng/deploy.yaml
This will make it so it actually auths which it was failing to do previously. Connection string does not contain any secrets.
=> Add user identity connection string to deployment

src/Maestro/Maestro.Web/Pages/Index.cshtml, src/Maestro/maestro-angular/angular.json, src/Maestro/maestro-angular/package-lock.json, src/Maestro/maestro-angular/package.json, src/Maestro/maestro-angular/patches/@angular-devkit+build-angular+0.13.9.patch, src/Maestro/maestro-angular/src/app/page/channel-graph/channel-graph.component.ts, src/Maestro/maestro-angular/src/d3.ts, src/Maestro/maestro-angular/src/index.html
Angular's minification of d3 removes functions that are used, causing a runtime error. This change brings in the d3 types to fix dagre-d3's import, adds a patch to build-angular to exclude d3 from minification, and pulls in d3.min.js from the cdn. This fixes https://github.com/dotnet/arcade/issues/4758 without having to turn off all optimizations.
=> Fix using d3 with angular

eng/deploy.yaml
It looks like the vs2019 image causes the powershell based tests to fail: https://github.com/dotnet/core-eng/issues/8884
I tested this image in this "validate only" deployment of a test branch: https://dev.azure.com/dnceng/internal/_build/results?buildId=514478&view=results
=> Move to vs2017-win2016 image for scenario tests

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/CommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/DarcOutputType.cs
- Add a global option to darc to switch to yaml/json.
- Implement option for gather-drop's manifest generation
Uses newtonsoft.json rather than System.Text.Json because of the netstandard2.1 target
=> Add json option for manifest file creation

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetChannelsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/CommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/DarcOutputType.cs
The yaml output type, which is the current default, is not really yaml much of the time.
=> Change yaml output type to "text"

src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/ChannelsController.cs, src/Maestro/maestro-angular/src/app/app-routing.module.ts, src/Maestro/maestro-angular/src/app/page/channel-graph/channel-graph.component.ts, src/Maestro/maestro-angular/src/app/page/channel/channel.component.html, src/Maestro/maestro-angular/src/app/page/channel/channel.component.ts, src/Maestro/maestro-angular/src/app/services/channel.service.ts, src/Maestro/maestro-angular/src/maestro-client/maestro.ts, src/Maestro/maestro-angular/src/themes/_base.scss
To improve the viewability of the flow graph, this change:
* Adds includeArcade option to GetFlowGraphAsync so that on barviz we can exclude arcade and its children from the graph
* Splits the organization and repository name in node labels
* Puts the label in a div to improve font size
* Changes the ranker algorithm to tight-tree
* Round the corners of the nodes
* Increases the number of days to summarize over to 30
* Add GetChannel(id) so that we can display the channel name in the header of the graph, rather than just "Channel"
Also fixes some indentation and removes some commented out code.
Future work will be to enable the user to toggle between including arcade and excluding arcade, and potentially further extending this to toggling only the longest build path vs. the entire tree.
=> Improve graph display

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/quota.dashboard.json
With most Azure resources there's no perf degradation til we hit the limit, and our staging environment typically exceeds 80%.  Further, Prod can (if it got used enough) easily hit 100% in non-exceptional circumstances though it's useful to know it happened.
=> Increase max quota to 95%

src/Maestro/Maestro.Web/.config/settings.Development.json, src/Maestro/Maestro.Web/Startup.cs
Relates to: https://github.com/dotnet/core-eng/issues/8696
Use connection string stored in KV to connect to maestrolocal Azure AppConfiguration when testing locally.
This one I can rightly say: it works on my machine.
=> Fix app configuration connection for local development.

src/Maestro/maestro-angular/src/app/page/channel-graph/channel-graph.component.ts, src/Maestro/maestro-angular/src/app/page/channel/channel.component.html, src/Maestro/maestro-angular/src/app/page/channel/channel.component.ts, src/Maestro/maestro-angular/src/maestro-client/maestro.ts, src/Maestro/maestro-angular/src/themes/_base.scss
* Add the toggle
* Get the flow graph with arcade
* If the toggle is disabled, do not display arcade master or release/3.x
* Also creates a list of nodes that either have no input or output edges, or whose only edges are to/from arcade and creates invisible edges between them, so that they do not clog up the graph (this essentially tricks the layout algorithm into thinking that they all have different ranks)
=> Add a toggle for including arcade in the flow graph

eng/test.yaml
This bug doesn't repro in current code, so this change removes the exclusion.
=> Turn on code coverage for Darc tests

src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddDefaultChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDefaultChannelBaseOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/SubscriptionsCommandLineOptions.cs, src/Shared/Microsoft.DotNet.Services.Utility/GitHelpers.cs
Relates to: https://github.com/dotnet/arcade/issues/4883
Normalize branch names before doing subscription and default-channel operations.
=> Normalize branch names when comparing.

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddBuildToChannelCommandLineOptions.cs
Make Darc add-build-to-channel wait (by default) for the promotion build to finish and report back to the user the result. Add option to let user tell Darc not to wait for said build.
Example outputs:
Default scenario (wait for promotion to finish) + success promotion:
```
PS C:\Users\disoares> dotnet C:\Workfolder\arcade-services\artifacts\bin\Microsoft.DotNet.Darc\Debug\netcoreapp2.1\Microsoft.DotNet.Darc.dll add-build-to-channel --id 43561 --channel "general testing"
Assigning the following build to channel 'General Testing':
Repository:    https://dev.azure.com/dnceng/internal/_git/dotnet-arcade
Branch:        refs/heads/FixConflictCheck
Commit:        07f46d783c0b017718a9c2c22e0a0e039bc8ae45
Build Number:  20200219.3
Date Produced: 2/19/2020 11:28 AM
Build Link: …
```
=> Make Darc wait for the promotion build to finish. Add option to not wait

eng/deploy.yaml
Right now, if approval is slow, the deployment time range includes the time we are waiting, which creates a false sense of this time for reporting.
=> Move approval to before the "notifyStartDeployment"

README.md
Based on feedback on the commit to add steps to validation, removing the line item to run scenario tests - https://github.com/dotnet/arcade-services/commit/50a6fae92044adeb6a11555b5664e47957352b36
Once the documentation on how to run scenario tests locally is added, the link for the same should be added to the ReadMe, this work is tracked here - https://github.com/dotnet/core-eng/issues/9103
Also collapsing the steps to manual deployment using a dev branch by default
=> Remove Scenario Test from the test locally list

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Fixes https://github.com/dotnet/arcade/issues/4929. Ensure that contributing builds matching the repo+sha also match the build id of the root build. Avoids cases where we would download two versions of the root repo.
Also removes some unused code
=> Fix gather-drop contributing builds

src/Maestro/tests/Scenarios/builds.ps1, src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
By default, exclude released builds from a drop. This is the most common scenario.
=> Make skip-released the default behavior

src/Monitoring/Sdk/README.md, src/Monitoring/grafana-init/grafana.ini, src/Monitoring/grafana-init/setup.sh
- some doc changes I had yet to commit
- disable snapshots to external server. Snapshots can be useful and I think we'll use them more. There's no reason to use an external server to host them.
=> Small grafana tweaks

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs
Contains a variety of improvements to gather-drop that focus on how the tool is normally used. The typical scenario is that someone runs gather drop to get a unified drop, the again to get the release layout. This is expensive, order dependent, and clunky. Instead, this commit changes the tool to gather both drops at the same time. In addition:
- Always use json for the manifest file (the parameter is not required)
- Call out a few commits in repos that do not have builds (because they pre-date maestro). Ignore these when determining whether there are dependencies missing builds. This is so we can use --continue-on-error.
- Trim the name, commit, and version parameters in version details files. This was causing the previous improvement to not work for a specific node.
- Copy files to both …
=> gather-drop improvements

eng/Versions.props, src/Maestro/tests/Maestro.ScenarioTests/MaestroScenarioTestBase.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs
Split out the shared logic in MaestroScenarioTests.cs and convert to a base class.
Update the test sdk version to 16.5 to avoid this issue: https://developercommunity.visualstudio.com/content/problem/831442/test-explorer-wont-run-tests-too-particular-about.html
=> Maestro scenario test base

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
Remove the --sdk, --aspnet, and --runtime shorthand switches.
The repo consolidation, repo org changes, etc. have made these options not particularly useful,
and I don't think they were particularly useful in the first place.
=> Remove url shorthand switches

src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs
Delete the PR branch when we detect that the PR has been merged or abandoned.
https://github.com/dotnet/arcade/issues/3214
Validation:
Validated this with these two dependency update PRs using the scenario tests:
https://github.com/maestro-auth-test/maestro-test2/pull/9519
https://dev.azure.com/dnceng/internal/_git/maestro-test2/pullrequest/6540
Github is nicer in that it actually shows that the app deleted the branch.
In the Azdo PR note that the Delete source branch button is greyed out, and that trying to get to the branch 404s.
=> Delete the Pull Request branch when a PR is manually merged or closed

src/Maestro/FeedCleanerService/FeedCleanerService.cs, src/Maestro/tests/FeedCleaner.Tests/FeedCleanerServiceTests.cs
Workaround for repos doing weird things and nuget being dumb with feeds that don't exist.
Tracking issue to re-enable this: https://github.com/dotnet/arcade/issues/5052
=> Do not delete feeds after deleting all packages

src/Microsoft.DotNet.ServiceFabric.ServiceHost/Microsoft.DotNet.ServiceFabric.ServiceHost.csproj, src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHost.cs
This is the one everyone is supposed to use, so lets just plop it in our default set
=> Add default IMetricTracker for all services

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
* Enable darc-add-build-to-channel to promote builds from Devdiv: 
This is for https://github.com/dotnet/arcade/issues/4986 and is needed to get NuGet insertions into .NET working again.
Triggered https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3556040&view=logs&j=f7bb3748-e35d-53de-9dd7-460ecd2014d6&t=299a6d6d-a279-539e-b6e9-1576018947a8 with these changes.
* Also fixes some validation errors that weren't failing the operation due to a bug in the validation code: dotnet/arcade#4941
=> Fixes to darc-add-build-to-channel

src/Shared/Microsoft.DotNet.Services.Utility/Microsoft.DotNet.Services.Utility.csproj
This is a dependency for DarcLib, so it needs to be published in order for the DarcLib package to be useable.
=> Publish Microsoft.DotNet.Services.Utility

src/Maestro/DependencyUpdater/DependencyUpdater.cs
When we were trying to update the longest build path table, it thought we were also trying to add a new channel, which was (correctly) being rejected, so the longest build path table wouldn't get updated. This change explicitly uses the Channel Id, rather than the channel object, to create the longest build path object.
Also adds some App Insights logging.
=> Fix longest build path history

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs
Relates to: https://github.com/dotnet/arcade/issues/4882
Fail faster if the Http response is 401 (Unauthorized).
=> Stop retries when response is 401

azure-pipelines.yml, eng/deploy.yaml, eng/refresh-service-fabric-services.ps1
Relates to: https://github.com/dotnet/core-eng/issues/9353
**What is it?**
A new script in `eng\` folder that removes all service fabric services currently running which type isn't present among the underlying Service Fabric Application service types. 
Implemented following suggestions from @alexperovich .
**Tests?**
- I tested the script locally for the Telemetry and Maestro applications. 
- **What's the best way to test this in INT? I.e., what's the best way to test the YAML part?**
**Sample output:**
```
Service types found:
SubscriptionActorServiceType
PullRequestActorServiceType
DependencyUpdaterType
Maestro.WebType
FeedCleanerServiceType
Currently running services:
fabric:/MaestroApplication/DependencyUpdater : DependencyUpdaterType
fabric:/MaestroApplication/FeedCleanerService : …
```
=> Infra for refreshing service fabric services.

eng/deploy.yaml
Build is broken because the ReleaseUtilities artifact wasn't downloaded before calling refresh-service-fabric-services.ps1: https://dnceng.visualstudio.com/internal/_build/results?buildId=573177&view=results
=> Fix build due to missing artifact download

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
fixes https://github.com/dotnet/arcade/issues/5122
Please note that I'm not an MSBuild expert. I don't know if creating this output parameter will have consequences on targets that call the task and don't handle the output.
=> Output build id as msbuild property in PushMetadataToBuildAssetRegistry

src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs
We were not doing the correct azdo/github repo uri and branch preferencing in update-dependencies and thus it was impossible to update from an azdo only build.
=> Correctly update dependencies from azdo only builds

src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/AssetsController.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/AssetsController.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Models/AssetAndLocation.cs
Relates to: https://github.com/dotnet/arcade/issues/5077
Add API that receive list of (asset id, [location, location type]) and persist all of it in BAR. This is a promising optimization for publishing.
=> Add Maestro Asset API that support bulk association of location to asset

src/Microsoft.DotNet.Darc/src/Darc/Options/SubscriptionsCommandLineOptions.cs
Relates to: https://github.com/dotnet/arcade/issues/5157
Without this modification if the two strings are compared: "https://github.com/dotnet/aspnetcore" and "https://github.com/dotnet/aspnetcore-tooling" the result will be `true` because the final else clause will find that one string is substring of the other. Is that the behavior we want? It seems a bit misleading given the parameter name `-Exact`. Also, same thing will happen with the `RegexMatch` flag - i.e., the regex fail but then the substring condition returns true.
=> Do exact comparison if Exact parameter is passed

src/Microsoft.DotNet.ServiceFabric.ServiceHost/KeyValuePairExtensions.cs
When this is public, anyone referencing this namespace get's in trouble,
because it becomes ambiguous with the one in the framework itself.
This one only works because "my namespace" always beats "imported namespace",
so it's not ambiguous here, but anyone that references this DLL in it's standard configuration
is going to end up with two ambiguous methods here.
=> Make KeyValuePair.Deconstruct internal

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/GitFileManagerTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Microsoft.DotNet.Darc.Tests.csproj, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/VersionPropsFiles/AlternateNamesDuplicated.props, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/VersionPropsFiles/DuplicatedSameConditions.props, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/VersionPropsFiles/NoDuplicatedDifferentConditions.props, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/VersionPropsFiles/NothingDuplicated.props, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/VersionPropsFiles/SimpleDuplicated.props
Relates to: https://github.com/dotnet/arcade/issues/4984
Check that no two combination of PropertyName + [cC]ondition exists in Version.props
=> Darc verify duplicated properties

arcade-services.sln, src/Maestro/MaestroApplication/ApplicationPackageRoot/ApplicationManifest.xml, src/Maestro/bootstrap.ps1, src/Microsoft.DncEng.Configuration.Bootstrap/Microsoft.DncEng.Configuration.Bootstrap.csproj, src/Microsoft.DncEng.Configuration.Bootstrap/Program.cs, src/Microsoft.DncEng.Configuration.Bootstrap/app.manifest, src/Microsoft.DncEng.Configuration.Extensions/ConfigurationConstants.cs, src/Microsoft.DncEng.Configuration.Extensions/LocalDevTokenCredential.cs, src/Microsoft.DncEng.Configuration.Extensions/Microsoft.DncEng.Configuration.Extensions.csproj, src/Microsoft.DncEng.DeployServiceFabricCluster/Microsoft.DncEng.DeployServiceFabricCluster.csproj
This change updates the auth flow for local development
to use a group and ACLs to restrict access to the cache file.
This removes the need to sign in from a debug breakpoint,
the sign-in can be done beforehand in boostrap.ps1.
dotnet/core-eng#9235
=> Fix local dev authentication flow

src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/BuildsController.cs, src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/BuildsController.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/BuildsController.cs, src/Maestro/MaestroApplication/ApplicationPackageRoot/ApplicationManifest.xml, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetBuildOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GetBuildCommandLineOptions.cs
- Add new optional parameters to lookup builds by the AzDO information
- Add new darc commands to lookup builds by repo+commit or the azdo URI.
The azdo URI option is currently disabled as it requires the new REST api.
=> Build lookup improvements

src/Maestro/Maestro.Contracts/DependencyUpdateSummary.cs, src/Maestro/Maestro.Contracts/IPullRequest.cs, src/Maestro/Maestro.MergePolicies/AllChecksSuccessfulMergePolicy.cs, src/Maestro/Maestro.MergePolicies/DontAutomergeDowngradesMergePolicy.cs, src/Maestro/Maestro.MergePolicies/IMergePolicyEvaluationContext.cs, src/Maestro/Maestro.MergePolicies/Maestro.MergePolicies.csproj, src/Maestro/Maestro.MergePolicies/NoRequestedChangesMergePolicy.cs, src/Maestro/Maestro.MergePolicies/StandardMergePolicy.cs, src/Maestro/SubscriptionActorService/IMergePolicyEvaluator.cs, src/Maestro/SubscriptionActorService/InProgressPullRequest.cs, src/Maestro/SubscriptionActorService/MergePolicyEvaluationContext.cs, src/Maestro/SubscriptionActorService/MergePolicyEvaluator.cs, src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs
Add merge policy that prevents auto merging PRs that contains package version downgrades.
@mmitche I implemented the idea that we discussed offline: add the list of required updates to the InProgressPullRequest object. To make that work I had to do a bunch of 'refactoring':
- Add the DependencyUpdateSummary class; This way we only serialize the information that we need.
- Had to create IPullRequest interface so that IMergePolicyEvaluatorContext could contain a 'PullRequest' property. 
- Small change in MergePolicies.csproj so that it can reference Maestro.Contracts.csproj
- Some changes to convert "prUrl" to "pr.Url"
- Some changes to work with DependencyUpdate instead of DependencyDetail
Tested locally + a private repo in Azdo: https://dnceng.visualstudio.com/internal/_git/Cesar2/pullrequ …
=> Don't automerge PRs with package downgrades

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddBuildToChannelCommandLineOptions.cs
Closes: https://github.com/dotnet/arcade/issues/5199
Adds additional parameters to Darc add-build-to-channel to let the user inform the new parameters added to the promotion pipelines: https://github.com/dotnet/arcade/pull/5160
=> Additional params to add-build-to-channel

arcade-services.sln, src/DotNet.Status.Web/Controllers/AzurePipelinesController.cs, src/DotNet.Status.Web/DotNet.Status.Web.csproj, src/Telemetry/AzureDevOpsClient/AzureDataTypes.cs, src/Telemetry/AzureDevOpsClient/AzureDevOpsClient.cs, src/Telemetry/AzureDevOpsClient/AzureDevOpsClient.csproj, src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimeline.cs, src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimeline.csproj
This dependency causes the web site to require 64-bit, where it otherwise would not,
and there is no compelling reason for that binding to exist.
=> Break the ServiceHost dependency on the web project

src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFile.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs
Relates to: dotnet/arcade#2427
The crux of the change is:
- The addition of a Metadata dictionary to the GitFile class so that we can record interesting information about files that were committed.
- Patch PullRequestActor to use the information below and update the PR description accordingly.
Tested it locally + private repo of mine. Sample PR is here: https://dnceng.visualstudio.com/internal/_git/Cesar2/pullrequest/7118
=> Show update to global.json as part of PR description

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddBuildToChannelCommandLineOptions.cs
Relates to: dotnet/arcade#5134
- Let user specify `--channel xyz` or `--default-channels` when calling `darc add-build-to-channel`.
- The new option (--default-channels) will be important moving forward because we'll soon let users use `darc add-build-to-channel --default-channels` at the end of their builds to call the build promotion pipeline.
Tested locally + INT + [DncEng promotion pipeline.](https://dnceng.visualstudio.com/internal/_build/results?buildId=597774&view=logs&s=47986e52-e7c7-5211-2268-5ed4cbcd44e4&j=5efe09e7-d552-5578-8f7a-2fec74a23f0f)
=> Add parameter to add-build-to-channel to let user add a build to all default channels.

src/Maestro/SubscriptionActorService/PullRequestActor.cs
Relates to: https://github.com/dotnet/arcade/issues/5245
I overlooked that we add some files to the list of committed files even when we didn't do any change to it. In that case the Metadata isn't set for the file :-(
Executed the tests locally and got this PR created: https://github.com/maestro-auth-test/maestro-test2/pull/10079
=> Check that metadata is present

src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs
Found this while working on another issue. Without using the custom dependency comparison class we'll end up with a bunch of repeated dependencies.
=> Don't duplicate dependencies when computing dependency graph

src/GitHubApps/DarcBot/AzureFunction.cs
Fixes the build break introduced in https://github.com/dotnet/arcade-services/pull/914 due to the renaming of this namespace.
=> Fix Microsoft.DotNet.GitHub.Authentication namespace in darcbot

src/Maestro/SubscriptionActorService/PullRequestActor.cs
Not only might the MergePolicies not exist, there might not be a branch
reference at all. This make several tests pass, so appears to be the
correct behavior.
=> Null safe GetMergePolicyDefinitions

eng/create-tag.ps1, src/Maestro/tests/Scenarios/common.ps1, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
This reverts commit 0ef73e1030a303bcd715c4311009fa2e55b90592.
All of our requests are getting 400 "bad request" with this body:
```json
{
"$id":"1",
"innerException":null,
"message":"The requested version \"5.0\" of the resource is under preview. The -preview flag must be supplied in the api-version for such requests. For example: \"5.0-preview\"",
"typeName":"Microsoft.VisualStudio.Services.WebApi.VssInvalidPreviewVersionException, Microsoft.VisualStudio.Services.WebApi",
"typeKey":"VssInvalidPreviewVersionException",
"errorCode":0,
"eventId":3000
}
```
=> Revert "Move from a soon-to-be-deprecated preview AzDO API (#1123)"

src/Maestro/Maestro.Data/Migrations/20200413233357_AddBuildIncoherenciesTable.cs
Builds are failing with:
```
System.Data.SqlClient.SqlException (0x80131904): Column names in each table must be unique. Column name 'Stable' in table 'Builds' is specified more than once.
```
This was caused by a recent PR of mine. I think I manually removed the `Stable` column from the Builds table in my local BAR before creating the migration.. consequently the migration added the column again and now it's causing errors.
=> Fix Arcade-services official build

src/Maestro/Client/src/Generated/MaestroApi.cs
Arcade services official builds are broken because of a bug in the Maestro.Client. The error had already been fixed but then I reverted the fix when I [merged this PR](https://github.com/dotnet/arcade-services/pull/1101/files#diff-d8dfc9d365bba862a19f59989e70418cL230).
Current PR is to re-introduce the patch.
=> Update Maestro Client

src/Microsoft.DotNet.Darc/src/Darc/runtimeconfig.template.json
Upgrading the used SDK in Arcade to 5.0 showed that Darc currently doesn't have a rollforward policy for major versions. This should be enabled for global tools to not depend on specific runtime version.
Fixes https://github.com/dotnet/arcade/issues/5412
cc @akoeplinger @missymessa
=> Allow rollforward on Major versions for Darc

src/Maestro/Client/src/AuthenticationException.cs, src/Maestro/Client/src/MaestroApi.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddDefaultChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/DefaultChannelStatusOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/DeleteBuildFromChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/DeleteChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/DeleteDefaultChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/DeleteSubscriptionsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetAssetOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetBuildOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetChannelsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDefaultChannelsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyFlowGraphOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyGraphOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetGoalOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetHealthOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetLatestBuildOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetRepositoryMergePoliciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/SetGoalOperations.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/SetRepositoryMergePoliciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/SubscriptionsStatusOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/TriggerSubscriptionsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateBuildOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateSubscriptionOperation.cs
Improve error message when access to Maestro API fail. Change from this:
```
fail: Microsoft.DotNet.Darc.Operations.Operation[0]
Error: Failed to retrieve channels
Microsoft.DotNet.Maestro.Client.RestApiException`1[Microsoft.DotNet.Maestro.Client.Models.ApiError]: The response contained an invalid status code 401 Unauthorized
Body:
at Microsoft.DotNet.Maestro.Client.Channels.OnListChannelsFailed(Request req, Response res) in /_/src/Maestro/Client/src/Generated/Channels.cs:line 151
at Microsoft.DotNet.Maestro.Client.Channels.ListChannelsAsync(String classification, CancellationToken cancellationToken) in /_/src/Maestro/Client/src/Generated/Channels.cs:line 116
at Microsoft.DotNet.DarcLib.MaestroApiBarClient.GetChannelsAsync(String classification) in …
```
=> Pretty print unauthorized Maestro API access

src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts
Relates to: https://github.com/dotnet/core-eng/issues/9760
The incoherencies field is returning "undefined" in some cases, this is messing with the Javascript and the UI. Add code to handle that.
=> BarViz UI, account for undefined values

src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts
Closes: https://github.com/dotnet/core-eng/issues/9760
Make BarViz UI not fail when `incoherencies` field is undefined.
=> [HOTFIX] BarViz UI, account for undefined values (#1154)

src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyAddUpdateTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyTestDriver.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateArcadeDependency2/output/global.json, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateArcadeDependencyWithSdkUpdate/input/NuGet.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateArcadeDependencyWithSdkUpdate/input/eng/Version.Details.xml, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateArcadeDependencyWithSdkUpdate/input/eng/Versions.props, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateArcadeDependencyWithSdkUpdate/input/global.json, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateArcadeDependencyWithSdkUpdate/output/eng/Version.Details.xml, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateArcadeDependencyWithSdkUpdate/output/eng/Versions.props, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/UpdateArcadeDependencyWithSdkUpdate/output/global.json
Fixes https://github.com/dotnet/arcade/issues/5433. The global json update
for the SDK was missed for the local flow. Refactor the code so that the
sdk update happens in UpdateDependencyFiles which is shared between Remote
and Local flows. Add tests
Other changes:
- Pass in a remote factory so we don't have to mangle the arcade repo uri.
- Fix one of the update dependencies tests which was not testing any global.json update.
=> Have update-dependencies work with the SDK

src/Maestro/Client/src/Microsoft.DotNet.Maestro.Client.csproj
When I tried plugging the latest version of Maestro.Client into Tasks.Feed ([testing this PR](https://github.com/dotnet/arcade/pull/5414)) I found out that due to a conflict of version the tasks in Tasks.Feed was failing at runtime. This PR is to fix that.
=> Up Azure.Core version

src/RolloutScorer/RolloutScorer/RolloutScorer.cs, src/RolloutScorer/RolloutScorer/Utilities.cs
1. Sort build breakdowns for real
2. Adjust for the changed hotfix label name
=> Small bugfixes in the RolloutScorer

src/DotNet.Status.Web/Controllers/AlertHookController.cs, src/DotNet.Status.Web/Options/GitHubConnectionOptions.cs, src/DotNet.Status.Web/appsettings.Production.json, src/DotNet.Status.Web/appsettings.Staging.json
Fixes a bug where two same alerts but from different environments use the same issue while there should be two separate ones
https://github.com/dotnet/core-eng/issues/9713
=> Make Grafana notifications environment specific

src/Maestro/Maestro.Data/Maestro.Data.csproj
3.1 stopped generating runtimeconfig.json for DLLs, but it's necessary for EF migrations to be run
=> We need this for EF migrations

src/Microsoft.DotNet.Darc/src/Darc/Operations/TriggerSubscriptionsOperation.cs
Filter and notify the user if some subscriptions are disabled. There have been a few cases where users expected PRs to be created but they were not.
=> Filter disabled subscriptions in trigger-subscriptions

src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs, src/Maestro/SubscriptionActorService/LocalGit.cs, src/Maestro/SubscriptionActorService/Program.cs
Previously DarcRemoteFactory was Singleon, but it injects a
DB context, which is scoped, which means it also, needed to be scoped,
when that happened, its _semaphoreSlim became useless, so every
call of the service tried to muck about with the zip file.
Extract out the part that handles the LocalGit, so that it can go back
to singleton, so that it's _semaphoreSlim is singleton again.
This is what's causing the last test failure (it uses local git, nothing else does)
=> Extract LocalGit to be singleton

src/Maestro/Maestro.Data/BuildAssetRegistryInstallationLookup.cs, src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/RepositoryController.cs, src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/SubscriptionsController.cs, src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/SubscriptionsController.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/BuildsController.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/SubscriptionsController.cs, src/Maestro/Maestro.Web/BackgroundQueue.cs, src/Maestro/Maestro.Web/Startup.cs
Fix lifetime of BackgroundQueue
The BackgroundQueue took a callback, which caused almost every caller
to pass a lambda that contained a bunch of bound objects with
unpredictable lifetimes.  Since the background queue runs
asynchronously, this means that often the items complete after
the caller has returns and disposed all the bound objects,
resulting in unpredictable behavior.
Change the contract of the queue so it's no longer to
flow lifetimes into the queue.
Make the BackgroundQueue create a scope (so that various items aren't
sharing the global scoped DbContext) for each item to manage
the lifetimes appropriately, and to resolve any dependencies.
=> Fix lifetimes

arcade-services.sln, src/Maestro/Maestro.Web/Controllers/WebHooksController.cs, src/Maestro/Maestro.Web/Maestro.Web.csproj, src/Maestro/Maestro.Web/Startup.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Builds.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Channels.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_DefaultChannels.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Dependencies.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_RepoPolicies.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraphNode.cs, src/Shared/Microsoft.DotNet.Internal.DependencyInjection.Tests/LazyTests.cs, src/Shared/Microsoft.DotNet.Internal.DependencyInjection.Tests/Microsoft.DotNet.Internal.DependencyInjection.Tests.csproj, src/Shared/Microsoft.DotNet.Internal.DependencyInjection/Microsoft.DotNet.Internal.DependencyInjection.csproj, src/Shared/Microsoft.DotNet.Internal.DependencyInjection/ResolvingLazy.cs, src/Shared/Microsoft.DotNet.Internal.DependencyInjection/ServiceCollectionExtensions.cs
Allow Lazy<T> resolution in DI.
Also, be sure to enumate DBContext lists and await all DBContext tasks, otherwise
there are multithreading issues.
=> Fix 2 issues related to DI scopeing and DB Context lifetimes

src/DotNet.Status.Web/appsettings.json
Configuring Build Monitor to assign me issues when `\\dotnet\arcade-validation\\dotnet-arcade-validation-for-promotion` fails.
=> I want to spam myself when more pipelines fail

src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHost.cs
Because of https://github.com/dotnet/runtime/issues/36908,
this is causing arbitrary http requests to crash with "FormatExceptions".
Activity information is being injected by services outside our control, so
we can't force a safe format, so our only choice to disable it.
=> Disable System.Net.Http.EnableActivityPropagation

src/Maestro/Maestro.Web/Startup.Api.cs
swagger-ui is breaking because it doesn't understand what we put in security schemes currently.
=> Fix security schemes

src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs
I encountered an issue for tests involving DarcLib where it was taking 8 minutes for a test to retry a function that was expected to fail.  This PR is to add the option to specify that Client functions employing retries should not use them.
=> Specify If Retries Allowed For GitHubClient And AzureDevOpsClient 

src/Maestro/Microsoft.AspNetCore.ApiPagination/Microsoft.AspNetCore.ApiPagination.csproj, src/Maestro/Microsoft.AspNetCore.ApiVersioning.Analyzers/DoNotUseUnversionedTypesInVersionedApis.cs, src/Maestro/Microsoft.AspNetCore.ApiVersioning.Analyzers/Microsoft.AspNetCore.ApiVersioning.Analyzers.csproj
The version bump made the analyzer unloadable by any compiler that isn't as new or newer than 3.5.0.
=> Make ApiPagination Packable and revert roslyn version in Analyzer

src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs
I encountered an issue for tests involving DarcLib where it was taking 8 minutes for a test to retry a function that was expected to fail. This PR is to add the option to specify that Client functions employing retries should not use them.  Note that LocalGitClient does not currently have functions employing retries, it just needed the property because it implements the IGitRepo interface.
Since the previous PR encountered build issues, this PR is to resolve them.
=> Specify If Retries Allowed For GitHubClient, AzureDevOpsClient, And LocalGitClient

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
After debugging errors reported by @lukas-lansky on the release pipeline ([see sample here](https://dev.azure.com/dnceng/internal/_build/results?buildId=654620&view=results)) I noticed the download of some assets is being cancelled because the current default timeout is too low and also the error message doesn't tell sufficient information about what happened. This PR is to increase the default timeout and also improve the error message.
=> Minor patches in gather-drop

src/Maestro/maestro-angular/src/app/page/build/build.component.ts
Builds that were aborted because jobs didn't start should be counted as failed
=> Count cancelled builds as failed

src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
I broke this when I refactored a bunch of code a bit back. We attempt to look up the arcade version of the SDK, but use the wrong remote to do so (use the AzDO remote for the github repo).
=> Fix arcade repo remote

src/Maestro/Maestro.Web/Startup.cs
Let's try this. The Logging says it shouldn't be here, but the condition
said we are here.
There is no reason to read the config for every single request... the value can't change,
so let's not even set up the pipeline if it's not going to work.
=> Only Read DoApiRedirect at boot and set up middleware

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/quota.dashboard.json
In order to avoid having gaps on the data for the issue https://github.com/dotnet/core-eng/issues/10044 doing this fix. 
This should be eventually reverted to avoid confusion, for this creating the next issue on the backlog https://github.com/dotnet/core-eng/issues/10051 
Link to the alert:
https://dotnet-eng-grafana-staging.westus2.cloudapp.azure.com/d/quota
=> Fix cores consumption graph

azure-pipelines.yml, eng/test.yaml
Exclude the categories we use.
Also, since we run "dotnet test", don't have the build also do the test,
since those results aren't uploaded, it's 100% impossible to see what even failed.
=> Make us do all testing only once

src/DotNet.Status.Web/Controllers/GitHubHookController.cs, src/DotNet.Status.Web/Controllers/GrafanaNotification.cs, src/DotNet.Status.Web/Controllers/GrafanaNotificationMatch.cs
Moving from .NET core 2.1 to 3.1 dropped Newtonsoft.Json in favor of System.Text.Json. Now, only parameterless constructors are used for model classes. This change modifies models as needed.
=> Fix deserialization

eng/test.yaml, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Builds.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Channels.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_DefaultChannels.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Dependencies.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_RepoPolicies.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs
This allows the tests to be run in parallel, which significantly increases
the throughput of the tests (instead of 5 minutes, it's closer to 20 seconds).
The "projects" value is expaned by Azure DevOps and the call is made
one project at a time.  "dotnet test" has parallelism built in, but when
targeting a single project, it can't do much.
=> Target the solution instead of the csproj for tests

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddBuildToChannelCommandLineOptions.cs
Related to: https://github.com/dotnet/arcade/issues/5303
This makes Darc add-build-to-channel forward the target publishing infra version to the build promotion pipeline.
Tested it locally + a testing promotion pipeline that I have: https://dnceng.visualstudio.com/internal/_build/results?buildId=700742&view=results
=> Forward target publishing infra version to the promote pipeline

src/GitHubApps/DarcBot/DarcBot.csproj, src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerAzureFunction.csproj
We moved to netcoreapp3.1, but didn't update AzureFunctionsVersion to v3. This fixes that in DarcBot and RolloutScorer.
Fixes https://github.com/dotnet/core-eng/issues/10196
=> Fix AzureFunctionsVersion

src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs
The semantics of LINQ here mean that you can't call it with a null input set.
GetDependenciesAsync returns null if a repo@sha does not have a version details file.
This exists in a single place (very old corefx dependency).
Add '?'
=> [HOTFIX] Do not call ToList() when dependencies are null

src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs
The semantics of LINQ here mean that you can't call it with a null input set.
GetDependenciesAsync returns null if a repo@sha does not have a version details file.
This exists in a single place (very old corefx dependency).
Add '?'
=> Do not call ToList() when dependencies are null (#1279)

eng/deploy.yaml, src/Maestro/tests/Maestro.ScenarioTests/Maestro.ScenarioTests.csproj, src/Maestro/tests/Maestro.ScenarioTests/MaestroScenarioTestBase.cs, src/Maestro/tests/Maestro.ScenarioTests/ObjectHelpers/SubscriptionBuilder.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Subscriptions.cs, src/Maestro/tests/Maestro.ScenarioTests/TestHelpers.cs, src/Maestro/tests/Maestro.ScenarioTests/TestParameters.cs, src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs
This is the same code as was previous reviewed with two additions - defining the AZDO_TOKEN variable in deploy.yaml and adding a null check to TestParameters (so that we can catch and log the exception before the Process string builder turns it into a null ref exception with no information about what was null). I'll add comments to the new additions to make them easier to find.
=> Maestro Scenario Tests: Subscription test fix

src/RolloutScorer/RolloutScorer/Commands.cs, src/RolloutScorer/RolloutScorer/RolloutScorer.cs, src/RolloutScorer/RolloutScorer/Scorecard.cs, src/RolloutScorer/RolloutScorer/Utilities.cs, src/RolloutScorer/RolloutScorer/config.json, src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerFunction.cs
I was not able to locally reproduce the Rollout Scorer not picking up issues like it has on a few scorecards (per #10188) -- both the rollout scorer console app and the Azure Function (run locally) produce the correct results. This suggests that the issue purely lies in the function when running in Azure. The best way to determine this, however, is to run the app in staging.
This PR adds a *ton* of AppInsights logging to the rollout scorer to help with debugging these things in prod & staging. This should make debugging much easier.
Logging added:
* Raw AzDO queries (uris, no auth or headers)
* Hotfix & rollback detection (from commit messages)
* GitHub API query & number of issues returned
* [TRACE] Logs looping over every issue noting labels for all
* Rollout …
=> Add more logging to the Rollout Scorer

.angulardoc.json, .gitignore, src/Microsoft.DotNet.Darc/src/Darc/Operations/Operations.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddBuildToChannelCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/CloneCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/CommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/DeleteBuildFromChannelCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GetBuildCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GetDependencyFlowGraphCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GetDependencyGraphCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/RedactFromLoggingAttribute.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/UpdateDependenciesCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Program.cs
It reports:
* any command line parsing error as a LogError with relevant information
* any exception that bubbles out to Main
* every verb executed including any options passed and their values
* sensitive options can be redacted with `[RedactFromLogging]`, which record they were specified, but not the values passed
=> A pretty simple telemetry solution for darc.exe

src/Maestro/FeedCleanerService/FeedCleanerService.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/FeedConstants.cs
https://github.com/dotnet/arcade/issues/5823
We previously missed cleaning up ~15k package versions since February as the registration URL we were previously using got replaced. I was under a misunderstanding that all nuget v3 registrations would use the same URI. This should ensure the cleaner looks up the right spot going forward.
Also adds additional logging so it's easier to find the last time we found a package in Nuget.org, as I had to poke in the DB to find out when this stopped working.
=> Use the package URI to check for packages in nuget.org instead of the registration URI 

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
Now it shows data always in units reqs/hour and dynamically change granularity. 
I have also set thresholds to5 failed-reqs/hours warning, 10 critical
=> Maestro failed requests granularity

docs/DevGuide.md
We use ngrok to satisfy azure.core requirement SSL when Bearer token is used.
=> Update DevGuide - ngrok redirection

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
Turns on alerting and issue creation for the Maestro Failed Requests/Hour graph.
=> Added alerting in Grafana for Maestro Failed Requests per Hour 

src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
This should mitigate our failures to open PRs due to sporadic 503s from Azdo.
https://github.com/dotnet/arcade/issues/5951
=> Allow GetFileContentsAsync to use the default 15 retries

Directory.Build.props
It probably doesn't matter, since CopyrightNetFoundation is always defined, but most of these variables intend to always be set.
=> Some of this stuff is in a weird condition

src/Maestro/Maestro.Web.Tests/LoggingConfigurationTests.cs, src/Shared/MIcrosoft.DotNet.Internal.Logging/OperationManager.cs
There are a few places that want all the logging goodness,
but can't afford to create and dispose entire ServiceProviders,
(like the Sql processor, which processes millions of messages).
So offer a new method that doesn't do the service scope stuff.
=> Offer a lighter weight LogginScope

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddBuildToChannelCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/AzureDevOps/AzureDevOpsPipelineRunDefinition.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/AzureDevOps/AzureDevOpsRepositoryResourceParameter.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/AzureDevOps/AzureDevOpsRunResourcesParameters.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/AzureDevOps/AzureDevOpsVariable.cs
This lets us queue pipelines with both template parameters and variables.
Add-build-to-channel just passes the same values for both for backwards compatibility.
The new pipeline definition pending in https://github.com/dotnet/arcade/pull/5896 removes some SDL variables / parameters. I'm keeping them until we've decided what to do with those, as this change also keeps things working for older builds.
V2 publishing build promoted using these changes: https://dnceng.visualstudio.com/internal/_build/results?buildId=771120&view=results (published to general testing)
related to https://github.com/dotnet/arcade/issues/5942. 
~We will either need a follow-up here to not pass the SDL parameters to v3 publishing, or we'll need to adjust the yaml of the promotion pipeline itself to support SDL …
=> Move StartBuildAsync to use the new run pipeline API and fix darc-add-build-to-channel for v3 promotion

eng/Packages.props, src/DotNet.Status.Web.Tests/DotNet.Status.Web.Tests.csproj, src/DotNet.Status.Web.Tests/Files/triage-items-with-diff-cat.expected.json, src/DotNet.Status.Web.Tests/Files/triage-items-with-invalid.expected.json, src/DotNet.Status.Web.Tests/Files/triage-items-with-multi-builds.expected.json, src/DotNet.Status.Web.Tests/TimeLineIssueTriageTests.cs
We just normalized our test dependency story, and we are trying to avoid implicit code.
Even after reading the documentation for AutoFixture,
I still can't really be sure what it's doin, and it makes the test
hard to reason over (Why are these things supposed to be different?
Where did they come from?)
We want to reduce the amount of libraries someone has to go
read about just to code review a simple test.
=> Remove auto fixture

src/Maestro/Maestro.Web.Tests/DefaultChannelsController20200220Tests.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/DefaultChannelsController.cs, src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddDefaultChannelOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddDefaultChannelCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs
With this change, default channel entries can include the prefix '-regex:', which when encountered (real branch names can never start with '-') is used to match on branch names.
Add some DefaultChannelsController tests.  See https://github.com/dotnet/arcade/issues/5131 for context
=> Add regex support for default channel 'branch' values

src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs
Fixes https://github.com/dotnet/arcade/issues/6044.
When GetLastCommitShaAsync looks to see if there is a last commit for a branch, the github API returns an UnprocessableEntity status code when the branch does not exist, rather than NotFound, which is what GetLastCommitShaAsync assumes.
We need to update the function to also look for UnprocessableEntity, as well as update ExecuteAsync to add UnprocessableEntity as a stopRetriesHttpStatusCode.
=> Add UnprocessableEntity as an expected failure for GetLastCommitShaAsync

src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
Some of the bots like msftbot will comment on a PR, but not reject the changes.
When a new commit is pushed, the comment is dismissed. We categorize
dismissals as rejections. Instead, classify them as comments.
=> Do not count dismissed reviews as rejected

azure-pipelines.yml
This prevents blah/master and blah/production from deploying. Followup to https://github.com/dotnet/arcade-services/pull/1383 and related to dotnet/core-eng#10679
Verified this build did not trigger the deployment steps even though it comes from a `riarenas/master` branch
=> Use the sourceBranch variable instead of SourceBranchName

src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs
As described [on this issue](https://github.com/dotnet/arcade/issues/5961), we are adding the URL of the changes (diff between 2 versions of a repo) in the body of the initial comment created by Maestro.
=> Maestro - Add the changes URL in update dependencies PRs

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
The visualstudio url is a legacy url.
=> Use the dev.azure.com url for promotion message.

src/Maestro/tests/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
After the recent changes, the AllChecksSuccessful check was pending (and not failing) as there are no other checks than the merge policies check in the scenario tests (WIP is ignored).
So at the end of the scenario test, we were expecting all the checks to be completed which is not the case anymore.
=> Fixing checks scenario test

src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_AzDoFlow.cs, src/Maestro/tests/Scenarios/azdoflow-feedflow.ps1
Change the arbitrary feed strings to avoid hash collisions.
=> Maestro Scenario Tests - Change feed strings to avoid hash collision

src/Maestro/maestro-angular/src/app/app.module.ts, src/Maestro/maestro-angular/src/app/page/build/build.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.ts
As requested [on this issue](https://github.com/dotnet/arcade/issues/6137), I'm adding some extra informations on BARViz.
I'll change the UI of the maestro web app to add new info to it (+ additional features to make it easier for everyone such as a button to copy the sha). 
Changes made:
=> Adding copy buttons to BARViz 

src/Maestro/Microsoft.AspNetCore.ApiVersioning.Analyzers/Microsoft.AspNetCore.ApiVersioning.Analyzers.csproj
This needs to target netstandard2.0 otherwise it gets the wrong references
and doesn't work in VS.
=> Fix analyzer TargetFramework

src/Maestro/DependencyUpdater/DependencyUpdater.cs, src/Maestro/Maestro.DataProviders/MaestroBarClient.cs, src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/ChannelsController.cs, src/Maestro/SubscriptionActorService/MaestroBarClient.cs, src/Maestro/tests/DependencyUpdater.Tests/DependencyUpdaterTests.cs, src/Maestro/tests/DependencyUpdater.Tests/UpdateLongestBuildPathTests.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyFlowGraphOperation.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyFlowGraph.cs
Changes:
- Flow graph generation was moved from `DependencyUpdater` and `ChannelsController` into `MaestroBarClient` so that now the whole logic is in single place. Both of the classes now get the graph using `IRemote` interface.
- Added missing `Async` suffix to `IBarClient.GetDependencyFlowGraph` and `IRemote.GetDependencyFlowGraph` methods.
- Added unit tests for `DependencyUpdater.UpdateLongestBuildPathAsync`.
- Changed `DependencyUpdater` so that it does not save longest build path in the database if graph is empty or does not contain any nodes marked as `OnLongestBuildPath` (fixes https://github.com/dotnet/core-eng/issues/10809)
=> Fix DependencyUpdater and unify flow graph generation code

src/Maestro/Maestro.Web/Controllers/AzDevController.cs, src/Maestro/maestro-angular/src/app/model/build-status.ts, src/Maestro/maestro-angular/src/app/page/build/build.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.ts, src/Maestro/maestro-angular/src/app/services/build-status.service.ts
As requested on this [issue](https://github.com/dotnet/arcade/issues/6150), I'm adding a button to access the latest ongoing build.
How does it look like?
- If a build is currently running
- Otherwise (if everything is fine or we recently had a failed build)
What does it do?
If you click on the link, it will redirect you to this page:
=> Adding a btn to access the latest ongoing build

src/Maestro/Maestro.Web/Api/v2018_07_16/Models/FlowEdge.cs, src/Maestro/maestro-angular/src/app/page/channel-graph/channel-graph.component.html, src/Maestro/maestro-angular/src/app/page/channel-graph/channel-graph.component.ts, src/Maestro/maestro-angular/src/app/page/channel/channel.component.html, src/Maestro/maestro-angular/src/app/page/channel/channel.component.ts, src/Maestro/maestro-angular/src/maestro-client/models.ts
The goal of this PR is to annotate every edge with a channel (the source channel of the subscription). 
Next to each edge, we have the corresponding source channel of the subscription. We don't annotate the edges that have the same channel than the one currently being viewed.
=> Adding source channels name to BARViz dependency flow graph

src/Maestro/Maestro.Web.Tests/DefaultChannelsController20200220Tests.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/DefaultChannelsController.cs, src/Maestro/Maestro.Web/HandleDuplicateKeyRowsAttribute.cs
Addresses dotnet/core-eng#10721 by:
- Fixed the bug in HandleDuplicateKeyRowsAttribute (which was supposed to cause HTTP 409).  It was causing HTTP 500 since the exception type did not match (was trying to match on `System.Data.SqlClient.SqlException` while the implementation threw `Microsoft.Data.SqlClient.SqlException`; now it handles both.)
- I removed this attribute from DefaultChannels.Create() after discussing w/ @ChadNedzlek as it both makes this friendlier to retry logic and more testable.
- DefaultChannels.Create() now looks up the existing DefaultChannel object and returns that if identical parameters are returned.
- Added test for duplicate add scenario
=> Fix handling of duplicated default channel assignments

eng/Versions.props, global.json, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/Models/Manifest.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/Models/ManifestBuildData.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
For the IsReleaseOnlyPackageVersion  to show in the merged manifest 
First part was Arcade master change -> dotnet/arcade#6340
Release 3.x -> https://github.com/dotnet/arcade/pull/6319
For the merged manifest, we need to update the MicrosoftDotNetVersionToolsVersion to the latest version and add the IsReleaseOnlyPackageVersion  attribute in the manifest. 
Test Build from arcade-services to generated updated Maestro task -> https://dev.azure.com/dnceng/internal/_build/results?buildId=846200&view=results
Test build from arcade with the updated maestro task , arcade sdk and feeds task -> https://dev.azure.com/dnceng/internal/_build/results?buildId=846325&view=results
=> Update VersionTools and add IsReleaseOnlyPackageVersion  

src/RolloutScorer/RolloutScorer/RolloutScorer.cs, src/RolloutScorer/RolloutScorer/Scorecard.cs, src/RolloutScorer/RolloutScorer/Utilities.cs, src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerFunction.cs
Fixes dotnet/core-eng#11096.
If an issue in core-eng has both the **Rollout Failure** label and a rollout repo label, the rollout scorer will now mark that rollout as a failure and calculate the scorecard accordingly.
Example scorecard with this from 2020-09-24 [here](https://github.com/dotnet/core-eng/blob/master/Documentation/Rollout-Scorecards/Scorecard_2020-09-24.md) and the failure issue that I used for that is [here](https://github.com/dotnet/core-eng/issues/11097). (That scorecard was calculated from 9/24 to the present date to make sure the issue was capture automatically and then I manually removed the builds that occurred in the rollouts since 9/24 and reset the time to rollout and hotfixes accordingly.)
Corollary documentation change: …
=> Add Rollout Scorer support for issues labeling rollouts as failures

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LocalHelpers.cs
Follow-up from https://github.com/dotnet/arcade/issues/5315 - turns out that we only check out certain files, add the .config folder to this list
=> Make sparse checkout know about the possibility of a .config folder

src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs, src/Maestro/Maestro.DataProviders/MaestroBarClient.cs
Fixes https://github.com/dotnet/arcade/issues/6210
After changes the logic for each graph edge is:
- Get the latest build of target node
- Find all build dependencies that were included in that build and come from source node
- If none of the dependencies have `IsProduct` set then subscription is tooling-only
=> Change way of finding tooling dependencies in the graph

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/GitFileManagerTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/AddFeedsToNuGetConfigWithoutManagedFeeds/NuGet.output.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/EnsureAppendsDisableEntryAfterLastClear/NuGet.output.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/PreserveCommentsInRightLocationsWhenReplacing/NuGet.output.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/PreserveCommentsInRightLocationsWithNoExistingBlock/NuGet.output.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/PreserveManagedFeedFromOutside/NuGet.output.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/RedisableCurrentlyEnabledIntSources/NuGet.output.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/ReplaceExistingFeedsWithNewOnes/NuGet.output.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/WhiteSpaceCorrectlyFormatted/NuGet.output.config
This is done in an attempt to avoid merge conflicts.  See test expected outputs for what this will look like.
https://github.com/dotnet/arcade/issues/5909
=> Order by repo name, use begin/end comments around maestro feeds

src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/UpdateDependenciesCommandLineOptions.cs
Makes all calls to GetRequiredCoherencyUpdatesAsync() (except where Legacy is explicitly specified) default to Strict, catch the update exception, then retry with Legacy mode
Addresses https://github.com/dotnet/arcade/issues/6431
=> Always* attempt strict coherency before using legacy coherency

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
This logs the promotion build URL when there's a failure in order to try and make the errors from the command more self-diagnosable
https://github.com/dotnet/arcade/issues/6446
=> log the promotion build in the error output

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
The final period is getting added to the link, making it invalid. See https://dev.azure.com/dnceng/internal/_build/results?buildId=874436&view=logs&j=56ebfe15-69d8-5dd1-65e4-c65998c8d8a6&t=0a9483a6-3ac1-5fd2-c450-3586b050b65b for an example
=> Fix the link to the promotion build during failure

src/Maestro/Client/src/Generated/Models/BuildData.cs, src/Maestro/DependencyUpdater/DependencyUpdater.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/AddAssetTests.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/MergeBuildManifestsTests.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/MergeSigningInfoTests.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/Mocks/VersionIdentifierMock.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/ParseBuildManifestMetadataTests.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/SharedMethods.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/Proxies/VersionIdentifierProxy.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
Master build: https://dnceng.visualstudio.com/internal/_build/results?buildId=871682&view=results
The only change that affects production is https://github.com/dotnet/arcade-services/commit/5ce43c7f1a810558b77e2fe1f97b27efa7f72488, but the log that it's trying to fix log is so noisy that I believe it's worth rolling out for it.
=> [Rollout] Production deployment for Nov 4th, 2020

azure-pipelines.yml
As part of SDL process we are required to enable component governance in the repository. This PR adds additional task in the `Build` stage that runs the component detection. At the moment no High or Critical vulnerabilities are reported.
Example report for this feature branch can be seen here: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade-services?_a=alerts&typeId=5066156&alerts-view-option=active
Related issue: https://github.com/dotnet/core-eng/issues/11356
=> Add component governance task to build template

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/GitFileManagerTests.cs
Addresses https://github.com/dotnet/core-eng/issues/11362.  It seems that this runs multiple times in Maestro (likely its own bug, but less pressing), and previously did not clear out the existing comments when doing so.
Test coverage is added to every test case by virtue of now running UpdatePackageSources() on the XML Document we get back from the first update and ensuring the result is still identical.
=> Make GitFileManager.UpdatePackageSources() idempotent for the same package sources

src/Maestro/maestro-angular/src/app/page/channel-graph/channel-graph.component.ts
While making some other changes to the Maestro front-end I modified the graph display a bit so that it's not scaled to fit the whole page but is displayed at normal scale and you can move it with scrollbars. The benefits of this are that:
- It's easier to read the text on the big graphs
- The graph is correctly resized when using browser zoom - previously it couldn't be zoomed-in or out that way
There's no real requirement for this change, it was just a quick experiment so if there's a reason to keep current behavior then that's ok.
**Before:**
**After:**
=> Show scrollbars for dependency flow graph instead of scaling it

src/Maestro/DependencyUpdater/DependencyUpdater.cs
Unit tests already exist for these functions.
Previously, we would not update a repo if the build noted in the `lastAppliedBuildId` was attempting to be applied again, even if that previous attempt resulted in an error. This change will always allow a build to be applied to a repo via their subscription even if it already has been applied previously.
=> Any subscription triggers will allow an update even if the repo is currently on the latest build

src/DotNet.Status.Web/Pages/Index.cshtml, src/DotNet.Status.Web/Pages/Token.cshtml, src/DotNet.Status.Web/Pages/_Layout.cshtml, src/DotNet.Status.Web/Pages/_ViewStart.cshtml, src/DotNet.Status.Web/Startup.cs
Issue https://github.com/dotnet/core-eng/issues/11584
Cookie expiration is currently set for 7 days and it should be at most 30 minutes 
Privacy footer is missing and it should be present.
=> Set cookie time out to max. allowed 30 minutes and added privacy footer

eng/deploy.yaml
Disabling this step to unblock the deployment. Once https://github.com/dotnet/core-eng/issues/11634 is understood we can re-enable
=> disable dotnet-status web app deployment due to failures

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/GitFileManagerTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/EnsureMultipleDisabledSourcesGetComments/NuGet.input.config, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/EnsureMultipleDisabledSourcesGetComments/NuGet.output.config
Context: https://github.com/dotnet/arcade/issues/6685
Also adds a test that will break if this regresses.
=> Fix a bug with deleting too many dependency flow comments

eng/deploy.yaml
Fixed related issue with Azure App config changes that don't seem to be represented in code anywhere. This PR is just to re-enable the deployment step.
=> Re-enable status site deployment

src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs
We moved getting the package sources for a repo + commit when there's more than one matching asset during coherency calculations to the IRemote interface in dotnet/arcade-services#1490 , but we didn't update this test so that the mocked remote returns the package source this test is looking for.
Fixes the build break in https://github.com/dotnet/core-eng/issues/11693
=> Fix broken test due to missing mocked method

src/Maestro/Maestro.Web/Startup.cs
SDL requires us to logout user from Maestro after 30 minutes of inactivity so I changed cookie configuration to use this value.
I did not modify lifetime of data protection keys. Previously it was set to `LoginCookieLifetime * 2  = 240 days` so I just statically set it to 240 days. If it should be updated as well then please let me know.
SDL work item: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1242739
Tracking issue: https://github.com/dotnet/core-eng/issues/11240.
=> Set login cookie lifetime to 30 minutes

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
Publish to multiple channels -> https://github.com/dotnet/arcade/issues/6669
Since comma does not work, using hyphen instead.
=> Publish to multiple channels -Part 1

src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Maestro/maestro-angular/package-lock.json, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs
Should help fix the broken downgrade check policy: https://github.com/dotnet/core-eng/issues/11718. 
We were previously never updating the list of updates that the PR object we keep in memory had, so no matter how many new updates came in, we would never find when a downgrade was fixed.
A PR that shows this working is here:
https://github.com/maestro-auth-test/maestro-test2/pull/12838
https://github.com/maestro-auth-test/maestro-test2/commit/202fe63fd4ff7dbb844693176097318b6f9551bc introduces a downgrade, and the check fails: https://github.com/maestro-auth-test/maestro-test2/runs/1671624730
https://github.com/maestro-auth-test/maestro-test2/pull/12838/commits/fad474abdfba8735c5bbc7ccda75827bd66f8469 fixes the downgrade, and now the check succeeds: …
=> Update the RequiredUpdates property when updating a PR's information

src/Maestro/SubscriptionActorService/LocalGit.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LocalHelpers.cs
In LocalGit.GetPathToLocalGitAsync, we download the git executable if we haven't downloaded it before. However, this function simply tests whether or not the variable _gitExecutable is null or empty. However, that doesn't guarantee that the file that _gitExecutable points to still exists on disk (we assume it does, but never check), and it doesn't guarantee that that executable isn't corrupted. This change adds the following hardening:
1) In addition to checking the contents of the variable _gitExecutable, also make sure that the file exists.
2) Once we know that the file exists, run a basic git command (git --version), to make sure that the git executable isn't corrupted.
This helps harden against the issue described in https://github.com/dotnet/arcade/issues/5997, where we found that, …
=> Add additional hardening when downloading the git executable

src/Maestro/maestro-angular/src/app/app.component.html, src/Maestro/maestro-angular/src/app/widget/side-bar/side-bar.component.html
This PR adds missing `role` attributes that caused SDL accessibility scan to fail.
Related issue: https://github.com/dotnet/core-eng/issues/11240
=> Add missing aria labels in Maestro

src/Maestro/Maestro.DataProviders/MaestroBarClient.cs, src/Maestro/Maestro.DataProviders/SharedKustoQueries.cs, src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/BuildTimeController.cs
Reported in: https://github.com/dotnet/arcade/issues/6737
Solution implemented here is following:
- I get AzDO BuildDefinitionId for the last build of given repo in default channel
- When querying average build time in Kusto I use this ID to include only builds that have that `DefinitionId`
=> Fix average build time calculation on dependency flow graph

src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs, src/Maestro/tests/SubscriptionActorService.Tests/SubscriptionOrPullRequestActorTests.cs
Fixes the issue that is preventing aspnetcore's servicing branch from receiving automatic updates: https://github.com/dotnet/core-eng/issues/11878
Updated the tests to mimic this edge case, both in the existing and incoming updates.
=> Fix edge case with duplicates when calculating a PRs list of updates

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Follow up from https://github.com/dotnet/arcade/issues/6640 when trying out with a "real" build where the repo only exists in AzDO
=> Fix bug with dependency generation in manifest when repo has no GitHub version

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json, src/Monitoring/Monitoring.ArcadeServices/notifications/Production/teamsHook.notification.json, src/Monitoring/Monitoring.ArcadeServices/notifications/Staging/teamsHook.notification.json
https://github.com/dotnet/core-eng/issues/11371
This hooks up this one particular alert so that it posts to the FR Bot Notifications channel.
I added the respective secrets to the prod and staging vaults, and you can see an example of how the connector works [here](https://teams.microsoft.com/l/message/19:035bc5fb656b4dc8ae7f457474dabf6d@thread.skype/1612295750291?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=147df318-61de-4f04-8f7b-ecd328c256bb&parentMessageId=1612295750291&teamName=.NET%20Eng%20Services&channelName=FR%20Bot%20Notifications&createdTime=1612295750291)
=> add teams webhook notification channel and add it to the .net eng status failed requests

docs/DevGuide.md, src/Maestro/tests/Maestro.ScenarioTests/MaestroScenarioTestBase.cs, src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Builds.cs, src/Maestro/tests/Maestro.ScenarioTests/TestHelpers.cs, src/Maestro/tests/Maestro.ScenarioTests/TestParameters.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/ManifestHelper.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DownloadedBuild.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/DarcManifestHelperTests.cs
https://github.com/dotnet/arcade/issues/6640
Allows for downloading and adding to the gather-drop manifest arbitrary assets via regex and their file name. Supports various dotnet-release scenarios while not explicitly adding (even) more understanding of these repositories to Arcade-Services.
=> Add "Extra Assets" regex flag to gather-drop

src/Maestro/FeedCleanerService/FeedCleanerService.cs, src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs
The message for 404 errors changed on github's side. To be safe, I've updated all of the error checking to not assume (Not Found) will be in the message.
When we move to 5.0, the HttpRequestException object also includes a StatusCode that we can reference, so we should check that instead of the message for additional safety.
=> Fix HttpRequest error handling in arcade-services

src/DotNet.Status.Web/Models/TeamMentionForwarder.cs
Cherry-pick of 543d9fd42ab5a422256492d8be51695b5c1ed5e6 in order to fix https://github.com/dotnet/core-eng/issues/12630
=> [Hotfix] Fix null ref in TeamMentionForwarder 

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Looks like at some point the `release.json` stopped populating the products node with the paths of the shipping assets. Turns out it only adds products it thinks has shipping assets, which wasn't being bubbled up. I added the extra download assets to be considered as well, let me know if that is not right.
=> Fix 'anyShipping' logic for gather-drop

src/Maestro/Maestro.Web.Tests/RepositoryUrlAttributeTests.cs, src/Maestro/Maestro.Web/RepositoryUrlAttribute.cs
There are github repos that have periods (.) in them. They should be allowed.
Fixes https://github.com/dotnet/arcade/issues/7150.
=> Fix the regex for github repos in RepositoryUrlAttribute

src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/ParseBuildManifestMetadataTests.cs
Fixing these failures in internal build:
https://dev.azure.com/dnceng/internal/_build/results?buildId=1063223&view=ms.vss-test-web.build-test-results-tab&runId=32747828&resultId=100504&paneView=debug
=> Fix unit tests after master/main renaming

src/Maestro/DependencyUpdateErrorProcessor/DependencyUpdateErrorProcessor.cs
Before, we wouldn't create a new issue if there was an issue already created for the particular repo/branch combo or subscription id, whether or not it was open or closed. In the closed case, it mean no issue was logged. This change fixes the fall through so that if the issue is closed, we create a new issue. It also adds additional logging for that path.
=> Fix DependencyUpdateErrorProcessor when found issue is closed

src/DotNet.Status.Web/appsettings.json
The notifications are no longer needed as the pipeline in question will only be used in an adhoc way.
Addresses https://github.com/dotnet/arcade/issues/7110.
=> Remove entry for arcade validation from notifications

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs
Occasionally, we get various HttpRequestExceptions when downloading assets in gather-drop. Most of these are retriable, so we should have a retry on this.
=> Add retry to gather-drop when downloading assets

src/Maestro/SubscriptionActorService/LocalGit.cs
Add additional logging so that if we come up against https://github.com/dotnet/core-eng/issues/12752 again, we may have a clearer idea of why we are trying to download git when files that are also downloaded when downloading git exist and currently are being used/can't be deleted do so when we've found that git itself doesn't exist.
=> Add additional logging to GetPathToLocalGitAsync

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
This change adds a --separated option to gather-drop and changes the default behavior to not create the separated layout. This significantly reduces (by half) the size of a build drop, which is especially important for drops with multiple sdks, as the duplicate layout causes us to go over the 100GB available on a buildpool machine.
This does not modify the manifest.json at all, and that will need to be addressed in future work, as there are many pieces of infrastructure that assume there are 2 targets in the targets list. Once all of the infrastructure that relies on the structure of the manifest.json file is fixed, we can revisit the manifest creation to not include the separated target when we do not pass --separated.
=> Add --separated option to gather-drop

src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/ParseBuildManifestMetadataTests.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/XmlSerializationHelperTests.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/XmlSerializationHelper.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/Models/Manifest.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
PushMetadataToBuildAssetRegistry doesn't know about assemblies with PublicKeyToken or TargetFramework, leading to multi-targeting collisions when trying to publish assets later on.
- Verified the data from the build manifest now properly flows into the merged manifests with the exact changes in this.  
- Refactored the functionality that had to change (pretty boring) into a separate class to add tests
- Noted a few places that we have "parse" tests that don't seem to really parse any XML, as well as a lack of coverage for collisions / ambiguity; will file follow-up issues.
=> Address https://github.com/dotnet/core-eng/issues/12911

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
When we added the --separated option, which made separated not the default, we didn't update how we create the release layout (which copied from the separated locations). Instead, copy from the unified locations, which will always exist.
=> Copy from the unified location when generating the release layout

src/Maestro/Maestro.Data/Migrations/20210429211510_AddPRFailureNotificationFieldToSubscription.Designer.cs, src/Maestro/Maestro.Data/Migrations/20210429211510_AddPRFailureNotificationFieldToSubscription.cs, src/Maestro/Maestro.Data/Models/Subscription.cs, src/Maestro/Maestro.Data/dotnet-ef.ps1, src/Maestro/Maestro.Web.Tests/SubscriptionsController20200220Tests.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/SubscriptionsController.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Models/Subscription.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Models/SubscriptionData.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Models/SubscriptionUpdate.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubClientFactory.cs
https://github.com/dotnet/core-eng/issues/12791
Adds `PullRequestFailureNotificationTags` field to subscription APIs for later consumption by dependency flow automation.
=> Add field to subscriptions and their relevant APIs to support failure notification tagging.

src/Maestro/SubscriptionActorService/PullRequestActor.cs
In order to gather more information for the issue: Some dependency updates are intermittently failing due to timeouts in service fabric actors (https://github.com/dotnet/arcade/issues/7262) adding more logs
=> Add logs to PullRequest Actor

src/Maestro/Client/src/Generated/Models/SubscriptionData.cs, src/Maestro/Maestro.DataProviders/MaestroBarClient.cs, src/Maestro/SubscriptionActorService/MaestroBarClient.cs, src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs, src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/AddSubscriptionPopUp.cs, src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/EditorPopUp.cs, src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/UpdateSubscriptionPopUp.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddSubscriptionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
API changes are in prod and the feature / swagger regeneration is now merged to main (should roll out next Weds) but without these CLI changes users have to update their subscriptions via the swagger client.  
Plumbs a new option through to call the new generated code.
https://github.com/dotnet/core-eng/issues/13008
=> Plumb new Subscription failure notification feature through Darc CLI

src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimeline.cs, src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/AzureDevOpsTimelineTests.cs, src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/BuildAndTimelineBuilder.cs
Fixes dotnet/arcade#7389. 
Build branch information is passed in the `Parameters` field of the AzDO `Build` object. If the pipeline YAML fails to parse, a build is recorded with this field null. 
This PR adds a check for a null Parameter field and, if found, logs it and continues with an empty branch name.
=> Fix missing branch info when retrieving timelines

src/DotNet.Status.Web/appsettings.json
This change will monitor [Validate-DotNet](https://dev.azure.com/dnceng/internal/_build?definitionId=827) builds that have been tagged with the [runtime tag](https://dev.azure.com/dnceng/internal/_build?definitionId=827&tagFilter=runtime), and open issues in dotnet/runtime with the area-Infrastructure label.
=> Add monitoring for Validate-DotNet for the dotnet/runtime tagged runs.

docs/DevGuide.md
The link no longer works and was taking to the landing page for the sql server website. I couldn't find a direct landing page for express, looks like they bundled them all in the same downloads site.
=> fix link to where to get the sql server 

src/Maestro/SubscriptionActorService/PullRequestPolicyFailureNotifier.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs
It seems it is indeed possible to have multiple contained subscriptions in a single non-batched PR
=> Address https://github.com/dotnet/arcade/issues/7445

src/Monitoring/grafana-init/grafana.ini
Configure Grafana to output JSON logs to syslogd, which can then get ingested by Azure Log Analytics. This allows logs to be inspected without SSHing into the VMs and makes it easy to enable other VM monitoring (e.g. perf counters, disk and CPU tracking).
I manually enabled in staging to verify operation. You can see the log output [here](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_Azure_Monitoring_Logs/LogsBlade/resourceId/%2Fsubscriptions%2Fa4fc5514-21a9-4296-bfaf-5c7ee7fa35d1%2Fresourcegroups%2Fmonitoring%2Fproviders%2Fmicrosoft.operationalinsights%2Fworkspaces%2Fgrafana/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAwuuLM7JT%252BeqUSjPSC1KVXDOzy0oLUktUrC1VVBPL0pMS8xL1C0uSUzPzEtXh6sKKMpPTi0u9kvMTUVWCFKQX5QC1J1UqRCSmZvqnpqXWpRYkpqikJJanAyU …
=> Configure Grafana logs to allow Log Analytics capture

src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/UpdateSubscriptionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Program.cs
Addresses https://github.com/dotnet/core-eng/issues/13178 ... sets up the ability to update subscriptions via calling the Darc CLI in a loop
=> Enable update-subscription to work from Darc CLI directly

src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
=> Consider a 'neutral' result as passing

eng/Packages.props, src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHost.AI.cs
This change upgrades our AI packages to 2.15.0 so that we can take advantage of the new service options available in that version, namely, being able to set EnableDependencyTrackingTelemetryModule to false to disable it. This will reduce our data usage in app insights, and hopefully stop us from hitting our daily cap.
Fixes https://github.com/dotnet/core-eng/issues/13297.
=> Disable dependency tracking telemetry module

src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHost.AI.cs
Fixes the original change to disable dependency tracking by moving the options setting to the correct function, as the original could have overwritten what we already were setting.
=> Fix the disabling of dependency tracking

src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateSubscriptionOperation.cs
Bug from work done for https://github.com/dotnet/core-eng/issues/13178 . 
I realized today that not providing merge policy values (even null) ends up overwriting them so plumbs through the existing data when calling from command line.
=> Fix bug where updating subscription from CLI stomps existing merge policies with no policy

src/Maestro/Maestro.MergePolicies/StandardMergePolicy.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
https://github.com/dotnet/core-eng/issues/13431
Adds the build analysis check to the ignore list for the standard merge policy to mitigate issues where maestro was auto merging PRs where after 5 minutes this was the only check.
=> Add build analysis to ignore checks in standard merge policy

azure-pipelines.yml, eng/deploy.yaml
I found that scenario tests for secret manager (introduced in https://github.com/dotnet/core-eng/issues/13259) weren't executed automatically.
=> enabled secret manager scenario tests

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
[This change was originally merged directly to the azure devops mirror, causing the two versions of the repo to get out of sync. This gets the commit through github so it can then be mirrored: https://dev.azure.com/dnceng/internal/_git/dotnet-arcade-services/pullrequest/16614]
https://github.com/dotnet/core-eng/issues/13556
The current state of the alert was creating noise because it triggers an alert every time a data center reports that it is down so I changed the alert to get triggered if a data center has been down for more than 30 minutes.
Trigger after 30 minutes of being down
=> Trigger after 30 minutes of being down

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
gather-drop had a hack that removed 64. and 86. from the asset version, which broke versions with legitimate uses. This hack was necessary up until we fixed out version numbers, and is no longer needed. Remove the hack.
=> Remove hack from gather-drop

src/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs, src/Microsoft.DncEng.SecretManager/SecretTypes/SqlServerConnectionString.cs
https://github.com/dotnet/core-eng/issues/13795
=> Allow 7 day grace period for rotation verification and allow extra settings for SQL connections

src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubApplicationClientFactory.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubClientFactory.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/IGitHubClientFactory.cs
For authing the GitHubApp, we need to make the authentication type Bearer.
=> Fix the auth for the GithubApp

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs
Plumb through an HttpCompletionOption param to the HttpRequestManager so that we can specify when we don't want the response buffer allocated.
I tested this by gathering the drop for build 99274 (I had to pass a longer timeout than the default 180 seconds, because this one asset is just too large)
https://github.com/dotnet/arcade/issues/7668
=> Don't allocate response buffer when downloading files during gather-drop

src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccountInteractiveSecretType.cs
This will cause some benign build breaks as the tool looks for -otp and the vault contains -secret. I will fix those up once this change is all the way through.
=> Switch back to -otp naming

src/DotNet.Status.Web/Controllers/AzurePipelinesController.cs
To create a new comment in an issue, we need to use the matching issue number, not its ID.
=> Fix bug in creating a new comment in BuildMonitor

src/Maestro/Maestro.Data/BuildAssetRegistryInstallationLookup.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubClientOptions.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/InMemoryCacheInstallationLookup.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/InstallationLookup.cs
It looks like our applications are getting intalled on organizations outside of our control,
leading to excess burden and unpredictable behavior.
Adding the ability to restrict an app to a subset of organizations.
=> Add ability to allow list organizations

src/Maestro/Maestro.Contracts/Maestro.Contracts.csproj
DarcLib depends on Maestro.Contracts, and is a packable library. However, because Maestro.Contracts is not packable, when another application that uses DarcLib tries to restore it, Maestro.Contracts cannot be found, as it is not packable. This change makes Maestro.Contracts packabe so that dependencies can be resolved.
=> Make Maestro.Contracts packable

src/DotNet.Status.Web/.config/settings.json
This change adds sdk and installer Validate-DotNet runs to the list of repos that we track for notifications.
=> Add Validate-DotNet notifications for installer and sdk

src/Microsoft.DncEng.SecretManager.Tests/SettingsFileValidatorTests.cs, src/Shared/Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen.Tests/ParameterTests.cs, src/Shared/Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen/ConfigMethod.cs, src/Shared/Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen/TestDataReceiver.cs
If there is a naming conflict in the namespace
of a test (say because the Test is in the A.B.C namespace,
and it's talking about something in the B.D namespace),
we need to add "global::" to the types to avoid the confusion.
Nullable parameters we not detected correctly either,
and resulted in "Nullable<Nullable<T>>" in the syntax.
Also, the settings file validator test didn't pass locally.
=> Fix TestData generator for nullable/global

Directory.Build.props
After a chat in the teams channel, everyone that piped up disliked the idea of implicit/global usings affecting a file. So I'm disabling them.
=> Disable implicit namespace

src/Maestro/Maestro.Web/.config/settings.json, src/Maestro/SubscriptionActorService/.config/settings.json, src/Maestro/SubscriptionActorService/LocalGit.cs
https://github.com/dotnet/arcade/issues/7343
- Use Mutex to wait 5 minutes for a (this instance's temp path-derived) turn, acquire this lock before any downloading
- Simplify check by always calculating the path to git.exe and checking for its existence, since the final path of _gitExecutable doesn't change per actor/instance
=> Add cross-process Mutex for portable git download in Pull Request actor

src/DotNet.Status.Web/.config/settings.json
This change adds aspnetcore Validate-DotNet runs to the list of repos that we track for notifications.
=> Add Validate-DotNet notifications for aspnetcore

Directory.Build.props
Enable default .NET analyzers for all projects (and fix a tab/spacing inconsistency).
=> Enable .NET analyzers

src/Microsoft.DotNet.Darc/src/Darc/Options/AddBuildToChannelCommandLineOptions.cs
Avoid some confusion and set v3 to be the default, as well as using arcade @ main for the source branch. These are the normal defaults everyone typically passes anyway.
=> Make v3 publishing the default

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
There are a few files now that are exceptionally large, for which the default timeouts are too low. This change increases the cancellation timeout from 180s to 400s, and the HttpClient timeout to 5 minutes.
Fixes https://github.com/dotnet/arcade/issues/7827.
Note: I attempted lower timeouts, but locally this would still fail. This was the combination I could guarantee would download the dotnet-sdk-source.*.tar.gz file, which is what has been failing.
=> Increase the timeout for gather-drop

src/Maestro/SubscriptionActorService/PullRequestActor.cs
Use an unambiguous (and MSFT-compliant) date and time format for Maestro PRs.
`09/10/2021 5:46 PM` -> `September 10, 2021 5:46:15 PM UTC`
=> Use accessible date format

eng/Version.Details.xml, eng/Versions.props
This pulls in the fix made here https://github.com/dotnet/arcade/pull/7769, which is necessary for an internal build, which pushes symbol packages to a nuget feed. The version identification is critical there because the version is a separate element of the azdo download path. This contrasts with public builds, where symbol packages end up in blob storage and no version identification is necessary.
=> Update the version tools to take in version identification fix

src/Maestro/Maestro.MergePolicies/DontAutomergeDowngradesMergePolicy.cs
Was looking at a downgrade today and it stuck out.
=> fix typo in DontAutomergeDowngrades policy

src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html, src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts, src/Maestro/maestro-angular/src/app/page/build/build.component.html, src/Maestro/maestro-angular/src/app/page/build/build.component.ts
By default, this changes dependencies of a build over to not showing if they are released. There is a new toggle to reenable. This is particularly useful in determining coherency in servicing, where there are many different builds of the same repo that are dependencies.
Example. This is aspnetcore before the change (with box checked):
And after
=> Ignore released builds by default

eng/Packages.props, src/Shared/Microsoft.DotNet.Kusto/KustoHelpers.cs, src/Shared/Microsoft.DotNet.Kusto/Microsoft.DotNet.Kusto.csproj
Let's save a lot of memory here and stream the CSV.
With System.IO.Pipelines, this is pretty straightforward,
and can save us a lot of buffering space/time in the services.
=> Stream CSV instead of buffering in memory

eng/Packages.props
Updates Azure.Core to latest and one incidental update needed to clean build.
Fallout from updating and unifying Azure.Storage.Blob versions for https://github.com/dotnet/core-eng/issues/14789
=> Update two package dependencies

src/Monitoring/grafana-init/setup.sh
The Grafana initialization script was missing the pieces for the Image Renderer plugin. This adds them. 
I manually fixed-up the existing instances so this won’t affect deployment, but it will help if the machines need to be rebuilt.
=> Add grafana-image-renderer

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json, src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/quota.dashboard.json
Set Grafana alerts to "keep state" if the backing query fails to execute.
HTTP 500s are actually pretty common when querying from app insights as often as we do. By default, Grafana treats "failed to query" as a time to alert. This should quiet the false-alerts a bit by ignoring that and instead maintaining the previous alert state.
=> Switch all alerts to keep state if query execution fails

eng/Publishing.props
This breaks the official build of arcade-services, probably because it's far out of date on templates.
=> Remove publishing.props file

src/Monitoring/Monitoring.ArcadeServices/datasource/Production/Azure Data Explorer.datasource.json, src/Monitoring/Monitoring.ArcadeServices/datasource/Production/Azure Monitor.datasource.json, src/Monitoring/Monitoring.ArcadeServices/datasource/Staging/Azure Data Explorer.datasource.json, src/Monitoring/Monitoring.ArcadeServices/datasource/Staging/Azure Monitor.datasource.json, src/Monitoring/grafana-init/grafana.ini
Secrets for the service principals were renamed as part of adopting Secret Manager. I missed updating the references in the data source definitions, which then broke. This renames them to be correct. 
While I was here, I also enabled Grafana's feature to use Azure's managed identities feature. The Azure Monitor plugin is the only piece that takes advantage of it, but I expect the other data sources to follow. And any removal of secrets is a good thing.
=> Fix service principal secret name

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
IsBlobFeedUrl was used as a check to see if a location is a sleet feed, but was also repurposed to check if it was simply a blob storage location. We don't actually care if index.json is at the end of the uri in the later case, and, in fact, the dotnetbuilds locations no longer include index.json in the asset locations.
This change removes the index.json check, and adds some additional logic around removing the index.json part of the asset location uri, so that gather-drop works with dotnetbuilds locations.
Will fix https://github.com/dotnet/arcade/issues/8225.
=> Fix gather-drop's IsBlobFeedUrl for dotnetbuilds locations

src/DotNet.Status.Web/Models/TeamMentionForwarder.cs
Github will send comment bodies as null if there is no comment body (as opposed to empty string). TeamMentionForwarder's HandleMentions assumes that the comment body will, at a minimum, be an empty string before checking to see if it contains the team name, which it uses to inform the team if there are any mentions we need to be aware of. When the comment body is null, this will throw an exception. This change adds a null check, and if the new body is null, or it doesn't contain the team name, we will not send a notification.
=> Fix exceptions in TeamMentionForwarder

src/Shared/Microsoft.DotNet.Internal.Testing.Utility/MockHttpClientFactory.cs
This makes a small modification to MockHttpClientFactory to support returning multiple different requests to the same URI by using the "This Has Been Sent" flag when matching requested URLs with their response. 
I think this is technically a behavior change, as previously it was perfectly legal to accept the same URL over and over and get the same response back, but you'd have to be careful about not over-disposing all the IDisposables involved. I've also confirmed all unit tests in arcade-services and dotnet-helix-services using this build.
=> Teach MockHttpClientFactory to support multiple requests

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Gather drop was incorrectly skipping some symbol nupkg files when they were shipping and on nuget feeds. This is a common internal servicing and stable package scenario. While originally reported for 6.0, this bug does appear for 5.0 servicing scenarios too.
To fix, reorder the conditionals because some .symbols.nupkg files would incorrectly match into of the original first conditional.
=> Fix symbol release generation

src/DotNet.Status.Web/.config/settings.Development.json, src/DotNet.Status.Web/.config/settings.json, src/DotNet.Status.Web/Startup.cs
Detected in https://github.com/dotnet/core-eng/issues/15239.  Basically, we had a secret that was a SAS URL of a blob in the same storage account used for other stuff in dotneteng-status* sites, but this wasn't automatically kept up.  By simply using the existing, secret-manager-managed secret in a different overload to the `PersistKeysToAzureBlobStorage()` call, we prevent having to manually regenerate the blob SAS URI every year or so.
=> Fix issue with github token storage

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
This sets the maestro availability alert in Grafana to ignore the "no_data" state. It doesn't add anything for our configuration and has only caused false positives.
=> Change Maestro availability to keep state if no data

src/Monitoring/Microsoft.DotNet.Monitoring.Sdk.Tests/MakePackTests.cs, src/Monitoring/Sdk/DeployImporter.cs, src/Monitoring/Sdk/GrafanaClient.cs, src/Monitoring/Sdk/GrafanaSerialization.cs, src/Monitoring/Sdk/README.md
These Grafana APIs include a field schemaVersion that describes the shape of the JSON. The current tool was implicitly designed to work with version 31. Grafana version 8.3.1, used by dnceng, is sending schemaVersion 33.
=> Grafana export/import tool updated so it can process grafana schemaVersion 33

src/DotNet.Status.Web/Controllers/AlertHookController.cs
Some alerts have charts that don't really bring much value and it might be confusing for FR ICs to see a graph with a single point in the middle because they might be wondering whether Grafana is working fine.
Example:
I have added a new Grafana notification channel which doesn't send the image with the alert but we need to ignore it in markdown too
=> Do not include graph image in issue when Grafana alert doesn't have it

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Reverts dotnet/arcade-services#1758
FSharp has decided on a different approach, so this is not needed.
=> Revert "Add F# to nuget gather process"

src/Maestro/Maestro.AzureDevOps/AzureDevOpsTokenProvider.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubAppTokenProvider.cs, src/Shared/Microsoft.DotNet.Internal.Health/AzureTableHealthReportProvider.cs, src/Shared/Microsoft.DotNet.Kusto.Tests/KustoClientProviderTests.cs, src/Shared/Microsoft.DotNet.Kusto.Tests/MockOptionMonitor.cs, src/Shared/Microsoft.DotNet.Kusto/KustoClientProvider.cs
IOptions is a non-dynamic value, so when secrets rotate in long lived
services, these values remain stuck at their old values
This replaces any usage of IOptions with IOptionsMonitor
if any of the values in those options are dynamic (based in secrets).
=> Use IOptionsMonitor for updating values

src/Microsoft.DncEng.PatGenerator.Tests/Microsoft.DncEng.PatGenerator.Tests.csproj, src/Microsoft.DncEng.PatGenerator/Microsoft.DncEng.PatGenerator.csproj, src/Microsoft.DncEng.PatGeneratorTool/Microsoft.DncEng.PatGeneratorTool.csproj
The framework and test references are managed by Directory.Build.props,
let's just let them get inherited here, since they aren't being overridden
for any particular reason.
=> Inherit Framework/NUnit from Directory.Build.props

src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/CreateMergedManifestBuildModelTests.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
https://github.com/dotnet/arcade/issues/8393
When moving away from using the buildData and using the constructed manfiest, we missed moving this one property.
=> Take the value of isStable from the constructed merged manifest

src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs
As part of anything that gets the build information from BAR, we may also want the AzDO build id, rather than having to parse it from the AzDO build link. This change updates the UxHelpers to also return the AzDO build id, in addition to everything else.
This will help push the work of https://github.com/dotnet/core-eng/issues/12374 forward, since today we would need to parse the build link to get the id, which could potentially break. Instead, we will be able to just grab the AzDO build id (all this so that our webhook won't have to directly talk to BAR itself).
=> Return the AzDO build id from get-build

azure-pipeline-codeql.yml, azure-pipelines.yml, eng/codeql.ps1, eng/local-codeql.ps1, src/DotNet.Status.Web/Controllers/DeploymentController.cs, src/DotNet.Status.Web/ZenHubClient.cs, src/Maestro/FeedCleanerService/FeedCleanerService.cs, src/Maestro/Maestro.Web/Pages/Account/AccountController.cs, src/Maestro/Maestro.Web/Pages/Index.cshtml, src/Maestro/maestro-angular/src/app/page/build-graph-table/popIncoherencies.component.html, src/Microsoft.DncEng.PatGenerator/AzureDevOpsPATGenerator.cs, src/Microsoft.DncEng.SecretManager/OneTimePasswordGenerator.cs, src/Microsoft.DncEng.SecretManager/SecretTypes/SqlServerConnectionString.cs, src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs, src/Monitoring/Sdk/GrafanaClient.cs, src/RolloutScorer/RolloutScorer/RolloutScorer.cs, src/Shared/Microsoft.DotNet.Internal.Health.Tests/MockHandler.cs, src/Shared/Microsoft.DotNet.Internal.Testing.Utility/MockHttpClientFactory.cs, src/Shared/Microsoft.DotNet.Web.Authentication.Tests/PersonalAccessTokenAuthenticationTests.cs, src/Telemetry/AzureDevOpsClient/AzureDevOpsClient.cs
This adds a CodeQL pipeline scheduled for a weekly analysis. This also makes changes to resolve existing errors.
New pipeline is [arcade-services-codeql](https://dev.azure.com/dnceng/internal/_build?definitionId=1084). Latest green build (from the head of this PR) is build [1627220](https://dev.azure.com/dnceng/internal/_build/results?buildId=1627220&view=results).
Resolves dotnet/core-eng#15329.
=> Add CodeQL pipeline and make repo compliant

src/Maestro/CoreHealthMonitor/CoreHealthMonitor.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/Actors/DelegatedActor.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/AppInsightsFlushLifecycle.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/DelegatedService.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/DelegatedStatefulService.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/DelegatedStatelessService.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/Lifecycle.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/ScheduledService/ScheduledService.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHost.cs
* Unhandled exceptions in RunAsync zombie the process
(because RunScheduleAsync never exits, so WhenAll never returns)
* Unhandled exception in RunAsync are never logged, for the same reason
* Exceptions close to process exist are never logged anyway
(because ServerTelemetryChannel doesn't flush on Dispose)
=> Correct resilience problems with our ServiceHost core

src/Maestro/CoreHealthMonitor/CoreHealthMonitor.cs
Files are being uploaded being named like this: 
This PR fixes the year value to be the year instead of YYYY.
=> Fix the formatting for the year value

src/Maestro/CoreHealthMonitor/.config/settings.json, src/Maestro/CoreHealthMonitor/CoreHealthMonitor.cs, src/Maestro/CoreHealthMonitor/MemoryDumpOptions.cs
Put dumps in Month/Day folders for easy delete/browsing
Also allow filtering of the dumps (to ignore, for example, the hundreds of MsSense crashes)
=> Organize and filter dumps

src/DotNet.Status.Web/Program.cs, src/Microsoft.DncEng.Configuration.Extensions/MappedJsonConfigurationProvider.cs, src/Microsoft.DncEng.Configuration.Extensions/MappedJsonConfigurationSource.cs, src/Microsoft.DncEng.Configuration.Extensions/ServiceConfigurationExtensions.cs, src/Microsoft.DncEng.DeployServiceFabricCluster/ClusterDeployer.cs, src/Microsoft.DncEng.DeployServiceFabricCluster/GatewaySettings.cs, src/Microsoft.DncEng.DeployServiceFabricCluster/Microsoft.DncEng.DeployServiceFabricCluster.csproj, src/Microsoft.DncEng.DeployServiceFabricCluster/Program.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHostWebSite.cs
Since it's using System.Threading.Timer, any exception
in the callback terminates the process from a background thread,
avoiding ALL other logging.
As such, we need to log this as well.  If we need this sort of thing in more places,
we might need some sort of "ITerminalExceptionReporter" or something.
=> Make sure the MappedConfig thing logs

eng/Packages.props, src/Maestro/Maestro.Contracts/Maestro.Contracts.csproj
This change fixes the errors we were seeing on M1 hardware by removing the runtimeIdentifier and updating the version of LibGit2Sharp to the latest preview.
Fixes https://github.com/dotnet/core-eng/issues/15536
=> Fix darc on mac M1 (arm64) architecture

azure-pipeline-codeql.yml, azure-pipeline-weekly.yml, azure-pipelines.yml, grafana-setup.yml
Somehow we thought we'd done this, I noticed it in today's rollouts.
=> Move all pipelines for arcade-services to NetCore1ES hosted pools

src/Microsoft.DotNet.ServiceFabric.ServiceHost.Tests/DelegatedServiceTest.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost.Tests/Microsoft.DotNet.ServiceFabric.ServiceHost.Tests.csproj, src/Microsoft.DotNet.ServiceFabric.ServiceHost/DelegatedService.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost/ScheduledService/ScheduledService.cs, src/Shared/Microsoft.DotNet.Internal.Testing.Utility/CountingLogger.cs
Also, test these behaviors
NOTE: This will be a breaking change to helix, because I pulled "CountingLogger" down into arcade-services, so there will be a conflict, and we'll want to delete the type from Helix and use the shared one.
=> Don't swallow the cancellation exception

azure-pipelines.yml, eng/common/templates/job/execute-sdl.yml, eng/common/templates/jobs/jobs.yml, eng/common/templates/post-build/channels/generic-internal-channel.yml, eng/common/templates/post-build/channels/generic-public-channel.yml, eng/common/templates/post-build/post-build.yml, eng/common/templates/post-build/setup-maestro-vars.yml, eng/deploy.yaml, eng/pre-deploy-tests.yaml
Continuation of previous PR; eng/common was littered with hosted pool info, but since updating arcade/3.x is much riskier, just update the eng/common folder of this repo to pick up proper images.
=> Move more pipelines to 1ES Hosted Pools

src/Maestro/DependencyUpdateErrorProcessor/DependencyUpdateErrorProcessor.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
Resolves dotnet/arcade#8579.
Maestro occasionally errors because of responses from GitHub. The current logging situation isn't giving quite enough info to determine if this is a Maestro problem or a GitHub problem. Application Insights telemetry shows that Octokit is throwing `ApiValidationException`s, but the default message and stack is missing context.
This PR adds extra logging around calls to capture the information GitHub sends in its response JSON. This should give much more detailed information on what exactly went wrong. Hopefully then that will be enough to know how to guard against them.
Info on the error payload format may be found at [Resources in the REST API - Client errors](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#client-errors).
=> Add extra logging around GitHub API calls

src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubAppTokenProvider.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubApplicationClientFactory.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubClientFactory.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubTokenProvider.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/IGitHubAppTokenProvider.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/IGitHubApplicationClientFactory.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication/IGitHubTokenProvider.cs, src/Shared/Microsoft.DotNet.Internal.DependencyInjection/ServiceCollectionExtensions.cs
This is the arcade-services part of resolving dotnet/arcade#8952. The dotnet-helix-service companion is [22274](https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/22274).
To allow MetricsObserver to monitor GitHub Apps, these changes are needed:
- Add overloads to classes that use GitHubAppTokenProvider to support [named options](https://docs.microsoft.com/en-us/dotnet/core/extensions/options#named-options-support-using-iconfigurenamedoptions).
- Add overload Dependency Injection Configuration method to support named options (and also expose configuration to builder)
- Minor quality-of-life log message improvements
- Minor changes to make the linter happy
=> Monitor GitHub app hook health

src/DotNet.Status.Web/Controllers/GitHubHookController.cs
When an issue is edited, it may have been edited from a null issue body (ie issueEvent.Changes.Body is null), but we assume that it is never null and blindly grab issueEvent.Changes.Body.From. This causes a lot of errors in DotNetStatus-Eng. This change adds a null check so that we don't fail in this instance.
Fixes https://github.com/dotnet/arcade/issues/8791
=> Add a null check to ProcessNotifications for edited events

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
This will give the investigator an easier starting point for investigating what the exceptions were and what was going on at the time of the exception.
=> Update the message for DotNetEng Status Failed Requests/Hour alert

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json, src/Monitoring/Monitoring.ArcadeServices/parameters.json
The custom pool provider is no more. Delete the seven panels that were monitoring it.
=> Remove pool provider panels from Grafana

arcade-services.sln, src/Shared/Microsoft.DotNet.GitHub.Authentication.Tests/GitHubAppTokenProviderTests.cs, src/Shared/Microsoft.DotNet.GitHub.Authentication.Tests/Microsoft.DotNet.GitHub.Authentication.Tests.csproj, src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubAppTokenProvider.cs
It sounds like, based on
https://github.com/AzureAD/azure-activedirectory-identitymodel-extensions-for-dotnet/issues/1433
that the default behavior sometimes changes to "true", which is basically
an alias for "destroy my process with no way out"
So lets override the caching behavior to be false and see if that helps
=> Try to fix a strange ObjectDisposedException in SubscriptionActorService

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
This should tamp down on dotnet/arcade#9234
Basically we stop splitting out the regions (North Central US is being incredibly flaky here), and dropped the threshold from "99%" (which basically means any failure at all), to 60% in 15 minutes. Each thing only pings once every 5 minutes, so the alert needs to be longer than that to avoid one spike causing an alert and then self resolving.
15 minutes = 3 intervals of 5 regions, so 60% means either every region failed 2 pings in a row (that's weird and bad), or 2 regions failed all 3 pings (also bad).
=> Reduce noise from source.dot.net in staging

src/Microsoft.DncEng.Configuration.Extensions/RegexConfigMapper.cs
This looks to be a breaking change from Microsoft.Extensions.Configuration.Json.  In the 5.0.0 -> 6.0.0 update, `{}` is interpreted, for some incomprehensible reason, as the null string.
This behavior is pretty nonsensical, but the 6.0.0 ship has sailed, so lets just deal with it.
=> Some settings are null, don't map those

.vault-config/dotneteng-status-prod.yaml, src/DotNet.Status.Web/.config/settings.json
Resolves dotnet/core-eng#15172.
This adds the pipelines run weekly against the Big Five dnceng repos. These pipelines have become a place to do periodic analysis and scans, where failures are harder to see but just as important.
=> Add weekly build pipelines to build monitor

.packages/Directory.Build.props, .packages/Directory.Build.targets, .packages/Directory.Packages.props, artifacts/Directory.Build.props, artifacts/Directory.Build.targets, artifacts/Directory.Packages.props
The "artifacts" and "packages" directories are inside our repository, meaning they implicitly grab settings here, which means we can't really touch stuff in our repo without artifacts breaking (like BAR publish).
This should break the connection in the cheapest way possible.
If this doesn't work, we either need to move artfacts/packages into a sub folder where we can put these files,
OR we need to move EVERYTHING in the repo "down a level" so we have a safe place to party.
=> Add empty Directory.* files

Directory.Build.props, NuGet.config, src/Monitoring/Sdk/Microsoft.DotNet.Monitoring.Sdk.csproj
Package mapping really doesn't play well with arcade/maestro,
since they dynamically add/remove feeds and packages,
which can't be mapped in advance.
=> Suppress this warning

src/Maestro/CoreHealthMonitor.Tests/DependencyRegistrationTests.cs, src/Maestro/Maestro.Web.Tests/DependencyRegistrationTests.cs, src/Maestro/Maestro.Web.Tests/LoggingConfigurationTests.cs, src/Maestro/tests/DependencyUpdater.Tests/DependencyRegistrationTests.cs, src/Maestro/tests/FeedCleaner.Tests/DependencyRegistrationTests.cs, src/Maestro/tests/SubscriptionActorService.Tests/DependencyRegistrationTests.cs, src/Maestro/tests/SubscriptionActorService.Tests/TestsWithServices.cs, src/Microsoft.DotNet.ServiceFabric.ServiceHost.Tests/ServiceHostTests.cs
Set Environment variable `ASPNETCORE_ENVIRONMENT` instead of `ENVIRONMENT` when configuring tests.
Resolves dotnet/arcade#9395 for this repo.
=> Set ASPNETCORE_ENVIRONMENT instead of ENVIRONMENT

src/DotNet.Status.Web/.config/settings.json
shows that this is the correct path.
https://github.com/dotnet/arcade/issues/9374
=> Fix path for arcade-services build in build monitor

src/RolloutScorer/RolloutScorer/Commands.cs, src/RolloutScorer/RolloutScorer/Config.cs, src/RolloutScorer/RolloutScorer/RolloutUploader.cs, src/RolloutScorer/RolloutScorer/Scorecard.cs, src/RolloutScorer/RolloutScorer/StandardConfig.cs
It's all in the title folkssss
Closes https://github.com/dotnet/arcade/issues/9329.
=> Change rollout scorer to have a max allowed time rather than dinging per minute over an "average" time

src/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs, src/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs, src/Microsoft.DncEng.SecretManager/Commands/ValidateAllCommand.cs, src/Microsoft.DncEng.SecretManager/Commands/ValidateCommand.cs, src/Microsoft.DncEng.SecretManager/InfoCommand.cs, src/Microsoft.DncEng.SecretManager/TestCommand.cs
Change `synchronize --force-secret=<secret-name>` to ignore all secrets except those specified. Previously, it would force-rotate specified secrets _and_ any other expired secret in the manifest. 
Also add tests around these arguments. 
To support testing the "force" arguments, no longer require confirmation when used in a noninteractive terminal (such as a test harness). Previously, the confirmation would fail on a noninteractive terminal.
=> Tweak "--force-secret" behavior and expand docs

src/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs, src/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs, src/Microsoft.DncEng.SecretManager/Commands/ValidateAllCommand.cs, src/Microsoft.DncEng.SecretManager/Commands/ValidateCommand.cs, src/Microsoft.DncEng.SecretManager/InfoCommand.cs, src/Microsoft.DncEng.SecretManager/TestCommand.cs
Reverts dotnet/arcade-services#1902
The `ForcedSecretsAreRotated()` test fails occasionally. I don't yet know why, but I do not want to get in the way.
=> Revert "Tweak "--force-secret" behavior and expand docs"

.vault-config/maestrolocal.yaml, .vault-config/shared/maestro-secrets.yaml
Manually cycling these secrets, they caused a null-ref since "text" kind needs " description".  So, fix them from text -> what they are.
@alexperovich please review...
=> Change secret type from text to azure-devops-access-token

.vault-config/shared/dotneteng-status-secrets.yaml, src/DotNet.Status.Web/.config/settings.json, src/DotNet.Status.Web/Controllers/AzurePipelinesController.cs
Updates:
* The secret used by Build Monitor to be explicit as to what it is using
* Changes the usage of IOptions to IOptionsSnapshot
* Updates the Build Monitor alerts for the weekly builds to include the First Responder label (as this generally means a secret expired)
Addresses https://github.com/dotnet/arcade/issues/9516
=> Update build moniter secret usage

src/Microsoft.DotNet.Internal.Tools.SynchronizePackageProps/Program.cs
We have updated one of our repos to use Directory.Packages.props, but we would like to continue to use this tool. This change updates SynchronizePackageProps to also know about Directory.Packages.props. Since the format of Directory.Packages.props is also different (it uses PackageVersion instead of PackageReference), updates were also made in the parsing of the xml doc to make sure that all cases are covered.
=> Refactor SynchronizePackageProps to also recognize Directory.Packages.props

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
In AddBuildToChannel, we would get all the channels that a build is supposed to be published to by default. However, as in the case of https://github.com/dotnet/arcade/issues/9508, where a default channel is set up for a specific branch and for a regex matching that branch, we'd add the same channel to the list multiple times. This caused arcade's publishing infrastructure to also get confused. We don't need to publish to the same channel twice, so we should distinct the list of channels that we will be publishing to, distinguished by their channel id.
=> Only add build to distinct channels

Directory.Packages.props, azure-pipelines.yml, src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerAzureFunction.csproj
Azure functions don't seem to support net6.0, reverting to net5.0 to unbreak the rollout scorer.
Closes https://github.com/dotnet/arcade/issues/9816.
The error that this should resolve:
```
System.Private.CoreLib: Could not load type 'System.Diagnostics.DebuggerStepThroughAttribute' from assembly 'System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
```
=> Upgrade RolloutScorerAzureFunction to work with net6.0

Directory.Packages.props
Previous change had the rollout scorer working locally but still broken in int. It seems upgrading this package may do the trick.
=> Update Microsoft.NET.Sdk.Functions for Rollout Scorer

src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHostWebSite.cs
The OAuth bounce from GitHub sends some very large cookie
tokens, and the default limits are small enough that, for some
some users with many teams/claims, they get rejected with
400 : Headers too large
=> Increase header size limits

azure-pipeline-codeql.yml, eng/codeql.ps1, eng/local-codeql.ps1
This adds the Grafana Init python code to the weekly CodeQL scans. 
See also [build 20220718.2](https://dev.azure.com/dnceng/internal/_build/results?buildId=1889568) for a test run.
=> Add the Grafana Init code to SDL scans

src/Microsoft.DncEng.PatGeneratorTool/Program.cs
`dotnet run --user redmond\dn-bot --password <password> --organizations dnceng --scopes build_execute code_write release_execute` now works 😃 
With Azure AD, using the account `redmond\dn-bot`, the TFS library makes a GET request to `https://login.microsoftonline.com/common/userrealm/redmond\dn-bot?api-version=1.0` causing a 404, and failing the authentication.  Rewriting `redmond\dn-bot` to `dn-bot@microsoft.com` allows the home realm discovery to succeed and thus the OAuth2 authentication.
Fixes https://github.com/dotnet/arcade/issues/9414
=> Fix PAT generator not working for domain accounts

src/Microsoft.DncEng.SecretManager/Readme.md, src/Microsoft.DncEng.SecretManager/StorageUtils.cs
This change adds the ability to specify more than one service when
generating an account SAS token. The previous implementation assumed
that only one service would ever be specifed.
This change also updates the Readme.md to account for this change.
=> Add multiple service support for account SAS tokens

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManager.cs
Looks for the commit on any branch, not just from HEAD down
=> Fix commit lookup for VMR sync/init

src/Microsoft.DotNet.Darc/src/Darc/Constants.cs, src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/MergePoliciesPopUpHelpers.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/SetRepositoryMergePoliciesOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/AddSubscriptionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/SetRepositoryMergePoliciesCommandLineOptions.cs
This got missed when the policy was added at some time back. It's part of the standard policy but not settable independently. Add to the UX
=> Add Do Not Automerge Downgrades policy to UX

src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/SourceMapping.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/SourceMappingParser.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerFactory.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Handles Source Build patches during initialization/synchronization of the VMR
Expects a new property in `source-mappings.json` pointing to where the patches are located in the VMR (later they can be moved):
```
{
"patchesPath": "src/installer/src/SourceBuild/tarball/patches",
...
}
```
Consider we're updating repo `A` from `sha1` to `sha2`, the new synchronization algorithm is as follows:
1. Checkout VMR
2. Clone individual repo A to temp
3. For each file that has a patch in the VMR, copy its `sha1` version from the clone to the VMR (to working tree only)
4. Prepare a diff from `A` for `sha1..sha2` and apply it onto the VMR
5. Apply any Source Build patches associated with the repo
6. Commit all above to the VMR
Resolves https://github.com/dotnet/arcade/issues/10261
=> Add source build patch support to VMR manager

src/Maestro/Maestro.MergePolicies/MergePolicyServiceCollectionExtensions.cs
This policy was added but only as part of the standard merge policy. It's currently not separately addressable. A previous commit added support in the Darc UX, but we still needed a little tweak in Maestro.
=> Add DontAutomergeDowngrades as a separately addressable policy

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrUpdater.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
The `.gitmodules` file, that has information about git submodules in a repository, is only relevant in the root of the repository. This means that we need to gather all `.gitmodules` files from all individual repos that we are synchronizing, compile a single file with all of them and place it in the root of the VMR.
This needs to happen at every commit. Additionally, we need to modify the paths to point into the `src/[repo]/..` paths. 
Also splits `IVmrManager` into `IVmrInitializer` and `IVmrUpdater` files and removes a forgotten `ignoreWorkingTree` parameter.
https://github.com/dotnet/arcade/issues/10583
=> Compile the `.gitmodules` file on every VMR commit

src/Maestro/Maestro.Contracts/MergePolicyEvalutationResult.cs, src/Maestro/Maestro.MergePolicies/AllChecksSuccessfulMergePolicy.cs, src/Maestro/Maestro.MergePolicies/MergePolicy.cs, src/Maestro/SubscriptionActorService/MergePolicyEvaluator.cs, src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
When we inform the user that checks were unsuccessful, we need to tell them which checks to look at as well, so they have an easier way to see why the dependency update isn't auto-completing.
Addresses https://github.com/dotnet/arcade/issues/10071
=> List the unsuccessful checks when AllChecksSuccessful fails

src/Maestro/DependencyUpdater/Program.cs, src/Maestro/Maestro.DataProviders/DarcRemoteFactory.cs, src/Maestro/Maestro.Web/Startup.cs, src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs, src/Maestro/SubscriptionActorService/Program.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs, src/Microsoft.DotNet.Darc/src/Darc/Helpers/RemoteFactory.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/VersionDetailsParser.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyTestDriver.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/GitFileManagerTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/RemoteTests.cs
Another small step to untangling `DarcLib` a bit more so that we can re-use the code for VMR flows.
No functional changes, just copy-pasting the code out to a re-usable component. Improvements to the class itself (such as support for SourceBuild tags) will come as a follow-up.
https://github.com/dotnet/arcade/issues/10264
=> Refactor parsing of Version.Details.xml to its own class

src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
Along with https://github.com/dotnet/arcade/pull/10638, cause usage of the -Svc build pool if running on dnceng organization
=> Make add-build-to-channel use a build pool matching the branch

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/VersionDetailsParser.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/VersionFiles.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyDetail.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/SourceBuildInfo.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/Microsoft.DotNet.DarcLib.Tests.csproj, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VersionDetailsParserTests.cs
Extended the parser to support the `<SourceBuild>` tags in `VersionDetails.xml`. The source-build metadata will be used in the VMR tooling (darc).
Additionally, the code was simplified, nullability enabled + some potential NREs dealt with.
https://github.com/dotnet/arcade/issues/10264
=> Refactor VersionDetails parser, add support for SourceBuild tags

src/DotNet.Status.Web/.config/settings.json
https://github.com/dotnet/arcade/issues/10656
This adds monitoring to the weekly secret synchronization builds for helix-machines and helix-service. We've had good results with having arcade-services monitored in this fashion and it will help increase the visibility of any failures so that we have enough time to react to them.
=> Add helix-service and helix-machines weekly to monitored definitions

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/VersionDetailsParser.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/VersionFiles.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/SourceBuildInfo.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VersionDetailsParserTests.cs
- Adds attribute needed for https://github.com/dotnet/source-build/issues/2481
- Resolves nullability problems and handles non-happy paths
- Adds tests for invalid XMLs
- Uses constants from `VersionFiles` more
=> Read the source-build `TarballOnly` attribute in `Version.Details.xml`

src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/InitializeOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/VmrOperationBase.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrUpdater.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrRegistrations.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
The initialize/synchronize operation will parse `Version.Details.xml` of each processed individual repository and recursively process all other SourceBuild dependencies.
This is a copy of what the tarball initialization does (but in MSBuild):  https://github.com/dotnet/installer/blob/12d0e4ba18890eae857199ada80b1debdf892e41/src/SourceBuild/Arcade/tools/SourceBuildArcadeTarball.targets#L117
https://github.com/dotnet/arcade/issues/10268
=> Add recursive VMR init / sync

azure-pipelines.yml, eng/common/templates/job/source-build.yml, eng/test.yaml
This change is required for builds to continue working in the new org, dev.azure.com/dnceng-public.
=> Update public pool names

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchProvider.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrRegistrations.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
This PR is pure refactoring, no functional changes apart from a small one-line fix in `VmrUpdater:88`.
Logic for handling patches is getting long (and will get longer soon) so let's extract it from the already long `VmrManager` classes.
We will add tests for this code later too.
=> Extract VMR patch handling into a separate file

src/Microsoft.DotNet.Darc/src/Darc/Program.cs
I found this very useful in `dotnet/xharness`.
Hopefully no one is dependent on parsing darc's debug output?
=> Print darc version + arguments in debug mode

src/Maestro/Maestro.DataProviders/DarcRemoteFactory.cs, src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs, src/Microsoft.DotNet.Darc/src/Darc/Helpers/RemoteFactory.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitSubmoduleInfo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/IGitFileManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/ILocalGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/GitHubClientTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/RemoteTests.cs
This PR:
- is a first step in untangling the `Remote` class and removes following inheritance `IGitRepo : ILocalGitRepo`,
- adds the ability to use and extend `ILocalGitRepo` with functionality tied to local `.git` folders which will be needed in the VMR later,
- adds the capability to list git submodules to `ILocalGitRepo`.
Problems this solves:
- Many implementations of `IGitRepo` that had to implement `ILocalGitRepo` too had `throw new NotImplemented..`.
- The only method used from `ILocalGitRepo` via `IGitRepo` was `GetFilesAtCommitAsync` whose implementation in `ILocalGitRepo` didn't make sense - it accepted URI and SHA but didn't use either, just listed files in a folder. It only was used in one place though `Local.cs` so I moved it there
- I removed a lot of dead code …
=> Split `IGitRepo`, `ILocalGitRepo`, enable listing git submodules

.vault-config/maestrolocal.yaml, .vault-config/shared/dotneteng-status-secrets.yaml, .vault-config/shared/maestro-secrets.yaml, src/Microsoft.DncEng.PatGenerator/AzureDevOpsPATScopes.cs, src/Microsoft.DncEng.SecretManager/Readme.md, src/Microsoft.DncEng.SecretManager/SecretTypes/AzureDevOpsAccessToken.cs
Also removed the github account option for this secret type because we never actually use it, and pat-generator can't work with it.
=> Update azure-devops-access-token secret type to produce instructions for pat-generator

src/Maestro/Maestro.DataProviders/DarcRemoteFactory.cs, src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs, src/Microsoft.DotNet.Darc/src/Darc/Helpers/RemoteFactory.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Commit.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitSubmoduleInfo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepoExtension.cs, src/Microsoft.DotNet.Darc/src/DarcLib/ILocalGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemoteGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrRegistrations.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/RemoteTests.cs
Based on the Teams discussion, adding the custom console formatter that turns this:
```
info: Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater[0]
Synchronizing installer from fdc96a7d0f3780df1aaee687692ba4145bb61d85 to https://github.com/dotnet/installer@HEAD
info: Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater[0]
Clone of https://github.com/dotnet/installer found, pulling new changes...
info: Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater[0]
Creating diff in /data/tmp/installer.patch..
info: Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater[0]
Diff created at /data/tmp/installer.patch - 0 commits, 355.058 KB
info: Microsoft.DotNet.DarcLib.VirtualMonoRepo.VmrUpdater[0]
Applying patch /data/tmp/installer.patch to src/installer...
info: …
```
=> Add a custom compact console formatter to darc CLI

src/Maestro/Maestro.DataProviders/DarcRemoteFactory.cs, src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs, src/Maestro/tests/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs, src/Microsoft.DotNet.Darc/src/Darc/Helpers/RemoteFactory.cs, src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitSubmoduleInfo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepoExtension.cs, src/Microsoft.DotNet.Darc/src/DarcLib/ILocalGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IRemoteGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/RemoteTests.cs
This is another attempt at refactoring out the `ILocalGitRepo` interface after the previous change was reverted (https://github.com/dotnet/arcade-services/pull/2030).
This change is much less invasive and tackles the problem in a better way than before. I have already ran the scenario tests locally and they pass.
- is a first step in untangling the `Remote` class and removes following inheritance `IGitRepo : ILocalGitRepo`,
- adds the ability to use and extend `ILocalGitRepo` with functionality tied to local `.git` folders which will be needed in the VMR later,
- adds the capability to list git submodules to `ILocalGitRepo`,
- removes some dead code.
This change removes following inheritance `IGitRepo : ILocalGitRepo`. It then splits `IGitRepo` into `IGitRemoteRepo` and `IGitRepo`. …
=> Split `IGitRepo` and `ILocalGitRepo`, add submodule listing

src/Monitoring/grafana-init/grafana.ini
This has already been disabled in both staging and production, adding to the config file for redeployments
=> Disable internal grafana metrics

.config/tsaoptions.json, azure-pipeline-codeql.yml
Swap Guardian for CodeQL 3000 Azure DevOps extension for CodeQL static code analysis.
Successful test build (minus TSA publish): [Pipelines - Run 2012488](https://dev.azure.com/dnceng/internal/_build/results?buildId=2012488&view=results)
Part of dotnet/arcade#11151
=> Use CodeQL 3000 instead of Guardian

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs
This algorithm follows what the tarball initialization does and looks for dependencies in `Version.Details.xml` using BFS instead of DFS.
The SHAs synchronized into the tarball now match the ones in the VMR.
=> Use breadth-first search when initializing VMR recursively

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
When we see the dependency the first time, we skip an update in case it's on the same SHA. However, if we see it later under a different version of some other repo, we will try to update to that version.
=> Fix recursive updates of dependencies that differ on lower level

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- Logging now includes parent dependency, from/to SHAs
- Also contains a propert fix instead of #2066
=> Improve logging when recursively updating VMR

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrRegistrations.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
Class that makes sure we don't clone/fetch unnecessarily. Will be more handy in a follow-up
=> Add a manager for temporary clones while synchronizing the VMR

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
This is needed but a temporary behavior too as we will probably stop listing commits and just diff two.
Resolves https://github.com/dotnet/arcade/issues/11360
=> Trim commit list when VMR sync contains too many commits

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
This makes the sync commits on a different branch and only makes a merge commit on the main branch so that main commits are always coherent and can be built okay.
Resolves https://github.com/dotnet/arcade/issues/11427
=> Create a dedicated branch for the recursive VMR sync

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- Deduplicated code for `VmrUpdater` and `VmrInitializer` and put it in a wrapper class
- I cannot use `IDisposal` for this purpose as I don't want this to trigger when exceptions happen
https://github.com/dotnet/arcade/issues/11530
=> Create a dedicated branch for VMR initialization commits

arcade-services.sln, src/Microsoft.DncEng.SecretManager/Microsoft.DncEng.SecretManager.csproj, src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccountInteractiveSecretType.cs, src/Shared/Microsoft.DotNet.Authentication.Algorithms.Tests/Microsoft.DotNet.Authentication.Algorithms.Tests.csproj, src/Shared/Microsoft.DotNet.Authentication.Algorithms.Tests/OneTimePasswordGeneratorTests.cs, src/Shared/Microsoft.DotNet.Authentication.Algorithms/Microsoft.DotNet.Authentication.Algorithms.csproj, src/Shared/Microsoft.DotNet.Authentication.Algorithms/OneTimePasswordGenerator.cs, src/Shared/Microsoft.DotNet.Web.Authentication.Tests/Microsoft.DotNet.Web.Authentication.Tests.csproj
This code is used in multiple places, let get it shared without a bunch of dependencies,
so we can use the code in helix too.
=> Share OTP code, since it's used in 2 places in helix

src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
https://github.com/dotnet/arcade/issues/11521
When the autoscaler is frozen, ProcessAutoscaleService can still trace ~2 traces per minute; this causes the alert to prematurely go green despite still being ongoing
=> Fix Autoscale out alert 

src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LocalHelpers.cs
This reverts commit 785cfc67c1c01cc6d465e4824ebf3a64fd75e2b3.
This change is breaking all the git scenarios in the repository, as seen by having every scenario test that uses git fail: https://dev.azure.com/dnceng/internal/_build/results?buildId=2036782&view=logs&j=4d9f00d7-d155-5977-7b70-2e6b79720ff2&t=4efd1961-d068-594b-7567-9ed5686ab047
=> Revert "Use --config-env to pass in user and pat (#2081)"

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/SourceMappingParser.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
Since we need to be able to map multiple different paths from within the development repositories into the VMR (and not only to VMR's root), we need to extend the functionality that synchronizes non-`src/` content. Example is the `eng/common` folder from `dotnet/installer`.
Previously, we had 1 path that we synchronized with the root of the VMR:
```json
"contentPath": "src/installer/src/SourceBuild/tarball/content",
```
Now we can have this:
```json
"additionalMappings": [
{
"source": "src/installer/src/SourceBuild/tarball/content",
"destination": ""
},
{
"source": "src/installer/eng/common",
"destination": "eng/common"
}
],
```
Resolves https://github.com/dotnet/arcade/issues/11548
=> Add the possibility to map any non-`src/` VMR content

src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/ManifestRecord.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/ReadmeComponentListGenerator.cs
The links in [the list of components of dotnet/dotnet](https://github.com/dotnet/dotnet#detailed-list) are currently all 404, because the code `url.Replace("//", "/")` leads to incorrect single-slashed `http:/github.com` URLs.
Also, the removal of `.git` in URLs wasn't working properly and was missing altogether in repo names.
With this PR, all component links in the README lead to valid pages.
https://github.com/dotnet/arcade/issues/11587
=> Fix URLs in VMR's README's auto-generated list of components

eng/deploy.yaml
There is a race condition in the production rollout pipeline where if we deploy before the publish using darc stage is complete, the main publishing pipeline could try to use the new version of darc before it is published, which will fail the publish job. This causes confusion for product teams when their jobs start failing. This change adds a dependency to the approval stage to only run after publish using darc completes, since if there is a failure there, we shouldn't approve anyway.
Addresses https://github.com/dotnet/arcade/issues/11575
=> Add publish-using-darc dependency in rollout pipeline

azure-pipelines.yml
Had a nightmare last night where I realized that this check existed for the merge of prod back to master specifically.
=> Fixup conditional GitHub issue check again

.vault-config/shared/dotneteng-status-secrets.yaml
Noted after merging https://github.com/dotnet/arcade/issues/11650 and testing pipelines.
=> Fix typo: there is no 'x' permission for Azure storage blob SAS Uris

src/DotNet.Status.Web/.config/settings.json
Originally, these were considered First Responder, but now that we have FROps, these fall more in the domain of that effort. Change the labels that are assigned to these build failures.
https://github.com/dotnet/arcade/issues/11692
=> Assign weekly secret job failures to FROps

eng/test.yaml, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/source-mappings.json
This PR temporarily adds a build step before the proper E2E tests are ready. This step adds about 8-12 minutes to the build because it needs to clone quite a lot of repositories and I haven't found a way to go around it.
It adds a lot of code coverage though before we add more unit tests and finish the proper E2E tests and we need the coverage at this moment to not break the VMR.
Sample run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=90844&view=logs&j=074323ca-ed16-5d66-87ac-2d9d4a30c602&t=6a6cde9d-c41f-5b7b-7538-ebe626f97918
https://github.com/dotnet/arcade/issues/11618
=> Add basic E2E test for the VMR tooling

azure-pipeline-codeql.yml, azure-pipelines.yml
Previously, Component Governance scans were enabled only on pipelines known to be run regularly and in the "production" configuration. The CG tools have changed how pipelines are tracked, making the selective path less effective.
This change lets CG run on all pipelines. This should be more like what CG tools expect and give a better reporting experience.
Part of [dotnet/arcade#11705](https://github.com/dotnet/arcade/issues/11705)
=> Let CG run on all pipelines

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
Resolves https://github.com/dotnet/arcade/issues/11716
=> Skip scanning empty VMR patch files

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncToolingE2ETest.cs
Resolves https://github.com/dotnet/arcade/issues/11847
=> Re-apply VMR patches at the end of a recursive sync

src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
Technically, we allow `null` token and we also even do it https://github.com/dotnet/arcade-services/blob/91b319ebd690281e46c035306c5145672e44dd26/src/Maestro/Maestro.DataProviders/DarcRemoteFactory.cs#L72
But.. it actually does not work as we get 401 from GH when the token in the header is empty. So let's allow this scenario as the VMR only clones public remotes and doesn't need a token then.
https://github.com/dotnet/arcade/issues/10549
=> Make GitHub client work without a token

Directory.Packages.props, src/DotNet.Status.Web/.config/settings.Production.json, src/DotNet.Status.Web/.config/settings.Staging.json, src/DotNet.Status.Web/.config/settings.json, src/DotNet.Status.Web/DotNet.Status.Web.csproj, src/DotNet.Status.Web/Startup.cs
Part of https://github.com/dotnet/arcade/issues/11852
The changes were extracted from @garath's branch https://github.com/dotnet/arcade-services/compare/main...garath:arcade-services:mistucke/11756-azure-keyvault, for easier validation.
I also enabled Managed Identity authentication on the staging storage account used for the staging DotNet.Status app to validate the Managed Identity changes
=> Migrate Dotnet.Status.Web to Azure.Security.Keyvault

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyUpdate.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
This PR simplifies how we pass around related metadata that we need during VMR sync.
No functional changes but preparing the ground for a follow-up PR.
https://github.com/dotnet/arcade/issues/11912
=> Use `VmrDependencyUpdate` everywhere

Directory.Packages.props
Cleans up the remaining references to Microsoft.Azure.KeyVault in the Directory.Packages
=> Clean up Microsoft.Azure.KeyVault

.config/dotnet-tools.json, .vault-config/shared/maestro-secrets.yaml
Part of https://github.com/dotnet/arcade/issues/11745
This repo already has the correct format in its manifests for PATs to get auto cycled, but we're using an older version of the tool that doesn't have the feature yet. This updates us to the package released during the latest production deployment.
=> update secret manager in repo to enable automatic PAT rotation features

src/Microsoft.DotNet.Darc/src/DarcLib/ILocalGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrMultipleRemotesTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
This makes it possible to synchronize a repo in the VMR from one remote to the other, e.g. a commit that is in public github.com repo onto one that is in the internal AzDO.
Resolves https://github.com/dotnet/arcade/issues/11913
=> Add support for multiple remotes of temporary clones

src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/InitializeOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/VmrOperationBase.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/src/DarcLib/GitRepoCloner.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/StringUtils.cs, src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepoCloner.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrUpdater.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrMultipleRemotesTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
This makes it possible to add a local directory as a remote when creating the clones which means we can make sure the clone has all the commits it needs (e.g. if we clone a fork, we can use the cloned fork to synchronize to it).
Also contains:
- Improvement into the clone manager where we first clone and fetch all remotes before we checkout a SHA
- Does not expect a repo to have `Version.Details.xml` inside no more
- Fixes a bug where we were not passing the `targetVersion`
=> Allow passing additional remotes to cloned repositories

src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/ScanOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/ScanCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Program.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrScanner.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrRegistrations.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrScanner.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrScannerTest.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
The PR adds a new command to the vmr: scan. The command scans the VMR, searching for files that shouldn't be there (the ones that are specified in the source-mappings.json as excluded, ignoring the ones permitted by the gitattributes). It does so by creating a git diff between the "zeroCommit" and the current branch HEAD
https://github.com/dotnet/arcade/issues/11985
=> Add the `darc vmr scan` command

src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/VmrOperationBase.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrSyncCommandLineOptions.cs
The original argument was conflicting with the positional one we use for repositories
=> Fix the `--additional-remotes` argument

src/Monitoring/Sdk/sdk/Sdk.props
https://github.com/dotnet/arcade/issues/11852#issuecomment-1373875060
We are building and publishing the Sdk project before calling `Monitoring.ArcadeServices.proj`, and in its build directory, it has the `Microsoft.Identity.Client` package, which is the problematic one, at least when I run the command on my machine. I think the problem is that the script is not actually using the locally built Sdk from the previous step, but rather something else: 
https://github.com/dotnet/arcade-services/blob/9c2ae5ed7ed8346952ef49e40d7586faf27f0317/src/Monitoring/Sdk/sdk/Sdk.props#L6-L7
even tho we set it to 
https://github.com/dotnet/arcade-services/blob/9c2ae5ed7ed8346952ef49e40d7586faf27f0317/src/Monitoring/Monitoring.ArcadeServices/Monitoring.ArcadeServices.proj#L6 which is the one built before …
=> Target the locally built sdk

src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/src/DarcLib/ILocalGitRepo.cs, src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
It seems like that the fetch provided by `AddRemotesIfMissing` only fetched named refs and not all commits which is what we need for our scenarios in the VMR. This is because AzDO shallow clones only a single commit which is not referenced and we then don't fetch it locally.
=> Perform a full fetch before VMR sync

src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
Somehow `fetch remoteName` does something else than `fetch remoteUri`
=> Fetch by remote URI not name during VMR sync

src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/GetRepoVersionOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/GetRepoVersionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrCommandLineOptionsBase.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrSyncCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Program.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrRepoVersionResolver.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrRegistrations.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrScanner.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Adds a new command that will give you the SHA of a repos you pass in
https://github.com/dotnet/arcade/issues/12258
=> Add the `darc vmr get-version` command

src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/BinaryFileScanOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/CloakedFileScanOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/ScanOperationBase.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/BinaryFileScanOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/CloakedFileScanOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrScanOptions.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrScanner.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrBinaryFileScanner.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrCloakedFileScanner.cs, src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrScanner.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrBinaryFileScannerTest.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrCloakedFileScannerTest.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
https://github.com/dotnet/arcade/issues/12238
We want to add baseline files to the VMR. These files won't appear in any of the scans.
For the implementation, we're appending a list of these to the `git diff` command in the following way:
`git diff <some options> :(exclude)<baseline_file>`
With this implementation, we don't have to do any parsing in case we want to use wildcard characters (things like arcade/documentation/*), git takes care of everything.
I tested the change with 39 of these baseline additions, and there was no performance hit. I'm not sure what would happen if we'd eventually have a list of 100+ of these, need to test that
=> Add baselines for ignored files during VMR scans

src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests.csproj, src/Shared/Microsoft.DotNet.Services.Utility/DefaultHttpHandlerConfiguration.cs, src/Shared/Microsoft.DotNet.Services.Utility/DefaultHttpHandlerConfigurationExtensions.cs, src/Shared/Microsoft.DotNet.Services.Utility/Microsoft.DotNet.Services.Utility.csproj
Make it easy to add a default handler for all HttpClients (in particular, so we can get retry behavior in some apps)
https://github.com/dotnet/arcade/issues/9875
=> Add a default HttpClient handler option

src/Monitoring/Sdk/sdk/Sdk.props
Revert a path change made in 5b8fe69f that breaks consumers of the Monitoring SDK. 
Resolves [dotnet/arcade#12375](https://github.com/dotnet/arcade/issues/12375)
=> Revert path change from 5b8fe69f

.gitignore, Directory.Packages.props, src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs, src/Microsoft.DotNet.Darc/src/Darc/Options/SubscriptionsCommandLineOptions.cs, src/Microsoft.DotNet.Darc/src/Darc/Properties/AssemblyInfo.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Helpers/ConsoleOutputIntercepter.cs, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Microsoft.DotNet.Darc.Tests.csproj, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_json.verified.txt, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_sorted_text.verified.txt, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_text.verified.txt, src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.cs
The JSON output is helpful for integration scenarios.
Added tests. Please note https://www.nuget.org/packages/Verify.NUnit/ needs to be added to https://dev.azure.com/dnceng/public/_artifacts/feed/dotnet-public feed (there's already Verify.XUnit variant).
Closes https://github.com/dotnet/arcade/issues/12442
=> Support JSON output for `darc get-subscriptions` command

Directory.Packages.props, src/DotNet.Status.Web/DotNet.Status.Web.csproj, src/Shared/Microsoft.DotNet.Kusto.Tests/KustoHelpersTests.cs, src/Shared/Microsoft.DotNet.Kusto/KustoHelpers.cs
I chose this version of Kusto.Ingest because it didn't have Microsoft.Azure.KeyVault in it's dependency tree and it didn't update any other packages. Choosing a higher version would have required some major version updating of packages like Newtonsoft.Json and many others.
=> Update/Remove packages that use Microsoft.Azure.KeyVault

src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrSyncCommandLineOptions.cs
Seems like the `commandline` library doesn't work when using the separator so we do it ourselves.
=> Fix parsing of the additional-remotes argument

src/Maestro/SubscriptionActorService/PullRequestDescriptionBuilder.cs
https://github.com/dotnet/arcade/issues/12793
I think there used to be a 4000 character limit for GitHub descriptions/comments. Looks like that limit is 65536 characters now (based on https://github.com/orgs/community/discussions/27190), so having the full SHAs in our PRs shouldn't be an issue
=> Increase SHA length for Maestro comparison links

src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Ensures that the linker packages get put into the package layout for nuget publishing.
@asvyat @rbhanda @tkapin @premun 
This is an area where we need to improve. Gather-drop today has to populate at least 2 (maybe 3) locations with the same files. The release automation understands this legacy "publish_files" location for the purposes of determining what to push to nuget.org and storage accounts and whatever. This is largely legacy of when we populated this stuff on vsufile.
This is confusing and inefficient and whenever we have changes in what repos push packages, we have to go and change things in multiple places. This cruft is expensive to maintain. Ideally we would:
- Remove the dependency on publish_files in the release pipeline. The release pipeline should just drive off staging …
=> Gather linker packages

src/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs, src/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs, src/Microsoft.DncEng.SecretManager/SecretProperties.cs, src/Microsoft.DncEng.SecretManager/StorageTypes/AzureKeyVault.cs
https://github.com/dotnet/arcade/issues/12792
The NextRotationOn property is already in the Tags, we don't need to have a separate Property just for it, since it's used only in one place
=> Only log errors if secrets in the manifest are missing the NextRotationOn tag

src/DotNet.Status.Web.Tests/AnnotationsControllerTests.cs, src/DotNet.Status.Web.Tests/DotNet.Status.Web.Tests.csproj, src/DotNet.Status.Web.Tests/DotNetStatusEmptyTestStartup.cs, src/DotNet.Status.Web.Tests/EmptyTestStartup.cs, src/DotNet.Status.Web.Tests/GitHubHookControllerTests.cs, src/Shared/Microsoft.DotNet.Internal.Testing.Utility/Microsoft.DotNet.Internal.Testing.Utility.csproj, src/Shared/Microsoft.DotNet.Internal.Testing.Utility/TestAppFactory.cs, src/Shared/Microsoft.DotNet.Web.Authentication.Tests/DefaultAuthorizeActionModelConventionTests.cs, src/Shared/Microsoft.DotNet.Web.Authentication.Tests/Microsoft.DotNet.Web.Authentication.Tests.csproj, src/Shared/Microsoft.DotNet.Web.Authentication.Tests/PersonalAccessTokenAuthenticationTests.cs
https://github.com/dotnet/arcade/issues/12952
The `EmptyTestStartup` class has to be in a project with an entry point. Since the `Testing.Utility` project is a library, it doesn't fulfill this requirement, so we have to create it in every Test project that wants to use `TestAppFactory`
=> Migrate TestAppFactory to Microsoft.DotNet.Internal.Testing.Utility

CredScanSuppressions.json
Fixes [dotnet/arcade#12993](https://github.com/dotnet/arcade/issues/12993) by adding the hash, as detected and calculated by credscan, to the local suppressions configuration file.
=> Suppress credscan false-positives in readme

azure-pipelines.yml, src/Maestro/CoreHealthMonitor.Tests/CoreHealthMonitor.Tests.csproj
Attempts to fix: https://github.com/dotnet/arcade/issues/12985 by building for x64 instead of `Any CPU`
=> Specify building architecture

.vault-config/maestrolocal.yaml, .vault-config/shared/maestro-secrets.yaml, src/Telemetry/AzureDevOpsTimeline/.config/settings.json
https://github.com/dotnet/arcade/issues/13039
Uses PATs with much narrower scope for the Azure DevOps timeline processing, also stops reusing the same PAT for both dnceng* organizations.
=> Add new PATs for azure devops timeline processing

src/Microsoft.DncEng.SecretManager.ScenarioTests/StorageTests.cs, src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageAccountSasUri.cs, src/Microsoft.DncEng.SecretManager/StorageUtils.cs
Staging publishing needs to use an account SAS. Currently, publishing supports SAS uris (not just suffixes). Support generation of these.
https://github.com/dotnet/arcade/issues/13041
=> Enable generation of account SAS uris

arcade-services.sln, src/DotNet.Status.Web.Tests/AzurePipelinesControllerTests.cs, src/DotNet.Status.Web/Controllers/AzurePipelinesController.cs, src/Telemetry/AzureDevOpsClient.Tests/AzureDevOpsClient.Tests.csproj, src/Telemetry/AzureDevOpsClient.Tests/TryGetImageNameTests.cs, src/Telemetry/AzureDevOpsClient/AzureDevOpsClient.cs, src/Telemetry/AzureDevOpsClient/IAzureDevOpsClient.cs, src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimeline.cs, src/Telemetry/AzureDevOpsTimeline/BuildLogScraper.cs, src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/BuildLogScraperTests.cs, src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/MockAzureClient.cs, src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/MockTimeoutAzureClient.cs
https://github.com/dotnet/arcade/issues/12997
The log structure changed a while ago, examples of the new logs:
- https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2150258/logs/4
- https://dev.azure.com/dnceng/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2150217/logs/1074
To avoid a thing like this happening, we could set up a grafana dashboard where we query the percentage rate of 1ES and MicrosoftHosted records with an ImageName, and fire an alert if the percentage is too low
=> Change Log Scraping regex for Microsoft Hosted Agents

eng/deploy.yaml
Part of [dotnet/arcade#13312](https://github.com/dotnet/arcade/issues/13312).
Deployments of dotneteng-status are broken. I think this will fix them. Unfortunately, I can't truly test it until it is merged into main (because no deployments happen with PR builds). 
This change only effects the deployment of dotneteng-status.
=> Change dotneteng-status to use zipDeploy

global.json
New component governance alerts require us to bump .NET to fix them as problems come from NuGet bundled inside of them
[#2675](https://github.com/dotnet/arcade-services/issues/2675)
=> Update .NET SDK to 6.0.410

azure-pipeline-weekly.yml, azure-pipelines.yml, eng/deploy.yaml, eng/templates/stages/secret-validation.yml
- The `production` build no longer publishes packages → speed-up of 60-90 minutes + we no longer publish old code with new version
- The `main` build no longer waits for package publishing as it's not really required → speed-up of 60 minutes for `main` builds
- Secret verification no longer happens twice (in `Build` and in its own stage)
- Removed unused code such as unused YAML parameters or variables
- Removed unnecessary steps such as .NET restore when it's done as part of Arcade build anyway
- Simplified YAML in many places
- GitHub verification stage is now omitted properly
- YAML de-duplication of secret rotation, pool configuration and more
- E2E test time limit increased from 90 to 120 minutes as it sometimes times out
The new rollout pipeline looks like this:
Sample rollout build …
=> Improve `main`/`production` pipeline run time, clean up YAML

azure-pipelines.yml, eng/enforce-issue.ps1
Associated GitHub issue is still required in the description, just the release notes can be in the PR.
Allow specifying release notes in PR description directly
Resolves https://github.com/dotnet/arcade-services/issues/2727
=> Allow specifying release notes in PR descriptions directly

azure-pipeline-weekly.yml
Changes the weekly pipeline trigger time from 2 PM Prague time, to 8 AM
https://github.com/dotnet/arcade-services/issues/2733
=> Trigger weekly pipeline every Monday at 6 AM (UTC)

src/Microsoft.DotNet.Darc/Darc/Operations/GetAssetOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/GetAssetCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs
https://github.com/dotnet/arcade-services/issues/2600
Added the possibility of filtering build assets by BAR build ID in `darc get-asset`
=> Allow scoping `get-asset` search by BAR ID

.github/ISSUE_TEMPLATE/rollout-issue.md
[Resolves #2735](https://github.com/dotnet/arcade-services/issues/2735)
There are actually two ways how to implement the issue templates on GitHub - 1) simple markdown templates and 2) YAML-based issue forms. I've investigated both and the more structured YAML forms seem to be an overkill for our purpose that would just be more difficult to read, hence I'm going with the simple Markdown based template.
@premun - I've unfortunately lost the original notes I've made so some of the steps (especially for the rollback) that we've talked about might be missing
=> GitHub template for rollout issues

src/Microsoft.DotNet.Darc/DarcLib/Helpers/FileSystem.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/IFileSystem.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
Recursively splits patches larger than 1GB and creates patches for their child folders
Resolves https://github.com/dotnet/arcade-services/issues/2710
Add support for VMR synchronization of repos >1GB
=> Split patches into smaller when over 1GB

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs, test/Microsoft.DotNet.Maestro.Tasks.Tests/MergedManifestTests.cs, test/Microsoft.DotNet.Maestro.Tasks.Tests/Mocks/MockBuildEngine.cs
When merging manifests, we were distincting the assets and erroring if there are dupes. This should have been done using an equality comparer that compares based on Id alone. Fix this, and add appropriate testing.
Resolves: https://github.com/dotnet/arcade-services/issues/2762
=> Disallow duplicate assets when merging manifests

eng/BuildTask.targets, src/Maestro/Microsoft.DotNet.Maestro.Tasks/Microsoft.DotNet.Maestro.Tasks.csproj
The resolution of https://github.com/dotnet/arcade-services/issues/2296 made the Maestro tasks package non-packable. This tasks package should either live in arcade-services or arcade (it has lived both places), but it's heavily tied into arcade infra and also heavily uses DarcLib functionality. It didn't move to dnceng or dnceng-shared, and so should be re-enabled.
Resolved https://github.com/dotnet/arcade-services/issues/2805
=> Make Maestro.Tasks packable again

.github/ISSUE_TEMPLATE/rollout-issue.md
- Adds notes about making sure we're not squash committing
- Hides the rollback section unless it's needed to keep the issue more clean
https://github.com/dotnet/arcade-services/issues/2826
Improved instructions in the rollout checklist
=> Improve rollout checklist, hide rollback by default

src/Microsoft.DotNet.Darc/Darc/Program.cs
Introduced in https://github.com/dotnet/arcade-services/pull/2809
https://github.com/dotnet/arcade-services/issues/2433
Fixed darc vmr command argument parsing regression
=> Fix darc vmr command argument parsing regression

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrScanner.cs
Non-src content rules were ignored (e.g. `eng/common/..`)
Resolves issue when ignoring an `.lss` file https://github.com/dotnet/source-build/issues/3589
Fixed VMR scan rules parsing for non-src content
=> Fix VMR scan rule parsing for non-`src/` content

Directory.Packages.props, src/Microsoft.DotNet.Darc/DarcLib/Microsoft.DotNet.DarcLib.csproj
This PR removes `Microsoft.Azure.Services.AppAuthentication` as it's no longer needed after https://github.com/dotnet/dnceng-shared/commit/da9b63e8cee2228dc0b333e0ff4c721cc7cb490f was made.
The rest of the changes is sorting the packages alphabetically.
CG build break: https://github.com/dotnet/arcade-services/issues/2855
CG alert: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade-services/alert/8147817?typeId=6567134
Stop using `Microsoft.Azure.Services.AppAuthentication`
=> Stop using `Microsoft.Azure.Services.AppAuthentication`

src/Maestro/Maestro.Contracts/CoherencyErrorDetails.cs, src/Maestro/Maestro.Contracts/IPullRequest.cs, src/Maestro/Maestro.MergePolicies/MergePolicyServiceCollectionExtensions.cs, src/Maestro/Maestro.MergePolicies/StandardMergePolicy.cs, src/Maestro/Maestro.MergePolicies/ValidateCoherencyMergePolicy.cs, src/Maestro/Maestro.MergePolicyEvaluation/MergePolicyConstants.cs, src/Maestro/SubscriptionActorService/InProgressPullRequest.cs, src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Microsoft.DotNet.Darc/Darc/Constants.cs, src/Microsoft.DotNet.Darc/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/SetRepositoryMergePoliciesOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/AddSubscriptionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/DarcLib/RemoteRepoBase.cs, test/Maestro.ScenarioTests/EndToEndFlowLogic.cs, test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs, test/Maestro.ScenarioTests/ObjectHelpers/SubscriptionBuilder.cs, test/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs, test/Maestro.ScenarioTests/ScenarioTests_MergePolicies.cs, test/SubscriptionActorService.Tests/PullRequestActorTests.cs
https://github.com/dotnet/arcade-services/issues/2687
This PR includes:
* The original "Remove the fallback to the legacy coherency algorithm." commit https://github.com/dotnet/arcade-services/commit/4b3f187465f0f760efe54ac26dd034977a7b961b which was rollback by https://github.com/dotnet/arcade-services/commit/ce6c541aa3d221c0d47093973461b59e7f39c88e
* New commit "Maestro++: Ensure that InProgress pull requests remain backward compatible with newer version of Maestro." which solves the problem described below.
Please pay attention to the second commit, but feel free to do a full review.
I extended the [InProgressPullRequest](https://github.com/dotnet/arcade-services/blob/main/src/Maestro/SubscriptionActorService/InProgressPullRequest.cs) serializable data type with two members, one of …
=> Maestro++: Ensure that InProgress pull requests remain backward compatible with newer version of Maestro.

src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs
https://github.com/dotnet/arcade-services/issues/2914
Display full build information after adding it to a channel
=> Get build information after adding it to channel

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
https://github.com/dotnet/arcade-services/issues/2876
Started deleting unused large (>1GB) VMR patches
=> Delete over-the-size-limit patch files

.github/ISSUE_TEMPLATE/rollout-issue.md, src/Microsoft.DotNet.Darc/DarcLib.AzDev/AzureDevOpsClient.cs
Add `refs/heads/` to branch name only if it doesn't start with it already so that the method can be called with the full branch name `$(Build.SourceBranch)` 
Issue: https://github.com/dotnet/arcade-services/issues/2845
This method will be used to start a run of Stage-DotNet-Validate-publish from Stage-DotNet-Prepare-Artifacts.
`$(Build.SourceBranch)` gives you the whole name starting with `refs/head/..` while `$(Build.SourceBranchName)` cuts off everything before the last slash and doesn't work for branches like `mhristova/branch`
SKIP IN RELEASE NOTES
=> Start pipeline build on refs/heads/branch

src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Microsoft.DotNet.Darc/Darc/Operations/UpdateDependenciesOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/UpdateDependenciesCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/Actions/Remote.cs, src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs, test/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs, test/SubscriptionActorService.Tests/PullRequestActorTests.cs
https://github.com/dotnet/arcade-services/issues/2911
Recently we removed the fallback to Legacy coherency algorithm in Maestro++ https://github.com/dotnet/arcade-services/issues/2687 so that only Strict one is in use. Now we need to remove the Legacy algorithm itself from Darc.
Darc `update-dependencies` command no longer has `legacy-coherency` option. Darc supports Strict Coherency Algorithm only.
=> Remove the Legacy coherency algorithm from Darc

src/Maestro/Maestro.Web/PackageRoot/ServiceManifest.xml, src/Maestro/MaestroApplication/ApplicationPackageRoot/ApplicationManifest.xml
The original PR (https://github.com/dotnet/arcade-services/pull/2948) wasn't correct. I added the endpoint in the `Override` section, but there was nothing to override, which broke the deployment https://dev.azure.com/dnceng/internal/_build/results?buildId=2288375&view=logs&j=b277f1ae-44e7-5ce4-4818-00049b2c7654&t=300ea8c8-976b-58c1-6a89-17701eb43612&l=87
=> Put the new endpoint configuration in the correct place

src/Maestro/Maestro.MergePolicies/ValidateCoherencyMergePolicy.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/InitializeOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrSyncCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrUpdater.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncRepoChangesTest.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
https://github.com/dotnet/arcade-services/issues/2913
VMR synchronization only generates a `CODEOWNERS` file when asked
=> Hide CODEOWNERS generation behind an option

Directory.Build.props
This PR prevents Visual Studio from hinting language features which will not be available during runtime as we are at .NET 6.0:
https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/configure-language-version
https://github.com/dotnet/arcade-services/issues/2978
Not release not worthy
=> Use C# 10 to match .NET 6.0

src/Microsoft.DotNet.Darc/Darc/Operations/Operation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/BackflowOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/VmrOperationBase.cs, src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/ICommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/BackflowCommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/IBaseVmrCommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrSyncCommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Program.cs, src/Microsoft.DotNet.Darc/DarcLib/Constants.cs, src/Microsoft.DotNet.Darc/DarcLib/ILocalGitRepo.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CodeBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInfo.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrRegistrations.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPusherTests.cs
- There are no tests yet as it is expected that this functionality might change a bit. We will add tests once we are able to also flow package versions. This was manually tested though.
- This change also utilizes `NativePath` more frequently whenever we expect a local file system path.
https://github.com/dotnet/arcade-services/issues/2979
Added `darc vmr backflow` command
=> Add `darc vmr backflow` command

azure-pipelines.yml, docs/DevGuide.md, eng/templates/stages/deploy.yaml, src/Maestro/maestro-angular/src/index.html, test/Maestro.ScenarioTests/ScenarioTests_AzDoFlow.cs, test/Maestro.ScenarioTests/ScenarioTests_Clone.cs, test/Maestro.ScenarioTests/ScenarioTests_Dependencies.cs, test/Maestro.ScenarioTests/ScenarioTests_MergePolicies.cs, test/Maestro.ScenarioTests/ScenarioTests_Subscriptions.cs, test/Maestro.ScenarioTests/TestParameters.cs
https://github.com/dotnet/arcade-services/issues/2988
Started: https://dev.azure.com/dnceng/internal/_build/results?buildId=2298595&view=results for testing purposes
Run some Maestro Scenario tests on the new URL
=> Run half of the tests on the new url

src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/UpdateCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrUpdater.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncRepoChangesTest.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
Resolves a problem found in https://github.com/dotnet/arcade-services/issues/3010
When we get 2 builds from the same SHA, the VMR would not update the package version in its metadata as it would assume no changes are needed.
Detect package version change even when SHA stays the same
=> Detect package version change even when SHA stays the same

src/Microsoft.DotNet.Darc/DarcLib/Actions/Local.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs, src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CodeBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
I found during some testing that when new refs are created in a remote and the local repo gets very outdated, not all new refs are pulled properly.
This change uses a new way to synchronize a remote once it's added/needs to be refreshed.
https://github.com/dotnet/arcade-services/issues/2982
Started using `git remote update` instead of `git fetch`
=> Use `git remote update` instead of `git fetch`

eng/templates/stages/deploy.yaml, eng/templates/stages/secret-validation.yml
This was broken by the move to the 8.0 Arcade: https://github.com/dotnet/arcade-services/issues/3053
Tested here: https://dev.azure.com/dnceng/internal/_build/results?buildId=2317181&view=logs&j=4d9f00d7-d155-5977-7b70-2e6b79720ff2&t=b6bdfb3b-13bb-5ba7-3230-bffa36e2e1b9
=> Fix running secret manage and scenario tests

azure-pipelines.yml, eng/templates/steps/test.yml
We will get these artifacts:
https://github.com/dotnet/arcade-services/issues/3074
=> Publish build logs through Arcade

src/Maestro/Maestro.DataProviders/DarcRemoteFactory.cs, src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs, src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/FileSystem.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/GitRepoType.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/GitRepoUrlParser.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/IFileSystem.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalLibGit2Client.cs, src/Microsoft.DotNet.Darc/DarcLib/RemoteConfiguration.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrGitClientFactory.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInfo.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncRepoChangesTest.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs, test/Microsoft.DotNet.DarcLib.Tests/Helpers/GitRepoUrlParserTest.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
When we synchronize commits from different remotes (i.e. GitHub vs AzDO), we will gradually fetch first from available (local) and public (GitHub) repos. If we find the commits there, we won't fetch from others (AzDO) internal ones.
This enables flow when commits can come from internal AzDO but can already be available in GitHub already. The synchronization into the VMR will work even in public (when merging `internal/release` to `release`) even though source-manifest or target commits are have AzDO URIs in `Version.Details.xml` associated with them. 
Tests will be added later, we need this in to unblock https://github.com/dotnet/installer/issues/17809 and https://github.com/dotnet/installer/issues/17785
Lazy-fetch repos during VMR sync to allow internal->public merges
=> Lazy-fetch repos during VMR sync to allow internal->public merges

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
Improvement of https://github.com/dotnet/arcade-services/issues/3080 to first fetch from local directories and public GitHub repos during the VMR sync
=> Order remotes when reading dependency tree

src/Microsoft.DotNet.Darc/DarcLib/GitNativeRepoCloner.cs, src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalLibGit2Client.cs
Seems like Azure DevOps changed the header it requires and the sync started failing: https://github.com/dotnet/arcade-services/issues/3075
The PR also uses tokens for a subsequential `remote update` and `remote fetch`.
- Azure DevOps: `Authorization: Bearer [BASE64 TOKEN]`
- GitHub: `Authorization: Basic [TOKEN]`
Use different auth header when cloning AzDO/GitHub repos
=> Use different auth header when cloning AzDO/GitHub repos

src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
Bug introduced in https://github.com/dotnet/arcade-services/issues/3091
Manifested as:
```
System.NotSupportedException: Collection was of a fixed size.
at System.SZArrayHelper.Add[T](T value)
at Microsoft.DotNet.DarcLib.LocalGitClient.AddGitAuthHeader(IList`1 args, IDictionary`2 envVars, String repoUri) in /_/src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs:line 369
at Microsoft.DotNet.DarcLib.LocalGitClient.UpdateRemoteAsync(String repoPath, String remoteName, CancellationToken cancellationToken) in /_/src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs:line 206
at Microsoft.DotNet.DarcLib.Local.AddRemoteIfMissingAsync(String repoDir, String repoUrl) in /_/src/Microsoft.DotNet.Darc/DarcLib/Actions/Local.cs:line 170
at Microsoft.DotNet.Darc.Operations.CloneOperation.HandleMasterCopy(Re …
```
=> Fix git auth header creation

Directory.Packages.props, src/Microsoft.DotNet.Darc/Darc/Microsoft.DotNet.Darc.csproj
https://github.com/dotnet/arcade-services/issues/3139
Updated the `YamlDotNet` library
=> Stop using a deprecated YamlDotNet package

src/Maestro/SubscriptionActorService/PullRequestDescriptionBuilder.cs, test/SubscriptionActorService.Tests/PullRequestDescriptionBuilderTests.cs
https://github.com/dotnet/arcade-services/issues/3114
I couldn't find any document online that says that using short shas works on AzDo, like it does on GitHub. Also did manual testing
Use full sha for commit comparison on AzDo
=> Use long SHAs in AzDO PR descriptions

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Fixes this log:
https://dev.azure.com/dnceng-public/public/_build/results?buildId=506596&view=logs&j=941f2e24-48a0-594a-6b1a-0e16aaeb8606&t=cffff4a5-f52c-50c6-45c9-52a0bd619b26&l=423
```
info: Recursively updating installer's dependency test-templates / 1e5f3603af2277910aad946736ee23283e7f3e16 → 1e5f3603af2277910aad946736ee23283e7f3e16
warn: Repository test-templates is already at 1e5f3603af2277910aad946736ee23283e7f3e16
info: Recursively updating installer's dependency fsharp / f41fe153f68dd6b20cf4f91de9ea1e55fc09bb20 → f41fe153f68dd6b20cf4f91de9ea1e55fc09bb20
warn: Repository fsharp is already at f41fe153f68dd6b20cf4f91de9ea1e55fc09bb20
info: Recursively updating installer's dependency vstest / ae25c3b96fe433c60af70e3991ace49fcbf7e970 → ae25c3b96fe433c60af70e3991ace49fcbf7e970
warn: …
```
=> Lower logging level for no-op VMR sync

Directory.Packages.props, test/Maestro.ScenarioTests/AsyncDisposable.cs, test/Maestro.ScenarioTests/AsyncDisposableValue.cs, test/Maestro.ScenarioTests/Disposable.cs, test/Maestro.ScenarioTests/EndToEndFlowLogic.cs, test/Maestro.ScenarioTests/Maestro.ScenarioTests.csproj, test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs, test/Maestro.ScenarioTests/ObjectHelpers/BuildRefComparer.cs, test/Maestro.ScenarioTests/ObjectHelpers/DependencyCollectionStringBuilder.cs, test/Maestro.ScenarioTests/ObjectHelpers/SubscriptionBuilder.cs, test/Maestro.ScenarioTests/ScenarioTests_AzDoFlow.cs, test/Maestro.ScenarioTests/ScenarioTests_Builds.cs, test/Maestro.ScenarioTests/ScenarioTests_Channels.cs, test/Maestro.ScenarioTests/ScenarioTests_Clone.cs, test/Maestro.ScenarioTests/ScenarioTests_DefaultChannels.cs, test/Maestro.ScenarioTests/ScenarioTests_Dependencies.cs, test/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs, test/Maestro.ScenarioTests/ScenarioTests_MergePolicies.cs, test/Maestro.ScenarioTests/ScenarioTests_RepoPolicies.cs, test/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs, test/Maestro.ScenarioTests/ScenarioTests_Subscriptions.cs, test/Maestro.ScenarioTests/Shareable.cs, test/Maestro.ScenarioTests/TemporaryDirectory.cs, test/Maestro.ScenarioTests/TestHelpers.cs, test/Maestro.ScenarioTests/TestHelpersTest.cs, test/Maestro.ScenarioTests/TestParameters.cs, test/Maestro.ScenarioTests/TestRepository.cs, test/Microsoft.DotNet.DarcLib.Tests/GitHubClientTests.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs, test/Microsoft.DotNet.Maestro.Tasks.Tests/MergedManifestTests.cs
This PR improves the work with the ScenarioTests project code:
- Ran analyzers and resolved compiler messages
- Bumped testing libraries
- Stopped using `NUnit.Assert` and started using `FluentAssertions` for better test failure messages
- Formatted code to match the rest of the repo
- Enabled nullability for some classes
There should be no functional changes, just re-formatting and adding nullability. Just errors from failed assertions should get better.
https://github.com/dotnet/arcade-services/issues/3031
This build verifies everything: https://dev.azure.com/dnceng/internal/_build/results?buildId=2340341&view=results
=> Resolve compiler messages in `ScenarioTests`, use `FluentAssertions`

Directory.Packages.props, eng/service-templates/ProductConstructionService/provision.bicep, src/ProductConstructionService/ProductConstructionService.Api/ProductConstructionService.Api.csproj, src/ProductConstructionService/ProductConstructionService.Api/Program.cs, src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json, src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json, src/ProductConstructionService/Readme.md
https://github.com/dotnet/arcade-services/issues/3163
Connects the Product Construction Service with it's environments Key Vault.
This allows us to use the secrets like `app.Configuration[<secret name>]`
In the staging environment, the service will authenticate using [Environmental Credentials](https://learn.microsoft.com/en-us/dotnet/api/azure.identity.environmentcredential?view=azure-dotnet). I created a new `app registration`, `product-construction-service-int`, gave it permissions to read secrets from ProductConstructionInt KV and put it's details in the Container App resource. The `DefaultAzureCredentails` will pick these up and connect to the vault. This is only a temporary solution tho, this approach isn't ideal because of two reasons:
- The App secret will expire and will require …
=> Enable the Product Construction Service to connect with KeyVaults

azure-pipelines-product-construction-service.yml, eng/deployment/product-construction-service-deploy.ps1
The deployment script wasn't properly handling all cases that the new revision could have been in. This should fix it. We will stay in the loop, until the revision is ready and `Running`, or it has `Failed`
https://github.com/dotnet/arcade-services/issues/3229
Fix Pcs deployment script
=> Pcs deployment fix

src/ProductConstructionService/ProductConstructionService.AppHost/Program.cs
Aspire workloads got updated and broke our CI. This PR comments out the code that's failing for us, until we have a permanent solution. Since this code is used only for local development, it won't affect our Staging env.
Don't include in release notes
=> Comment out the code that's breaking the CI

src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs
- see https://github.com/dotnet/arcade-services/issues/3258
- see also https://github.com/dotnet/arcade/issues/14445 (the main driving force)
- see also https://github.com/dotnet/dnceng/issues/1145
- parameter is no longer needed and may cause errors if used
=> Eliminate the `useServicingBuildPool` parameter to promotion pipeline

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCloakedFileScanner.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrScanner.cs
https://github.com/dotnet/arcade-services/issues/3282
This error happened because of the way we're building our git command.
We're going through the list of the cloaked filters, for example `src/arcade/**/*.dll` and appending them to the `git diff --names-only <zero commit sha>` command, so Git will only look for those files.
The config had default cloaked files, so this list was never empty.
The new VMR branch `main-ub` doesn't have any default cloaked files, so some repos are just running `git diff <zero commit sha>`, which is just displaying all of the files.
If a repo has no cloaked files, we should just skip scanning it
Don't run the VMR Cloaked File Scan on repos with no excluded files
=> Don't run the scan on repos with no filters

src/Microsoft.DotNet.Darc/Darc/Models/PopUps/SubscriptionPopUp.cs, test/Maestro.ScenarioTests/ScenarioTests_Subscriptions.cs
Fix for a bug introduced in https://github.com/dotnet/arcade-services/issues/3281 that is failing E2E tests
=> Fix `darc add-subscription` pop-up dialog values

src/Microsoft.DotNet.Darc/DarcLib/BarApiClient.cs, src/Microsoft.DotNet.Darc/DarcLib/HealthMetrics/SubscriptionHealthMetric.cs
Fixes an uncaught exception where an API used to return `null` before
https://github.com/dotnet/arcade-services/issues/3284
Fix `darc get-latest-build` when searching multiple channels
=> Fix `darc get-latest-build` when searching multiple channels

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrCodeflowTest.cs
We have decided to not flow packages for forward flow after all. I separated this removal into a dedicated PR because we might reconsider it in the future so it might be valuable to keep it as a separate commit.
https://github.com/dotnet/arcade-services/issues/3253
=> Do not flow packages in forward code flow

Directory.Packages.props, src/Microsoft.DotNet.Darc/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/ManifestHelper.cs, test/Microsoft.DotNet.DarcLib.Tests/Helpers/DarcManifestHelperTests.cs
https://github.com/dotnet/release/issues/820
Modify the gather-drop command to add the asset owner information to the manifest.json file generation.
=> Extend the manifest.json file generation to contain the asset owner information.

src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/BackflowOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/CodeFlowOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/ForwardFlowOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/CodeFlowCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/WorkBranchFactory.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrCodeflowTest.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
This will allow us to be able to control the name of the PR branch from Maestro.
Before we used to signal with branch name or `null` whether a new branch was created but now we return a boolean.
Made the VMR code flow branch name customizable
=> Allow code flow branch name customization

src/Microsoft.DotNet.Darc/DarcLib/Helpers/GitRepoUrlParser.cs, src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/SourceManifest.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrRepoVersionResolver.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
This PR adds a different way of executing the VMR code flow that is more suitable for using inside of PCS (the current APIs are used in `darc`).
The new API in `VmrForwardFlower` and `VmrBackFlower` also allows targeting a given branch of the VMR/repo that we want to synchronized to.
Eventually, the target branch of the subscription will be used there.
Later, we will use these new APIs as part of https://github.com/dotnet/arcade-services/issues/3316.
Tests will be added once we have an E2E flow in place.
=> Allow targeting a specific branch in VMR code flow

src/ProductConstructionService/ProductConstructionService.Api/Controllers/CodeFlowController.cs, src/ProductConstructionService/ProductConstructionService.Api/Controllers/StatusController.cs, src/ProductConstructionService/ProductConstructionService.Api/DatabaseConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/InitializationBackgroundService.cs, src/ProductConstructionService/ProductConstructionService.Api/InitializationHealthCheck.cs, src/ProductConstructionService/ProductConstructionService.Api/PcsConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/Program.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/JobConsumer.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/JobConsumerOptions.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/JobProcessors/CodeFlowJobProcessor.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/JobProcessors/IJobProcessor.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/JobProcessors/TextJobProcessor.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/JobScope.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/JobScopeManager.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/Jobs/CodeFlowJob.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/Jobs/Job.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/JobsProcessorState.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/QueueConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/TestController.cs, src/ProductConstructionService/ProductConstructionService.Api/VirtualMonoRepo/VmrConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json, src/ProductConstructionService/ProductConstructionService.Api/appsettings.json, test/ProductConstructionService.Api.Tests/JobScopeTests.cs, test/ProductConstructionService.Api.Tests/JobsProcessorScopeManagerTests.cs
https://github.com/dotnet/arcade-services/issues/3316
This PR adds a first meaningful background job for code flow. The job is not 100% functional but a stub only so far.
While doing so, I improved how PCS behaves locally + how the code is named:
- Less log noise from SQL, Queue client
- Increased verbosity for our code (`DarcLib`)
- Lowered queue read period for faster debugging
- Improved configuration - configuration keys are now unified in one class
- Renamed `JobProcessor` to `JobConsumer` to match `JobProducer`
- Renamed `JobRunner` to `JobProcessor` as it better reflects its function
=> Improve PCS configuration, add `CodeFlowJob`

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/Models/Manifest.cs, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs, test/Microsoft.DotNet.Maestro.Tasks.Tests/CreateMergedManifestBuildModelTests.cs, test/Microsoft.DotNet.Maestro.Tasks.Tests/ParseBuildManifestMetadataTests.cs
Issue: https://github.com/dotnet/arcade-services/issues/3308
Add `DotNetReleaseShipping` property to assets in MergedManifest.xml
=> Add property to MergedManifest for packages published as part of .NET

src/Maestro/SubscriptionActorService/BatchedPullRequestActorImplementation.cs, src/Maestro/SubscriptionActorService/NonBatchedPullRequestActorImplementation.cs, src/Maestro/SubscriptionActorService/PullRequestActor.cs
This is a preparation for https://github.com/dotnet/arcade-services/issues/3317.
No functional changes here, just moving code around to mostly reduce nesting.
Changes:
- Moved `BatchedPullRequestActorImplementation` and `NonBatchedPullRequestActorImplementation` classes out of the main file
- Reduced nesting and return early from some more complicated methods
- Re-order flow of methods to handle state gradually "no PR `->` no updates `->` update PR"
=> Refactor `PullRequestActor` a bit

test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrCodeflowTest.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
The `Version.Details.xml` file will be getting changes via code flow as well as Maestro updates. We are adding a test that makes sure that bumps of packages from different repos do not clash with each other.
https://github.com/dotnet/arcade-services/issues/3379
=> Add an E2E test for `Version.Details.xml` conflicts

src/Maestro/SubscriptionActorService/BatchedPullRequestActorImplementation.cs, src/Maestro/SubscriptionActorService/IPullRequestPolicyFailureNotifier.cs, src/Maestro/SubscriptionActorService/NonBatchedPullRequestActorImplementation.cs, src/Maestro/SubscriptionActorService/Properties/AssemblyInfo.cs, src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/Maestro/SubscriptionActorService/PullRequestDescriptionBuilder.cs, src/Maestro/SubscriptionActorService/PullRequestPolicyFailureNotifier.cs, src/Maestro/SubscriptionActorService/StateModel/ActorCollectionStateManager.cs, src/Maestro/SubscriptionActorService/StateModel/ActorStateManager.cs, src/Maestro/SubscriptionActorService/StateModel/InProgressPullRequest.cs, src/Maestro/SubscriptionActorService/StateModel/SubscriptionPullRequestUpdate.cs, src/Maestro/SubscriptionActorService/StateModel/SynchronizePullRequestResult.cs, src/Maestro/SubscriptionActorService/StateModel/UpdateAssetsParameters.cs, test/SubscriptionActorService.Tests/Properties/AssemblyInfo.cs, test/SubscriptionActorService.Tests/PullRequestActorTests.cs, test/SubscriptionActorService.Tests/PullRequestDescriptionBuilderTests.cs, test/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs
Every time we need to set Service Fabric reminders or read/store/remove stored state, we need to pass in the key. We could mess up the key/stored type combination so it's a bit error prone. Together with the fact that I will be adding more state, I decided to encapsulate the state access and bind the key once at the initialization.
I also moved the state model classes in a separate folder.
This is a preparation for https://github.com/dotnet/arcade-services/issues/3317.
No functional changes here.
=> Make working with SF state more safe

src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
This PR improves a workaround for problems described in #3277. The problem is that with a weird mix of conditions under which files were created and which git config EOL settings were set, files are left behind dirty in the working tree with no chance of discarding the changes. Not even hard reset works. This just commits them in another way.
This PR doesn't solve https://github.com/dotnet/arcade-services/issues/3277 entirely but unblocks the synchronization with a (possibly unsafe) operation so that installer PR unified build legs get working again (https://github.com/dotnet/installer/pull/18917)
Fixes a problem with EOLs during VMR synchronization on Windows
=> Improve workaround for EOL problems on Windows

src/Microsoft.DotNet.Darc/DarcLib/Helpers/ManifestHelper.cs
Propagating `DotNetReleaseShipping` from `MergedManifest.xml` to assets in `manifest.json`
Issue: https://github.com/dotnet/release/issues/740
Set `DotNetReleaseShipping` property in `manifest.json` in gather-drop
=> Set `DotNetReleaseShipping` property in `manifest.json`

test/SubscriptionActorService.Tests/PendingUpdatesTests.cs, test/SubscriptionActorService.Tests/PullRequestActorTests.cs, test/SubscriptionActorService.Tests/UpdateAssetsTests.cs
This PR only splits tests into their own files as the 1000+ line file is hard to navigate through.
We will be adding many new tests so this is just a preparation for that.
=> Split Actor tests to seprate files

azure-pipelines-pr.yml, azure-pipelines.yml, eng/templates/stages/deploy.yaml, eng/templates/stages/secret-validation.yml, eng/templates/steps/build.yml, eng/templates/steps/generate-sbom.yml
Contributes to https://github.com/dotnet/arcade-services/issues/3396
Migrates the AzDO YAML we use to 1ES-compatible logic. 
Example build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2403332&view=results
The build contains several warnings that are expected to be there until this PR hits `main` and gets mirrored internally. This is related to the [baseline](https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1es/1es-docs/1es-pipeline-templates/features/sdlanalysis/autobaselining) for issues that 1ES PT introduces.
The extra work needed to resolve the warnings and the baseline is described in https://github.com/dotnet/arcade-services/issues/3396#issuecomment-1997184304
- split the pipeline into two based on trigger / purpose:
- `azure-pipelines.yml` - …
=> Migrate to 1es-compatible pipeline

src/Maestro/SubscriptionActorService/PullRequestActor.cs
Fixing a bug introduced in https://github.com/dotnet/arcade-services/issues/3381
Fixed a problem where PRs older than March 13th were not able to update anymore
=> Forget the PR state when deserialization fails

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
We do not restore files one by one but rather reverse-apply the patch
https://github.com/dotnet/arcade-services/issues/3410
Fixed VMR synchronization for cases with VMR patches with renames inside
=> Fixes VMR synchronization for cases with VMR patches with renames inside

src/ProductConstructionService/ProductConstructionService.Api/Configuration/PcsConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/Program.cs, test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
In a previous PR I introduced a bug that attempted to read a secret before initializing secrets from the KV. This PR fixes it
https://github.com/dotnet/arcade-services/issues/3435
Read BAR connection string secret after connecting to the KV
=> Read BAR connection string secret after connecting to the KV

eng/templates/stages/deploy.yaml, test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs, test/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs
Adds coverage for a recent bug https://github.com/dotnet/arcade-services/issues/3382
Sample PR created by the test: https://dev.azure.com/dnceng/internal/_git/maestro-test2/pullrequest/38602
=> Add an AzDO version for the `ArcadeSdkUpdate` E2E test

Directory.Packages.props, src/ProductConstructionService/ProductConstructionService.Api/Configuration/PcsConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/Program.cs, src/ProductConstructionService/ProductConstructionService.AppHost/Program.cs, test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
https://github.com/dotnet/dnceng/issues/1797
https://github.com/dotnet/dnceng/issues/1917
Bump aspire version to preview 4, only use swagger when running locally
=> Only use swagger when running locally, bump aspire version

src/Maestro/Client/src/Generated/Models/Subscription.cs, src/Maestro/Client/src/Generated/Models/SubscriptionData.cs, src/Maestro/Client/src/Generated/Models/SubscriptionUpdate.cs, src/Maestro/Client/src/Generated/Subscriptions.cs, src/Maestro/Maestro.Data/Migrations/20240403133733_CodeEnabledSubscriptions3.Designer.cs, src/Maestro/Maestro.Data/Migrations/20240403133733_CodeEnabledSubscriptions3.cs, src/Maestro/Maestro.Data/Models/Subscription.cs, src/Maestro/Maestro.DataProviders/SqlBarClient.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/SubscriptionsController.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Models/Subscription.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Models/SubscriptionData.cs, src/Maestro/Maestro.Web/Api/v2020_02_20/Models/SubscriptionUpdate.cs, src/Microsoft.DotNet.Darc/Darc/Helpers/UxHelpers.cs, src/Microsoft.DotNet.Darc/Darc/Models/PopUps/AddSubscriptionPopUp.cs, src/Microsoft.DotNet.Darc/Darc/Models/PopUps/SubscriptionPopUp.cs, src/Microsoft.DotNet.Darc/Darc/Models/PopUps/UpdateSubscriptionPopUp.cs, src/Microsoft.DotNet.Darc/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/UpdateSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/SubscriptionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/SubscriptionsCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/BarApiClient.cs, src/Microsoft.DotNet.Darc/DarcLib/IBarApiClient.cs, src/ProductConstructionService/ProductConstructionService.Api/Queue/JobProcessors/CodeFlowJobProcessor.cs, test/Maestro.ScenarioTests/ObjectHelpers/SubscriptionBuilder.cs, test/Microsoft.DotNet.Darc.Tests/Operations/GetBuildOperationTests.cs, test/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_json.verified.txt, test/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_sorted_text.verified.txt, test/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.cs, test/Microsoft.DotNet.DarcLib.Tests/Models/Darc/DependencyFlowNodeTests.cs, test/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs
- Adds the DB column
- Adds the field to API controllers
- Regenerates the API C# client
- Extends the `darc` commands/pop-ups with this new field
https://github.com/dotnet/arcade-services/issues/3368
Added `TargetDirectory` field to subscriptions
=> Add `TargetDirectory` field to subscriptions

Directory.Packages.props, src/Maestro/Client/src/Microsoft.DotNet.Maestro.Client.csproj
This allows for easier upgrading of the client library in downlevel versions of Arcade which may not be targeting net6+
https://github.com/dotnet/arcade-services/issues/3485
Target netstandrd in Maestro client libs.
=> Allow the Maestro client to target netstandard

src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/SubscriptionsController.cs
https://github.com/dotnet/arcade-services/issues/3540
The difference between the cli interface and the popup interface is that when you set sourceEnabled to False in the popUp interface, both SourceDirectory and TargetDirectory are set to null [arcade-services/src/Microsoft.DotNet.Darc/Darc/Models/PopUps/SubscriptionPopUp.cs at main · dotnet/arcade-services (github.com)](https://github.com/dotnet/arcade-services/blob/main/src/Microsoft.DotNet.Darc/Darc/Models/PopUps/SubscriptionPopUp.cs#L182C1-L187C10)
Then, in [arcade-services/src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/SubscriptionsController.cs at main · dotnet/arcade-services (github.com)](https://github.com/dotnet/arcade-services/blob/main/src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/SubscriptionsController.cs#L222C1-L2 …
=> Fixed a bug that prevents customers from updating the Source-enabled parameter on the subscription level

src/Maestro/Client/src/MaestroApi.cs, src/Maestro/Client/src/MaestroApiCredential.cs, src/Maestro/Client/src/MaestroApiFactory.cs, src/Maestro/Client/src/MaestroApiOptions.cs, src/Maestro/Client/src/MaestroApiTokenCredential.cs, src/Maestro/Client/src/Microsoft.DotNet.Maestro.Client.csproj, src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs, src/Maestro/SubscriptionActorService/Program.cs, src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs, src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs, src/Microsoft.DotNet.Darc/Darc/Models/PopUps/AuthenticateEditorPopUp.cs, src/Microsoft.DotNet.Darc/Darc/Operations/AuthenticateOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/ICommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/BarApiClient.cs, src/Microsoft.DotNet.Darc/DarcLib/IBarApiClient.cs, src/Microsoft.DotNet.Darc/DarcLib/ILocalLibGit2Client.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalLibGit2Client.cs, src/ProductConstructionService/ProductConstructionService.Api/Configuration/PcsConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/Program.cs, src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json, src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json, test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs, test/Maestro.ScenarioTests/TestParameters.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs, test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
This makes the `-p` argument optional.
- If provided, will use it in the auth header
- If omitted, will try to authenticate using the browser auth flow using the `InteractiveBrowserCredential`
- If omitted and `--disable-interactive-auth` argument provided, will use `AzureCliCredential`
https://github.com/dotnet/dnceng/issues/2694
`darc` does not require BAR password anymore and support interactive sign-in
=> Make `darc` work without a BAR token

src/Maestro/Client/src/MaestroApiOptions.cs
The credential needs to recieve the `null` token instead and decide based on that. Otherwise it would act as an anonymous (no-credential) API client.
=> Fix Maestro API credential factory

src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs, src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs, src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrCommandLineOptionsBase.cs
Fixes a bug introduced in https://github.com/dotnet/arcade-services/issues/3561 where we no longer use the PATs provided in arguments if no local darc settings file was found.
=> Fix PAT initialization when no local dark settings

src/Maestro/Client/src/MaestroApi.cs, src/Maestro/Client/src/MaestroApiCredential.cs, src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs
Fixing "key not found" when using the old URIs
=> [Hotfix] Make new darc auth work with old URIs

test/Maestro.ScenarioTests/ScenarioTests_Builds.cs, test/Maestro.ScenarioTests/ScenarioTests_Channels.cs, test/Maestro.ScenarioTests/ScenarioTests_DefaultChannels.cs, test/Maestro.ScenarioTests/ScenarioTests_Dependencies.cs, test/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs, test/Maestro.ScenarioTests/ScenarioTests_MergePolicies.cs, test/Maestro.ScenarioTests/ScenarioTests_RepoPolicies.cs, test/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs, test/Maestro.ScenarioTests/ScenarioTests_Subscriptions.cs
Let's try speeding up the E2E tests. Some tests are already marked as non-parallelizable
=> Run E2E scenario tests in parallel

src/Microsoft.DotNet.Darc/Darc/Operations/GetBuildOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/GetBuildCommandLineOptions.cs
Our infra relies on custom HTTP calls to Maestro API which provides this information but `darc` only offers a slice of that. This PR makes it possible to print everything.
We will need this for https://dev.azure.com/dnceng/internal/_workitems/edit/6478
Allowed printing full build info in `darc get-build`
=> Enable printing full build info in `darc get-build`

eng/templates/stages/deploy.yaml, test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
In https://github.com/dotnet/arcade-services/issues/3595, we made teste parallizable but they still don't run in parallel
=> Make test fixtures run in parallel

test/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs
In https://github.com/dotnet/arcade-services/issues/3595, we made teste parallizable and this test started to fail.
=> Make test `ArcadeSdkUpdate` non-parallizable

src/Maestro/SubscriptionActorService/PullRequestPolicyFailureNotifier.cs
As reported in https://github.com/dotnet/arcade-services/issues/3601, multiple comments get posted when a build check fails.
This happens because a bug within the GitHub Octokit library cannot parse the ID of the created comment and we never note down that we have created the comment.
Fixed a problem were Maestro kept notifying repo owners about a failed check
=> Fix multiple PR notifications getting posted to PRs

src/Maestro/SubscriptionActorService/Program.cs, src/ProductConstructionService/ProductConstructionService.Client/PcsApiCredential.cs, src/ProductConstructionService/ProductConstructionService.Client/PcsApiFactory.cs, src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionService.Client.csproj, src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionServiceApi.cs, src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionServiceApiOptions.cs
https://dev.azure.com/dnceng/internal/_workitems/edit/6423
PCS client can now use Azure credentials for auth
=> Add credential support to PCS API client

Directory.Packages.props, src/Maestro/SubscriptionActorService/PullRequestPolicyFailureNotifier.cs
Fixes https://github.com/dotnet/arcade-services/issues/3601
Updated the Octokit library to resolve some int overflow issues in GitHub REST API
=> Bump Octokit to 12.0 to fix int overflows

src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs
This fixes a problem where people's old local settings had the old name serialized.
Fixed a problem where `darc` forgot the BAR password
=> Support old BAR password in local settings

.github/pull_request_template.md, eng/enforce-issue.ps1
We will use the GitHub release notes (https://github.com/dotnet/arcade-services/issues/3633)
=> Stop requiring rollout notes in PRs

src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs, src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs, src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/Operation.cs, src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/ICommandLineOptions.cs
Fixes a bug when an AzDO PAT was not used from local settings.
The problem were commands that were more DI-based (we still have half and half unfortunately) and the DI didn't know about the local settings, only the PATs from the options directly.
We now stop reading the local settings in many places and let the options object initialize from there.
=> Make local darc settings available in DI

src/Maestro/Client/src/MaestroApiOptions.cs, src/Maestro/DependencyUpdater/.config/settings.Staging.json, src/Maestro/DependencyUpdater/.config/settings.json, src/Maestro/DependencyUpdater/Program.cs, src/Maestro/FeedCleanerService/.config/settings.Staging.json, src/Maestro/FeedCleanerService/.config/settings.json, src/Maestro/FeedCleanerService/Program.cs, src/Maestro/Maestro.Common/AppCredentials/AppCredentialResolver.cs, src/Maestro/Maestro.Common/AppCredentials/AppCredentialResolverOptions.cs, src/Maestro/Maestro.Common/AppCredentials/CredentialResolverOptions.cs, src/Maestro/Maestro.Common/AzureDevOpsTokens/AzureDevOpsTokenProvider.cs, src/Maestro/Maestro.Common/AzureDevOpsTokens/AzureDevOpsTokenProviderOptions.cs, src/Maestro/Maestro.Web/.config/settings.Staging.json, src/Maestro/Maestro.Web/.config/settings.json, src/Maestro/Maestro.Web/Startup.cs, src/Maestro/SubscriptionActorService/.config/settings.json, src/Maestro/SubscriptionActorService/Program.cs, src/ProductConstructionService/ProductConstructionService.Client/ProductConstructionServiceApiOptions.cs
This PR makes the Maestro cluster use its system-assigned managed identity for AzureDevOps communication.
It does not affect `darc` or `PCS` where `RemoteConfiguration` is still used.
https://dev.azure.com/dnceng/internal/_workitems/edit/6419
=> Remove AzDO tokens from Maestro

src/Maestro/DependencyUpdater/.config/settings.Development.json, src/Maestro/DependencyUpdater/.config/settings.Production.json, src/Maestro/DependencyUpdater/.config/settings.json, src/Maestro/FeedCleanerService/.config/settings.Development.json, src/Maestro/FeedCleanerService/.config/settings.Production.json, src/Maestro/FeedCleanerService/.config/settings.json, src/Maestro/Maestro.Web/.config/settings.Development.json, src/Maestro/Maestro.Web/.config/settings.Production.json, src/Maestro/Maestro.Web/.config/settings.json, src/Maestro/SubscriptionActorService/.config/settings.Development.json, src/Maestro/SubscriptionActorService/.config/settings.Production.json, src/Maestro/SubscriptionActorService/.config/settings.Staging.json, src/Maestro/SubscriptionActorService/.config/settings.json
The previous change https://github.com/dotnet/arcade-services/issues/3662 didn't take it because the settings layers merge together. So when `settings.json` had the `Tokens` defined, all other layers inherited this. We only want this in staging, so we need to define it in the env levels and not in `settings.json`.
=> Use MIs in staging Maestro instead of AzDO tokens

eng/templates/stages/deploy.yaml
The builds are failing because the variable group was removed. However our secret validation is green
=> Stop using a deleted variable group

src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrPatchAddedTest.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncRepoChangesTest.cs
Fixes a problem found in https://github.com/dotnet/sdk/issues/41793. The problem is that if SDK is the root repo where VMR patches are stored, and SDK gets pulled into the VMR, we must restore the previous versions of those VMR patches in the SDK before the new SDK changes were merged into the VMR.
This manifests in us trying to restore VMR patches that will only be added during the sync later.
The new code stops evaluating which VMR patches must be removed and strips all VMR patches always and then returns all back. So this simplifies the code a bit.
=> Restore and re-apply all VMR patches always

src/Maestro/Maestro.Web/Startup.cs
We see exceptions like these:
> Specified argument was out of the range of valid values. (Parameter 'Azure DevOps account dnceng does not have a configured PAT or credential. Please add the account to the 'AzureDevOps.Tokens' or 'AzureDevOps.ManagedIdentities' configuration
Possibly introduced here:
https://github.com/dotnet/arcade-services/issues/3673
=> Fix binding of AzDO configuration

src/Microsoft.DotNet.Darc/Darc/Operations/Operation.cs
Resolves https://github.com/dotnet/arcade-services/issues/3718
Found by https://dev.azure.com/dnceng/internal/_build/results?buildId=2492728&view=results
DI is complaining about:
```
System.InvalidOperationException: Unable to activate type 'Microsoft.DotNet.DarcLib.AzureDevOpsClient'. The following constructors are ambiguous:
Void .ctor(Maestro.Common.AzureDevOpsTokens.IAzureDevOpsTokenProvider, Microsoft.DotNet.DarcLib.Helpers.IProcessManager, Microsoft.Extensions.Logging.ILogger`1[Microsoft.DotNet.DarcLib.AzureDevOpsClient])
Void .ctor(Maestro.Common.AzureDevOpsTokens.IAzureDevOpsTokenProvider, Microsoft.DotNet.DarcLib.Helpers.IProcessManager, Microsoft.Extensions.Logging.ILogger)
```
I couldn't find a way to remove one of the constructors and not break one of the services or Darc, so …
=> Fixup AzDO client construction in DI

eng/templates/stages/deploy.yaml
When we're trying to test `add-build-to-channel` we need to use the Prod Maestro, since that's where the 'General Testing' channel is, and where the build gets published
https://github.com/dotnet/arcade-services/issues/3724
=> Use prod darc to validate darc

src/Microsoft.DotNet.Darc/Darc/Operations/Operation.cs
https://github.com/dotnet/dnceng/issues/3470
In my previous PR I did the registration wrong, this fixes it
=> Initialize IRemoteProvider when it's needed, not during DI registration

src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/InitializeOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrSyncCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CredScanSuppressionsGenerator.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrUpdater.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInfo.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrRegistrations.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncRepoChangesTest.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
Almost all of the entries in .gdnbaselines in the VMR are from CredScan and we already have suppression files in the individual repos so we can hydrate a common one, similar to what we do for CODEOWNERs.
Helps with https://github.com/dotnet/source-build/issues/4259
=> Add option to generate common CredScan suppression file for VMR sync

eng/templates/stages/deploy.yaml
Fixes https://dev.azure.com/dnceng/internal/_build/results?buildId=2498289&view=logs&j=4d9f00d7-d155-5977-7b70-2e6b79720ff2&t=c5fa51d8-f4b1-5178-14fd-2c49e5155c0d
Probably it was using the global .NET?
=> Use the right .NET installation in E2E tests

src/Maestro/SubscriptionActorService/PullRequestActor.cs
Possibly a fix for https://github.com/dotnet/arcade-services/issues/3232 and https://github.com/dotnet/arcade-services/issues/3642 where Maestro pushes empty commits into PRs such as this: https://dev.azure.com/dnceng/internal/_git/dotnet-helix-service/pullrequest/40767?_a=commits
=> Fix Maestro pushing empty commits to PRs

src/Maestro/DependencyUpdater/.config/settings.Development.json, src/Maestro/FeedCleanerService/.config/settings.Development.json, src/Maestro/Maestro.Common/AppCredentials/CredentialResolverOptions.cs, src/Maestro/Maestro.Common/AzureDevOpsTokens/AzureDevOpsTokenProvider.cs, src/Maestro/Maestro.Common/Maestro.Common.csproj, src/Maestro/Maestro.Web/.config/settings.Development.json, src/Maestro/SubscriptionActorService/.config/settings.Development.json
Resolves https://dev.azure.com/dnceng/internal/_workitems/edit/6699/
In draft state as it depends on https://github.com/dotnet/dnceng-shared/pull/82
Re-uses `LocalDevTokenCredential` to fetch AzDO token in Maestro local development. This class is used by the [bootstrap script](https://github.com/dotnet/arcade-services/blob/main/src/Maestro/bootstrap.ps1) to obtain and cache login information of the developer's user. When use by Maestro, it reads the saved login information and uses it to obtain the token it needs for AzDO through its Azure app (the same way it does for other auth flows).
Since the information we need is already stored by the` LocalDevTokenCredential`, we don't need to change the bootstrap script in any way
=> Use local creds for maestro local development

Directory.Packages.props
Resolves https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade-services/alert/10013733?typeId=6567134
=> Bump `Azure.Core` to `1.41.0`

docs/DevGuide.md, src/Maestro/Maestro.Web/Pages/Index.cshtml.cs, src/Maestro/Maestro.Web/Program.cs, src/Maestro/Maestro.Web/Properties/launchSettings.json, src/Maestro/Maestro.Web/Startup.cs
This fixes some problems with static files and local usage of HTTPs so that it's possible to run the `Maestro.Web` project directly without needing to run Service Fabric. This can be used to develop the frontend web app (Angular..).
=> Fix running `Maestro.Web` locally (outside of SF)

.vault-config/maestrolocal.yaml, .vault-config/shared/maestro-secrets.yaml, src/Maestro/Maestro.Authentication/AuthenticationConfiguration.cs, src/Maestro/Maestro.Web/.config/settings.Development.json, src/Maestro/Maestro.Web/.config/settings.Production.json, src/Maestro/Maestro.Web/.config/settings.Staging.json, src/Maestro/Maestro.Web/Startup.cs
Right now, redirection from local/INT to prod so that we can show prod data in the BarViz portal is using a BAR token too.
This PR switches to using the Maestro credential (so MI in a service and local credentials for local development).
The redirection was actually broken and this PR fixes it too. It also kills another boolean flag `ForceLocalApi` that was used for local development.
https://dev.azure.com/dnceng/internal/_workitems/edit/6740
=> Use Entra auth during API redirection

test/Maestro.ScenarioTests/EndToEndFlowLogic.cs
We were creating a second build but never assigning it to a channel, so when we triggered the subscription, there was nothing to update with
https://github.com/dotnet/arcade-services/issues/3786
=> Add second build to channel before triggering the subscription

azure-pipelines.yml, eng/templates/stages/deploy.yaml
Contributes to https://dev.azure.com/dnceng/internal/_workitems/edit/6604/
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2511524&view=results
Changes:
- instead of using the client ID of the service principal from the service connection the tests now use the Maestro app client ID from a variable group
- moved template parameters for `deploy.yaml` to variables in the stages they are used
Should be merge right after we stich the client IDs in the service connections for Darc
=> Update maestro token for e2e tests

src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
https://github.com/dotnet/arcade-services/issues/3844
this PR makes it so we use the same logic as in the `darc add-build-to-channel` command when determining the default channels of a build
=> Use same logic as add-build-to-channel when checking default channels

Directory.Packages.props, eng/service-templates/ProductConstructionService/provision.bicep, src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs, src/ProductConstructionService/ProductConstructionService.Api/ProductConstructionService.Api.csproj, src/ProductConstructionService/ProductConstructionService.Api/Program.cs, src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json, src/ProductConstructionService/ProductConstructionService.AppHost/ProductConstructionService.AppHost.csproj, src/ProductConstructionService/ProductConstructionService.AppHost/Program.cs, src/ProductConstructionService/ProductConstructionService.Common/ConfigurationKeys.cs, src/ProductConstructionService/ProductConstructionService.Common/ProductConstructionService.Common.csproj, src/ProductConstructionService/ProductConstructionService.Common/ProductConstructionServiceExtension.cs, test/ProductConstructionService.Api.Tests/DependencyRegistrationTests.cs
Contributes to https://github.com/dotnet/arcade-services/issues/3805
Adds a Redis client to PCS for future use.
<details>
<summary>Example usage</summary>
```csharp
public class RedisController : Controller
{
private readonly IDatabase _cache;
public RedisController (IConnectionMultiplexer redis)
{
_cache = redis.GetDatabase();
}
[HttpPost("key")]
public async Task SetCacheKey([FromBody, Required] CacheKey cacheKey)
{
await _cache.StringSetAsync(cacheKey.Key, cacheKey.Value);
}
[HttpGet("key/{key}")]
public async Task<string> GetCacheKey(string key)
{
var value = await _cache.StringGetAsync(key);
return value.ToString();
}
}
```
</details>
=> Add Redis cache

src/Maestro/Maestro.Web/Pages/DependencyFlow/Incoming.cshtml.cs
Fixes https://github.com/dotnet/arcade-services/issues/3795
Thanks for the test seed data @premun. I was able to use that to verify this fixes the NRE we were seeing. The BuildChannel seed data points to builds containing fake branches and commits explaining the "(unknown)" output, but it looks like we're calling the GitHub APIs correctly, so I think it will work with real data.
=> Fix NRE in DependencyFlow's Incoming.cshtml.cs

.vault-config/maestrolocal.yaml, .vault-config/shared/maestro-secrets.yaml, eng/templates/jobs/e2e-tests.yml, eng/templates/stages/deploy.yaml
Contributes to https://dev.azure.com/dnceng/internal/_workitems/edit/6594/
Replaces AzDO PAT from a key vault with an MI token retrieved before the test run
Passing build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2524160&view=results
=> Remove AzDO PAT from CI tests

azure-pipelines-product-construction-service.yml, eng/deployment/product-construction-service-deploy.ps1
Example: https://dev.azure.com/dnceng/internal/_build/results?buildId=2525411&view=logs&j=4032b39f-a33d-55dd-373e-29d781cedb05&t=580fbd09-8e6b-5a54-4d1f-785b8aacd3d3&l=116
=> Print direct link to revision logs when deployment fails

src/ProductConstructionService/ProductConstructionService.Api/Configuration/GitHubClientFactoryConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/Configuration/KeyVaultSecretsWithPrefix.cs, src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs, src/ProductConstructionService/ProductConstructionService.Api/appsettings.json
Previously, the secrets would go to the top-level section of the config, potentially overriding configuration there
=> Load KV secrets into a dedicated config section

Directory.Packages.props
> ##[error].dotnet\packs\Aspire.Hosting.Sdk\8.2.0\Sdk\Sdk.targets(79,5): error : (NETCORE_ENGINEERING_TELEMETRY=Restore) ProductConstructionService.AppHost is a .NET Aspire AppHost project that needs a package reference to Aspire.Hosting.AppHost version 8.2.0 or above to work correctly. You are using version 8.1.0.
[[build]](https://dev.azure.com/dnceng/internal/_build/results?buildId=2526902&view=logs&j=bb592630-4b9d-53ad-3960-d954a70a95cf&t=6acf3fd6-22e8-5cce-cc91-f1b299977c9d&l=46)
=> Update Aspire to 8.2.0

src/Maestro/Maestro.Web/Pages/DependencyFlow/Incoming.cshtml.cs
@premun I was able to modify the seed data to point to some real commits and demonstrate that it can indeed pick up out-of-date dependencies. I only bothered updating the seed data for the meastro-test1 dependency, but I think it's sufficient to prove the fix works.
Fixes https://github.com/dotnet/arcade-services/issues/3898
=> Use BuildDependency.DependentBuildId over BuildId in Incoming.cshtml.cs

src/ProductConstructionService/ProductConstructionService.FeedCleaner/ProductConstructionService.FeedCleaner.csproj, src/ProductConstructionService/ProductConstructionService.LongestBuildPathUpdater/ProductConstructionService.LongestBuildPathUpdater.csproj, src/ProductConstructionService/ProductConstructionService.SubscriptionTriggerer/ProductConstructionService.SubscriptionTriggerer.csproj
One more thing to make the PCS jobs run well. Alternatively, we'd have to install globalization support into the docker images
https://github.com/dotnet/arcade-services/issues/3806
=> Disable invariant globalization in PCS jobs

src/ProductConstructionService/ProductConstructionService.SubscriptionTriggerer/appsettings.Staging.json
Before we renamed the service to SubscriptionTriggerer, I created a different MI and put the MI ID. When I recreated the identity with a new name, I didn't change the ID.
This is the correct MI https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/e6b5f9f5-0ca4-4351-879b-014d78400ec2/resourceGroups/product-construction-service/providers/Microsoft.ManagedIdentity/userAssignedIdentities/SubscriptionTriggererInt/overview
https://github.com/dotnet/arcade-services/issues/3916
=> Put the correct MI ID for Sub triggerer

src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/HttpRequestManager.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
Clears the log from errors which are not real errors (checking if branch exists kinda expects 404 if we believe the branch should not be there). This will help debugging.
Also fixes some build messages around logging.
https://github.com/dotnet/arcade-services/issues/3807
=> Do not log errors for expected cases

src/ProductConstructionService/ProductConstructionService.Api/appsettings.Development.json, src/ProductConstructionService/Readme.md, test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs, test/ProductConstructionService.ScenarioTests/ProductConstructionService.ScenarioTests.csproj, test/ProductConstructionService.ScenarioTests/TestParameters.cs
- Uses local credentials to obtain PCS and AzDO tokens
- Adds instructions on how to run the PCS scenario tests locally
https://github.com/dotnet/arcade-services/issues/3837
=> Improve dev UX when running PCS scenario tests + docs

src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs, src/ProductConstructionService/ProductConstructionService.Api/VirtualMonoRepo/VmrConfiguration.cs
PCS will no longer depend on this secret. It will clone the real VMR using the GitHub app
=> Do not use GitHub PAT in VMR initialization

docs/DevGuide.md, src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs, src/ProductConstructionService/Readme.md, test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs, test/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs, test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests_SdkUpdate.cs
They were using real Arcade and the local dev Maestro app doesn't have access to it so these were never green even in old Maestro.
Also made the test check for PRs every 30 seconds instead of a minute to speed things up.
=> Make E2E Arcade tests use maestro-auth-test arcade

src/Microsoft.DotNet.Darc/Darc/Operations/SetRepositoryMergePoliciesOperation.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests_RepoPolicies.cs
The way it's set up, if the repo never had any policies, it won't be able to get one (unless you trigger a subscription over the repo at least once). We're not actually querying repositories in the check but a repository branches instead.
=> Fix repo merge policies E2E test

src/ProductConstructionService/ProductConstructionService.Common/RedisCache.cs
This is so that our cache just doesn't grow indefinitely. 90 days should be enough to complete a PR but it should be fine for Maestro to forget about it after that.
https://github.com/dotnet/arcade-services/issues/3805
=> Add default expiration to all cache entries

eng/service-templates/ProductConstructionService/provision.bicep, eng/service-templates/ProductConstructionService/scheduledContainerJob.bicep
We used to call Container Jobs dlls from the Api folder. Because of this, the jobs would take appsettings.json from the Api folder, which caused issues. This fixes things so that we go to the Container Job first, and then execute it.
https://github.com/dotnet/arcade-services/issues/3916
=> Fix how were calling container jobs

src/ProductConstructionService/ProductConstructionService.Common/RedisCache.cs
Getting while deleting is not supported until Redis 6.2 while Azure only has 6.0
=> Do not use Get/Delete in Redis

src/ProductConstructionService/ProductConstructionService.Common/MetricRecorder.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItem.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemConsumer.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemProducer.cs
There was a serialization problem - serializing `TimeSpan` and deserializing `int`
https://github.com/dotnet/arcade-services/issues/3933
=> Fix measuring the queue wait time delay

eng/deployment/product-construction-service-deploy.ps1, src/ProductConstructionService/ProductConstructionService.Api/Controllers/StatusController.cs, src/ProductConstructionService/ProductConstructionService.Client/Generated/ProductConstructionServiceApi.cs, src/ProductConstructionService/ProductConstructionService.Client/Generated/Status.cs
Will allow https://github.com/dotnet/arcade-services/issues/3938 to change service status from C#
=> Version the status endpoint and include it in the C# client

src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs
Consider skipped checks as meeting Maestro policy
=> Consider skipped checks as meeting Maestro policy

.config/dotnet-tools.json, eng/Version.Details.xml, eng/Versions.props, eng/deployment/product-construction-service-deploy.ps1, global.json, src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs, src/ProductConstructionService/ProductConstructionService.Api/Controllers/StatusController.cs, src/ProductConstructionService/ProductConstructionService.Client/Generated/ProductConstructionServiceApi.cs, src/ProductConstructionService/ProductConstructionService.Client/Generated/Status.cs, src/ProductConstructionService/ProductConstructionService.Common/MetricRecorder.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItem.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemConsumer.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemProducer.cs, test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
Rollout issue: https://github.com/dotnet/arcade-services/issues/3971
=> [Rollout] Production rollout 2024-09-19

src/Maestro/Maestro.Authentication/AuthenticationConfiguration.cs, src/Maestro/Maestro.Web/Pages/Account/AccountController.cs, src/Maestro/Maestro.Web/Pages/Error.cshtml, src/Maestro/Maestro.Web/Pages/Error.cshtml.cs, src/Maestro/Maestro.Web/Startup.cs, src/ProductConstructionService/ProductConstructionService.Api/Controllers/AccountController.cs, src/ProductConstructionService/ProductConstructionService.Api/Pages/Error.cshtml, src/ProductConstructionService/ProductConstructionService.Api/Pages/Error.cshtml.cs, src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
Unlike the previous "dependency flow" pages which as of now are still hosted at https://dependencyflow.azurewebsites.net/ ([example](https://dependencyflow.azurewebsites.net/incoming/3883/dotnet/aspnetcore)), the same page on https://maestro.dot.net/DependencyFlow ([example](https://maestro.dot.net/DependencyFlow/incoming/3883/dotnet/aspnetcore)) cannot be rendered inside an iframe due to the `X-Frame-Options: Deny` response header and the `SameSite=Lax` cookies (as opposed to `SameSite=None`).
Fixes https://github.com/dotnet/arcade-services/issues/4004
Thanks again for all the help on this @premun!
=> Support DependencyFlow in AzDO dasboard iframe

src/Maestro/Maestro.Data/Models/Build.cs, src/ProductConstructionService/ProductConstructionService.Common/RedisMutex.cs, src/ProductConstructionService/ProductConstructionService.Common/Utility.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/BatchedPullRequestUpdater.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/DependencyFlowConfiguration.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/IPullRequestUpdater.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/SubscriptionTriggerer.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/WorkItemProcessors/BuildCoherencyInfoProcessor.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/WorkItemProcessors/PullRequestCheckProcessor.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/WorkItemProcessors/SubscriptionUpdateProcessor.cs, src/ProductConstructionService/ProductConstructionService.Deployment/Deployer.cs, test/ProductConstructionService.DependencyFlow.Tests/SubscriptionUpdaterTests.cs
Maestro Actors each have individual queues, and they process things one at a time. Because of this, calling trigger subscription twice fast doesn't create two PRs, the first item gets processed and then the second one sees the PR is already up and does nothing.
In PCS we now have multiple replicas working in parallel, all taking items from one queue. Because of this, we need to have some synchronization. 
https://github.com/dotnet/arcade-services/issues/3937
=> Add Redis Mutex to all classes that are converted Maestro Actors

src/ProductConstructionService/ProductConstructionService.DependencyFlow/WorkItemProcessors/PullRequestCheckProcessor.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/ReminderManager.cs, test/ProductConstructionService.DependencyFlow.Tests/MockReminderManager.cs
Fixes 2 problems:
1. When we receive a reminder from queue, we wanted to clear the cache but we also try to remove the queue message too which ends up throwing because message is not in the queue anymore.
2. When we try to unset a reminder, it might have just been processed and the message also won't be in the queue.
=> Clear reminders from cache upon receiving

src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/BackflowOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/CodeFlowOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/ForwardFlowOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/CodeFlowCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/ILocalGitRepo.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitRepo.cs
Dusting off some code that has never been exercised and making the VMR codeflow darc commands work again.
Right now, these commands will be just for testing purposes only but we want them working for our own purpose.
https://github.com/dotnet/arcade-services/issues/2995
=> Fix `darc vmr forwardflow/backflow` commands

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CloneManager.cs
Fixes https://github.com/dotnet/arcade-services/issues/4006
=> Re-clone a repo if dir is not a git repo

src/Maestro/SubscriptionActorService/PullRequestActor.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/Maestro.ScenarioTests/MaestroScenarioTestBase.cs, test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
Resolves https://github.com/dotnet/arcade-services/issues/3944
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2563944&view=results
=> Fixup dependency update from commit in PR description

.vault-config/maestroprod.yaml, .vault-config/product-construction-dev.yaml, .vault-config/product-construction-prod.yaml, .vault-config/vmr-synchronization.1.yaml
https://github.com/dotnet/dnceng/issues/4141
We don't want to rotate this PAT by mistake because the same PAT is in another KeyVault used by Arcade infra. We agreed we will use a different one in this repo anyway.
=> Stop tracking GitHub bot PAT in secret manifests

.vault-config/product-construction-prod.yaml, azure-pipelines-product-construction-service.yml, docs/DevGuide.md, eng/templates/jobs/e2e-pcs-tests.yml, eng/templates/jobs/e2e-tests.yml, eng/templates/stages/deploy.yaml
Contributes to https://github.com/dotnet/arcade-services/issues/4081
Replaces current GitHub PATs with fine-grained PATs that only have the required scopes for the operations performed.
Resource clean-up after this PR is merged is described in https://github.com/dotnet/arcade-services/issues/4081#issuecomment-2435688549
PCS build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2568184&view=results
Maestro build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2568257&view=results
=> Replace GitHub tokens used in CI

src/ProductConstructionService/ProductConstructionService.Cli/Operations/DeploymentOperation.cs
Improves the deployment command to clean all revisions that might have spawned when we changed the ACA configuration, removes labels before deactivating revisions
https://github.com/dotnet/arcade-services/issues/4103
=> Change how we deactivate all revisions

src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/GetRepoVersionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrCommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrCommandLineOptionsBase.cs, test/Maestro.Web.Tests/TestDatabase.cs, test/Microsoft.DotNet.Darc.Tests/DependencyRegistrationTests.cs, test/ProductConstructionService.Api.Tests/TestDatabase.cs
Fixes https://github.com/dotnet/source-build/issues/4713
- Fixes the DI registatration for one of the VMR commands which inherits differently than the others
- Fixes the DI test to generate a test case per each darc operation so that the DI container is not re-used but gets created every time
- Also fixes flaky test DB setup in tests that has been bugging us for quite some time and have now been somehow more flaky with this PR
=> Fix DI for the `darc vmr get-version` command

src/Maestro/Maestro.Authentication/AuthenticationConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/Controllers/StatusController.cs
Resolves https://github.com/dotnet/arcade-services/issues/4063
Adds an authentication policy for Admin role and assigns the policy to the `api/status` controller
The role already exists in `int`, will add it to `prod` and give it to the team + deployment MI once the PR is approved
=> Add policy for admin role

src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/SubscriptionsController.cs, src/ProductConstructionService/ProductConstructionService.Api/Api/v2018_07_16/Controllers/SubscriptionsController.cs
Resolves https://github.com/dotnet/arcade-services/issues/4128
Replaces the raw message string in `BadRequest` responses for subscription triggering with the expected `ApiError` object in line with how these types of responses are handled throughout Maestro / PCS
Example of the exception thrown by Darc after the change:
```
PS C:\Users\odidyk> darc trigger-subscriptions --bar-uri https://localhost:53180/ --id 00000000-d81a-43a9-ad8c-86b6fa5394ca
Will trigger the following 1 subscriptions...
https://github.com/dotnet/dnceng (.NET Eng Services - Prod) ==> 'https://github.com/dotnet/arcade-services' ('main')
Continue? (y/n) y
Triggering 1 subscriptions...fail: Unexpected error while triggering subscriptions.
Microsoft.DotNet.Maestro.Client.RestApiException`1[Microsoft.DotNet.Maestro.Client.Mo …
```
=> Fixup invalid request response for subscription trigger

eng/service-templates/ProductConstructionService/provision.bicep
Resolves https://github.com/dotnet/arcade-services/issues/4133
Adds missing trigger frequency to container `EXEC` command
=> Fix missing scheduled container job frequency

src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/DarcLib/IAzureDevOpsClient.cs, src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleaner.cs, src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerConfiguration.cs, src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerJob.cs, src/ProductConstructionService/ProductConstructionService.FeedCleaner/Program.cs, test/FeedCleaner.Tests/FeedCleanerServiceTests.cs, test/ProductConstructionService.FeedCleaner.Tests/FeedCleanerTests.cs
https://github.com/dotnet/arcade-services/issues/4073
Resolves several issues in the feed cleaner:
- Already deleted (in recycle bin) feeds are re-scanned each time
- Feeds were processed one at a time and the feed cleaner runs too long (~20 hours). Parallelization was added and the time needed went down to 20 minutes.
- Feeds are shuffled so that they are not processed in the same order (so we never reach the tail)
- Logging is improved
=> Parallelize feed cleaner

src/ProductConstructionService/ProductConstructionService.BarViz/Components/BuildInfo.razor, src/ProductConstructionService/ProductConstructionService.BarViz/Components/PinnedChannels.razor, src/ProductConstructionService/ProductConstructionService.BarViz/Layout/NavMenu.razor
Contributes to https://github.com/dotnet/arcade-services/issues/4048
Accessibility improvements:
- fixes missing `aria` labels on non-interactable navigation menu items by moving them out of the navigation menu itself
- fixes poor contrast on build date in the build info component
General fixes:
- fixes being able to pin the same channel multiple times
=> Minor BarViz improvements

Directory.Build.props
Resolves issue found during work on https://github.com/dotnet/arcade-services/issues/4048
Adds back a property that was originally removed as it was breaking debugging of BarViz in PCS when the project was in its hackaton stage.
After the project was merged with the rest of the service, the debugging stopped working without this property being set.
=> Fixup BarViz debugging

src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/AddBuildToChannelCommandLineOptions.cs
Contributes to https://github.com/dotnet/arcade-services/issues/2508
The option is not referenced in any up-to-date repositories within `dotnet` org or internally. Existing references are just repositories using an old version of Arcade (~2years old) and should not be impacted by this change
=> Remove unused option in add-build-to-channel

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PatchApplicationFailedException.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrPatchChangingFileTest.cs
Encountered problems like in https://github.com/dotnet/sdk/issues/44757 or https://github.com/dotnet/sdk/pull/44751 where a patch being applied together with incoming changes for a repo that is also being patched can end up with failures.
Instead of several rounds of restoring and reapplication of VMR patches, we strip all at the beginning and apply all at the end of the sync which makes it much simpler and less error prone.
=> Fix VMR patch re-application

src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs
Contributes to https://github.com/dotnet/arcade-services/issues/2508
Fixes an issue introduced in https://github.com/dotnet/arcade-services/pull/4143
While named exactly like the command option, the promotion pipeline argument in `AddBuildToChannelOperation` is still a valid and actively used option and should not have been removed
=> Fixup removed promotion pipeline argument

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/ProductConstructionService/ProductConstructionService.FeedCleaner/appsettings.json, src/ProductConstructionService/ProductConstructionService.LongestBuildPathUpdater/appsettings.json, src/ProductConstructionService/ProductConstructionService.SubscriptionTriggerer/appsettings.json
The logs are full of `Azure.Identity` logs when booting into the managed identity etc. [Example log](https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Ffbd6122a-9ad3-42e4-976e-bccb82486856%2FresourceGroups%2Fproduct-construction-service%2Fproviders%2FMicrosoft.OperationalInsights%2Fworkspaces%2Fproduct-construction-service-workspace-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAAzXKMQqAMAwAwN1XdHMqqKC4SgcX8QulYqhFbUoSKYKP18Wbz2AUFyLQkJLByHjAhJ6tmYpH5Q0IlPnLSHil2Z1gWbE4Es5BNlXytWih4P23SWeA%252Fbh1Ilx10%252FddW1dV%252BQIzK9f0ZwAAAA%253D%253D/timespan/P1Y/limit/30000)
=> Reduce logging verbosity for container jobs

Directory.Packages.props
Contributes to https://github.com/dotnet/arcade-services/issues/4048
Bumps Fluent UI libraries to `4.10.4` to resolve an issue with a missing `aria` tag in a fluent component
=> Bump fluent UI to 4.10.4

src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/SubscriptionsController.cs
The preset values in the code editor during subscription creation is `''` which then ends up sending empty strings instead of nulls to the API which then counts those as a real value and fails the validation
https://github.com/dotnet/arcade-services/issues/4159
=> Allow empty strings for directories when creating codeflow subscriptions

src/Microsoft.DotNet.Darc/Darc/Options/AddBuildToChannelCommandLineOptions.cs
Reverts https://github.com/dotnet/arcade-services/issues/4143
Seems like it is not as easy - we missed some servicing branches which are still using it.
=> Revert "Remove unused option in add-build-to-channel"

docs/DevGuide.md, src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CloneManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInfo.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/ReminderManager.cs, src/ProductConstructionService/Readme.md, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTwoWayCodeflowTest.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
Fixes problems introduced in #4181
- Fix how we look for git refs after we fetch from all remotes
- Fix getting the path to the `AllRepoVersions.props` file
https://github.com/dotnet/arcade-services/issues/3942
=> Fix E2E code flow tests (fetching refs, updating version files)

src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/InitializeOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/InitializeCommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/UpdateCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrUpdater.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
https://github.com/dotnet/arcade-services/issues/4166
We need to skip the look-up in some scenarios such as public PR builds of dotnet/sdk where we run the sync but don't have access to AzDO.
=> Allow skipping BAR build look-up (+fix how we do it)

src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs
https://github.com/dotnet/arcade-services/issues/4159
This means that we will ignore the flag during forward codeflows which would not otherwise be possible because we want to disable the pipeline sync for a repo always first.
But it's okay to do this because when we want to synchronize a single repository, it doesn't make sense to just refuse to do it because it's toggled off. It does make sense to adhere to this flag during a recursive sync (which happens in the pipeline sync).
Also improves the exception when we can't create a PR.
=> Ignore mapping disables during non-recursive synchronization

eng/templates/jobs/e2e-pcs-tests.yml, src/Maestro/Client/src/MaestroApiOptions.cs, src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/ProductConstructionServiceApiOptions.cs, test/ProductConstructionService.ScenarioTests/TestParameters.cs
The INT app was re-created and got a new URL last week. Fixing so that we go green in tests
https://github.com/dotnet/arcade-services/issues/3797
=> Change PCS staging URL

src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/PullRequestController.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
The cache is getting full of entries which are never removed if a PR is closed by someone other than Maestro.
Also improves the table that shows tracked PRs so it's easier to understand.
https://github.com/dotnet/arcade-services/issues/4198
=> Remove cache entries for already merged PRs

src/ProductConstructionService/ProductConstructionService.DependencyFlow/NonBatchedPullRequestUpdater.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestStatus.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_SdkUpdate.cs
A follow-up for https://github.com/dotnet/arcade-services/issues/4239 where another edge case meant that data lingered in cache after PR was dead.
https://github.com/dotnet/arcade-services/issues/4172
=> Simplify PR updater, improve logging and cache clean-up

test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_SdkUpdate.cs, test/ProductConstructionService.ScenarioTests/TestRepository.cs
This is the last test that is not cleaning up its branches properly. Also made it name branches/channels the same way as the other tests.
https://github.com/dotnet/arcade-services/issues/4172
=> Fix clean-up after the ArcadeSDK E2E test

src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/PullRequestController.cs, src/ProductConstructionService/ProductConstructionService.BarViz/Layout/MainLayout.razor, src/ProductConstructionService/ProductConstructionService.BarViz/Pages/PullRequests.razor
- Adds a main menu item for the "Tracked PRs" page
- Decodes GUIDs in org/repo names of AzDO PR URLs
- Makes the page refresh every 30 seconds
https://github.com/dotnet/arcade-services/issues/4198
=> Improve the "Tracked PRs" page

eng/templates/stages/deploy.yaml
The tests are flaky and we run them in the PCS pipeline anyway
https://github.com/dotnet/arcade-services/issues/3455
=> Stop running old E2E tests

src/ProductConstructionService/ProductConstructionService.BarViz/Components/DependencyGrid.razor
Also align with start like the other columns.
=> Make Age column wider in DependencyGrid.razor

src/Microsoft.DotNet.Darc/Darc/Operations/AddBuildToChannelOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/AddBuildToChannelCommandLineOptions.cs
Fixes https://github.com/dotnet/arcade-services/issues/4276
Recently we've hit quite a few times issues with unnoticed missing dependency flow or symbols publishing due to improperly configured default branch->channels association.
In such case the command succeeds with the message:
```
The build '{build.Id}' is already on these target channel(s):
```
This is missleading to untrained eye - especially in a long build output spew.
Instead we'd like to have an option to error out if the essociation is missing
Added optional option `--default-channels-required` that enables enforcing the existence of branch->channel association.
=> Add --default-channels-required option for 'darc add-build-to-channel'

src/ProductConstructionService/ProductConstructionService.WorkItems/ReminderManager.cs
Fixes a problem introduced in https://github.com/dotnet/arcade-services/issues/4278.
The receipt stayed in the memory longer than the queue message so upon completion, the service didn't set the follow-up reminder because the receipt was still there.
=> Set reminder receipt TTL same as the queue message's

src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemScope.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemScopeManager.cs
This makes the start/end/exception log item have the same operationId inside so it's easier to look for it in application insights
=> Log work item start/end/exception using current's scope logger

docs/DevGuide.md, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCloneManager.cs, src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs, src/ProductConstructionService/ProductConstructionService.Api/VirtualMonoRepo/VmrConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/appsettings.Production.json, src/ProductConstructionService/ProductConstructionService.Api/appsettings.Staging.json, src/ProductConstructionService/ProductConstructionService.Api/appsettings.json
With the way the VMR cloning was reworked in https://github.com/dotnet/arcade-services/issues/4175, it's no longer necessary to distinguish the local runs as it will use a local clone the same way as when initializing in cloud.
This means it's no longer necessary to clone the VMR manually and add it to the configuration when running the service locally for the first time.
=> Simplify PCS initialization for local developer workflows

src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/ILocalGitRepo.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitRepo.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrUpdater.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/ProductConstructionServiceApiOptions.cs, src/ProductConstructionService/ProductConstructionService.ReproTool/ReproTool.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/GitOperationsHelper.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrBackflowTest.cs
https://github.com/dotnet/arcade-services/issues/4294
I went through all of the places that called the `GitCommitAsync` method, and checked if they need to be amended in some cases
test: PR created in maestro-test-auth with the repro tool: https://github.com/maestro-auth-test/dotnet/pull/11
=> Make code flow updates a single commit

src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs
Noticed there's a new message which caused these exceptions to be logged.
=> Silence a well-known exception when merging AzDO PRs

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CloneManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrUpdater.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrBackFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrForwardFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCloneManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInitializer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrUpdater.cs, src/ProductConstructionService/ProductConstructionService.Api/InitializationBackgroundService.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/GitOperationsHelper.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrRepositoryCloningTest.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlow.cs
https://github.com/dotnet/arcade-services/issues/4251
=> Properly reset PCS branches during codeflow

src/Microsoft.DotNet.Darc/DarcLib/LocalLibGit2Client.cs
Fixes a problem introduced in https://github.com/dotnet/arcade-services/issues/4348 where the local branch was not tracking anything and we were not able to reset it when we tried to use it the next time.
This sets the tracking to the just pushed branch.
=> Set tracked branch after pushing

src/Maestro/Maestro.MergePolicies/AllChecksSuccessfulMergePolicy.cs, src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
This makes it easier to debug which policies is PCS waiting for.
They will also appear in the comment that the service drops on PRs:
=> Enumerate failed checks in merge policy logging/comments

src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/SubscriptionsController.cs
We consider that batching the backflow subscription from the VMR to other repos is undesirable enough that it's worth disallowing. Modify the PCS API to return a 400 error when requests attempt to create batched subscriptions from the VMR.
https://github.com/dotnet/arcade-services/issues/4359
=> Disallow batched subscription from the VMR

src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Subscriptions.razor
- Added more search filters + a pop-up with a legend
- Fixed sorting by last updated
- Fixed the disabled toggle semantics
=> Improve subscription page UX

src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/IDependencyFileManager.cs, test/Microsoft.DotNet.DarcLib.Tests/Helpers/DependencyFileManagerTests.cs
https://github.com/dotnet/arcade-services/issues/4390
Adds a `RemoveDependencyAsync` method with the same API as `AddDependencyAsync`
=> Add RemoveDependency method to DependencyFileManager

src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs, src/Microsoft.DotNet.Darc/Darc/Models/PopUps/AuthenticateEditorPopUp.cs, src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs
Token is no longer supported (https://github.com/dotnet/arcade-services/issues/4312)
`darc` will
- stop reading/storing the BAR token from the local settings
- stop using it if it's supplied as an argument (but not fail yet)
- warn if it's supplied
- stop giving a warning when the user has not called `darc authenticate` yet
=> Stop using the BAR token in darc

.config/dotnet-tools.json, eng/Version.Details.xml, eng/Versions.props, global.json, src/Microsoft.DotNet.Darc/Darc/Helpers/LocalSettings.cs, src/Microsoft.DotNet.Darc/Darc/Models/PopUps/AuthenticateEditorPopUp.cs, src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/IDependencyFileManager.cs, src/ProductConstructionService/ProductConstructionService.Api/Program.cs, test/Microsoft.DotNet.DarcLib.Tests/Helpers/DependencyFileManagerTests.cs
https://github.com/dotnet/arcade-services/issues/4416
=> [Rollout] Production rollout 2025-02-05

src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs, test/ProductConstructionService.ScenarioTests/TestHelpers.cs
Partially reverted https://github.com/dotnet/arcade-services/issues/4415 where we still want to be able to pass in the token. This happens in the scenario tests where we get it from Azure CLI manually.
=> Allow passing in the Entra token

src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemProcessorState.cs, test/ProductConstructionService.WorkItem.Tests/WorkItemsProcessorScopeManagerTests.cs
https://github.com/dotnet/arcade-services/issues/4414
- We want the service to start working right after booting so that random container reboots don't stop the service from processing.
- We also don't want to stop working when the cache gets emptied.
=> Start the service as working always

test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_Dependencies.cs
The channel is being left behind the scenario tests
=> Clean up test channel in the `ArcadeDependencies_EndToEnd` scenario test

src/ProductConstructionService/ProductConstructionService.Api/Configuration/SubscriptionTriggerConfiguration.cs, src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
Follows better what we do for other configuration and cleans up the startup file where we go quite often.
=> Move EF trigger to its own file

src/ProductConstructionService/ProductConstructionService.Api/Configuration/MaestroAuthTestRepositoryExtensions.cs, src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs
I discovered that using the repro tool locally does not entirely work because during code flows, we try to use all of the previous remotes (such as the URI stored in the `source-manifest.json`).
We cannot override those in the repositories because some scenarios such as previous flow reconstructions would still break.
So it's easier to override the URI like this and just keep cloning the repos that we have access to.
=> Only use `maestro-auth-test` repos locally

src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/IDependencyFileManager.cs, src/Microsoft.DotNet.Darc/DarcLib/Local.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrBackflowTest.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrCodeFlowTests.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTwoWayCodeflowTest.cs, test/Microsoft.DotNet.DarcLib.Tests/Helpers/DependencyFileManagerTests.cs
With the addition of `RemoveDependencyAsync`, we can stop generating XMLs when we need to omit a package inside a test.
https://github.com/dotnet/arcade-services/issues/4390
=> Use Add/RemoveDependency during VMR test setup

eng/templates/jobs/darc-and-api-tests.yml, eng/templates/stages/deploy.yaml
https://github.com/dotnet/arcade-services/issues/4404#issue-2823400220
Also brought back some Scenario tests we had for Darc. These are useful because if something is wrong with these darc commands, no one can publish their builds
=> Add API anonymous access test, and bring back darc Scenario Tests

src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleaner.cs, src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerConfiguration.cs, src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerJob.cs, src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerOptions.cs, src/ProductConstructionService/ProductConstructionService.FeedCleaner/appsettings.json, test/ProductConstructionService.FeedCleaner.Tests/FeedCleanerTests.cs
https://github.com/dotnet/arcade-services/issues/4266
Discussed with Matt, we don't need to look at AzDo feeds anymore, everything that's released should be in NuGet
=> Only look at NuGet when cleaning darc feeds

src/ProductConstructionService/ProductConstructionService.Api/Configuration/SubscriptionTriggerConfiguration.cs
Suspected fix for https://github.com/dotnet/arcade-services/issues/4454
`EveryBuild` trigger was incorrectly comparing the source repo of the build to the subs source directory, resulting in no subscriptions being triggered
=> Fixup invalid source comparison for build trigger

src/Maestro/Maestro.Common/AppCredentials/AppCredential.cs, src/Maestro/Maestro.Common/AppCredentials/CachedInteractiveBrowserCredential.cs
Resolves https://github.com/dotnet/arcade-services/issues/4389
Fixup for a forced authentication attempt from Darc when using interactive (browser) credentials. An example where this was causing issues - https://github.com/dotnet/arcade-services/issues/4389#issuecomment-2663058878
Added a `Cached` token credential that encapsulates the interactive one and handles reading from existing cache on initialization and writing to cache on the first token request
=> Fix forced auth attempt when using interactive creds

src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/SourceMappingFile.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CodeFlowVmrUpdater.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/SourceMappingParser.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrInfo.cs
https://github.com/dotnet/arcade-services/issues/4186
We'l also have to add this path to the VMR
=> Don't use hardcoded template path, get it from the VMR

src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, src/ProductConstructionService/ProductConstructionService.ReproTool/ReproTool.cs, test/ProductConstructionService.DependencyFlow.Tests/UpdateAssetsForCodeFlowTests.cs
We have a pending TODO where we don't fill the `RequiredUpdates` yet. However, the merge policy check fails on an NRE if this is null.
Example: https://github.com/dotnet/scenario-tests/pull/213/checks?check_run_id=37710832910
https://github.com/dotnet/arcade-services/issues/3866
https://github.com/dotnet/arcade-services/issues/4159
=> Fix a "no downgrade" merge policy NRE

src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/SourceManifest.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/Exceptions.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrBackFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrForwardFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrCodeFlowTests.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTwoWayCodeflowTest.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs, test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlow.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlowConflicts.cs
https://github.com/dotnet/arcade-services/issues/4352
This PR:
- Makes us lookup previous builds instead of just using previous commits when reconstructing flows during conflicts
- Fixes a bug in `ConflictInPrBranchException` that was happening during backflow
- Fixes the VmrUri not getting updated when preparing the VMR
=> Look up previous builds when reconstructing flows during conflicts

src/Maestro/Maestro.Data/Migrations/20250227091038_IncreaseAssetNameSize.Designer.cs, src/Maestro/Maestro.Data/Migrations/20250227091038_IncreaseAssetNameSize.cs, src/Maestro/Maestro.Data/Models/Asset.cs
A break in the `dotnet/binaryen` repo due to https://github.com/dotnet/arcade/commit/412357836b422acfd19ce283cc601bd71c834e6d when publishing to BAR:
```
RestApiException`1: The response contained an invalid status code 400 Bad Request
Body: {"message":"The request is invalid","errors":["The field Name must be a string with a maximum length of 150.","The field Name must be a string with a maximum length of 150."]}
```
It's because the symbol blob ID is now 153 chars with that change in the `MergedManifest.xml`
=> Increase the `Asset.Name` column size to 250

src/ProductConstructionService/ProductConstructionService.Api/Api/v2018_07_16/Models/AssetData.cs
Adjusted validation attribute to database field size
This is follow-up to: https://github.com/dotnet/arcade-services/pull/4504
Issue: https://github.com/dotnet/arcade-services/issues/4504
=> Asset name length updated according to database field

src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/DarcLib/IRemoteGitRepo.cs, src/Microsoft.DotNet.Darc/DarcLib/Models/PrInfo.cs, src/Microsoft.DotNet.Darc/DarcLib/Remote.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/ProductConstructionService.DependencyFlow.Tests/PendingCodeFlowUpdatesTests.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs, test/ProductConstructionService.DependencyFlow.Tests/UpdateAssetsForCodeFlowTests.cs, test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
We have 2 different calls to get PR status but both lead to the same API endpoint (both AzDO and GitHub):
- `GetPullRequestAsync`
- `GetPullRequestStatusAsync`
We call both during dependency updates which means extra calls to GitHub.
This PR unifies them into a single call and reuses the data loaded with the first call instead of the second call.
https://github.com/dotnet/arcade-services/issues/4524#issuecomment-2710525969
=> Query PR status only once during dependency flow

src/ProductConstructionService/ProductConstructionService.BarViz/Code/Helpers/StringExtensions.cs, src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Subscriptions.razor
- Adds a support for "quoting search terms" when filtering in the Subscription page
- Resolves https://github.com/dotnet/arcade-services/issues/4494
=> Allow quoting search terms on the Subscription page

test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlowConflicts.cs
- Makes sure the test deletes the PR branch (which is left behind after each run)
- Improves error messages when assertions fail
=> Clean up branch after backflow scenario test

Directory.Packages.props, src/Maestro/Maestro.Common/AppCredentials/AppCredential.cs, src/Maestro/Maestro.Common/Maestro.Common.csproj
We need to be on the latest versions so that some S360 KPIs which measure from what libraries we auth against our Maestro app can be later satisfied.
=> Update Identity libraries

src/Microsoft.DotNet.Darc/Darc/Operations/GatherDropOperation.cs
This queues the task on the threadpool, with the same max concurrency. This drastically improves the performance when downloading blobs. Packages got reasonable concurrency, but we only got one ore two concurrent downloads on blobs.
=> Use Task.Run for concurrency

src/Maestro/Maestro.MergePolicies/DependencyUpdateSummary.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/BackflowOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/CodeFlowOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/ForwardFlowOperation.cs, src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/CodeFlowResult.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/PcsVmrBackFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestBuilderTests.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlow.cs
https://github.com/dotnet/arcade-services/issues/4407#issue-2823541261
- Extend DependencyUpdateSummary to include From/To commit sha's that can be used to build the PR description. Previously, DependencyUpdateSummary objects were saved in InProgressPullRequest for some kind of edge case check, and were not used to build the PR description. Instead, the entire list of dependencies was built from source of truth for every subscription contained in a PR on every PR update, regardless of the existing DependencyUpdateSummary objects persisted in the InProgressPullRequest. Because the code flow brings in partial dependency updates (that come only from the most recent diff), this works a bit differently for codeflow.
- Add a post-processing method on the codeflow PR description that searches …
=> Add dependency updates to codeflow PR description

src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestBuilderTests.cs
https://github.com/dotnet/arcade-services/issues/4463#issue-2853754710
=> Add codeflow documentation in PR description

src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/VersionDetailsParser.cs, src/Microsoft.DotNet.Darc/DarcLib/Models/VersionDetails.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionFileCodeFlowUpdater.cs, test/Microsoft.DotNet.DarcLib.Tests/Helpers/VersionDetailsParserTests.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VersionFileConflictResolverTests.cs
This will be needed for our tooling (such as in https://github.com/dotnet/arcade-services/issues/4539) so that users don't need to keep passing in the mapping name and we can tell from/to where is the repo mapped in the VMR
=> Include mapping name in the Source tag

src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs
Example: https://github.com/dotnet/dotnet/issues/163 (click `Edit` on the title)
=> Remove an extra space from PR titles

test/ProductConstructionService.ScenarioTests/CodeFlowScenarioTestBase.cs, test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs
Wrong fix happened in https://github.com/dotnet/arcade-services/issues/4576
=> Fix Source tag matching in scenario tests

azure-pipelines-pr.yml, azure-pipelines.yml
Resolves https://github.com/dotnet/arcade-services/issues/4596
There are no 24.04 images in the agent pools we use so pivoted to 22.04 instead
Internal build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2671619&view=results
=> Bump agent image to ubuntu 22.04

arcade-services.sln, tools/FlatFlowMigrationCli/FlatFlowMigrationCli.csproj, tools/FlatFlowMigrationCli/MigrationLogger.cs, tools/FlatFlowMigrationCli/Operations/MigrateOperation.cs, tools/FlatFlowMigrationCli/Options/Options.cs, tools/FlatFlowMigrationCli/SubscriptionMigrator.cs, tools/ProductConstructionService.ReproTool/DarcProcessManager.cs, tools/ProductConstructionService.ReproTool/Operations/FlowCommitOperation.cs, tools/ProductConstructionService.ReproTool/Operations/Operation.cs, tools/ProductConstructionService.ReproTool/Operations/ReproOperation.cs, tools/ProductConstructionService.ReproTool/Options/FlowCommitOptions.cs, tools/ProductConstructionService.ReproTool/Options/Options.cs, tools/ProductConstructionService.ReproTool/Options/ReproOptions.cs, tools/ProductConstructionService.ReproTool/ProductConstructionService.ReproTool.csproj, tools/ProductConstructionService.ReproTool/Program.cs, tools/Tools.Common/Constants.cs, tools/Tools.Common/Tools.Common.csproj, tools/Tools.Common/VmrDependencyResolver.cs
Adds a new command that takes a given commit in `maestro-auth-test/` repo/VMR and flows it to a given target repo/VMR.
(it creates a fake build that will flow)
Useful for testing various changes, conflicts etc.
https://github.com/dotnet/arcade-services/issues/4535
=> Add the `flow-commit` ReproTool command

src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/BuildsController.cs
Fixes a common NRE that happens when we query builds for commits that don't exist (e.g. during scenario tests):
https://ms.portal.azure.com#@72f988bf-86f1-41af-91ab-2d7cd011db47/blade/Microsoft_OperationsManagementSuite_Workspace/Logs.ReactView/resourceId/%2Fsubscriptions%2Ffbd6122a-9ad3-42e4-976e-bccb82486856%2FresourceGroups%2Fproduct-construction-service%2Fproviders%2Fmicrosoft.insights%2Fcomponents%2Fproduct-construction-service-ai-prod/source/LogsBlade.AnalyticsShareLinkToQuery/q/H4sIAAAAAAAAA0utSE4tKMnMzysGAGAbcigKAAAA/timespan/PT12H/limit/1000
=> Fix an NRE in BuildsController

src/Maestro/Maestro.DataProviders/RemoteFactory.cs, src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs, src/Microsoft.DotNet.Darc/Darc/Operations/SetRepositoryMergePoliciesOperation.cs, src/Microsoft.DotNet.Darc/DarcLib/GitRepoFactory.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/GitRepoUrlUtils.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/ManifestRecord.cs, src/Microsoft.DotNet.Darc/DarcLib/RemoteTokenProvider.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPusher.cs, src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/PullRequestController.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestConflictNotifier.cs, test/Microsoft.DotNet.DarcLib.Tests/Helpers/GitRepoUrlParserTest.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlowConflicts.cs, tools/ProductConstructionService.ReproTool/Operations/FlowCommitOperation.cs, tools/ProductConstructionService.ReproTool/Operations/Operation.cs, tools/ProductConstructionService.ReproTool/Operations/ReproOperation.cs
https://github.com/dotnet/arcade-services/issues/4604
Makes it so the conflict messages have the follow format:
- `file name` - `source repo` / `target repo`
=> Add both source and target repo in Conflict messages

test/ProductConstructionService.ScenarioTests/CodeFlowScenarioTestBase.cs, test/ProductConstructionService.ScenarioTests/ScenarioTestBase.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlow.cs
https://github.com/dotnet/arcade-services/issues/4638
=> Extend the backflow test so it also tests pinned dependencies

src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/CodeFlowOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/InitializeOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/VmrDiffOperation.cs, src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/CodeFlowParameters.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CodeFlowVmrUpdater.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrManagerBase.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
I originally thought that we would just remove the additional mappings from VMR's `source-mappings.json` but that does not work because the flow will be based on the last flown commit where it's likely the additional mappings will still be present.
So we need to explicitly disable this feature for code flows.
https://github.com/dotnet/arcade-services/issues/4618
=> Ignore additional mappings during codeflow

src/Microsoft.DotNet.Darc/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/DarcLib/Local.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTwoWayCodeflowTest.cs, test/ProductConstructionService.DependencyFlow.Tests/UpdateAssetsForCodeFlowTests.cs
Removed several no longer relevant TODOs, mostly around exception handling which now seems to be handled usually on the appropriate level.
Some TODOs were resolved with additional handling/logging but since we now see how the code behaves in runtime, I believe we will be able to add more error handling as we see fit and these TODOs are just artifacts of some premature ideas of how things will work.
- https://github.com/dotnet/arcade-services/issues/4178
- https://github.com/dotnet/arcade-services/issues/3866
- https://github.com/dotnet/arcade-services/issues/4342
- https://github.com/dotnet/arcade-services/issues/2995
- https://github.com/dotnet/arcade/issues/1095
=> Remove no longer relevant TODOs

src/Maestro/Maestro.MergePolicies/BackFlowMergePolicy.cs, src/Maestro/Maestro.MergePolicies/ForwardFlowMergePolicy.cs, src/Maestro/Maestro.MergePolicies/MergePolicyServiceCollectionExtensions.cs, src/Maestro/Maestro.MergePolicies/StandardMergePolicy.cs, src/Maestro/Maestro.MergePolicyEvaluation/MergePolicyConstants.cs, src/Microsoft.DotNet.Darc/Darc/Models/PopUps/MergePoliciesPopUpHelpers.cs, src/Microsoft.DotNet.Darc/Darc/Operations/AddSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/Darc/Operations/UpdateSubscriptionOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/AddSubscriptionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/SubscriptionCommandLineOptions.cs, src/Microsoft.DotNet.Darc/Darc/Options/UpdateSubscriptionCommandLineOptions.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
Reverts https://github.com/dotnet/arcade-services/issues/4680
This reverts commit 15c4f8e39a963a4598f0bbf2e6d70aad13766629.
=> Revert "Improve `darc update-subscription` by allowing to specify policy checks"

eng/templates/stages/deploy.yaml, tools/ProductConstructionService.Cli/Operations/DeploymentOperation.cs, tools/ProductConstructionService.Cli/Options/DeploymentOptions.cs
This should enable rerunning deployment stages of older production pipeline runs to quickly roll back PCS
=> Add attempt number into ACA revision

src/Microsoft.DotNet.Darc/Darc/Microsoft.DotNet.Darc.csproj
Darc was mistakenly updated to .NET 8 in https://github.com/dotnet/arcade-services/issues/4650
=> Keep darc on .NET 6.0

tools/ProductConstructionService.Cli/Operations/DeploymentOperation.cs
I didn't notice [in the previous fix](https://github.com/dotnet/arcade-services/issues/4690) that we actually generate the real name later.
Test deployment: https://dev.azure.com/dnceng/internal/_build/results?buildId=2688720
=> Fix generating ACA revision including the attempt

src/Microsoft.DotNet.Darc/DarcLib/GitHubTokenProvider.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
https://github.com/dotnet/arcade-services/issues/4644
There was a bug in forwardflow when the previous flow was backwards
Basically, we were leaving the submodules as is in our repo, but creating the patches for them from 0 commit. When these patches we're applied, we were getting exceptions that the files already exist in the index.
This PR fixes the issue by making sure we remove the submodules at the beginning of the forward flow, so we restore them like the normal repo, from the 0 commit
=> Fix handling submodules during forward flow

src/Microsoft.DotNet.Darc/DarcLib/Helpers/HttpRequestManager.cs
Fix the issue with contains certain HTTP status code in error message. Problem was that 401 appeared in the name of non-existent feed and it was interpreted as unauthorized access.
Issue: https://github.com/dotnet/arcade-services/issues/4703
https://github.com/dotnet/arcade-services/issues/2479
=> Fix the 401 HTTP status code check from string

src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs
One of the issues seen in https://github.com/dotnet/arcade-services/issues/4721
=> Add `global.json` mapping for `CMake.Sdk`

src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionFileCodeFlowUpdater.cs, test/Microsoft.DotNet.DarcLib.Tests/Helpers/DependencyFileManagerTests.cs
Fixes a problem of a code path that was not really exercised but has been present in the codebase for years where `AddDependency` would fail to update an existing item and instead would create a new one.
https://github.com/dotnet/arcade-services/issues/4720
=> Fix upserting of `Versions.props` properties

tools/ProductConstructionService.Cli/Options/DeploymentOptions.cs
We started seeing failures in the deployments because some other identity is being picked up suddenly.
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2694710&view=results
=> Prefer the `az cli` credential in CI deployments

docs/DevGuide.md, src/Maestro/Maestro.Common/AzureDevOpsTokens/AzureDevOpsTokenProvider.cs, src/Microsoft.DotNet.Darc/Darc/Operations/GatherDropOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/GatherDropCommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/AzureAuthentication.cs, src/ProductConstructionService/ProductConstructionService.Api/Configuration/DataProtection.cs, src/ProductConstructionService/ProductConstructionService.Api/PcsStartup.cs, src/ProductConstructionService/ProductConstructionService.SubscriptionTriggerer/SubscriptionTriggererConfiguration.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemConfiguration.cs, tools/ProductConstructionService.Cli/Options/DeploymentOptions.cs
We shouldn't be using `DefaultAzureCredential` when running in a pipeline or a service. We should be using either ManagedIdentityCredential, or AzureCliCredential.
https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication/best-practices?tabs=aspdotnet#:~:text=and%20mitigation%20techniques.-,Use%20deterministic%20credentials%20in%20production%20environments,-DefaultAzureCredential%20is%20the
https://github.com/dotnet/arcade-services/issues/4738
=> Don't use DefaultAzureCredential when not running locally

src/Maestro/Maestro.MergePolicies/AllChecksSuccessfulMergePolicy.cs, src/Maestro/Maestro.MergePolicies/BackFlowMergePolicy.cs, src/Maestro/Maestro.MergePolicies/DontAutomergeDowngradesMergePolicy.cs, src/Maestro/Maestro.MergePolicies/ForwardFlowMergePolicy.cs, src/Maestro/Maestro.MergePolicies/MergePolicy.cs, src/Maestro/Maestro.MergePolicies/NoRequestedChangesMergePolicy.cs, src/Maestro/Maestro.MergePolicies/ValidateCoherencyMergePolicy.cs, src/Maestro/Maestro.MergePolicyEvaluation/MergePolicyEvaluationResult.cs, src/Maestro/Maestro.MergePolicyEvaluation/MergePolicyEvaluationResults.cs, src/Maestro/Maestro.MergePolicyEvaluation/MergePolicyEvaluationStatus.cs, src/Microsoft.DotNet.Darc/DarcLib/AzureDevOpsClient.cs, src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/DarcLib/IRemoteGitRepo.cs, src/Microsoft.DotNet.Darc/DarcLib/Remote.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/MergePolicyEvaluator.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs, test/ProductConstructionService.DependencyFlow.Tests/UpdaterTests.cs
https://github.com/dotnet/arcade-services/issues/4610#issue-2960200075
=> Allow some PR checks to be skipped

src/ProductConstructionService/ProductConstructionService.DependencyFlow/PcsVmrBackFlower.cs
This is a temporary work around so we unblock the flow but we will have to address it properly later.
https://github.com/dotnet/arcade-services/issues/4763
=> Always push into an existing codeflow PR

src/Maestro/Maestro.DataProviders/RemoteFactory.cs, src/Microsoft.DotNet.Darc/Darc/Helpers/RemoteFactory.cs, src/Microsoft.DotNet.Darc/Darc/Operations/UpdateDependenciesOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/CoherencyUpdateResolver.cs, src/Microsoft.DotNet.Darc/DarcLib/ICoherencyUpdateResolver.cs, src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/DarcLib/Remote.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestPolicyFailureNotifier.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/RemoteFactory.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs, test/Microsoft.DotNet.DarcLib.Tests/RemoteTests.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VersionFileCodeFlowUpdaterTests.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestBuilderTests.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestPolicyFailureNotifierTests.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
This repository was ridden with places where we were passing dependencies as arguments. We have mostly removed that but yesterday during the bug squashing I found few more places where it's then harder to use the classes so improving that.
=> Inject services instead of passing them as method parameters

src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/CodeFlowOperation.cs, src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/CodeFlowResult.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PcsVmrBackFlower.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
https://github.com/dotnet/arcade-services/issues/4777
Fixes a problem where we were just using the last flown SHA regardless of flow direction. So that can also be the SHA of the last incoming flow while we care about the last ongoing flow.
=> Fix source SHA in commit diff links

src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs
Fixes an issue with missing services for `IRemote` resolution in Darc introduced in https://github.com/dotnet/arcade-services/pull/4756
=> Add missing service registration for remote

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrRegistrations.cs, test/Maestro.Data.Tests/DependencyRegistrationTests.cs, test/Microsoft.DotNet.DarcLib.Tests/Microsoft.DotNet.DarcLib.Tests.csproj, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrRegistrationsTests.cs
Infra pipeline will use the new DI registration method to be able to use GitNativeRepoCloner.
Consumer is a code which is implemented for: https://github.com/dotnet/release/issues/1264
=> DI registration for GitNativeRepoCloner

src/Maestro/Maestro.DataProviders/SqlBarClient.cs, src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/IPullRequestUpdater.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestConflictNotifier.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/SubscriptionTriggerer.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/WorkItemProcessors/SubscriptionUpdateProcessor.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/WorkItems/SubscriptionUpdateWorkItem.cs, test/ProductConstructionService.DependencyFlow.Tests/PendingUpdatePullRequestUpdaterTests.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs, test/ProductConstructionService.DependencyFlow.Tests/SubscriptionUpdaterTests.cs, test/ProductConstructionService.DependencyFlow.Tests/UpdateAssetsPullRequestUpdaterTests.cs
List of assets can be too large to store in the Message Queue, therefore they should not be defined inside work items. To fix this, builds are queried at the beginning of the PullRequestUpdater flow, and the assets are taken from there.
https://github.com/dotnet/arcade-services/issues/4745#issue-3019865179
=> Do not store assets work items

src/Microsoft.DotNet.Darc/DarcLib/GitHubClient.cs, src/Microsoft.DotNet.Darc/DarcLib/Remote.cs
A possible fix for https://github.com/dotnet/arcade-services/issues/4751 where we use `NotFound` as a signal whether a source repo is or is not a VMR
=> Improve GitHub exception handling

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
Resolves https://github.com/dotnet/arcade-services/issues/4807
1. There was a change in the VMR: https://github.com/dotnet/dotnet/commit/2774010bee5a0e2a8a554bf87490d9eacebc39ab
2. It was not backflown correctly: https://github.com/dotnet/arcade/pull/15814
3. It works with the fix: https://github.com/maestro-auth-test/arcade/pull/1
=> Do not ignore `eng/common` during arcade backflows

src/ProductConstructionService/ProductConstructionService.DependencyFlow/PcsVmrBackFlower.cs, tools/ProductConstructionService.ReproTool/Operations/Operation.cs, tools/ProductConstructionService.ReproTool/Operations/ReproOperation.cs
The repro tool was not ignoring case when replacing the source mapping/manifest records.
We could do a case-insensitive replace but it just felt better to work with the JSON.
Found during https://github.com/dotnet/arcade-services/issues/4665
=> Make repro tool work with `NuGet.Client`

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
Problem was with the submodule loops which throw because we change the `Submodules` collections mid way through the loop.
https://github.com/dotnet/arcade-services/issues/4822
=> Fix auto-resolution of forward flow conflicts

src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleaner.cs, src/ProductConstructionService/ProductConstructionService.FeedCleaner/FeedCleanerJob.cs, test/ProductConstructionService.FeedCleaner.Tests/FeedCleanerTests.cs
https://github.com/dotnet/arcade-services/issues/4767#issue-3028200957
After talking with Matt, we agreed that we'll delete symbols that are already published to NuGet and exist in BAR. We won't delete the symbol feeds tho, this is what caused the crashes we saw
=> Stop cleaning symbol feeds

tools/ProductConstructionService.ReproTool/Operations/Operation.cs
The repro tool didn't match the URI because of casing and started creating new forks every time:
=> Fix synchronization of nuget.client forks

src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
Possibly introduced in https://github.com/dotnet/arcade-services/issues/4542 where the newly used SQL client does not throw when a subscription does not exist
=> Fix a new NRE in our service

src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/VmrDiffOperation.cs, src/Microsoft.DotNet.Darc/Darc/Options/VirtualMonoRepo/VmrDiffOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
Adds a new option that only lists the differing file names
https://github.com/dotnet/source-build/issues/5201
=> Add the `darc vmr diff --name-only` option

src/ProductConstructionService/Microsoft.DotNet.ProductConstructionService.Client/Subscription.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestConflictNotifier.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs
https://github.com/dotnet/arcade-services/issues/4841#issue-3068326194
At first I thought this issue was happening only because we were using URL-generating methods intended for normal repos in the VMR - but the VMR needs an additional "src/repoName" in the file paths.
But there was another issue as well, which this PR fixes. The conflict comment was linking to files in the target branches - but the target branch is the one that doesn't have the file until the PR is merged. Therefore, the generated link has to point at the head branch instead.
On top of fixing the issue, I also rewrote the code to make it a bit easier to understand - it was like a mini IQ test to decipher the ternary conditionals for backflow, forward flow, source repo, and target repo.
Tested by modifying scenario tests …
=> Fix broken file links again

.github/ISSUE_TEMPLATE/codeflow-issue.yml, README.md, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/SourceMappingParser.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/ProductConstructionService/ProductConstructionService.BarViz/Pages/Home.razor, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs, test/Microsoft.DotNet.Darc.Tests/inputs/source-mappings.json
The documents were moved in the VMR and this change is now being backflown: https://github.com/dotnet/arcade/issues/15853
=> Point references to UB documentation to new location

src/Microsoft.DotNet.Darc/DarcLib/Helpers/ProcessExecutionResult.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/Exceptions.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestConflictNotifier.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
Resolves https://github.com/dotnet/arcade-services/issues/4854
=> Make sure comment about conflicts is sent always

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs
This PR does the same as https://github.com/dotnet/arcade-services/issues/4882 where another code path was omitted and which did not post a comment here: https://github.com/dotnet/runtime/pull/115833
https://github.com/dotnet/arcade-services/issues/4854
=> Post a comment about a PR conflict

src/Microsoft.DotNet.Darc/DarcLib/Remote.cs, src/ProductConstructionService/ProductConstructionService.Api/appsettings.json, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemConsumer.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemScope.cs, src/ProductConstructionService/ProductConstructionService.WorkItems/WorkItemScopeManager.cs, test/ProductConstructionService.WorkItem.Tests/WorkItemScopeTests.cs
This PR makes it so that we include the time we wait for a delay into the work item wait metric so that we correctly measure how long we need to wait for example for VMR related work items that have to wait for the distributed lock.
=> Include mutex wait time in work item delay

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionFileCodeFlowUpdater.cs
https://github.com/dotnet/arcade-services/issues/4697#issue-3001812116
This fixes the dependency update commit message for backflow, where the
wrong list of dependencies was used when creating
=> Fix dependency updates in backflow commit msg

src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/VmrDiffOperation.cs
- Fixes how we locate and read `source-mappings.json` to get the list of exclusions
- Fixes scenarios where we run the tool from the VMR folder
- Improves how we parse input (more readable vmr/repo variables)
- Uses built-in functions for git commands instead of manual shell
The tool still has a few usability bugs where diffing a specific SHA of repo from the VMR folder does not work but wanted to check this in because it already fixes several bugs
https://github.com/dotnet/source-build/issues/5201
=> Fix a few bugs in `darc vmr diff`

src/Maestro/Maestro.MergePolicyEvaluation/MergePolicyEvaluationResults.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/MergePolicyEvaluator.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/ProductConstructionService.DependencyFlow.Tests/MergePolicyEvaluationTests.cs, test/ProductConstructionService.DependencyFlow.Tests/PendingUpdatePullRequestUpdaterTests.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs, test/ProductConstructionService.DependencyFlow.Tests/SubscriptionOrPullRequestUpdaterTests.cs, test/ProductConstructionService.DependencyFlow.Tests/UpdateAssetsPullRequestUpdaterTests.cs, test/ProductConstructionService.DependencyFlow.Tests/UpdaterTests.cs
https://github.com/dotnet/arcade-services/issues/4913
The actual bug fix (plus a few minor changes) are in commit 4: [Merge policy evaluation fixes](https://github.com/dotnet/arcade-services/pull/4934/commits/c177273513b7ed22d66ccf56180e34253b85b2f7)
=> Ignore deprecated merge policy results + add evaluation tests

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CodeflowChangeAnalyzer.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrRegistrations.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PcsVmrForwardFlower.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrForwardFlowTest.cs, test/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/CodeflowChangeAnalyzerTests.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestUpdaterTests.cs
This PR adds a basic heuristic which will prevent no-op forward flows that only flow package updates that happened in the last backflow and no other changes.
https://github.com/dotnet/arcade-services/issues/4178
=> Avoid creating PRs with meaningless updates

src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs
Reverts https://github.com/dotnet/arcade-services/issues/4957
This started to fail the `Vmr_BackwardConflictFlowTest` test. I need to investigate why before re-introducing this.
=> Revert "Ignore whitespace changes when blaming files"

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/VmrBackflowTest.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/VmrCodeFlowTests.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/VmrForwardFlowTest.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/VmrTestsBase.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/VmrTwoWayCodeflowTest.cs
https://github.com/dotnet/arcade-services/issues/4947
Basically, we were calculating the lastCodeflow, and lastLastCodeflow from the same VMR commit, which gave us the same result.
=> Recreate previous flow fix

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/WorkBranch.cs
Handles a case when CRLF settings are changed on files to their default.
These files would then appear as dirty in the working tree while git would be unable to handle these properly.
This adds a check for whitespace changes only and allows to merge the work branch even when these changes are present only.
https://github.com/dotnet/source-build/issues/5207
=> Ignore differing EOLs when merging work branches

src/Microsoft.DotNet.Darc/DarcLib/Helpers/DependencyFileManager.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/IDependencyFileManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VersionFileCodeFlowUpdater.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/Constants.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/VmrBackflowTest.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/VmrCodeFlowTests.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VersionFileCodeFlowUpdaterTests.cs
https://github.com/dotnet/arcade-services/issues/4847
=> Always flow dotnet sdk version from VMRs root global.json

src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, test/ProductConstructionService.ScenarioTests/CodeFlowScenarioTestBase.cs, test/ProductConstructionService.ScenarioTests/ScenarioTests/ScenarioTests_CodeFlowConflicts.cs
The root cause of the problem was calculating `lastLastFlows` in repos that only had one. So I had to make those flows happen and adjust some of the tests, but now all of them passed locally
https://github.com/dotnet/arcade-services/issues/4982
=> Make scenario tests work when git blame uses the `-w` flag

src/Maestro/Maestro.MergePolicies/DependencyUpdateSummary.cs, src/Microsoft.DotNet.Darc/DarcLib/Models/Darc/DependencyUpdate.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestBuilderTests.cs, test/ProductConstructionService.DependencyFlow.Tests/SubscriptionOrPullRequestUpdaterTests.cs
When we are updating the PR description, we create new link references counting again from `[1]` so the following happens:
So previous and new links both point to the first URL.
Instead, we count the links and add new references (keeping the old ones in case some packages didn't get updated).
Resolves https://github.com/dotnet/arcade-services/issues/4963
=> Fix link references during codeflow PR updates

src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestBuilder.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PullRequestUpdater.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestBuilderTests.cs
The SHA is sometimes confusing because technically it shows a diff from the last flow and can be totally different than the delta of the current repo in the VMR (we're often only flowing the delta between the VMR and the repo).
Example: https://github.com/dotnet/diagnostics/issues/5492
=> Do not display current repo in associated repo changes

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
fixes a bug from https://github.com/dotnet/arcade-services/issues/5030
=> When calculating commit difference between two branches, fully qualify target branch

src/Microsoft.DotNet.Darc/Darc/Options/CommandLineOptions.cs, src/Microsoft.DotNet.Darc/DarcLib/Helpers/StringUtils.cs, src/Microsoft.DotNet.Darc/DarcLib/IRedisCacheClient.cs, src/Microsoft.DotNet.Darc/DarcLib/IRemote.cs, src/Microsoft.DotNet.Darc/DarcLib/Models/VirtualMonoRepo/SourceManifest.cs, src/Microsoft.DotNet.Darc/DarcLib/Remote.cs, src/ProductConstructionService/ProductConstructionService.Api/Api/v2020_02_20/Controllers/BuildsController.cs, src/ProductConstructionService/ProductConstructionService.Common/ProductConstructionService.Common.csproj, src/ProductConstructionService/ProductConstructionService.Common/ProductConstructionServiceExtension.cs, src/ProductConstructionService/ProductConstructionService.Common/RedisCacheClient.cs, test/Microsoft.DotNet.DarcLib.Tests/RemoteTests.cs, test/ProductConstructionService.DependencyFlow.Tests/PullRequestPolicyFailureNotifierTests.cs
For a given commit SHA, there can only be one source manifest. This commit adds SHA-based caching for SourceManifest files. It adds a redis cache client in DarcLib that acts as a no-op implementation in Darc, and the standard redis cache when called from the PCS.
https://github.com/dotnet/arcade-services/issues/4737#issue-3018184105
=> Cache SourceManifests by their commit

eng/templates/stages/deploy.yaml
Missed in https://github.com/dotnet/arcade-services/issues/5051
=> Use Windows 2022 in the deployment stage

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrCodeflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/GitOperationsHelper.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/VmrCodeFlowUpdatingPRsTests.cs
In https://github.com/dotnet/arcade-services/issues/5032, we found out that if we make a series of flows and the last one has a conflict with one that is not the most recent, we need to correctly reconstruct all the previous ones until we find the one that is conflicting with us. Then we base the PR branch before it and let users handle the config.
This PR makes the previous flow reconstructions algorithm work iteratively back until it finds the one where we can apply changes on top.
=> Reconstruct previous flows iteratively until conflicts are cleared

tools/ProductConstructionService.ReproTool/Operations/FlowCommitOperation.cs
Test changes were left behind in https://github.com/dotnet/arcade-services/issues/5119
Also fixes a bug with setting up the builds in the forwardflow subscriptions
=> Revert test changes in `FlowCommitOperation`

src/Microsoft.DotNet.Darc/DarcLib/Helpers/GitObjectType.cs, src/Microsoft.DotNet.Darc/DarcLib/ILocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/ILocalGitRepo.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitClient.cs, src/Microsoft.DotNet.Darc/DarcLib/LocalGitRepo.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CloneManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CodeFlowConflictResolver.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
Fixes a problem where when an already existing PR had existed, we'd never check out the `targetBranch` of a clone.
Later, when we were trying to update its `global.json` and other files, we were not able to retrieve the files from that branch as it didn't exist locally.
This PR makes sure the desired branch is fetched locally in our clone during clone preparation.
#5098
=> Assure requested branch exists locally in a clone

src/Microsoft.DotNet.Darc/Darc/Operations/VirtualMonoRepo/ResetOperation.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrForwardFlower.cs
Found an exception in the service:
```
"Problem": Microsoft.DotNet.DarcLib.Helpers.ProcessFailedException at Microsoft.DotNet.DarcLib.Helpers.ProcessExecutionResult.ThrowIfFailed:15,
"Message": Failed to remove files from /mnt/datadir/tmp/sdk
Exit code: 1
Std err:
error: the following file has local modifications:
src/Microsoft.CodeAnalysis.NetAnalyzers/README.md
(use --cached to keep the file, or -f to force removal)
```
=> Force-remove files when flowing opposite direction

.github/ISSUE_TEMPLATE/rollout-issue.md
We changed the pipeline names in https://github.com/dotnet/arcade-services/issues/5153, this is just reflecting those changes in the rollout issue template
=> Update rollout issue template

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CloneManager.cs
Resolves the following frequent exception:
> Failed to check out 3ac608c737eabed78486ee3fe598e76a889b6015 in /mnt/datadir/tmp/E1F74BB5AEE5F69C
Exit code: 1
Std err:
error: Your local changes to the following files would be overwritten by checkout:
src/Microsoft.CodeAnalysis.NetAnalyzers/README.md
Please commit your changes or stash them before you switch branches.
Aborting
We do clean after the checkout but if the repo had all the right refs already and was dirty, it does not work
=> Handle dirty working tree when checking out clones

test/Microsoft.DotNet.DarcLib.Codeflow.Tests/CodeFlowTestsBase.cs, test/Microsoft.DotNet.DarcLib.Codeflow.Tests/TwoWayCodeflowTests.cs
https://github.com/dotnet/arcade-services/issues/5148
Fixed the title
~~Scenario test for opposite flow merged during open PR~~ -> Codeflow test for opposite flow merged during open PR
=> Codeflow test for opposite flow merged during open PR

Directory.Build.props
Change `DebugType` compiler prop to fix BarViz not being debuggable in VS and VS Code
=> Fix BarViz debugging

Directory.Build.props
Visual Studio was recommending C# 14 features which would not build in CI and in the docker container that has .NET 8
=> Set C# version to 12.0 in `Directory.Build.props`

src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/CloneManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs, src/Microsoft.DotNet.Darc/DarcLib/VirtualMonoRepo/VmrBackflower.cs, src/ProductConstructionService/ProductConstructionService.Api/Configuration/MaestroAuthTestRepositoryExtensions.cs, src/ProductConstructionService/ProductConstructionService.DependencyFlow/PcsVmrBackFlower.cs, test/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
I found 2 problems in how we handle cloning:
- `PcsVmrBackflower` has its own `PrepareRepoAndVmr` which is almost the same as `VmrBackflower` except it does not check out the SHA of the last flow correctly. I guess we do check it out later somewhere because otherwise I don't know how this would work.
- When calling `darc vmr backflow`, we might end up cloning the repo into TMP instead of properly using the one the user is targeting with the command. Then we fetch the needed commits into the TMP one and fail to find the commits later in the one the user specified.
#5312
=> Fix re-use of existing clones

Directory.Packages.props
Resolves a CG alert: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-arcade-services/alert/11630022?typeId=6567134&pipelinesTrackingFilter=0
=> Update Aspire to `9.5.1`

src/Microsoft.DotNet.Darc/Darc/Operations/UpdateDependenciesOperation.cs
https://github.com/dotnet/arcade-services/issues/5221 fixes a bug introduced in https://github.com/dotnet/arcade-services/pull/5340 where there's an NRE if there are no excluded assets
=> Fix darc update-dependencies NRE
