dotnet/arcade-services

- src/Maestro/DependencyUpdater/DependencyUpdater.cs
- src/Maestro/Maestro.Contracts/IDependencyUpdater.cs
- src/Maestro/Maestro.Data/Migrations/20181120175727_add_NonShippingBit.Designer.cs
- src/Maestro/Maestro.Data/Migrations/20181120175727_add_NonShippingBit.cs
- src/Maestro/Maestro.Data/Models/Asset.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/AssetsController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/SubscriptionsController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/Asset.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/AssetData.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/SubscriptionData.cs
- src/Maestro/Maestro.Web/RepositoryUrlAttribute.cs
- src/Maestro/tests/DependencyUpdater.Tests/CheckSubscriptionsAsyncTests.cs
- src/Maestro/tests/DependencyUpdater.Tests/UpdateDependenciesAsyncTests.cs
- src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs
- src/Maestro/tests/SubscriptionActorService.Tests/SubscriptionOrPullRequestActorTests.cs
- https://github.com/dotnet/arcade/pull/1378
> Port recent changes from arcade:

- BlobFeed.pushproj
- azure-pipelines.yml
Here are the bits I believe we need for publishing darc
Some of these bits (in particular, packing up the darc artifact, and the BlobFeed.pushproj) 
are to be used in the release definition as part of shipping to production.
> Darc publishing

- azure-pipelines.yml
- eng/BlobFeed.pushproj
The existing import has a target, let's just use it.
> Fix publish project

- azure-pipelines.yml
Avoid "waiting for exclusive lock on feed" problem.
> Temporarily switch feed url

- azure-pipelines.yml
https://github.com/dotnet/arcade-services/issues/59
> Disable stable package generation and tagging

- src/Microsoft.DotNet.Darc/src/DarcLib/Microsoft.DotNet.DarcLib.csproj
Reverts dotnet/arcade-services#58
> Revert "Downgrade client to stable version"

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/TriggerSubscriptionsOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/TriggerSubscriptionsCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/Darc/Program.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs
Allow for command line triggering of subscriptions by id, or by specific criteria
> Trigger subscription command

- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/AssetsController.cs
Closes: https://github.com/dotnet/arcade/issues/1796
The publishing pipeline will be able to add/remove asset locations for an asset.
> Add API to add/remove asset locations for an asset

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyGraphOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/GetDependencyGraphCommandLineOptions.cs
Added this to help out Mark this morning, figured it was worth keeping around
> Add option to log GraphViz output

- eng/Version.Details.xml
- eng/Versions.props
The Microsoft.DotNet.Maestro.Tasks version was not updated since the repo was not correct
> Updating Version files

- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/AssetsController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/BuildsController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/ChannelsController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/DefaultChannelsController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/PipelinesController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/RepositoryController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/SubscriptionsController.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/BuildsController.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/SubscriptionsController.cs
- src/Maestro/Maestro.Web/Pages/SwaggerUi.cshtml
- src/Maestro/Maestro.Web/Startup.Api.cs
- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/Microsoft.AspNetCore.ApiVersioning.Swashbuckle/ConfigureSwaggerVersions.cs
- src/Maestro/Microsoft.AspNetCore.ApiVersioning.Swashbuckle/Microsoft.AspNetCore.ApiVersioning.Swashbuckle.csproj
- src/Maestro/Microsoft.AspNetCore.ApiVersioning.Swashbuckle/SwaggerApiResponseAttribute.cs
- src/Maestro/Microsoft.AspNetCore.ApiVersioning/ApiVersioningOptions.cs
This change fixes a bug caused by SwaggerResponseAttribute getting inherited.
> Fix SwaggerResponseAttribute inheritance

- src/Maestro/update-database.ps1
> Releases are now picking sometimes up the 2.2 SDKs and the subpath to ef.dll is different

- src/Maestro/Maestro.Data/Models/Repository.cs
- src/Maestro/Maestro.Data/Models/Subscription.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/AssetsController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/BuildsController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/ChannelsController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/DefaultChannelsController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/PipelinesController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/RepositoryController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/SubscriptionsController.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/BuildsController.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/SubscriptionsController.cs
- src/Maestro/Maestro.Web/Startup.Api.cs
- src/Maestro/Microsoft.AspNetCore.ApiVersioning.Swashbuckle/ConfigureSwaggerVersions.cs
- src/Maestro/Microsoft.AspNetCore.ApiVersioning.Swashbuckle/SwaggerApiVersioningExtensions.cs
This change adds documentation comments to all the Maestro APIs that will get included in the swagger document.
> Add documentation for all controller actions

- src/Maestro/SubscriptionActorService/PullRequestActor.cs
Closes https://github.com/dotnet/arcade/issues/2025
> Handle not found subscriptions

- src/Microsoft.DotNet.Darc/src/Darc/Operations/SubscriptionStatusOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/SubscriptionStatusCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/Darc/Program.cs
Closes https://github.com/dotnet/arcade/issues/2034
> Add operation to enable/disable subs

- src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs
> Fix update-dependencies

- src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs
Fixes arcade's official builds
> Handle build==null cases

- src/Microsoft.DotNet.Darc/src/Darc/Helpers/LocalSettings.cs
- src/Microsoft.DotNet.Darc/src/Darc/Helpers/RemoteFactory.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyGraphOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Properties/launchSettings.json
- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/AzureDevOpsClient.cs
Found these while running darc in my box.
> Fix random bugs

- src/Microsoft.DotNet.Darc/src/Darc/Helpers/RemoteFactory.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/TriggerSubscriptionsOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/SubscriptionsCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/Darc/Properties/launchSettings.json
- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
> Output batchable and enabled info for subscriptions

- Directory.Build.props
- src/Maestro/Maestro.Contracts/Maestro.Contracts.csproj
- src/Maestro/Maestro.Data/Maestro.Data.csproj
- src/Maestro/ServiceFabricMocks/ServiceFabricMocks.csproj
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Microsoft.DotNet.ServiceFabric.ServiceHost.csproj
Related to arcade's https://github.com/dotnet/arcade/issues/393
> Upgrade TMF to net472

- src/Maestro/Maestro.Data/Models/Build.cs
Have to insert the build before trying to insert the buildchannel, otherwise we won't have the build.buildid
> Insert build before trying to insert buildchannel

- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/maestro-angular/package-lock.json
Since the publish using pipelines feature is opt-in, Maestro++ should only trigger the pipeline if the build is marked with PublishUsingPipelines.
> Only trigger pipeline if build is onboarded with publish using pipelines

- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs
This was causing 400s in POST and PUT requests
> Include content type in http message

- src/Maestro/Maestro.Web/.config/settings.Production.json
- src/Maestro/Maestro.Web/.config/settings.json
- src/Maestro/Maestro.Web/Controllers/AzDevController.cs
- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/maestro-angular/proxy.conf.json
- src/Maestro/maestro-angular/src/helpers.ts
- Proxy api requests from the Website to prod in staging and local dev
- change topologicalSort to be breadth-first rather than depth-first
> More BAR visualization fixes

- src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs
These may be visualstudio.com URLs
Currently breaking aspnet's updates.
> Normalize urls sent to DarcRemoteFactory

- src/Maestro/SubscriptionActorService/MaestroBarClient.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/AddBuildToChannelCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/Darc/Program.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
Adds a build to a specific channel and then let's the user know what will happen.
> add-build-to-channel

- src/Maestro/Maestro.Web/Api/v2018_07_16/Models/Channel.cs
- src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html
- src/Maestro/maestro-angular/src/app/page/build/build.component.html
- src/Maestro/maestro-angular/src/app/page/build/build.component.ts
- src/Maestro/maestro-angular/src/app/services/channel.service.ts
- src/Maestro/maestro-angular/src/app/widget/side-bar-channel/side-bar-channel.component.html
- src/Maestro/maestro-angular/src/app/widget/side-bar-channel/side-bar-channel.component.ts
- src/Maestro/maestro-angular/src/app/widget/side-bar/side-bar.component.html
- src/Maestro/maestro-angular/src/app/widget/side-bar/side-bar.component.ts
- src/Maestro/maestro-angular/src/stateful/stateful.directive.ts
- src/Maestro/maestro-angular/src/styles.scss
- Add info for loading each section of the sidebar
- Animate the opening of the sidebar sections
- Include all non-test channels
> Update the BAR vis sidebar

- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs
Fixes graph generation cases like: https://dnceng.visualstudio.com/internal/_build/results?buildId=130867 where we cleared values on dependencies when we shouldn't had to like https://github.com/aspnet/EntityFrameworkCore/commit/43223fa3fc317cc25d47a4c15f3db69f22b4a73d#diff-5c6a1c77fe216efcfbbdccb11b863063
> Handle empty field cases

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Part 1 of fix of: https://github.com/dotnet/corefx/issues/36248
I'll also need to update https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/Versions.props once this change is in and also pass the RepoName to the task in https://github.com/dotnet/arcade/blob/master/src/Microsoft.DotNet.Arcade.Sdk/tools/SdkTasks/PublishBuildAssets.proj
> If provided, use the repo path

- src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html
- src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts
- src/Maestro/maestro-angular/src/app/page/build/build.component.ts
- src/Maestro/maestro-angular/src/helpers.ts
- Dependency Table help conflicting build icon matches the icon in the table now
- Build and Commit links use the same code and are correct now
> Fix bar visualization bugs

- src/Maestro/Maestro.Data/Models/Build.cs
https://github.com/dotnet/arcade/issues/2301
Only insert unique Default Channels when inserting into the DB.
> Add Distinct to BuildChannel insertion

- eng/Version.Details.xml
- eng/Versions.props
- src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
- src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.csproj
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/AzureDevOps/AzureDevOpsRelease.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/AzureDevOps/AzureDevOpsReleaseStatus.cs
Fixes: https://github.com/dotnet/arcade/issues/2303
> File a GH issue when a release pipeline fails

- src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
Correctly acquire the token based on the installation. Also adding more logs to make debugging easier.
> Add more logs and generate new tokens

- src/Maestro/ReleasePipelineRunner/.config/settings.json
- src/Maestro/ReleasePipelineRunner/Program.cs
- src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
- src/Maestro/SubscriptionActorService/Program.cs
These missing service settings were causing InvalidOperation exceptions avoiding that GH issues were effectively filed.
> Add missing service configurations

- eng/Version.Details.xml
- eng/Versions.props
- eng/common/PublishToSymbolServers.proj
- eng/common/templates/phases/publish-build-assets.yml
- global.json
- src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
It's only the retry change and Arcade updates. Should be helpful to diagnose some issues we've been seeing, and see if we should add this retry to other Octokit operations.
> Merge master into production

- README.md
Documentation for best practices when using BARViz
> Best practices for BARViz

- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/maestro-angular/proxy.conf.json
- src/Maestro/maestro-angular/src/app/app.module.ts
- src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.html
- src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts
- src/Maestro/maestro-angular/src/app/page/build/build.component.html
- src/Maestro/maestro-angular/src/app/page/build/build.component.ts
- src/Maestro/maestro-angular/src/app/pipes/build-link.pipe.spec.ts
- src/Maestro/maestro-angular/src/app/pipes/build-link.pipe.ts
- src/Maestro/maestro-angular/src/app/pipes/commit-link.pipe.spec.ts
- src/Maestro/maestro-angular/src/app/pipes/commit-link.pipe.ts
- src/Maestro/maestro-angular/src/helpers.ts
- Set ApplicationName in the data protection config to fix issues reading the cookie on multiple machines
- Change the build commit links to point to github if it is avaliable
- Make favicon.ico work with local dev
- Monospace the commit links and abbreviate them
- Stop text wrapping in the dependency table
> Fix more BARViz problems

- src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
Fixes https://github.com/dotnet/arcade/issues/2529
> Filter out builds with unknown channels

- src/Maestro/tests/Scenarios/README.md
- src/Maestro/tests/Scenarios/all.ps1
- src/Maestro/tests/Scenarios/common.ps1
- src/Maestro/tests/Scenarios/githubflow-release-pipeline-nonbatched.ps1
fixes https://github.com/dotnet/arcade/issues/2319
Runs a very simple release pipeline https://dnceng.visualstudio.com/internal/_release?view=all&_a=releases&definitionId=45 and waits for PR creation.
> add e2e test for release pipeline runner

- src/Maestro/maestro-angular/package-lock.json
- src/Maestro/maestro-angular/package.json
- src/Maestro/maestro-angular/src/app/app.module.ts
- src/Maestro/maestro-angular/src/app/page/asset-table/asset-table.component.html
- src/Maestro/maestro-angular/src/app/page/asset-table/asset-table.component.scss
- src/Maestro/maestro-angular/src/app/page/asset-table/asset-table.component.spec.ts
- src/Maestro/maestro-angular/src/app/page/asset-table/asset-table.component.ts
- src/Maestro/maestro-angular/src/app/page/build/build.component.html
- src/Maestro/maestro-angular/src/themes/_base.scss
This change paginates the build assets table to avoid breaking the page when many assets are shown.
> Add pagination to the build assets table

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Closes: https://github.com/dotnet/arcade/issues/2521
The current implementation does not actually add the AssetLocationData to the locations list.
> Fix refactoring mistake - Assets are dropping AssetLocations

- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/DefaultChannelsController.cs
Subscription -> DefaultChannel
> Fix incorrect return type

- src/Maestro/Maestro.MergePolicies/MergePolicyServiceCollectionExtensions.cs
- src/Maestro/Maestro.MergePolicies/NoRequestedChangesMergePolicy.cs
- src/Microsoft.DotNet.Darc/src/Darc/Constants.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/AddSubscriptionCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/Review.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/ReviewState.cs
Adds a merge policy which disallows merges if changes are requested or the PR is rejected altogether
> Implement "no changes requested" merge policy

- src/Maestro/Client/src/Generated/Models/UpdateFrequency.cs
- src/Microsoft.DotNet.Darc/src/Darc/Constants.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetDependencyFlowGraphOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/AddSubscriptionCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/GetDependencyFlowGraphCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
:watch: depends on https://github.com/dotnet/arcade-services/pull/390
Adds support to the darc client for using new subscription frequencies.
@mmitche
> [client] Add twiceDaily and everyWeek subscription frequencies 

- src/Maestro/tests/Scenarios/all.ps1
- src/Maestro/tests/Scenarios/arcade-update.ps1
- src/Maestro/tests/Scenarios/azdoflow-batched.ps1
- src/Maestro/tests/Scenarios/azdoflow-nonbatched-all-checks-successful.ps1
- src/Maestro/tests/Scenarios/azdoflow-nonbatched-require-checks.ps1
- src/Maestro/tests/Scenarios/common.ps1
- src/Maestro/tests/Scenarios/githubflow-batched.ps1
- src/Maestro/tests/Scenarios/githubflow-nonbatched-all-checks-successful.ps1
- src/Maestro/tests/Scenarios/githubflow-nonbatched-require-checks.ps1
- src/Maestro/tests/Scenarios/githubflow-nonbatched-with-coherency.ps1
- src/Maestro/tests/Scenarios/githubflow-nonbatched.ps1
- src/Maestro/tests/Scenarios/githubflow-release-pipeline-nonbatched.ps1
* Add tests for merge policies, arcade specific dependency flow, batched subscriptions
* Remove verbose output when deleting resources
* Some more refactoring of common scripts for reusability
> Add more scenario tests

- src/Microsoft.DotNet.Darc/src/Darc/Constants.cs
- src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/AddSubscriptionPopUp.cs
- src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/SubscriptionPopUp.cs
- src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/UpdateSubscriptionPopUp.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddSubscriptionOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateSubscriptionOperation.cs
- Fix update and add subscription dialogs to work properly (there were issues with the JToken handling before).
- Ensure that the Standard merge policy actually works.
- Fix some of the merge policy help
> Various subscription fixes

- src/Maestro/maestro-angular/src/app/page/build-graph-table/build-graph-table.component.ts
Tracks toggle events in Application Insights with the following information: 
* Event Name: "featureEnabled" 
* Options: 
** featureName: showSubDependencies, includeToolsets
** featureState: boolean
> Telemetry around toggles on build page

- src/Maestro/Client/src/Generated/PagedResponse.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
The paging generator assumes the link header will exist
Change builds to use the new paging scheme
> Fix paging

- src/Maestro/tests/Scenarios/common.ps1
> Better fix to subscription creation during scenario tests

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetAssetOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/GetAssetCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/Darc/Program.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
Simple lookup for assets, useful for answering random questions
> Add command get-asset to get information on assets

- src/Maestro/Maestro.Web/Controllers/AzDevController.cs
- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
Solves [#181 in dnceng](https://dev.azure.com/dnceng/internal/_workitems/edit/181).
> Add X.509 certificate revocation check

- src/Maestro/DependencyUpdater/DependencyUpdater.csproj
- src/Maestro/Maestro.Contracts/Maestro.Contracts.csproj
- src/Maestro/Maestro.Web/Maestro.Web.csproj
- src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.csproj
- src/Maestro/ServiceFabricMocks/ServiceFabricMocks.csproj
- src/Maestro/SubscriptionActorService/SubscriptionActorService.csproj
- src/Maestro/maestro-angular/package-lock.json
- src/Maestro/maestro-angular/package.json
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Microsoft.DotNet.ServiceFabric.ServiceHost.csproj
OSS  package updates for arcade-services.
> OSS Package Updates

- eng/Versions.props
- src/Maestro/maestro-angular/package-lock.json
- src/Maestro/maestro-angular/package.json
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/FixedApplicationInsigthtsLoggerProvider/FixedApplicationInsightsLoggerFactoryExtensions.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/FixedApplicationInsigthtsLoggerProvider/FixedApplicationInsightsLoggerProvider.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Microsoft.DotNet.ServiceFabric.ServiceHost.csproj
Second set of packages that need to be updated due to OSS review.
> OSS Package Updates Round 2

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
I'll need publish to BAR to expose this value to AzDO so I can forward the ID to subsequent stages in the pipeline.
> Expose BAR BuildId and default channel list to AzDO

- eng/Versions.props
- src/Maestro/Client/src/Generated/MaestroApi.cs
- src/Maestro/Client/src/Generated/PagedResponse.cs
Closes: https://github.com/dotnet/arcade/issues/2922
> Use latest swagger generator

- azure-pipelines.yml
Relates to: https://github.com/dotnet/arcade/issues/3016
> On-board in yaml-based publishing

- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs
More https://github.com/dotnet/arcade/issues/2174
As of https://github.com/dotnet/arcade/pull/3140 the asset locations include the suffix.
> add service index suffix to ManagedFeed matching regex

- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs
Also moves things a bit so we don't do unnecessary work if there aren't any feeds and fixes a small typo.
> Only add managed feed comments if there are any feeds

- azure-pipelines.yml
Test Build - https://dev.azure.com/dnceng/internal/_build/results?buildId=243667&view=results
> Turn on SDL for Arcade-Services

- src/Maestro/tests/Scenarios/all.ps1
- src/Maestro/tests/Scenarios/arcade-update.ps1
- src/Maestro/tests/Scenarios/azdoflow-batched.ps1
- src/Maestro/tests/Scenarios/azdoflow-nonbatched-all-checks-successful.ps1
- src/Maestro/tests/Scenarios/azdoflow-nonbatched.ps1
- src/Maestro/tests/Scenarios/channels.ps1
- src/Maestro/tests/Scenarios/clone.ps1
- src/Maestro/tests/Scenarios/common.ps1
- src/Maestro/tests/Scenarios/githubflow-batched.ps1
- src/Maestro/tests/Scenarios/githubflow-nonbatched-all-checks-successful.ps1
- src/Maestro/tests/Scenarios/githubflow-nonbatched-with-coherency.ps1
- src/Maestro/tests/Scenarios/githubflow-nonbatched.ps1
- src/Maestro/tests/Scenarios/githubflow-release-pipeline-nonbatched.ps1
A few modifications to the powershell scripts to bring them up to standards
> Fix up powershell scripts

- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs
Closes: https://github.com/dotnet/arcade/issues/3220
> Parse / recognize azure storage proxy feeds

- src/Maestro/tests/Scenarios/all.ps1
Disabling until https://github.com/dotnet/arcade/issues/324 is fixed
> Disable AzdoFlow-nonbatched-all-checks-successful test

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Closes: https://github.com/dotnet/arcade/issues/3228
> Search only for .xml files when looking for manifests

- src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs
Fixes the Remote portion of https://github.com/dotnet/arcade/issues/2862
Respect the file's mode when creating the commit.
> Respect Git file mode during dependency updates

- azure-pipelines.yml
> Re-enable sdl

- src/Maestro/SubscriptionActorService/SubscriptionActor.cs
Related to https://github.com/dotnet/arcade/issues/3379
Check if the subscription was found in the DB before trying to update.
> Check if subscription exists before trying to update it

- src/Maestro/Maestro.Web/PackageRoot/Config/Settings.xml
https://github.com/dotnet/arcade/issues/3391
Making the fix in Master so we have some time to test if this breaks anything.
> Increase Maestro.Web timeout

- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LocalHelpers.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs
Avoid what I think is a credential manager popup in Service fabric
> Do not ask for password

- src/Maestro/tests/Scenarios/common.ps1
- src/Maestro/tests/Scenarios/githubflow-nonbatched.ps1
Make the PR validation go through the array comparison codepath
> Fix scenario tests

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Relates to: https://github.com/dotnet/arcade/issues/3757
> Make darc gather drop works with AzDO nuget feeds

- src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
Instead of processing one item at a time, process all items in the RP queue each pass.
The previous behavior was fine until we ended up with lots of builds on stages. This caused a lot of requeuing, as builds were not yet finished when they went through the RP runner the first time around. This caused the queue length to increase, and significant delays starting the release pipelines
> Process all items in RP queue

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Parallelize the download of a single build within the drop. This drastically improves the performance of gather drop (order of magnitude maybe). Also introduce a string buffer per asset so that this doesn't cause egregious interleaving of console output.
> Improve gather-drop performance

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
When I increased the amount of parallelism in gather-drop, I found a few cases where we may have been getting throttled and the downloads halted. When --skip-existing is passed, this means a subsequent download might not download a file which was half downloaded from the previous run. Instead of downloading directly to the target file, use a temporary file and move to the target file.
> Use a temporary file when downloading in gather-drop

- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
We cannot just look up assets by name and version. The sha must also be taken into account because the same version may be produced across multiple shas.
> Fix asset location lookup

- src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
Reverts dotnet/arcade-services#625
> Revert "Process all items in RP queue"

- src/Maestro/Microsoft.AspNetCore.ApiVersioning.Analyzers/Microsoft.AspNetCore.ApiVersioning.Analyzers.csproj
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/Microsoft.DotNet.Maestro.Tasks.csproj
Fix NuGet errors introduced by updating to Preview 9 SDK
> Set SuppressDependenciesWhenPacking

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetAssetOperation.cs
List the locations with get-asset to help determine where assets are without going to the swagger page
> List locations with get-asset

- arcade-services.sln
- eng/Versions.props
- src/Microsoft.DotNet.Metrics/ApplicationInsightsMetricTracker.cs
- src/Microsoft.DotNet.Metrics/IMetricTracker.cs
- src/Microsoft.DotNet.Metrics/Microsoft.DotNet.Metrics.csproj
We might want to switch to Kusto soon for these (or some other source)
and I don't want to propigate hard dependencies to AppInsights everywhere
so let's abstract it away
> Add IMetricTracker for tracking metrics

- src/Maestro/Maestro.Web/Startup.cs
Reverts dotnet/arcade-services#496
> Revert "[HOTFIX] Special case ASPNetCore to trigger dependency updates for assets with…"

- src/Maestro/Client/src/Generated/Assets.cs
- src/Maestro/Client/src/Generated/Builds.cs
- src/Maestro/Client/src/Generated/Channels.cs
- src/Maestro/Client/src/Generated/DefaultChannels.cs
- src/Maestro/Client/src/Generated/Models/AssetLocation.cs
- src/Maestro/Client/src/Generated/Models/AssetLocationData.cs
- src/Maestro/Client/src/Generated/Models/Build.cs
- src/Maestro/Client/src/Generated/Models/BuildGraph.cs
- src/Maestro/Client/src/Generated/Models/SubscriptionData.cs
- src/Maestro/Client/src/Generated/Models/SubscriptionPolicy.cs
- src/Maestro/Client/src/Generated/Pipelines.cs
- src/Maestro/Client/src/Generated/Repository.cs
- src/Maestro/Client/src/Generated/Subscriptions.cs
- src/Maestro/SubscriptionActorService/MaestroBarClient.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs
Fixes issues with VS 16.3 and use of "default" in comparisons.
> Update client using new generator

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/TriggerSubscriptionsOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/SubscriptionsCommandLineOptions.cs
- Filter by update frequency
- Filter by subscriptions that target branches+repos that will apply default to specific channels
> Additional subscription filters

- src/Maestro/Client/src/Generated/Assets.cs
- src/Maestro/Client/src/Generated/Builds.cs
- src/Maestro/Client/src/Generated/DefaultChannels.cs
- src/Maestro/Client/src/Generated/Pipelines.cs
- src/Maestro/Client/src/Generated/Repository.cs
- src/Maestro/Client/src/Generated/Subscriptions.cs
Regenerate client after latest round of fixes for nullable types
> Regenerate client

- src/Maestro/maestro-angular/src/app/services/channel.service.ts
Fixes https://github.com/dotnet/arcade/issues/4059
The repository list was generated speculatively by combining subscriptions and default channels.  This would create repositories listed in a channel which didn't have any actual builds and that would cause an infinite spinner.  This change, instead, just grabs the builds from a channel and uses those builds to determine the repository list.
> Use builds in a channel to determine repository list

- src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.cs
During the 3.0 GA timeframe, we worked around an issue where maestro could not launch the legacy release pipeline for builds coming from other AzDO orgs (specifically msbuild and roslyn). This worked fine and builds got assigned to the appropriate channels, but there was a missed call to trigger dependency updates for any EveryBuild subscription. Thus, updates for those repos currently have to be triggered manually.
> [production] Fix everyBuild subscriptions pulling from other orgs

- azure-pipelines.yml
Also move SDL settings into a variable group
> Update AreaPath for SDL Tool runs

- src/Maestro/maestro-angular/src/app/app.component.html
Closes: https://github.com/dotnet/arcade/issues/4243 
Closes: https://github.com/dotnet/core-eng/issues/8194
> Update authentication error message

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Corner case where a download failure would cause darc to crash
> Only delete target file if exists

- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
This will help with diagnosing https://github.com/dotnet/arcade/issues/4193
> [HOTFIX] Add extra logging for arcade dependency update PR inconsistencies

- azure-pipelines.yml
- eng/deploy.yaml
- grafana-setup.yml
- src/DotNet.Status.Web/InMemoryCacheInstallationLookup.cs
- src/Dotnet.Status.Web/Controllers/AlertHookController.cs
- src/Dotnet.Status.Web/GitHubUserTokenHandler.cs
- src/Dotnet.Status.Web/Startup.cs
- src/Dotnet.Status.Web/appsettings.Production.json
- src/Dotnet.Status.Web/appsettings.json
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubAppTokenProvider.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubTokenProvider.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/ServiceCollectionExtensions.cs
- src/Shared/Microsoft.DotNet.Web.Authentication/ContextAwareAuthenticationSchemeProvider.cs
- "ok" alerts didn't update state
- app token caused circular reference
- some yaml wasn't quite right yet
> Fix issues found during validate

- src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHost.cs
ASP.NET keeps making more interfaces, inject them all so various versions all find what they need
> Fix DI for actors

- azure-pipelines.yml
- eng/deploy.yaml
My arcade build seems to be ok, but there is some failing test that's preventing me from getting to the last point, but it looks like it should work...
> Fix maestro endpoint

- src/DotNet.Status.Web/DotNet.Status.Web.csproj
- src/Maestro/Maestro.Data/Maestro.Data.csproj
- src/Maestro/Maestro.Web/Maestro.Web.csproj
- src/Maestro/ReleasePipelineRunner/ReleasePipelineRunner.csproj
- src/Maestro/SubscriptionActorService/SubscriptionActorService.csproj
We should match the casing in the directory structure.
FYI @garath @ChadNedzlek
> Fix casing of project references in csprojs

- src/Maestro/Maestro.Data/Models/GoalTime.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/GoalController.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Models/Goal.cs
Forgot to add headers for newly created files in my previous PR. Adding them
> Add headers to newly created files

- arcade-services.sln
Per the Validation Pattern, the scenario tests should exist in the solution for better visibility.
> Including scenario tests in the solution for better visibility

- src/Maestro/Readme.md
Add additional detail to the instructions to clarify which artifacts folder contains the required objects.
> Update Maestro database update instructions

- eng/Versions.props
- eng/convert-codecoveragetoxml.ps1
- eng/test.yaml
- src/Maestro/tests/DependencyUpdater.Tests/DependencyUpdater.Tests.csproj
- src/Maestro/tests/SubscriptionActorService.Tests/SubscriptionActorService.Tests.csproj
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Microsoft.DotNet.Darc.Tests.csproj
Added Microsoft.CodeCoverage package to test projects; programatically search for codecoverage.exe
> Code coverage improvements

- src/Maestro/SubscriptionActorService/PullRequestActor.cs
Closes: https://github.com/dotnet/arcade/issues/4441
> Add subscription ID to PR description

- src/DotNet.Status.Web/InMemoryCacheInstallationLookup.cs
- src/DotNet.Status.Web/Pages/Error.cshtml.cs
- src/DotNet.Status.Web/Pages/Status.cshtml
- src/DotNet.Status.Web/Pages/Status.cshtml.cs
* Installing the app in two places broke our lookup
* Any bad status turns into a 400 because of the antiforgery token on Status/Error
* Have status not return HTML when json is requested
> Fix up some lingering site issues

- src/Maestro/SubscriptionActorService/MaestroBarClient.cs
- src/Maestro/tests/Scenarios/common.ps1
- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/DeleteBuildFromChannelOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/DeleteBuildFromChannelCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/Darc/Program.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
- Add delete-build-from-channel
- Modify scenario tests to use darc rather the the darc commands for add and delete.
> darc functionality to remove builds from channels

- src/Monitoring/Microsoft.DotNet.Monitoring.Sdk.Tests/MakePackTests.cs
- src/Monitoring/Monitoring.ArcadeServices/datasource/Production/AI-dnc-eng.datasource.json
- src/Monitoring/Monitoring.ArcadeServices/datasource/Production/AI-grafana.datasource.json
- src/Monitoring/Monitoring.ArcadeServices/datasource/Production/AzureMonitor-helix.datasource.json
- src/Monitoring/Monitoring.ArcadeServices/datasource/Staging/AI-dnc-eng.datasource.json
- src/Monitoring/Monitoring.ArcadeServices/datasource/Staging/AI-grafana.datasource.json
- src/Monitoring/Monitoring.ArcadeServices/datasource/Staging/AzureMonitor-helix.datasource.json
- src/Monitoring/Sdk/GrafanaSerialization.cs
When the server tells us about "secure" values, it looks like:
```json
{
"secureJsonFields": {
"name": true
}
}
```
but when we post, we need to change it to
```json
{
"secureJsonData": {
"name": "value"
}
}
> When posting, it needs to be "Data", on get, it's "Fields"

- src/Monitoring/Sdk/GrafanaClient.cs
- src/Monitoring/Sdk/MonitoringPublish.cs
We are calling the "uid" endpoint using the normal id, which causes a 500
> Notification id uid

- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
> Compact the availability page a touch

- src/Maestro/Client/src/Generated/Assets.cs
- src/Maestro/Client/src/Generated/Builds.cs
- src/Maestro/Client/src/Generated/Repository.cs
- src/Maestro/Client/src/Generated/Subscriptions.cs
- src/Maestro/tests/Scenarios/all.ps1
Regenerate client to deal with https://github.com/dotnet/arcade/issues/4728
> Fix gather-drop and other get-builds operations.

- src/RolloutScorer/RolloutScorer/RolloutScorer.cs
- src/RolloutScorer/RolloutScorer/RolloutUploader.cs
- src/RolloutScorer/RolloutScorer/Utilities.cs
- src/RolloutScorer/RolloutScorer/config.json
- src/RolloutScorer/RolloutScorerAzureFunction/Configs.cs
Small bugfixes and changes to make warnings more useful.
> Rollout Scorer adjustments and fixes

- src/Maestro/Maestro.Web/Pages/Index.cshtml
- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/maestro-angular/src/app/app.component.html
- src/Maestro/maestro-angular/src/app/app.component.ts
- src/Maestro/maestro-angular/src/app/services/cookie.service.ts
This change adds a toggle in the user dropdown to enable/disable the api redirection to prod for the web ui.
> Enable turning off the api redirection to prod

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
During a --release gather-drop, generate the publish_files\nuget directory previously generated by @dagood's tool.
> Enable generation of nuget staging drop during gather-drop

- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddChannelOperation.cs
Also fix https://github.com/dotnet/arcade/issues/4670 in the process
> Add json support to add-channel

- src/RolloutScorer/RolloutScorerAzureFunction/Configs.cs
- src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerFunction.cs
Fixes dotnet/core-eng#9026.
Additionally, added a bunch of logging which will help debug issues like this in the future.
> Fix configuration bug; add more logging to aid with debugging in Azure

- src/Microsoft.DotNet.Darc/src/Darc/Operations/CloneOperation.cs
1. Break lines.
2. Add minor edits, move a few line breaks.
I did the breaks when I was trying to read this comment and understand the code, and figured I'd submit a PR with my edits.
> Improve comment for CloneOperation

- eng/deploy.yaml
Add a job that does nothing to make Azure DevOps happy
> Remove job dependencies (they are incorrect)

- src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateDependenciesOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/UpdateDependenciesCommandLineOptions.cs
Relates to : #4905
- Add new parameter to the operation
- Add new "else if" block to handle new parameter
- Factor out code from existing "else if" block that can be used in the new one
- Patch code to call new methods
Tested locally.
> Update dependencies based on BAR build id

- src/Maestro/SubscriptionActorService/Program.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Extensions.cs
Helix uses this pattern exclusively, so this will help reduce the change scope there.
> Add section fetching overload to Configure

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
- src/Shared/Microsoft.DotNet.Services.Utility/ExponentialRetry.cs
File.Delete will sometimes fail when pushing a drop to a UNC share. Add a retry for this
Fix a bug where if the first target file location in the list is missing, we'd not copy it on subsequent runs.
> Harden gather-drop

- src/Maestro/tests/Maestro.ScenarioTests/Maestro.ScenarioTests.csproj
- src/Maestro/tests/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
- src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Channels.cs
- src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_SdkUpdate.cs
- src/Maestro/tests/Maestro.ScenarioTests/TestHelpers.cs
- src/Maestro/tests/Maestro.ScenarioTests/TestParameters.cs
- Add Channel and Default Channel C# Maestro tests
- Port Maestro tests from XUnit to NUnit
> Switch Maestro tests to NUnit and add new tests

- src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/DeleteBuildFromChannelOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetAssetOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetBuildOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetLatestBuildOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateBuildOperation.cs
Add the ability to print json output for the get-asset operation.
> Support json for get-asset

- eng/import-grafana.ps1
This fetches the secrets from known vaults as the current user,
which simplifies the import process.
It's not part of the SDK itself, because the SDK is resource agnostic...
it doesn't care where the values come from.
> Add Grafana import helper script

- src/Maestro/DependencyUpdateErrorProcessor/.config/settings.Production.json
- src/Maestro/DependencyUpdateErrorProcessor/.config/settings.json
- src/Maestro/DependencyUpdateErrorProcessor/DependencyUpdateErrorProcessor.cs
- src/Maestro/DependencyUpdateErrorProcessor/DependencyUpdateProcessorOptions.cs
- src/Maestro/DependencyUpdateErrorProcessor/Program.cs
- src/Maestro/MaestroApplication/ApplicationPackageRoot/ApplicationManifest.xml
Calling the feature flag directly from the config.
> Feature Flag

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
When pushing to BAR, add a build tag for the BAR id
> Add BAR ID build tag

- azure-pipelines.yml
this is breaking the deployments.
> Remove the principals node too

- src/Maestro/Maestro.Data/Models/Build.cs
- src/Maestro/Maestro.Web/Startup.cs
Relates to: https://github.com/dotnet/arcade/issues/4725
We don't need this check anymore. It's been a few weeks that `autoBuildPromotion == false`.
> Remove AutoBuildPromotion infra

- src/DotNet.Status.Web/Controllers/AlertHookController.cs
- src/DotNet.Status.Web/InMemoryCacheInstallationLookup.cs
- src/DotNet.Status.Web/Startup.cs
- src/Maestro/DependencyUpdateErrorProcessor/DependencyUpdateErrorProcessor.cs
- src/Maestro/DependencyUpdateErrorProcessor/Program.cs
- src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs
- src/Maestro/Maestro.Data/BuildAssetRegistryRegistrations.cs
- src/Maestro/Maestro.Web/Controllers/WebHooksController.cs
- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs
- src/Maestro/SubscriptionActorService/Program.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubAppTokenProvider.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubClientFactory.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubHelper.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubTokenProvider.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubTokenProviderOptions.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/IGitHubTokenProvider.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/InstallationLookup.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/ServiceCollectionExtensions.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/StringPrivateKeySource.cs
Issue -> https://github.com/dotnet/core-eng/issues/9625
> Changing  Microsoft.Dotnet.GitHub.Authentication to  Microsoft.DotNet.GitHub.Authentication;

- src/Maestro/maestro-angular/package-lock.json
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DependencyGraph.cs
Reacting to this PR comment: https://github.com/dotnet/arcade-services/pull/1120#discussion_r412271319
> Adjust DependencyGraph dependency comparer

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Fixes https://github.com/dotnet/arcade/issues/5348
Use - instead of :
> Fix build tag logging command in PushMetadataToBuildAssetRegistry

- src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/Microsoft.DotNet.DarcLib.AzDev.csproj
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/ScheduledService/ScheduledService.cs
Try this. I see this exception in AI a lot, hopefully this is it?
@riarenas
> Don't need the whole IServiceScope, just the factory

- src/Maestro/DependencyUpdateErrorProcessor/PackageRoot/ServiceManifest.xml
- src/Maestro/DependencyUpdater/PackageRoot/ServiceManifest.xml
- src/Maestro/FeedCleanerService/PackageRoot/ServiceManifest.xml
- src/Maestro/Maestro.Web/PackageRoot/ServiceManifest.xml
- src/Maestro/SubscriptionActorService/PackageRoot/ServiceManifest.xml
- src/Telemetry/AzureDevOpsTimeline/PackageRoot/ServiceManifest.xml
This should help diagnosing weird crashes/exit codes
> Capture console output of services

- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Actors/DelegatedActor.cs
Fixes https://github.com/dotnet/core-eng/issues/9675
A subtle switcheroo in my PR
> We returned the proxy, causing an infitnire loop

- eng/common/sdl/init-sdl.ps1
- eng/create-tag.ps1
- src/Maestro/tests/Scenarios/common.ps1
- src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
Any hints on how to test this better are welcomed.
> Move from a soon-to-be-deprecated preview AzDO API

- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/RepositoryController.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/SubscriptionsController.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/SubscriptionsController.cs
- src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/SubscriptionsController.cs
- src/Maestro/Maestro.Web/Startup.cs
Fix https://github.com/dotnet/core-eng/issues/9718
> Fix IActorProxyFactory usage in the website

- eng/deploy.yaml
This is blocking the prod deployment from starting,
> [Hotfix] Darcbot deploy job should not depend on a stage

- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
Relates to: https://github.com/dotnet/arcade/issues/5408
- Check if the user specified "release/3.x" as --source-branch and if so warns and switch to "master"
- Check if promoting a build that uses an Arcade 3.x and if so warns and switch to "master"
> Switch to Arcade master branch when promoting a build that uses Arcade 3.x

- src/Maestro/SubscriptionActorService/PullRequestActor.cs
Issue -> https://github.com/dotnet/arcade/issues/4504
I did test this using scenario test. 
I was able to fit in the entire title, it is a minor fix. 
[internal/release/3.0.1xx] Update dependencies from dnceng/internal/_git/dotnet-core-setup
> Improve internal dependency flow titles

- src/Maestro/tests/Scenarios/azdoflow-batched.ps1
- src/Maestro/tests/Scenarios/common.ps1
- src/Maestro/tests/Scenarios/githubflow-batched.ps1
> Fix test for PR title

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Address https://github.com/dotnet/arcade/issues/5450
> Error out when duplicate entries are pushed to BAR

- eng/create-tag.ps1
- src/Maestro/tests/Scenarios/common.ps1
- src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
Issue => https://github.com/dotnet/arcade/issues/4126
> Update Azdo API from preview 5.0-preview.1/3 to release 5.0 version 

- azure-pipelines.yml
This reverts commit 3623a2eeb785e0f93d5428f113a157b7025c8ec7.
> Revert "Try adding RID (#1179)"

- azure-pipelines.yml
> Update nuget version to avoid cred issue

- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
Issue => https://github.com/dotnet/core-eng/issues/9535
Updated the dashboard to add Certification Expiration Panels for Pool provider Internal, Public with alerts.
> Certificate Expiration For Pool Provider Internal & Public 

- src/Maestro/Maestro.Web/.config/settings.Staging.json
This should hopefully break int like we broke master so we can diagnose it without fear of breaking customers.
I tried making local work like prod, but there are just so many "if IsDevelopment" that I can't get the behavior to happen.  Hopefully we can get it to work in staging, otherwise this is gonna be weird.
> Try to break master the same was as production

- src/DotNet.Status.Web/Startup.cs
- src/Maestro/Maestro.Web/Startup.cs
Rewrite has to come before Routing, and AuthN has to come before rewrite,
so let's try this order
> Rearrange uses

- src/Maestro/Maestro.Web/.config/settings.Staging.json
- src/Maestro/Maestro.Web/Startup.cs
Put staging back to the way it was
> Revert break int

- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
Fixes https://github.com/dotnet/core-eng/issues/10021. One character change.
> Fix maestro failed requests graph with mvexpand -> mv-expand

- src/Maestro/Readme.md
Fixes https://github.com/dotnet/arcade/issues/3958
Also changes the markdown numbered lists so they are easier to edit in the future.
> Update Maestro readme with Azure Development workload

- src/Maestro/Maestro.Web.Tests/ChannelsController20180716Tests.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/ChannelsController.cs
Fixes https://github.com/dotnet/core-eng/issues/10124
> Fix invalid Includes in older version of the ChannelsController

- src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs
- src/Maestro/Maestro.Web.Tests/BuildController20190116Tests.cs
Test and fix this particular failure
> Fix the BuildGraph query

- src/DotNet.Status.Web/appsettings.json
https://github.com/dotnet/core-eng/issues/9713
> Define environment labels field in base appsettings

- README.md
Quick fix for the links to the tests in the readme
> Fix tests links

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/Models/ManifestBuildData.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Using attributes from the manifests instead of expecting them as an input
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=724799&view=results
> Grab attributes from manifest

- src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/BuildsController.cs
Fixes issue noted while investigating other issues; not likely the cause of non-trigger subscriptions
> Fix Null ref noted in logging

- eng/deploy.yaml
- src/Maestro/tests/Maestro.ScenarioTests/Maestro.ScenarioTests.csproj
- src/Maestro/tests/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
- src/Maestro/tests/Maestro.ScenarioTests/ObjectHelpers/SubscriptionBuilder.cs
- src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Subscriptions.cs
- src/Maestro/tests/Maestro.ScenarioTests/TestHelpers.cs
- src/Maestro/tests/Maestro.ScenarioTests/TestParameters.cs
- src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs
Add maestro scenario subscription tests in the Post-Deployment test category
> Re-add subscription tests with category fix

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
To avoid things like https://dnceng.visualstudio.com/internal/_build/results?buildId=741565&view=logs&j=40e1e683-ea82-5be9-b25e-899b65e1c0cb&t=94a692ec-20f2-55dd-1884-cf0cad1763a4&l=19
> Only do MergedManifest stuff when PublishingVersion is >= v3

- src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
https://github.com/dotnet/core-eng/issues/10248
Always a good thing to not leak these. fixes them using the new fancy simplified using syntax.
Easier to review ignoring whitespace.
> stop leaking IDisposables in AzureDevOpsClient

- src/Maestro/Maestro.Web/Startup.Api.cs
- src/Maestro/maestro-angular/package-lock.json
https://github.com/dotnet/core-eng/issues/10119
Fixes swagger not sending the authorization header correctly.
Validated locally that I'm able to do authenticated requests now and the token is passed through
> Fix swagger bearer token

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/FileExtensionSignInfoComparer.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/FileSignInfoComparer.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/ItemsToSignComparer.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/Models/Manifest.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/StrongNameSignInfoComparer.cs
Adapting to change in https://github.com/dotnet/arcade/pull/5899
> Change `SigningInfo` `File` and `Extension` to `Include`

- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/FeedConstants.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/GitFileManager.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/GitFileManagerTests.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/AddFeedsToNuGetConfigWithoutManagedFeeds/NuGet.output.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/EnsureAppendsDisableEntryAfterLastClear/NuGet.input.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/EnsureAppendsDisableEntryAfterLastClear/NuGet.output.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/NonManagedDisabledFeedSources/NuGet.input.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/NonManagedDisabledFeedSources/NuGet.output.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/PreserveCommentsInRightLocationsWhenReplacing/NuGet.output.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/PreserveCommentsInRightLocationsWithNoExistingBlock/NuGet.output.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/PreserveManagedFromFromOutside/NuGet.output.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/RedisableCurrentlyEnabledIntSources/NuGet.input.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/RedisableCurrentlyEnabledIntSources/NuGet.output.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/RemoveAllManagedFeeds/NuGet.output.config
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/inputs/NugetConfigFiles/WhiteSpaceCorrectlyFormatted/NuGet.output.config
- Fix expected outputs XML files for existing tests to pass.
- Add test cases to make sure we hit all the branches in CreateOrUpdateDisabledSourcesBlock()
> Update disabledPackageSources node processing transport feed info

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetBuildOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/GetBuildCommandLineOptions.cs
Remove un-implemented BuildUri option, make repo match on substring
> Address https://github.com/dotnet/arcade/issues/5194 

- src/Microsoft.DncEng.Configuration.Extensions/ServiceConfigurationExtensions.cs
- src/Microsoft.DncEng.DeployServiceFabricCluster/ClusterDeployer.cs
- src/Microsoft.DncEng.DeployServiceFabricCluster/ClusterSettings.cs
I also fixed the storage account naming and included a function to get an appropriately configured AzureServiceTokenProvider that helix needs.
> Make cluster deploy support existing AI resource

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
https://dnceng.visualstudio.com/internal/_build/results?buildId=776740&view=results shows the MergedManifest.xml is created and has what we need but MergedManifest is not been pushed to BAR since the process was happening after the fact.
> Make sure assets are updated before push

- src/Maestro/Maestro.Web/Startup.Api.cs
OpenApi v3 doesn't support request body names natively.
This change adds an extension that contains the name so we can
use that name in the generator
> Add RequestBody name extension to swagger output

- src/Maestro/Client/src/Generated/Subscriptions.cs
- src/Maestro/DependencyUpdater/DependencyUpdater.cs
- src/Maestro/Maestro.Contracts/IDependencyUpdater.cs
- src/Maestro/Maestro.DataProviders/MaestroBarClient.cs
- src/Maestro/Maestro.Web.Tests/SubscriptionsController20200220Tests.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/SubscriptionsController.cs
- src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/SubscriptionsController.cs
- src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/SubscriptionsController.cs
- src/Maestro/SubscriptionActorService/MaestroBarClient.cs
- src/Maestro/maestro-angular/package-lock.json
- src/Microsoft.DotNet.Darc/src/Darc/Operations/TriggerSubscriptionsOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/TriggerSubscriptionsCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IBarClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
Addresses https://github.com/dotnet/arcade/issues/4906
> Add ability to specify BAR build id when triggering a subscription

- azure-pipelines.yml
https://github.com/dotnet/core-eng/issues/10679
> Dont deploy if not master or production branch

- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
In cases where:
- There are chains of coherency tied dependencies that share common ancestors
- The coherency constraints can't be satisfied.
- Strict coherency is in use
We will fail to update the common ancestor, but also fail to do so over and over.
And we will log each of these errors. To avoid unecessary duplication (it's hard
to avoid processing the ancestor more than once), de-dupe the errors.
> Improve strict coherency error messages

- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
This PR implements [#10407](https://github.com/dotnet/core-eng/issues/10407)
It fixes [previous PR](https://github.com/dotnet/arcade-services/pull/1363) that was [reverted](https://github.com/dotnet/arcade-services/pull/1366)
> Import new dashboard for DotNetEng Status Web

- src/Maestro/tests/Maestro.ScenarioTests/EndToEndFlowLogic.cs
- src/Maestro/tests/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
- src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Clone.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
- Add the C# version of the cloning ubertest
> Maestro Scenario Tests - Add cloning uber test

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/CertificatesSignInfoComparer.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/Models/Manifest.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
CertificatesSignInfo was added to the asset manifest so MergeManifest needs to know how to merge it.
Test run: https://dnceng.visualstudio.com/internal/_build/results?buildId=811497
> Include CertificatesSignInfo

- src/Maestro/Microsoft.AspNetCore.ApiVersioning.Analyzers/Microsoft.AspNetCore.ApiVersioning.Analyzers.csproj
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/CertificatesSignInfoComparer.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/Models/Manifest.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
- src/Maestro/maestro-angular/package-lock.json
- src/Maestro/maestro-angular/src/app/app.module.ts
- src/Maestro/maestro-angular/src/app/page/build/build.component.html
- src/Maestro/maestro-angular/src/app/page/build/build.component.ts
- src/Shared/Microsoft.DotNet.Web.Authentication/AccessToken/PersonalAccessTokenAuthenticationHandler.cs
- src/Shared/Microsoft.DotNet.Web.Authentication/AccessToken/PersonalAccessTokenEvents.cs
Master build being deployed: https://dnceng.visualstudio.com/internal/_build/results?buildId=811684&view=results
> [Rollout] Production rollout, Sept 16th, 2020

- src/Monitoring/Sdk/README.md
Fix documentation URLs to the staging and production Grafana instances.
> Fix Grafana URLs

- src/DotNet.Status.Web/TimelineIssueTriage.cs
> Additional labels, removing InTriage category

- Microsoft.DotNet.DarcLib.Tests/GitHubClientTests.cs
- Microsoft.DotNet.DarcLib.Tests/Microsoft.DotNet.DarcLib.Tests.csproj
- src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IGitRepo.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/LocalGitClient.cs
https://github.com/dotnet/arcade/issues/5629
Add basic class for GitHubClient tests and some tests for the modified function.
> Make GitHubClient only look at the most recent, actionable reviews

- src/Maestro/Maestro.Web/Api/v2020_02_20/Models/Commit.cs
- src/Maestro/maestro-angular/src/app/page/build/build.component.html
> trim commit message to 1st line

- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
https://github.com/dotnet/core-eng/issues/11068
> #11068: Updated  "Helix API Average Response Time" alert to new datasource

- eng/deploy.yaml
- eng/deployment/Deploy-FabricApplication.ps1
- eng/deployment/deploy.ps1
- eng/deployment/helpers.psm1
- src/Maestro/MaestroApplication/PublishProfiles/Int.xml
- src/Maestro/MaestroApplication/PublishProfiles/Prod.xml
https://github.com/dotnet/core-eng/issues/10696
> Change SF deploy to use certificate from key vault

- src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
I don't remember making this change but apparently I did. Possibly the culprit for the failing scenario test.
> Reverting inadvertant change to an async call

- src/Maestro/DependencyUpdater/DependencyUpdater.cs
- src/Maestro/maestro-angular/package-lock.json
Should help with https://github.com/dotnet/arcade/issues/5877
I changed the query so that we get less filtered data from the DB and do the filtering in memory instead.
The previous query was timing out after 30 seconds, and some adhoc testing by running the translated query manually shows it averages 31 seconds. This new DB query averages 8 seconds and relies on the service doing the filtering afterwards.
Let me know if you're interested and I'll paste what the old and new SQL queries look like.
> Change up the query to find subscriptions for a specified frequency to avoid DB timeouts

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
https://github.com/dotnet/arcade/issues/6404
> Unblock Nuget

- src/Maestro/DependencyUpdateErrorProcessor/Program.cs
- src/Maestro/DependencyUpdater/Program.cs
- src/Maestro/FeedCleanerService/Program.cs
- src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs
- src/Maestro/Maestro.Data/SqlServerDbContextOptionsExtensions.cs
- src/Maestro/Maestro.Web/Pages/Account/AccountController.cs
- src/Maestro/Maestro.Web/Startup.Auth.cs
- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/SubscriptionActorService/Program.cs
Based on Ricardo comment:
https://github.com/dotnet/core-eng/issues/11330#issuecomment-722458625
Additionally, two places using sql transactions, had to be wrapped into ExecutionStrategy as described here https://github.com/dotnet/core-eng/issues/11330#issuecomment-722458625
> Maestro - EnableRetryOnFailure option for EF SQL

- src/Maestro/DependencyUpdateErrorProcessor/Program.cs
- src/Maestro/DependencyUpdater/Program.cs
- src/Maestro/FeedCleanerService/Program.cs
- src/Maestro/Maestro.Data/BuildAssetRegistryContext.cs
- src/Maestro/Maestro.Data/SqlServerDbContextOptionsExtensions.cs
- src/Maestro/Maestro.Web/Pages/Account/AccountController.cs
- src/Maestro/Maestro.Web/Startup.Auth.cs
- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/SubscriptionActorService/Program.cs
master build: https://dnceng.visualstudio.com/internal/_build/results?buildId=884169&view=results
> [Rollout] Production rollout Nov 18th, 2020

- src/DotNet.Status.Web/TimelineIssueTriage.cs
Changing labels to better align with telemetry needs
> Changing issue labels

- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/IRemote.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/DependencyCoherencyTests.cs
Issue -> https://github.com/dotnet/arcade/issues/6651
> NullRef in Darc's DisambiguateAssetsAsync

- eng/deploy.yaml
Testing to see if the deploy.yaml is the correct spot to add this - there are several options and it's not entirely clear which one we use. Unless someone knows for sure I'm just going to try deploying this and see if it works (there another project that uses this approach for the settings that end up in the Configuration tab on Azure).
> Add WEBSITE_RUN_FROM_PACKAGE setting to Status site deployment

- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- src/Maestro/maestro-angular/package-lock.json
- src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
Master build: https://dev.azure.com/dnceng/internal/_build/results?buildId=943535&view=results
> [rollout] Rollout for January 13th, 2021

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DownloadedBuild.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/DarcManifestHelperTests.cs
See https://github.com/dotnet/arcade/issues/6640 for context
> Support partial releases by including dependency info for root builds of gather-drop

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DownloadedBuild.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/DarcManifestHelperTests.cs
This reverts commit d4664753159cf110092ce75f94c8d7b990708baa.
> Revert "Support partial releases by including name, commit, version, and repoUri data for all root builds in gather-drop. (#1507)"

- docs/DevGuide.md
- src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Builds.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DownloadedBuild.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/DarcManifestHelperTests.cs
Fixed the broken scenario test, and cleaned up the "how to run scenario tests" in the dev guide with my pain.
https://github.com/dotnet/arcade/issues/6640
See https://github.com/dotnet/arcade-services/blob/6da7750ec817e4f817ce68740e5f8286155cdf75/docs/DevGuide.md for updated dev guide changes.
> Support partial releases by including name, commit, version, and repo Uri data for all root builds in gather-drop.

- azure-pipelines.yml
I did miss one place in the YAML
> fix left-over reference to the deleted scenario tests during the build

- NuGet.config
- docs/DevGuide.md
- src/Maestro/tests/Maestro.ScenarioTests/MaestroScenarioTestBase.cs
- src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_Builds.cs
- src/Maestro/tests/Maestro.ScenarioTests/TestHelpers.cs
- src/Maestro/tests/Maestro.ScenarioTests/TestParameters.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/ManifestHelper.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/Darc/DownloadedBuild.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/DarcManifestHelperTests.cs
Master build being deployed: https://dev.azure.com/dnceng/internal/_build/results?buildId=986472&view=results
> [Rollout] Production rollout, Feb 17th, 2021

- src/Maestro/FeedCleanerService/FeedCleanerService.cs
- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/AddBuildToChannelOperation.cs
- src/Microsoft.DotNet.Darc/src/DarcLib.AzDev/AzureDevOpsClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs
Cherry-picking https://github.com/dotnet/arcade-services/pull/1538 for a second deployment today to fix issues seen when trying to open dependency update PRs
> [HOTFIX] Fix HttpRequest error handling in arcade-services (#1538)

- src/DotNet.Status.Web/Startup.cs
> Add security headers to DotNet.Status.Web

- src/Maestro/Maestro.Web.Tests/ChannelsController20180716Tests.cs
- src/Maestro/Maestro.Web.Tests/ChannelsController20200220Tests.cs
- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/ChannelsController.cs
- src/Maestro/Maestro.Web/Api/v2020_02_20/Controllers/ChannelsController.cs
https://github.com/dotnet/arcade/issues/7084
> Do not fail when repeatedly adding the same build to a channel

- src/RolloutScorer/RolloutScorer/RolloutUploader.cs
Fallout of https://github.com/dotnet/core-eng/issues/12484
> Target core-eng/main in RolloutScorer

- eng/Packages.props
- src/DotNet.Status.Web/appsettings.json
- src/Microsoft.DncEng.SecretManager.Tests/SecretManifestTests.cs
- src/Microsoft.DncEng.SecretManager/Microsoft.DncEng.SecretManager.csproj
- src/Microsoft.DncEng.SecretManager/SecretManifest.cs
Staging build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1048423&view=results
> [rollout] production rollout, March 24th, 2021

- eng/Packages.props
- src/Microsoft.DncEng.SecretManager.Tests/SecretManifestTests.cs
- src/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs
- src/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
- src/Microsoft.DncEng.SecretManager/InfoCommand.cs
- src/Microsoft.DncEng.SecretManager/Microsoft.DncEng.SecretManager.csproj
- src/Microsoft.DncEng.SecretManager/NameAttribute.cs
- src/Microsoft.DncEng.SecretManager/NamedObjectRegistry.cs
- src/Microsoft.DncEng.SecretManager/ParameterizedObject.cs
- src/Microsoft.DncEng.SecretManager/Program.cs
- src/Microsoft.DncEng.SecretManager/RotationContext.cs
- src/Microsoft.DncEng.SecretManager/SecretData.cs
- src/Microsoft.DncEng.SecretManager/SecretManifest.cs
- src/Microsoft.DncEng.SecretManager/SecretProperties.cs
- src/Microsoft.DncEng.SecretManager/SecretType.cs
- src/Microsoft.DncEng.SecretManager/SecretTypeRegistry.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageConnectionString.cs
- src/Microsoft.DncEng.SecretManager/SecretValue.cs
- src/Microsoft.DncEng.SecretManager/StorageLocationType.cs
- src/Microsoft.DncEng.SecretManager/StorageLocationTypeRegistry.cs
- src/Microsoft.DncEng.SecretManager/StorageTypes/AzureKeyVault.cs
- src/Microsoft.DncEng.SecretManager/TestCommand.cs
I still need to add logging and tests, but I wanted to get eyes on this.
> Add synchronize command and azure storage connection string type

- azure-pipelines.yml
The CG was turned off by mistake in #1545 and never ran since then
> Enable CG in internal pipeline

- src/Microsoft.DncEng.SecretManager.Tests/OneTimePasswordGeneratorTests.cs
- src/Microsoft.DncEng.SecretManager/OneTimePasswordGenerator.cs
- src/Microsoft.DncEng.SecretManager/PasswordGenerator.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubBotAccount.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/SqlServerConnectionString.cs
https://github.com/dotnet/core-eng/issues/12820
> #12820: Implement cycling secrets that require human interaction for github bot passwords

- eng/Packages.props
- src/DotNet.Status.Web/DotNet.Status.Web.csproj
- src/Maestro/Maestro.Web/Maestro.Web.csproj
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Microsoft.DotNet.ServiceFabric.ServiceHost.csproj
- src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerAzureFunction.csproj
- src/Shared/MIcrosoft.DotNet.Internal.Logging/Microsoft.DotNet.Internal.Logging.csproj
- src/Shared/Microsoft.DotNet.Internal.Testing.Utility/Microsoft.DotNet.Internal.Testing.Utility.csproj
https://github.com/dotnet/core-eng/issues/12829
> Update System.Text.Encodings.Web version

- src/Microsoft.DncEng.SecretManager/ConsoleExtension.cs
- src/Microsoft.DncEng.SecretManager/ConsoleExtensions.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureDevOpsAccessToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccountInteractiveSecretType.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubBotAccount.cs
Description in https://github.com/dotnet/core-eng/issues/12390
> #12390: Implement secret type "Azure DevOps access token"

- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccessToken.cs
https://github.com/dotnet/core-eng/issues/12391
> Implement secret type "github access token"

- src/Maestro/Client/src/BuildData.cs
- src/Maestro/Client/src/Generated/Builds.cs
- src/Maestro/Client/src/Generated/MaestroApi.cs
- src/Maestro/Client/src/Generated/Models/BuildData.cs
- src/Maestro/Client/src/Generated/Models/Commit.cs
- src/Maestro/Client/src/Generated/Models/FlowEdge.cs
- src/Maestro/Client/src/Generated/Models/Subscription.cs
- src/Maestro/Client/src/Generated/Models/SubscriptionData.cs
- src/Maestro/Client/src/Generated/Models/SubscriptionUpdate.cs
- src/Maestro/Client/src/Generated/Subscriptions.cs
- src/Maestro/Client/src/Subscriptions.cs
- src/Maestro/Maestro.DataProviders/MaestroBarClient.cs
- src/Maestro/SubscriptionActorService/IPullRequestPolicyFailureNotifier.cs
- src/Maestro/SubscriptionActorService/InProgressPullRequest.cs
- src/Maestro/SubscriptionActorService/MaestroBarClient.cs
- src/Maestro/SubscriptionActorService/Program.cs
- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- src/Maestro/SubscriptionActorService/PullRequestPolicyFailureNotifier.cs
- src/Maestro/tests/Maestro.ScenarioTests/ObjectHelpers/SubscriptionBuilder.cs
- src/Maestro/tests/SubscriptionActorService.Tests/PullRequestActorTests.cs
- src/Maestro/tests/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/DependencyFlowNodeTests.cs
Context:  : https://github.com/dotnet/core-eng/issues/13009
As I had to regenerate the Swagger C# client for this to work, I've also attempted to correct all the fallout from folks manually updating the generated code.
Creating as draft as this works, but needs something added in scenario tests.
> Implementing Source repo notifications for dependency flow PRs

- src/Maestro/maestro-angular/package-lock.json
- src/Maestro/maestro-angular/package.json
https://github.com/dotnet/arcade-services/security/dependabot
> Resolve dependatbot alerts

- src/Microsoft.DncEng.SecretManager/SecretTypes/GrafanaApiKey.cs
https://github.com/dotnet/core-eng/issues/12393
> Implement secret type "grafana access token"

- src/Microsoft.DncEng.SecretManager/CharExtension.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAppSecret.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubOAuthSecret.cs
https://github.com/dotnet/core-eng/issues/12394
> Implement secret type "github app secrets"

- src/DotNet.Status.Web/Pages/_Layout.cshtml
https://github.com/dotnet/core-eng/issues/13187
> fix placement of <html> tag in status website

- src/Microsoft.DncEng.SecretManager/SecretTypes/DomainAccount.cs
https://github.com/dotnet/core-eng/issues/12395
> Domain Account Password Secret

- src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateSubscriptionOperation.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs
Addresses https://github.com/dotnet/core-eng/issues/13177
> Prevent a null ref when updating a subscription with no failure request notification tags from the Darc CLI

- src/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs
- src/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
- src/Microsoft.DncEng.SecretManager/DisposableList.cs
- src/Microsoft.DncEng.SecretManager/ParameterConverter.cs
- src/Microsoft.DncEng.SecretManager/RotationContext.cs
- src/Microsoft.DncEng.SecretManager/SecretManifest.cs
- src/Microsoft.DncEng.SecretManager/SecretReference.cs
- src/Microsoft.DncEng.SecretManager/SecretType.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureDevOpsAccessToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageBlobSasUri.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageContainerSasUri.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageTableSasUri.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccessToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccountInteractiveSecretType.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAppSecret.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubBotAccount.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubOAuthSecret.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/RandomBase64.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/SqlServerConnectionString.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/TextSecretType.cs
- src/Microsoft.DncEng.SecretManager/StorageLocationType.cs
https://github.com/dotnet/core-eng/issues/13185
> Support referencing secrets from other vaults in a secret manifest

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
We expect to publish the pacakges from emsdk, so it needs to be in the list of packages.
> Add emsdk to the list of repos we want to publish packages from

- src/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs
- src/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
- src/Microsoft.DncEng.SecretManager/DisposableList.cs
- src/Microsoft.DncEng.SecretManager/ParameterConverter.cs
- src/Microsoft.DncEng.SecretManager/RotationContext.cs
- src/Microsoft.DncEng.SecretManager/SecretManifest.cs
- src/Microsoft.DncEng.SecretManager/SecretReference.cs
- src/Microsoft.DncEng.SecretManager/SecretType.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureDevOpsAccessToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageBlobSasUri.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageContainerSasUri.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageTableSasUri.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/DomainAccount.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccessToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccountInteractiveSecretType.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAppSecret.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubBotAccount.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubOAuthSecret.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/RandomBase64.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/SqlServerConnectionString.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/TextSecretType.cs
- src/Microsoft.DncEng.SecretManager/StorageLocationType.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateSubscriptionOperation.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs
- src/Monitoring/grafana-init/grafana.ini
staging build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1160639&view=results
> [Rollout] Production rollout Jun 2nd, 2021

- src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/MergeBuildManifestsTests.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
Issue -> https://github.com/dotnet/core-eng/issues/13242
> Publish to BAR support for mstest and vstest

- src/Maestro/SubscriptionActorService/PullRequestPolicyFailureNotifier.cs
- src/Maestro/tests/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs
Address https://github.com/dotnet/core-eng/issues/13261 - For things that have automerge checks, we tag everything, ignore all maestro checks
> Don't consider maestro checks when deciding to tag notification requests on PRs

- src/Maestro/Microsoft.DotNet.Maestro.Tasks.Tests/MergeBuildManifestsTests.cs
- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
- src/Maestro/SubscriptionActorService/PullRequestPolicyFailureNotifier.cs
- src/Maestro/maestro-angular/package-lock.json
- src/Maestro/tests/SubscriptionActorService.Tests/PullRequestPolicyFailureNotifierTests.cs
- src/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs
- src/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
- src/Microsoft.DncEng.SecretManager/Readme.md
- src/Microsoft.DncEng.SecretManager/RotationContext.cs
- src/Microsoft.DncEng.SecretManager/SecretType.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/ADApplication.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureDevOpsAccessToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/DomainAccount.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccessToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccountInteractiveSecretType.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubBotAccount.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/KustoConnectionString.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/UpdateSubscriptionOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/UpdateSubscriptionCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/Darc/Program.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1174677&view=results
> [Rollout] Production rollout Jun 9th, 2021 

- Directory.Build.props
- src/DotNet.Status.Web.Tests/DotNet.Status.Web.Tests.csproj
- src/DotNet.Status.Web/DotNet.Status.Web.csproj
- src/Maestro/CoreHealthMonitor/CoreHealthMonitor.csproj
- src/Maestro/DependencyUpdateErrorProcessor/DependencyUpdateErrorProcessor.csproj
- src/Maestro/DependencyUpdater/DependencyUpdater.csproj
- src/Maestro/Maestro.Web.Tests/Maestro.Web.Tests.csproj
- src/Maestro/Maestro.Web/Maestro.Web.csproj
- src/Maestro/Microsoft.AspNetCore.ApiVersioning/Microsoft.AspNetCore.ApiVersioning.csproj
- src/Maestro/tests/Maestro.ScenarioTests/Maestro.ScenarioTests.csproj
- src/Microsoft.DncEng.Configuration.Bootstrap/Microsoft.DncEng.Configuration.Bootstrap.csproj
- src/Microsoft.DncEng.DeployServiceFabricCluster/Microsoft.DncEng.DeployServiceFabricCluster.csproj
- src/Microsoft.DncEng.SecretManager/Microsoft.DncEng.SecretManager.csproj
- src/Microsoft.DotNet.Darc/src/Darc/Microsoft.DotNet.Darc.csproj
- src/Microsoft.DotNet.Internal.Tools.SynchronizePackageProps/Microsoft.DotNet.Internal.Tools.SynchronizePackageProps.csproj
- src/Microsoft.DotNet.ServiceFabric.ServiceHost.Tests/Microsoft.DotNet.ServiceFabric.ServiceHost.Tests.csproj
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Microsoft.DotNet.ServiceFabric.ServiceHost.csproj
- src/Shared/Microsoft.DotNet.Kusto.Tests/Microsoft.DotNet.Kusto.Tests.csproj
- src/Shared/Microsoft.DotNet.Web.Authentication.Tests/Microsoft.DotNet.Web.Authentication.Tests.csproj
Something about trying to fix the MSIL warning just made everything explode, revert it
> Try and fix up deployment by reverting Directory.Build.props

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
This now produces a shipping package.
> Add sdk to gathering

- arcade-services.sln
- src/Microsoft.DncEng.SecretManager.ScenarioTests/EventHubTests.cs
- src/Microsoft.DncEng.SecretManager.ScenarioTests/Microsoft.DncEng.SecretManager.ScenarioTests.csproj
- src/Microsoft.DncEng.SecretManager.ScenarioTests/ScenarioTestsBase.cs
- src/Microsoft.DncEng.SecretManager.ScenarioTests/ServiceBusTests.cs
- src/Microsoft.DncEng.SecretManager.ScenarioTests/StorageTests.cs
https://github.com/dotnet/core-eng/issues/13259
> secrets management scenario tests

- eng/deploy.yaml
This new secret name is managed by the secret manager.
> Use new secret name for db admin connection

- .vault-config/helixkv.yaml
- .vault-config/maestroint.yaml
- .vault-config/maestrolocal.yaml
- .vault-config/maestroprod.yaml
- .vault-config/shared/maestro-secrets.yaml
- azure-pipeline-weekly.yml
- azure-pipelines.yml
- eng/deploy.yaml
- eng/firewall.ps1
- src/Maestro/Maestro.MergePolicies/StandardMergePolicy.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubBotAccount.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/GitHubClient.cs
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1210860&view=results
> [Rollout] Production rollout - June 30th, 2021

- src/Microsoft.DncEng.SecretManager.ScenarioTests/StorageTests.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageConnectionString.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageKey.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubOAuthSecret.cs
- src/Microsoft.DncEng.SecretManager/StorageKeyUtils.cs
https://github.com/dotnet/core-eng/issues/13433 - changes to support product builds under arcade
> #13433: Changes to support product builds

- .vault-config/dotneteng-status-local.yaml
- azure-pipeline-weekly.yml
- src/DotNet.Status.Web.Tests/AzurePipelinesControllerTests.cs
- src/DotNet.Status.Web/.config/settings.Development.json
- src/DotNet.Status.Web/.config/settings.json
- src/DotNet.Status.Web/Controllers/AzurePipelinesController.cs
- src/DotNet.Status.Web/Options/BuildMonitorOptions.cs
- src/Microsoft.DncEng.SecretManager.Tests/SettingsFileValidatorTests.cs
- src/Microsoft.DncEng.SecretManager.Tests/SynchronizeCommandTests.cs
- src/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
- src/Microsoft.DncEng.SecretManager/HumanInterventionRequiredException.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/ADApplication.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureDevOpsAccessToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/DomainAccount.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GenericAccessToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccessToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAppSecret.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubBotAccount.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubOAuthSecret.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/SqlServerConnectionString.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/TextSecretType.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHost.AI.cs
- src/Shared/Microsoft.DncEng.CommandLineLib/ConsoleExtensions.cs
https://dev.azure.com/dnceng/internal/_build/results?buildId=1220970
> [Rollout] Production rollout July 6th, 2021

- src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerFunction.cs
Addresses https://github.com/dotnet/core-eng/issues/13602 .  New Secret Manager means this secret gets invalidated regularly, so just convert it to use the other secret.
I've updated the old secret so this should work until this rolls out next week.
> Change secret used by rollout scorer to be the auto-updated one

- src/Microsoft.DncEng.SecretManager.ScenarioTests/StorageTests.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageConnectionString.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageContainerSasToken.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageContainerSasUri.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureStorageKey.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/Base64Encoder.cs
- src/Microsoft.DncEng.SecretManager/StorageUtils.cs
Added additional features for product builds - azure-storage-container-sas-token and base-64 encoder secret type.
https://github.com/dotnet/core-eng/issues/13433
> #13433: Added additional features for product builds azure-storage-container-sas-token and base-64 encoder

- src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs
https://github.com/dotnet/arcade/issues/7632
This test is redundant with the automerge test.
> remove github allcheckssuccessful test

- src/Maestro/Microsoft.DotNet.Maestro.Tasks/src/PushMetadataToBuildAssetRegistry.cs
There is not enough logs around this area, I think the issue is in this part but I need logs to be able to corroborate that.
> Add log when Github Url Verification fails

- src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_GitHubFlow.cs
- src/Microsoft.DncEng.SecretManager/Commands/SynchronizeCommand.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/SqlServerConnectionString.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/HttpRequestManager.cs
- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubApplicationClientFactory.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubClientFactory.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/IGitHubClientFactory.cs
- src/Shared/Microsoft.DotNet.Internal.Testing.DependencyInjection.Abstractions/Microsoft.DotNet.Internal.Testing.DependencyInjection.Abstractions.csproj
- src/Shared/Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen/Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen.csproj
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1260251&view=results
> [Rollout] Production rollout July 28th, 2021

- src/DotNet.Status.Web/Controllers/AzurePipelinesController.cs
- src/Microsoft.DncEng.SecretManager/Readme.md
- src/Microsoft.DncEng.SecretManager/SecretTypes/GitHubAccountInteractiveSecretType.cs
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1269410&view=results
> [Rollout] Production rollout August 4th, 2021 

- src/DotNet.Status.Web/.config/settings.json
- src/Maestro/Maestro.Contracts/Maestro.Contracts.csproj
- src/Maestro/Maestro.Data/BuildAssetRegistryInstallationLookup.cs
- src/Microsoft.DncEng.SecretManager.Tests/SettingsFileValidatorTests.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Actions/Remote.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubClientOptions.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/InMemoryCacheInstallationLookup.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/InstallationLookup.cs
- src/Shared/Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen.Tests/ParameterTests.cs
- src/Shared/Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen/ConfigMethod.cs
- src/Shared/Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen/TestDataReceiver.cs
Staging build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1279521&view=results
> [Rollout] Production rollout, Aug 11th, 2021

- Directory.Build.props
- src/Maestro/Maestro.MergePolicies/DontAutomergeDowngradesMergePolicy.cs
- src/Maestro/Maestro.Web/.config/settings.json
- src/Maestro/SubscriptionActorService/.config/settings.json
- src/Maestro/SubscriptionActorService/LocalGit.cs
- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- src/Maestro/maestro-angular/package-lock.json
- src/Microsoft.DncEng.SecretManager/Readme.md
Staging build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1293261&view=results
> [Rollout] Production rollout, Aug 18th, 2021

- src/Microsoft.DotNet.Darc/src/DarcLib/DarcCoherencyException.cs
Addresses https://github.com/dotnet/arcade/issues/7639.
> Add serializable constructor for DarcCoherencyException

- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
https://github.com/dotnet/core-eng/issues/13816 --- Mission control is off, time to remove its alerts before eventually deleting it.
> Remove Mission Control's panel and alerts

- azure-pipeline-weekly.yml
- eng/monitor-service-fabric-connections.ps1
Issue -> https://github.com/dotnet/core-eng/issues/12072
Test-> https://dev.azure.com/dnceng/internal/_build/results?buildId=1338619&view=logs&j=3dc8fd7e-4368-5a92-293e-d53cefc8c4b3&t=526cb169-4442-5378-373a-5a950554349c
> Monitor service fabric connections weekly 

- azure-pipeline-weekly.yml
- eng/monitor-service-fabric-connections.ps1
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/AddBuildToChannelCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/GatherDropCommandLineOptions.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1342299&view=results
> [Rollout] production rollout September 8th, 2021

- src/Maestro/SubscriptionActorService/.config/settings.json
- src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs
- src/Maestro/SubscriptionActorService/LocalGit.cs
- src/Maestro/SubscriptionActorService/SubscriptionActorService.csproj
https://github.com/dotnet/arcade/issues/7343
> Use portable-git published into the SF package

- eng/Packages.props
- eng/Version.Details.xml
- eng/Versions.props
- global.json
- src/Maestro/Maestro.Web/Maestro.Web.csproj
- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Microsoft.DotNet.ServiceFabric.ServiceHost.csproj
- src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerAzureFunction.csproj
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1359607&view=results
> [Rollout] Production rollout September 15th, 2021

- src/Maestro/Maestro.MergePolicies/DontAutomergeDowngradesMergePolicy.cs
- src/Maestro/SubscriptionActorService/.config/settings.json
- src/Maestro/SubscriptionActorService/DarcRemoteFactory.cs
- src/Maestro/SubscriptionActorService/LocalGit.cs
- src/Maestro/SubscriptionActorService/SubscriptionActorService.csproj
Staging build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1362652&view=results
> [Rollout] Production rollout Sept 22nd, 2021

- src/Shared/Microsoft.DotNet.Kusto/KustoHelpers.cs
If anyone disposed one of these, we'd then hand out the old, disposed one. That would be bad.
> Since clients are reused, wrap them with a non-disposable wrapper

- eng/Packages.props
- src/Shared/Microsoft.DotNet.Kusto/KustoHelpers.cs
- src/Shared/Microsoft.DotNet.Kusto/Microsoft.DotNet.Kusto.csproj
This reverts commit 97f1fe777ecc6be8ba78474a8a36c0c106795007.
> Revert "Stream CSV instead of buffering in memory (#1731)"

- eng/deploy.yaml
- eng/pre-deploy-tests.yaml
Ignores (eng/common/ as this is already done in dotnet/arcade, and will flow)
> Update hosted agent pools to windows-2019 versions.  

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Resolves https://github.com/dotnet/arcade/issues/8094 and let's us start untangling some F# issues.
> Add F# to nuget gather process

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GatherDropOperation.cs
Addresses https://github.com/dotnet/arcade/issues/8150.
> Add razor-tooling to nuget gathering

- src/Maestro/SubscriptionActorService/PullRequestActor.cs
- src/Maestro/SubscriptionActorService/PullRequestDescriptionBuilder.cs
- src/Maestro/tests/SubscriptionActorService.Tests/PullRequestDescriptionBuilderTests.cs
Issue link : https://github.com/dotnet/arcade/issues/7339
> Refactor PR description building and write tests

- .config/dotnet-tools.json
Adding the tool for ease of installation / restore.
> Add secret manager tool to repo

- azure-pipelines.yml
https://github.com/dotnet/arcade/issues/8265
> [HOTFIX] Disable sdl

- azure-pipelines.yml
I removed these steps as part of testing sdl changes. Wasn't meant to be merged but I did it anyways sigh.
> re-add build steps that were deleted by mistake

- azure-pipelines.yml
> Remove out of date comment about sdl being disabled

- CredScanSuppressions.json
- azure-pipelines.yml
- eng/PoliCheckExclusions.xml
- eng/common/pipeline-logging-functions.ps1
- eng/common/sdl/configure-sdl-tool.ps1
- eng/common/sdl/execute-all-sdl-tools.ps1
- eng/common/sdl/extract-artifact-archives.ps1
- eng/common/sdl/init-sdl.ps1
- eng/common/sdl/packages.config
- eng/common/sdl/push-gdn.ps1
- eng/common/sdl/run-sdl.ps1
- eng/common/templates/job/execute-sdl.yml
- eng/common/tools.ps1
- eng/deploy.yaml
- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1542433&view=results
> [Rollout] Production rollout 2022-01-12

- eng/deploy.yaml
- src/Monitoring/Sdk/DeployPublisher.cs
- src/Monitoring/Sdk/GrafanaClient.cs
- src/Monitoring/Sdk/MonitoringPublish.cs
- src/Monitoring/Sdk/sdk/Sdk.targets
Quality of life improvement: Grafana records a commit message with any dashboard save. This PR teaches the deployment tool to allow sending this message, and modifies the build pipeline to create a message with some deployment tracing info.
> Send along a change note with build information when posting dashboards

- src/Monitoring/Monitoring.ArcadeServices/notifications/Production/statusHook.imageless.12h_reminder.notification.json
- src/Monitoring/Monitoring.ArcadeServices/notifications/Production/statusHook.imageless.notification.json
- src/Monitoring/Monitoring.ArcadeServices/notifications/Staging/statusHook.imageless.12h_reminder.notification.json
- src/Monitoring/Monitoring.ArcadeServices/notifications/Staging/statusHook.imageless.notification.json
This will give us the options to omit charts from GitHub issues where they don't make sense
> Add imageless Grafana notification channels

- src/DotNet.Status.Web/Controllers/AlertHookController.cs
> Fix displaying Grafana alert issue images

- azure-pipelines.yml
- eng/generate-sbom.yml
https://github.com/dotnet/core-eng/issues/15463
Adds a template to generate and upload the SBOM.
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1587406&view=results
> Add SBOM generation template

- azure-pipelines.yml
- eng/generate-sbom.yml
- src/Microsoft.DncEng.SecretManager/StorageUtils.cs
- src/Microsoft.DotNet.Darc/src/Darc/Helpers/UxHelpers.cs
Main build: https://dev.azure.com/dnceng/internal/_build?definitionId=252
> [Rollout] Production rollout, 2022-02-09

- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/quota.dashboard.json
Exclude standardDASv4Family and increase the condition date range from 5 minutes to 10 minutes
https://github.com/dotnet/core-eng/issues/15646
> Exclude standardDASv4Family and increase the condition date range

- azure-pipeline-codeql.yml
- eng/codeql.ps1
- eng/local-codeql.ps1
- src/DotNet.Status.Web/Controllers/DeploymentController.cs
- src/DotNet.Status.Web/ZenHubClient.cs
- src/Maestro/FeedCleanerService/FeedCleanerService.cs
- src/Maestro/Maestro.Web/Pages/Account/AccountController.cs
- src/Maestro/Maestro.Web/Pages/Index.cshtml
- src/Maestro/maestro-angular/package-lock.json
- src/Maestro/maestro-angular/package.json
- src/Maestro/maestro-angular/src/app/page/build-graph-table/popIncoherencies.component.html
- src/Microsoft.DncEng.PatGenerator/AzureDevOpsPATGenerator.cs
- src/Microsoft.DncEng.SecretManager/OneTimePasswordGenerator.cs
- src/Microsoft.DncEng.SecretManager/SecretTypes/SqlServerConnectionString.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/RemoteRepoBase.cs
- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/quota.dashboard.json
- src/Monitoring/Sdk/GrafanaClient.cs
- src/RolloutScorer/RolloutScorer/RolloutScorer.cs
- src/Shared/Microsoft.DotNet.Internal.Health.Tests/MockHandler.cs
- src/Shared/Microsoft.DotNet.Internal.Testing.Utility/MockHttpClientFactory.cs
- src/Shared/Microsoft.DotNet.Web.Authentication.Tests/PersonalAccessTokenAuthenticationTests.cs
- src/Telemetry/AzureDevOpsClient/AzureDevOpsClient.cs
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1636370&view=results
> [Rollout] Production rollout, 2022-03-02

- src/RolloutScorer/RolloutScorer/Commands.cs
- src/RolloutScorer/RolloutScorer/StandardConfig.cs
Fixes https://github.com/dotnet/core-eng/issues/15718.
> Update Rollout Scorer to create new scorecards in arcade

- .vault-config/shared/dotnet-grafana-secrets.yaml
- README.md
- src/DotNet.Status.Web/Controllers/GitHubHookController.cs
Update these links to the new locations
> Update links to core-eng docs and wiki

- .vault-config/shared/dotnet-grafana-secrets.yaml
- README.md
- src/DotNet.Status.Web/Controllers/GitHubHookController.cs
- src/Maestro/CoreHealthMonitor/CoreHealthMonitor.cs
- src/Maestro/maestro-angular/package-lock.json
- src/Maestro/maestro-angular/package.json
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Actors/DelegatedActor.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/AppInsightsFlushLifecycle.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/DelegatedService.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/DelegatedStatefulService.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/DelegatedStatelessService.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Lifecycle.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/ScheduledService/ScheduledService.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHost.cs
- src/Monitoring/Sdk/DeployImporter.cs
- src/RolloutScorer/RolloutScorer/Commands.cs
- src/RolloutScorer/RolloutScorer/StandardConfig.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1644428&view=results
> [Rollout] Production rollout, 2022-03-09

- src/Maestro/CoreHealthMonitor/CoreHealthMonitor.cs
> Scope the using to prevent the File.Delete from working

- src/Maestro/CoreHealthMonitor/CoreHealthMonitor.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Extensions.cs
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1662906&view=results
> [Rollout] Production rollout, 2022-03-16

- global.json
Addresses the maestro-int and maestro-prod aspects of https://github.com/dotnet/core-eng/issues/15720
> Upgrade the dotnet version to 5.0.406, so that we are on the latest version (5.0.15)

- src/DotNet.Status.Web/Controllers/GitHubHookController.cs
- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubAppTokenProvider.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubApplicationClientFactory.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubClientFactory.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubTokenProvider.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/IGitHubAppTokenProvider.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/IGitHubApplicationClientFactory.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/IGitHubTokenProvider.cs
- src/Shared/Microsoft.DotNet.Internal.DependencyInjection/ServiceCollectionExtensions.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1724870&view=results
> [Rollout] Production rollout, 2022-04-20

- eng/Packages.props
- src/Shared/Microsoft.DotNet.Kusto.Tests/KustoClientProviderTests.cs
- src/Shared/Microsoft.DotNet.Kusto.Tests/Microsoft.DotNet.Kusto.Tests.csproj
- src/Shared/Microsoft.DotNet.Kusto/IKustoClientProvider.cs
- src/Shared/Microsoft.DotNet.Kusto/KustoClientProvider.cs
Part of a fix for https://github.com/dotnet/arcade/issues/9096
> Added another method for streamable kusto queries

- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubAppTokenProvider.cs
Set a default key size.
Resolves https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1537225.
> Set default size

- azure-pipeline-weekly.yml
Fallout from https://github.com/dotnet/arcade/issues/9304
> Remove no-longer-needed build stage in weekly arcade-services build

- Directory.Packages.props
- src/Monitoring/Sdk/Microsoft.DotNet.Monitoring.Sdk.csproj
> Downgrade this package to try and make msbuild loading work

- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/AssetsController.cs
Work around for https://github.com/dotnet/arcade/issues/9471 while we figure out next steps
This takes "hate your own code" to a whole new level.
> [HOTFIX] hardcode darc version to last known good

- src/DotNet.Status.Web/.config/settings.json
Add the pipelines that run CodeQL every week to the build monitor.
> Add more weekly pipelines to build monitor

- src/RolloutScorer/RolloutScorer/Commands.cs
- src/RolloutScorer/RolloutScorer/RolloutScorer.cs
- src/RolloutScorer/RolloutScorer/Scorecard.cs
- src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerFunction.cs
Fixes https://github.com/dotnet/arcade/issues/9206.
> Add back rollout start date check

- src/Shared/Microsoft.DotNet.Kusto/KustoHelpers.cs
As part of https://github.com/dotnet/arcade/issues/9503.
> Add ICslAdminProvider  to KustoIngestClientFactory

- src/Shared/Microsoft.DotNet.Kusto.Tests/KustoClientProviderTests.cs
- src/Shared/Microsoft.DotNet.Kusto/KustoClientProvider.cs
This is part of the work for: https://github.com/dotnet/arcade/issues/9096
I did these changes based on testing some Kusto queries and on the example documentation, specifically this section: https://github.com/Azure/azure-kusto-samples-dotnet/blob/master/client/HelloKustoV2/Program.cs#L137
> Addressed some null issues with ExecuteStreamableKustoQuery

- src/Shared/Microsoft.DotNet.GitHub.Authentication.Tests/GitHubAppTokenProviderTests.cs
- src/Shared/Microsoft.DotNet.GitHub.Authentication/GitHubAppTokenProvider.cs
> Mark false positive

- src/Shared/Microsoft.DotNet.Kusto/KustoClientProvider.cs
- src/Shared/Microsoft.DotNet.Kusto/KustoHelpers.cs
https://github.com/dotnet/arcade/issues/9503
> Move kusto query string manipulation to kusto helpers

- src/Shared/Microsoft.DotNet.Kusto/KustoClientProvider.cs
- src/Shared/Microsoft.DotNet.Kusto/KustoHelpers.cs
main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1850776&view=results
> [rollout] production rollout, 2022-07-06

- Directory.Packages.props
- src/DotNet.Status.Web.Tests/AzurePipelinesControllerTests.cs
- src/DotNet.Status.Web.Tests/GitHubHookControllerTests.cs
- src/DotNet.Status.Web/Controllers/AzurePipelinesController.cs
- src/DotNet.Status.Web/Controllers/GitHubHookController.cs
- src/Maestro/Maestro.Web.Tests/TestDatabase.cs
- src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerAzureFunction.csproj
- src/Shared/Microsoft.DotNet.Services.Utility/RetryAllHandler.cs
- src/Telemetry/AzureDevOpsClient/AzureDevOpsClient.cs
- src/Telemetry/AzureDevOpsClient/AzureDevOpsClientFactory.cs
- src/Telemetry/AzureDevOpsClient/IAzureDevOpsClient.cs
- src/Telemetry/AzureDevOpsClient/IAzureDevOpsClientFactory.cs
- src/Telemetry/AzureDevOpsTimeline/.config/settings.json
- src/Telemetry/AzureDevOpsTimeline/AugmentedTimelineRecord.cs
- src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimeline.cs
- src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimelineOptions.cs
- src/Telemetry/AzureDevOpsTimeline/BuildLogScraper.cs
- src/Telemetry/AzureDevOpsTimeline/IBuildLogScraper.cs
- src/Telemetry/AzureDevOpsTimeline/KustoTimelineTelemetryRepository.cs
- src/Telemetry/AzureDevOpsTimeline/Program.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/AzureDevOpsTimelineTests.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/AzureDevOpsTimelineTimeoutTests.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/BuildLogScraperTests.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/MockAzureClient.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/MockDelayedHttpMessageHandler.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/MockTimeoutAzureClient.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/TimelineBuilder.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1872063&view=results
> [Rollout] Production rollout, 2022-07-13

- Directory.Packages.props
Also migrates indirect dependencies forward as required by Central Package Version Management changes
> Update Microsoft.Azure.WebJobs.Extensions.Storage to latest available

- src/Shared/Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen.Tests/ArrayTests.cs
- src/Shared/Microsoft.DotNet.Internal.Testing.DependencyInjectionCodeGen/SymbolNameHelper.cs
Fixes https://github.com/dotnet/arcade/issues/9741
> Handle array parameters in TestDependencyInjectionSetup

- src/Telemetry/AzureDevOpsClient/AzureDevOpsClient.cs
- src/Telemetry/AzureDevOpsClient/IAzureDevOpsClient.cs
- src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimeline.cs
- src/Telemetry/AzureDevOpsTimeline/BuildLogScraper.cs
- src/Telemetry/AzureDevOpsTimeline/IBuildLogScraper.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/AzureDevOpsTimelineTests.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/BuildLogScraperTests.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/MockAzureClient.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/MockTimeoutAzureClient.cs
https://github.com/dotnet/arcade/issues/10247
> Log scrape logs to get docker images used for building

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/SourceMappingParser.cs
- adds a new "defaults" section for repetitive inclusion/exclusion rules. This will unite the sets from the `defaults` and from the mapping,
- adds support for `ignoreDefaults: true` on a mapping to override the defaults completely,
- when no include is specified, `**/*` is assumed.
Example `source-mappings.json`:
```json
{
"defaults": {
"defaultRef": "main",
"exclude": [
"**/*.dll",
"**/*.exe",
"**/*.pdb",
"**/*.mdb",
"**/*.zip",
"**/*.nupkg"
]
},
"mappings": [
{
"name": "runtime",
"defaultRemote": "https://github.com/dotnet/runtime",
"exclude": [
"docs/**/*"
]
},
]
}
```
https://github.com/dotnet/arcade/issues/10285
> Add a "defaults" section into `source-mappings.json`

- Directory.Packages.props
Bump Azure.Storage libraries to latest. It's a small increase, very low risk.
> Bump Azure.Storage.* to latest

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrManager.cs
Adds 2 overrides that accept mapping name and look the mapping up and calls the already existing methods
> Add VmrManager string overrides

- src/Monitoring/Monitoring.ArcadeServices/dashboard/arcade-services/arcadeAvailability.dashboard.json
See https://github.com/dotnet/arcade/issues/10556 for context.
> Fix role name for autoscaler

- src/Maestro/Maestro.Web/Api/v2018_07_16/Controllers/AssetsController.cs
Last change needed for https://github.com/dotnet/arcade/issues/9948
Need to hold off on merging this PR until after the artifact change in OSOB rolls out.
> Revert hardcoding darc version

- src/Microsoft.DotNet.Darc/src/Darc/Helpers/CompactConsoleLoggerFormatter.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/Operation.cs
Somehow #2036 ended up merging as an empty commit and the follow-up PR overrode it?
I merged two PRs and the first got merged as the contents of the second and the second merged as an empty commit Surprised
The PRs:
- https://github.com/dotnet/arcade-services/pull/2036
- https://github.com/dotnet/arcade-services/pull/2035
The commits:
- https://github.com/dotnet/arcade-services/commit/c94eaaef5f5b39aee1d3878ac90609c3966f198e
- https://github.com/dotnet/arcade-services/commit/605fdaa751bd5b76f9846801cebf5814e700f9ef
> Add a compact console formatter to darc CLI

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/SourceMappingParser.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
https://github.com/dotnet/arcade/issues/11099
> Allow comments in `source-mappings.json`

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
https://github.com/dotnet/arcade/issues/10799
> Fix trailing slash bug in VMR synchronization

- azure-pipeline-codeql.yml
Test run with TSA reporting enabled:
https://dnceng.visualstudio.com/internal/_build/results?buildId=2017647&view=logs&j=179e7e63-bd3a-519a-2d5e-221496da915a
> Changes to enable TSA reporting for CodeQL runs

- .config/tsaoptions.json
- azure-pipeline-codeql.yml
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/init-tools-native.ps1
- global.json
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/SourceMappingParser.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Monitoring/grafana-init/grafana.ini
- src/Shared/Microsoft.DotNet.Web.Authentication/GitHub/GitHubClaimResolver.cs
main build: https://dnceng.visualstudio.com/internal/_build/results?buildId=2017008&view=results
> [Rollout] Production rollout, 2022-10-12

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Resolves https://github.com/dotnet/arcade/issues/11245
> Add tags to commits created by VMR tooling

- eng/Version.Details.xml
- eng/Versions.props
- global.json
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/ManifestRecord.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/SourceManifest.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2028355&view=results
> [Rollout] Production rollout, 2022-10-26

- src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/VmrOperationBase.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/SourceMappingParser.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrRegistrations.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
Fixes https://github.com/dotnet/arcade/issues/11389
> Handle VMR patches been modified by incoming changes

- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LocalHelpers.cs
This is to stop Geneva from logging the user and PAT in the command line
> Use --config-env to pass in User and PAT during Git Checkout

- src/Shared/Microsoft.DncEng.CommandLineLib/DefaultConsoleBackend.cs
- src/Shared/Microsoft.DncEng.CommandLineLib/IConsoleBackend.cs
Some apps in helix want to read entire files from STDIN, so let's expose a way that we can do that that remains testable
> Expose Console.In for some command line apps

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/SourceMappingParser.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
Resolves https://github.com/dotnet/arcade/issues/11500
> Keep `tarball/content` and VMR's root synchronized always

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/ReadmeComponentListGenerator.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/ThirdPartyNoticesGenerator.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
This helps when debugging the tool locally
> Initialize VMR even without `README`/`THIRD-PARTY-NOTICES` files

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
https://github.com/dotnet/arcade/issues/11483
> Fix VMR synchronization when pulling empty commits

- .github/pull_request_template.md
- azure-pipelines.yml
- eng/enforce-issue.ps1
Linked issue: https://github.com/dotnet/arcade/issues/11433
> Add linked issue/release notes check

- eng/enforce-issue.ps1
> Ignore AzDO workitems, add better logging

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
https://github.com/dotnet/arcade/issues/11528
> Fix recursive detection of dependencies in VMR synchronization

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/ReadmeComponentListGenerator.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/ThirdPartyNoticesGenerator.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs
https://github.com/dotnet/arcade/issues/11567
> Synchronize `README`/`THIRD-PARTY-NOTICES` into VMR as templates

- eng/enforce-issue.ps1
> Add some more exclusions to the release notes check

- Directory.Packages.props
- src/Microsoft.DotNet.Darc/src/DarcLib/Microsoft.DotNet.DarcLib.csproj
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
https://github.com/dotnet/arcade/issues/11565
> Replace `MD5` with `XxHash64` for getting clone dir name

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Fixes https://github.com/dotnet/arcade/issues/11596
> Fix handling of VMR patch removal during VMR synchronization

- azure-pipelines.yml
> Switch to target branch for prod check

- Directory.Packages.props
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/dotnet-install.sh
- eng/enforce-issue.ps1
- global.json
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LocalHelpers.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Microsoft.DotNet.DarcLib.csproj
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/ManifestRecord.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/ReadmeComponentListGenerator.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/RepositoryCloneManager.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/SourceMappingParser.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/ThirdPartyNoticesGenerator.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/RepositoryCloneManagerTests.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
Main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2045214&view=results
issue: https://github.com/dotnet/arcade/issues/11632
> [Rollout] Production rollout 2022-11-16

- Directory.Packages.props
Addresses some warnings seen in internal builds.  See https://github.com/dotnet/arcade/issues/11650 for context.
> Update some package versions

- .vault-config/helixkv.yaml
Addresses https://github.com/dotnet/arcade/issues/11669
> add dnb2-bot to secret manifests

- azure-pipelines.yml
> Source branch mixup fixup

- src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
https://github.com/dotnet/arcade/issues/10549
> Remove dependency of VMR tooling on `IRemoteFactory`

- src/RolloutScorer/RolloutScorer/Commands.cs
- src/RolloutScorer/RolloutScorer/RolloutUploader.cs
- src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerFunction.cs
https://github.com/dotnet/arcade/issues/11253
Tested and working with the staging scorecard environment.
> Fix ancient rollout scorer bug & do some analyzer updates for .NET 6

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
https://github.com/dotnet/arcade/issues/11716
> Fix zero-sized VMR patch detection

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
https://github.com/dotnet/arcade/issues/11788
> Initialize new repositories during recursive sync

- .vault-config/maestrolocal.yaml
- .vault-config/shared/maestro-secrets.yaml
- src/Maestro/DependencyUpdater/.config/settings.json
- src/Maestro/Maestro.Web/.config/settings.json
- src/Maestro/SubscriptionActorService/.config/settings.json
https://github.com/dotnet/arcade/issues/11798 is the issue tracking supporting the domoreexp org.
> Onboard dn-bot for https://domoreexp.visualstudio.com/

- src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHost.cs
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/ServiceHostEventListener.cs
> Add EventSource logging to help diagnose actor issues

- Directory.Packages.props
- src/RolloutScorer/RolloutScorer.Tests/RolloutScorerTests.cs
- src/RolloutScorer/RolloutScorer/Commands.cs
- src/RolloutScorer/RolloutScorer/RolloutScorer.csproj
- src/RolloutScorer/RolloutScorerAzureFunction/RolloutScorerFunction.cs
Part of https://github.com/dotnet/arcade/issues/11756
We split things for easier validation
> Migrate RolloutScorer to Azure.Security.KeyVault

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncToolingE2ETest.cs
This is needed for this:
https://github.com/dotnet/installer/pull/15134
https://github.com/dotnet/arcade/issues/11960
> Move VMR's `git-info` directory into `prereqs/git-info`

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
https://github.com/dotnet/arcade/issues/11912
> Use URIs from `Version.Details.xml` for recursive sync

- eng/deploy.yaml
- src/Monitoring/Sdk/DeployPublisher.cs
- src/Monitoring/Sdk/Microsoft.DotNet.Monitoring.Sdk.csproj
- src/Monitoring/Sdk/MonitoringPublish.cs
- src/Monitoring/Sdk/sdk/Sdk.props
- src/Monitoring/Sdk/sdk/Sdk.targets
Part of https://github.com/dotnet/arcade/issues/11852
The changes were extracted from @garath's branch https://github.com/dotnet/arcade-services/compare/main...garath:arcade-services:mistucke/11756-azure-keyvault, for easier validation.
> Migrate Monitoring to Azure.Security.KeyVault

- Directory.Packages.props
- src/Maestro/DependencyUpdater/DependencyUpdater.csproj
- src/Maestro/FeedCleanerService/FeedCleanerService.csproj
- src/Maestro/Maestro.Web/.config/settings.Production.json
- src/Maestro/Maestro.Web/.config/settings.Staging.json
- src/Maestro/Maestro.Web/Api/v2019_01_16/Controllers/GoalController.cs
- src/Maestro/Maestro.Web/Maestro.Web.csproj
- src/Maestro/Maestro.Web/Startup.cs
- src/Maestro/tests/Maestro.ScenarioTests/ScenarioTests_MergePolicies.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Microsoft.DotNet.DarcLib.csproj
- src/Microsoft.DotNet.ServiceFabric.ServiceHost/Microsoft.DotNet.ServiceFabric.ServiceHost.csproj
- src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimeline.csproj
- src/Telemetry/TelemetryApplication/ApplicationPackageRoot/ApplicationManifest.xml
Part of https://github.com/dotnet/arcade/issues/11852
The changes were extracted from @garath's branch https://github.com/dotnet/arcade-services/compare/main...garath:arcade-services:mistucke/11756-azure-keyvault, for easier validation.
> Migrate Maestro and Darc to Microsoft.Security.KeyVault

- src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/InitializeOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/UpdateOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/VmrOperationBase.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/InitializeCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/SourceMappingFile.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrInitializer.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrUpdater.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/SourceMappingParser.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrRegistrations.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/LoadSourceMappingsFromInstallerTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsOneTimeSetUp.cs
https://github.com/dotnet/arcade/issues/11982
> Synchronize `source-mappings.json` from installer too

- src/Monitoring/Sdk/DeployPublisher.cs
- src/Monitoring/Sdk/Microsoft.DotNet.Monitoring.Sdk.csproj
Fix for https://github.com/dotnet/arcade-services/pull/2153
> Add Microsoft.Identity.Client package reference in Monitoring.Sdk

- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/SourceMappingFile.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrPatchHandler.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/LoadSourceMappingsFromInstallerTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.DarcLib.Tests/VirtualMonoRepo/VmrPatchHandlerTests.cs
https://github.com/dotnet/arcade/issues/12086
> Sync a file into VMR's non-src content

- CodeCoverage.runsettings
- Directory.Packages.props
https://github.com/dotnet/arcade/issues/11856
> Update CodeCoverage package version and remove workaround

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInitializer.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrManagerBase.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
https://github.com/dotnet/arcade/issues/12089
> Respect additional remotes when getting `Version.Details.xml`

- src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/VmrOperationBase.cs
> Fix exception when syncing without additional-remotes

- src/Maestro/Maestro.Web/.config/settings.Production.json
> Correct maestro prod storage account

- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LibGit2SharpHelpers.cs
> Output more readable error when commit is not found

- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
Reported here https://github.com/dotnet/installer/pull/15130
https://github.com/dotnet/arcade/issues/11864
> Handle a case when file is being added together with its patch

- .vault-config/helixkv.yaml
Part of the work for: https://github.com/dotnet/arcade/issues/12194
> Adding new bot account to KV manifest

- Directory.Packages.props
- eng/Versions.props
- src/Microsoft.DotNet.ServiceFabric.ServiceHost.Tests/Microsoft.DotNet.ServiceFabric.ServiceHost.Tests.csproj
https://github.com/dotnet/arcade/issues/11856
> Update Microsoft Test SDK version

- src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/ScanOperationBase.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrScanner.cs
https://github.com/dotnet/arcade/issues/11267
> Output a plain list of files and set exit code during VMR scans

- src/DotNet.Status.Web/Controllers/GitHubHookController.cs
- src/Microsoft.DotNet.Internal.Tools.SynchronizePackageProps/Program.cs
There are some silly bugs here.
> Fix sync-package-versions

- Directory.Packages.props
> Update AspNetCore.Http for CG issues

- src/Microsoft.DotNet.Darc/src/DarcLib/MaestroApiBarClient.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Microsoft.DotNet.DarcLib.csproj
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrBinaryFileScanner.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrCloakedFileScanner.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrScanner.cs
https://github.com/dotnet/arcade/issues/12260
> Also Scan VMR base folder

- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/FileSystem.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/IFileSystem.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Helpers/LocalPath.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/GitOperationsHelper.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrPatchAddingSubmoduleFileTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrPatchChangingFileTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncAdditionalMappingsTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncRepoChangesTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsOneTimeSetUp.cs
https://github.com/dotnet/arcade/issues/12273
> Return fast when no update is necessary

- src/DotNet.Status.Web/.config/settings.json
https://github.com/dotnet/arcade/issues/12284
> Add `Maestro Build Promotion` to monitored pipelines

- src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrScanOptions.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/IVmrScanner.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrBinaryFileScanner.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrCloakedFileScanner.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrScanner.cs
https://github.com/dotnet/arcade/issues/12339
The baseline file argument should be optional
> make baseline-file an optional argument

- Directory.Packages.props
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/GitOperationsHelper.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/LoadSourceMappingsFromInstallerTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests.csproj
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrBinaryFileScannerTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrCloakedFileScannerTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrMultipleRemotesTests.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrPatchesTestsBase.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncRepoChangesTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsOneTimeSetUp.cs
Fixes https://github.com/dotnet/arcade/issues/12371
> Fix new repo initializion during a sync

- src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrCommandLineOptionsBase.cs
https://github.com/dotnet/arcade/issues/12422
> Load token from darc settings if not provided

- src/Shared/Microsoft.DncEng.CommandLineLib/DependencyInjectedConsoleApp.cs
> Make appsettings.json optional

- .gitignore
- Directory.Packages.props
- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetSubscriptionsOperation.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/SubscriptionsCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrCommandLineOptionsBase.cs
- src/Microsoft.DotNet.Darc/src/Darc/Properties/AssemblyInfo.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrScanner.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Helpers/ConsoleOutputIntercepter.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Microsoft.DotNet.Darc.Tests.csproj
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_json.verified.txt
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_sorted_text.verified.txt
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.GetSubscriptionsOperationTests_ExecuteAsync_returns_text.verified.txt
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Operations/GetSubscriptionsOperationTests.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/GitOperationsHelper.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/LoadSourceMappingsFromInstallerTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests.csproj
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrBinaryFileScannerTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrCloakedFileScannerTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrMultipleRemotesTests.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrPatchesTestsBase.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrSyncRepoChangesTest.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsBase.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrTestsOneTimeSetUp.cs
- src/Monitoring/Sdk/sdk/Sdk.props
- src/Shared/Microsoft.DotNet.Services.Utility/DefaultHttpHandlerConfiguration.cs
- src/Shared/Microsoft.DotNet.Services.Utility/DefaultHttpHandlerConfigurationExtensions.cs
- src/Shared/Microsoft.DotNet.Services.Utility/Microsoft.DotNet.Services.Utility.csproj
Rollout issue: https://github.com/dotnet/arcade/issues/12437
Main Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2105921&view=results
> [Rollout] Production rollout 2023-02-08

- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/AllVersionsPropsFile.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/SourceManifest.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrRepoDeletionTest.cs
https://github.com/dotnet/arcade/issues/12489
> Remove repo from the VMR 

- Directory.Packages.props
- src/DotNet.Status.Web/DotNet.Status.Web.csproj
- src/Shared/Microsoft.DotNet.Kusto.Tests/KustoHelpersTests.cs
- src/Shared/Microsoft.DotNet.Kusto/KustoHelpers.cs
https://learn.microsoft.com/en-us/azure/data-explorer/kusto/management/csv-mapping mentions that we every mapping element must have the Ordinal Property. I was not able to verify things locally, but we should be able to do so on the Staging environment like the last time
> Dkurepa/fix kusto.ingest bump

- src/Microsoft.DncEng.SecretManager/StorageTypes/AzureKeyVault.cs
https://github.com/dotnet/arcade/issues/12363
> Produce an error when a secret does not have next-rotation-on

- global.json
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests.csproj
https://github.com/dotnet/arcade/issues/12828
> Bump .NET 6.0 SDK version

- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureDevOpsAccessToken.cs
https://github.com/dotnet/arcade/issues/13002
> Output a better error if corpnet is required for secret rotation

- .vault-config/shared/dotneteng-status-secrets.yaml
https://github.com/dotnet/arcade/issues/13030
Adds a description to the applications insights instrumentation key secrets.
> add description to applications insights instrumentation key text secret

- CredScanSuppressions.json
- src/Maestro/ServiceFabricMocks/ServiceFabricMocks.csproj
- src/Microsoft.DncEng.SecretManager/SecretTypes/AzureDevOpsAccessToken.cs
Rollout issue: https://github.com/dotnet/arcade/issues/13005
Main Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2148237&view=results
> [rollout] Production rollout 2023-04-05

- src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrSyncCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/AllVersionsPropsFile.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/SourceManifest.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrRepoDeletionTest.cs
I think some commits were reverted by mistake in https://github.com/dotnet/arcade-services/commit/ebe2d59a1bdb5fed2cd5eb8a326fd3ea58d22430
https://github.com/dotnet/arcade/issues/12489
> Bring back mistakenly reverted changes

- src/Microsoft.DotNet.Darc/src/Darc/Operations/GetBuildOperation.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Helpers/ConsoleOutputIntercepter.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.Tests/Operations/GetBuildOperationTests.cs
https://github.com/dotnet/arcade/issues/12933
> Remove duplicates from the DARC get build output

- src/Maestro/Maestro.Web.Tests/TestDatabase.cs
https://github.com/dotnet/arcade/issues/13192
> Suppress the CodeQL warning in Maestro.Web.Tests

- arcade-services.sln
- eng/Version.Details.xml
- eng/Versions.props
- global.json
- src/DotNet.Status.Web.Tests/AzurePipelinesControllerTests.cs
- src/DotNet.Status.Web/Controllers/AzurePipelinesController.cs
- src/Maestro/DependencyUpdater/DependencyUpdater.cs
- src/Microsoft.DotNet.Darc/src/Darc/Options/VirtualMonoRepo/VmrSyncCommandLineOptions.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/AllVersionsPropsFile.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/SourceManifest.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrInfo.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrUpdater.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrRepoDeletionTest.cs
- src/Telemetry/AzureDevOpsClient.Tests/AzureDevOpsClient.Tests.csproj
- src/Telemetry/AzureDevOpsClient.Tests/TryGetImageNameTests.cs
- src/Telemetry/AzureDevOpsClient/AzureDevOpsClient.cs
- src/Telemetry/AzureDevOpsClient/IAzureDevOpsClient.cs
- src/Telemetry/AzureDevOpsTimeline/AzureDevOpsTimeline.cs
- src/Telemetry/AzureDevOpsTimeline/BuildLogScraper.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/BuildLogScraperTests.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/MockAzureClient.cs
- src/Telemetry/Microsoft.DotNet.AzureDevOpsTimelineTests/MockTimeoutAzureClient.cs
Rollout issue: https://github.com/dotnet/arcade/issues/13181
Main Build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2159070&view=results
> [rollout] Production rollout 2023-04-19

- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/AllVersionsPropsFile.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/ManifestRecord.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/Models/VirtualMonoRepo/SourceManifest.cs
- src/Microsoft.DotNet.Darc/src/DarcLib/VirtualMonoRepo/VmrDependencyTracker.cs
- src/Microsoft.DotNet.Darc/tests/Microsoft.DotNet.Darc.VirtualMonoRepo.E2E.Tests/VmrRepoDeletionTest.cs
https://github.com/dotnet/arcade/issues/13124
https://github.com/dotnet/source-build/issues/2250
> Dont override package version with a default when none available

- src/Microsoft.DotNet.Darc/src/Darc/Operations/VirtualMonoRepo/VmrOperationBase.cs
> Make reading additional remotes more resilient

- .vault-config/shared/dotneteng-status-secrets.yaml
https://github.com/dotnet/arcade/issues/13305
> Fix dn-bot for dotnet-status PAT configuration

- src/Microsoft.DotNet.Darc/src/Darc/Models/PopUps/AuthenticateEditorPopUp.cs
https://github.com/dotnet/arcade/issues/13010
> Mention SSO token requirement in `darc authenticate`

- azure-pipelines.yml
This effort is done trying to fix:  https://github.com/dotnet/arcade/issues/13477
> Use PublishPipelineArtifact instead of PublishBuildArtifact for Maestro.Data

- azure-pipelines.yml
- eng/BuildTask.targets
- eng/deploy.yaml
- src/DotNet.Status.Web/DotNet.Status.Web.csproj
- src/Microsoft.DncEng.Configuration.Bootstrap/Microsoft.DncEng.Configuration.Bootstrap.csproj
- src/Microsoft.DncEng.DeployServiceFabricCluster/Microsoft.DncEng.DeployServiceFabricCluster.csproj
- src/Microsoft.DncEng.PatGeneratorTool/Microsoft.DncEng.PatGeneratorTool.csproj
- src/Microsoft.DncEng.SecretManager/Microsoft.DncEng.SecretManager.csproj
- src/Microsoft.DotNet.Internal.Tools.SynchronizePackageProps/Microsoft.DotNet.Internal.Tools.SynchronizePackageProps.csproj
- src/Monitoring/Sdk/Microsoft.DotNet.Monitoring.Sdk.csproj
issue: https://github.com/dotnet/arcade/issues/13650
Validation PR run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2186664&view=results
> make dnceng tools non packable

- .config/dotnet-tools.json
- azure-pipeline-weekly.yml
- azure-pipelines.yml
- eng/BuildTask.targets
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/templates/job/job.yml
- eng/deploy.yaml
- global.json
- src/DotNet.Status.Web/DotNet.Status.Web.csproj
- src/Maestro/bootstrap.ps1
- src/Microsoft.DncEng.Configuration.Bootstrap/Microsoft.DncEng.Configuration.Bootstrap.csproj
- src/Microsoft.DncEng.DeployServiceFabricCluster/Microsoft.DncEng.DeployServiceFabricCluster.csproj
- src/Microsoft.DncEng.PatGeneratorTool/Microsoft.DncEng.PatGeneratorTool.csproj
- src/Microsoft.DncEng.SecretManager/Microsoft.DncEng.SecretManager.csproj
- src/Microsoft.DotNet.Internal.Tools.SynchronizePackageProps/Microsoft.DotNet.Internal.Tools.SynchronizePackageProps.csproj
main build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2194270&view=results
> [Rollout] Production rollout, 2023-06-07

- Directory.Packages.props
https://github.com/dotnet/arcade-services/issues/2648
> Update Microsoft.VisualStudio.Web.CodeGeneration.Design package

- Directory.Packages.props
https://github.com/dotnet/arcade-services/issues/2675
> Bump `Microsoft.VisualStudio.Web.CodeGeneration.Design`
